table: Bimp_ImportPaiement
primary: id
common_fields: 1
icon: fas_file-import
controller: import_paiement

entity_name: importPaiement

list_page_url:
    controller: index
    url_params: 
        tab: import_paiement
    
header_list_name: default
header_edit_form: default

header_btn: 
    callback: getActionsButtons

labels: 
    name: Import de paiement
    name_plur: Import de paiements
     
objects:  
    files:
        relation: hasMany
        delete: 1
        instance:
            bimp_object:
                module: bimpcore
                name: BimpFile
        list: 
            filters:
                parent_module: bimpfinanc
                parent_object_name: Bimp_ImportPaiement
                deleted: 0
    lignes: 
        relation: hasMany
        delete: 1
        instance: 
            bimp_object: Bimp_ImportPaiementLine
                
fields: 
    banque:
        label: Banque
        type: int
        default_value: 
            callback: getDefaultBankAccount
#        input: 
#              type: select_mysoc_account
        values: 
            callback: getBankAccountsArray
    
forms:
    default:
        all_fields: 1
    add: 
        rows: 
            banque:
                field: banque
            file:
                custom: 1
                label: Fichier
                custom: 1
                input_name: file
                input:
                    type: file_upload
    
filters_panels: 
    default: 
        filters: 
            1:
                field: banque
                
lists:
    default: 
        checkboxes: 1
        configurable: 1
        sort_field: id
        sort_way: desc
        n: 25
        delete_btn: 1
        modal_view: default
        add_form_name: add
        filters_panel: default
        edit_btn: 1
        page_btn: 1
        cols:
            date_create:
            banque:
            user_create:
                
    client: 
        extends: default
        n: 0
        cols: 
            fk_soc: unset
    
views: 
    default: 
        modal_format: medium
        rows: 
            - cols:     
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: infos
            - cols: 
                - type: list
                  list: 
                      name: default
                      children: lignes
                      title: Lignes

fields_tables: 
    infos: 
        panel: 0
        rows: 
            - field: banque
                      
                     
        
        


