table: bimp_commission
common_fields: 0
icon: fas_comment-dollar
controller: commission

list_page_url:
    controller: index
    url_params: 
        tab: default
    
header_list_name: default
header_btn: 
    callback: getActionsButtons
    
labels: 
    name: Commission
    is_female: 1
    
fields: 
    type: 
        label: Type
        values: 
            array: types
        default_value: 1
    id_user: 
        label: Utilisateur
        type: id_object
        object: user
        input:
            type: search_user
        display_if: 
            field_name: type
            show_values: 1
        required_if: type=1
        default_value: 0
    id_entrepot: 
        label: Entrepôt
        type: id_object
        object: bimp_entrepot
        input: 
            type: search_entrepot
            has_commissions_only: 1
        display_if: 
            field_name: type
            show_values: 2
        required_if: type=2
        default_value: 0
    secteur: 
        label: Secteur
        values: 
            array: secteurs
        display_if: 
            field_name: type
            show_values: 2
    date: 
        label: Date
        type: date
        input: 
            display_now: 1
    total_marges: 
        label: Total marges
        type: money
        default_value: 0
    total_pa:
        label: Total Achat
        type: money
        default_value: 0
    total_ca:
        label: Total CA
        type: money
        default_value: 0
    status: 
        label: Statut
        type: int
        values: 
            array: status_list
        
fields_tables: 
    infos: 
        title: Informations
        icon: fas_info-circle
        rows: 
            - field: type
            - field: id_user
              display: card
              show: 
                  field_value: id_user
            - field: id_entrepot
              display: nom_url
              show: 
                  field_value: id_entrepot
            - field: secteur
            - field: status
            - field: date
            - label: Ecarts secteurs
              value: 
                  callback: displaySecteursErrors
            
    amounts: 
        title: Montants
        icon: fas_euro-sign
        rows: 
            - label: Total CA
              value: 
                  callback: 
                      method: displayAmount
                      params: 
                          - total_ca
            - label: Total achats
              value: 
                  callback: 
                      method: displayAmount
                      params: 
                          - total_pa
            - label: Total revalorisations
              value: 
                  callback: 
                      method: displayAmount
                      params: 
                          - total_reval
            - label: Total marges
              value: 
                  callback: 
                      method: displayAmount
                      params: 
                          - total_marges
            - label: Taux de marge
              value: 
                  callback: 
                      method: displayAmount
                      params: 
                          - tx_marge
            - label: Taux de marque
              value: 
                  callback: 
                      method: displayAmount
                      params: 
                          - tx_marque
                          
    amounts_serv:
        title: Montants services
        icon: fas_euro-sign
        open : 0
        rows: 
            - label: Total CA
              value: 
                  callback: 
                      method: displayAmount
                      params: 
                          - total_ca_serv
            - label: Total achats
              value: 
                  callback: 
                      method: displayAmount
                      params: 
                          - total_pa_serv
            - label: Total revalorisations
              value: 
                  callback: 
                      method: displayAmount
                      params: 
                          - total_reval_serv
            - label: Total marges
              value: 
                  callback: 
                      method: displayAmount
                      params: 
                          - total_marges_serv
        
    amounts_prod:
        title: Montants produits
        icon: fas_euro-sign
        open : 0
        rows: 
            - label: Total CA
              value: 
                  callback: 
                      method: displayAmount
                      params: 
                          - total_ca_prod
            - label: Total achats
              value: 
                  callback: 
                      method: displayAmount
                      params: 
                          - total_pa_prod
            - label: Total revalorisations
              value: 
                  callback: 
                      method: displayAmount
                      params: 
                          - total_reval_prod
            - label: Total marges
              value: 
                  callback: 
                      method: displayAmount
                      params: 
                          - total_marges_prod
                
views: 
    default: 
        objects_change_reload: Bimp_Facture,BimpRevalorisation
        rows: 
            - cols: 
                - type: object_header
            - cols: 
                  - type: fields_table
                    col_lg: 6
                    col_md: 6
                    fields_table: 
                        name: infos
                  
                  - type: fields_table
                    col_lg: 6
                    col_md: 6
                    fields_table:
                        name: amounts
                  
                  - type: fields_table
                    col_lg: 6
                    col_md: 6
                    fields_table:
                        name: amounts_serv
                  
                  - type: fields_table
                    col_lg: 6
                    col_md: 6
                    fields_table:
                        name: amounts_prod
                        
            - cols: 
                - type: custom
                  custom: 
                      callback: renderDetailsView
    
forms: 
    default: 
        rows: 
            - field: type
            - field: id_user
            - field: id_entrepot
            - field: secteur
            - field: date
            - custom: 1
              label: Inclure uniquement les facture entièrement payées
              input_name: paid_only
              value: 0
              data_type: bool
              input: 
                  type: toggle
            
    generate: 
        title: Générer des commissions par groupe
        icon: fas_cogs
        msgs: 
            - type: info
              content: Cet outil permet de générer les commissions de chaque utilisateur d'un groupe
        rows: 
            - custom: 1
              label: Groupe d'utilisateur
              input_name: id_group
              data_type: id
              required: 1
              input: 
                  type: search_group
            - field: date
            - custom: 1
              label: Inclure uniquement les facture entièrement payée
              input_name: paid_only
              value: 0
              data_type: bool
              input: 
                  type: toggle
    
filters_panel: 
    default: 
        filters: 
            id_user:
            id_entrepot:
            date:
            status:

lists_cols: 
    owner: 
        label: Utilisateur / Entrepôt
        value: 
            callback: displayLinkedObject
    tx_marque:
        label: Taux de marque
        value: 
          callback:
              method: displayTaux
              params: 
                  -  marque

lists: 
    default: 
        title: Liste des commissions
        checkboxes: 1
        bulk_actions:
            - label: supprimer les commissions sélectionnées
              icon: fas_trash-alt
              onclick: deleteSelectedObjects('list_id', $(this))
        filters_panel: default
        sort_field: id
        sort_way: desc
        n: 10
        page_btn: 1
        modal_view: default
        add_form_name: default
        add_form_values: 
            fields: 
                id_user: 
                    request: id_user
        add_btn_label: Nouvelle commission
        delete_btn: 1
        header_buttons: 
            callback: getListHeaderButtons
        extra_btn: 
            callback: getListExtraBtn
        cols: 
            date: 
            owner: 
            total_marges: 
            status: 
            total_ca:
            tx_marque:
        list_filters: 
            callback: getListFilters
            
    user: 
        extends: default
        cols: 
            owner: unset
    
