table: bimp_revalorisation
common_fields: 0

icon: fas_search-dollar

list_page_url:
    controller: index
    url_params: 
        tab: revalorisations
    
header_list_name: default
header_btn: 
    callback: getActionsButtons

labels: 
    name: Revalorisation
    is_female: 1

objects: 
    facture_line: 
        relation: hasOne
        delete: 0
        instance: 
            bimp_object: 
                module: bimpcommercial
                name: Bimp_FactureLine
            id_object: 
                field_value: id_facture_line
                
    user_processed: 
        extends: user
        instance: 
            id_object: 
                field_value: id_user_processed
                
    user_commission: 
        extends: commission
        instance: 
            id_object: 
                field_value: id_user_commission
                
    entrepot_commission: 
        extends: commission
        instance: 
            id_object: 
                field_value: id_entrepot_commission
                                    
fields: 
    id_facture: 
        label: Facture
        type: id_object
        object: facture
        input: 
            type: search_object
        required: 1
        
    id_facture_line:
        label: Ligne de facture
        type: id_object
        object: facture_line
        input: 
            type: select
            options: 
                array: factureLines
        display_if: 
            field_name: id_facture
            hide_values: 0
        depends_on: id_facture
        required: 1

    id_user_commission: 
        label: Commission utilisateur
        type: id_object
        object: user_commission
        default_value: 0
        
    id_entrepot_commission: 
        label: Commission entrepôt
        type: id_object
        object: entrepot_commission
        default_value: 0
    
    type: 
        label: Type
        values: 
            array: types
        required: 1
            
    date: 
        label: Date
        type: date
        required: 1
        
    amount: 
        label: Montant unitaire
        type: money
        required: 1
        
    qty: 
        label: Qté
        type: qty
        decimals: 4
        default_value: 0
        
    status: 
        label: Statut
        type: int
        values: 
            array: status_list
        default_value: 0
        
    date_processed: 
        label: traitée le
        type: date
        
    id_user_processed: 
        label: Traitée par
        type: id_object
        object: user_processed
        
forms: 
    default: 
        rows: 
            - field: id_facture
              show: 
                  callback: isNotLoaded
            - field: id_facture_line
              show: 
                  callback: isNotLoaded
            - field: type
            - field: date
            - field: amount
            - field: qty
        
    add_to_commission: 
        title: Ajout à une commission
        rows:       
            - custom: 1
              label: Commission
              input_name: id_commission
              data_type: id
              required: 1
              input: 
                  type: select
                  options: 
                      array: draftCommission
                  
fields_tables: 
    infos: 
        title: Informations
        icon: fas_info-circle
        rows: 
            - field: type
            - field: date
            - field: amount
            - field: qty
              edit: 1
            - label: Total
              value: 
                  callback: displayTotal
            - field: status
            - field: id_user_commission
              display: nom_url
              show: 
                  field_value: id_user_commission
            - field: id_entrepot_commission
              display: nom_url
              show: 
                  field_value: id_entrepot_commission
            
    elements: 
        title: Eléments liés
        icon: fas_link
        rows: 
            - field: id_facture
              display: card
            - label: Ligne de facture
              value: 
                  callback: displayDesc
              
views: 
    default: 
        rows: 
            - cols: 
                - type: object_header
            - cols: 
                  - type: fields_table
                    col_lg: 6
                    col_md: 6
                    fields_table: 
                        name: infos
                  
                  - type: fields_table
                    col_lg: 6
                    col_md: 6
                    fields_table:
                        name: elements
            
filters_panel: 
    default: 
        filters: 
            - field: status
            - field: type
            - field: date
            - field: amount
            - field: ef_type
              child: facture
            - field: entrepot
              child: facture
            
lists_cols: 
    facture: 
        field: id_facture
        display: nom_url
    type: 
        field: type
    commercial: 
        label: Commercial facture
        value: 
            callback: 
                method: displayCommercial
                object: facture
        search: 
            input: 
                type: search_user
    date: 
        field: date
    desc: 
        label: Désignation
        value: 
            callback: displayDesc
    amount: 
        field: amount
    qty: 
        field: qty
        edit: 1
    total: 
        label: total
        value: 
            callback: displayTotal
    status: 
        field: status
    commissions: 
        label: Commissions
        value: 
            callback: displayCommissions
    secteur: 
        field: ef_type
        child: facture
    entrepot: 
        field: entrepot
        child: facture
    client_facture: 
        field: fk_soc
        child: facture
        display: nom_url
    
lists: 
    default: 
        title: Liste des revalorisations
        checkboxes: 1
        configurable: 1
        bulk_actions:
            - label: supprimer les revalorisations sélectionnées
              icon: fas_trash-alt
              onclick: deleteSelectedObjects('list_id', $(this))
        list_filters: 
            callback: getListFilters
        filters_panel: default
        sort_field: id
        sort_way: desc
        n: 10
        modal_view: default
        add_form_name: default
        add_btn_label: Nouvelle revalorisation
        edit_btn: 1
        edit_form: default
        delete_btn: 1
        update_btn: 1
        extra_btn: 
            callback: getActionsButtons
        cols: 
            facture: 
            type: 
            commercial: 
            date: 
            desc: 
            amount: 
            qty: 
            total:
            status: 
            commissions: 
        
    commission: 
        configurable: 1
        enable_search: 0
        pagination: 1
        n: 20
        sort_field: id
        sort_way: asc
        extra_btn: 
            callback: 
                method: getCommissionListButtons
        modal_view: default
        cols: 
            facture: 
            type: 
            date: 
            desc: 
            total: 
            status: 
                
    user_commission: 
        extends: commission
        extra_btn: 
            callback: 
                params: 
                    - 1
                    
    entrepot_commission: 
        extends: commission
        extra_btn: 
            callback: 
                params: 
                    - 2
                
    facture: 
        pagination: 1
        n: 20
        sort_field: id
        sort_way: asc
        extra_btn: 
            callback: getActionsButtons
        edit_btn: 1
        edit_form: default
        modal_view: default
        cols: 
            type: 
            date: 
            desc: 
            total: 
            status:  
            commissions: 
