ALTER TABLE llx_bimpalert_produit
  ADD COLUMN msgOnParent BOOLEAN NOT NULL DEFAULT 0,
  ADD COLUMN searchByCallback BOOLEAN NOT NULL DEFAULT 0,
  ADD COLUMN callbackFunction VARCHAR(100) NOT NULL DEFAULT ''
  ADD COLUMN checkIfNoteNonLue BOOLEAN NOT NULL DEFAULT 0;
