dol_object: 
    instance: 
        dol_object: synopsisfichinter
        
table: synopsis_fichinter
primary: rowid
controller: fichinter
icon: fas_ambulance

list_page_url:
    controller: index
    params: 
        tab:fi
header_list_name: default

labels: 
    name: fiche d'intervention
    name_plur: fiches d'intervention
    is_female: 1
     
objects:  
    lines: 
        relation: hasMany
        delete: 1
        instance: 
            bimp_object: 
                module: bimpfichinter
                name: Bimp_Fichinterdet      
                
    commande: 
        instance: 
            id_object: 
                field_value: fk_commande
                
    propal: 
        instance: 
            bimp_object: 
                module: bimpsupport
                name: BS_SavPropal
                
    contrat:
        instance: 
            id_object: 
                field_value: fk_contrat
            
    client:
        instance:
            id_object:
                field_value: fk_soc
                
    files:
        relation: hasMany
        delete: 1
        instance:
            bimp_object:
                module: bimpcore
                name: BimpFile
        list: 
            filters:
                parent_module: bimpfichinter
                parent_object_name: Bimp_Fichinter
                
    user_author: 
        extends: user
        instance:
            id_object:
                field_value: fk_user_author
                
    user_valid: 
        extends: user
        instance:
            id_object:
                field_value: fk_user_valid
                
fields: 
    description:
        label: Description
        type: text
    fk_soc:
        label: Client
        type: id_object
        object: client
        create_form: client_light
        input: 
            type: search_societe
            societe_type: customer
            help: Entrez le nom ou la référence d'un client pour effectuer une recherche
        search:
            input: 
                type: search_societe
                societe_type: customer 
        dol_prop: socid
    fk_commande: 
        label: Commande
        object: commande
        type: id_object
        values:
            array: list_commande
    ref:
        label: Ref
        type: string
    model_pdf:
        label: Model PDF
        type: string
        dol_prop: modelpdf
    fk_contrat:
        label: Contrat
        type: id_object
        object: contrat
        values:
            array: list_contrat
#    fk_facture:
#        label: Facture
#        type: id_object
#        object: facture
#        values:
#            array: list_facture
    fk_statut:
        label: Statut
        type: int
        values: 
            array: status_list
        dol_prop: statut
    datei:
        label: Date d'intervention
        type: date
        dol_prop: date
        #required: 1
    date_valid:
        label: Date de validation
        type: date
    fk_user_author:
        label: Intervenant
        type: id_object
        object: user_author
        input: 
            type: search_user
#    fk_user_modif:
#        label: User modif
#        type: id_object
#        object: user
#        search:
#            input: 
#                type: search_user
    fk_user_valid:
        label: Valideur
        type: id_object
        object: user_valid
        search:
            input: 
                type: search_user
                
    duree:
        label: Durée
        type: time_last
        input: 
            type: timer
        display:
            default: 
                type: timer
        
    note_public:
        label: Note Public
        type: text
    note_private:
        label: Note Privée
        type: text
    total_ht:
        label: Total Ht
        type: money
        show: 
            callback:
                method: canViewPrice
    total_tva:
        label: Total Tva
        type: money
        show: 
            callback:
                method: canViewPrice
    total_ttc:
        label: Total Ttc
        type: money
        show: 
            callback:
                method: canViewPrice
    natureInter:
        label: Nature de l'inter
        type: int
        values: 
            array: nature_list
    extra35:
        label: Type d'inter
        type: int
        extra: 1
        values: 
            array: type_list
    extra17:
        label: Terminée
        type: bool
        extra: 1
    di:
        label: Demande
        type: string
        extra: 1
        no_strip_tags: 1     
    extra18:
        label: Date du prochain RDV
        type: date
        extra: 1
        display_if: 
            field_name: extra17
            show_values: 0
        show: 1
    extra24:
        label: Heure d'arrivé AM
        type: string
        extra: 1
    extra26:
        label: Heure de départ AM
        type: string
        extra: 1
    extra25:
        label: Heure d'arrivé PM
        type: string
        extra: 1
    extra27:
        label: Heure de départ PM
        type: string
        extra: 1
        
# fields manquant :
#    fk_projet
#    entity
#    tms
#    datec
#    dateo
#    datee
#    datet
#    extraparams
#    ref_ext
#    last_main_doc
#    Import_key
        
forms:
    default: 
        rows:
            - field: fk_soc
            - field: datei
            - field: description
            - field: fk_contrat
            - field: fk_commande
            - field: fk_statut
            - field: note_public
            - field: note_private
            - field: extra35
            - field: natureInter
            - field: extra17
            - field: extra18
    
filters_panels: 
    default: 
        filters: 
            fk_statut:
            ref:
            fk_commande:
            fk_contrat:
            datei:
            date_valid:
            total_ht:
            total_tva:
            total_ttc:
            fk_user_author:
            
lists_cols:
    fk_commande: 
        display: nom_url
    fk_contrat: 
        display: nom_url
    commercial: 
        label: Commercial
        value: 
            callback: displayCommercial
        search: 
            input: 
                type: search_user
                
lists:
    defaultAbstract: 
        checkboxes: 1
        configurable: 1
        sort_field: rowid
        sort_way: desc
        n: 25
        delete_btn: 0
        modal_view: default
        add_form_name: default
        filters_panel: default
        page_btn: 1
        edit_btn: 1
        cols:
            ref:
            fk_soc:
            fk_commande:
            fk_contrat:
            datei:
            date_valid:
            fk_user_author:
            fk_statut:
            duree:
            total_ht:
            natureInter:
            typeInter:
            commercial:
    default: 
        extends: defaultAbstract     
        cols:
            fk_soc:
                show:
                    callback:
                        method: getFieldFiltre
                        params:
                            - fk_soc
                            - show
        list_filters:
            callback:
                method: getFieldFiltre
                params:
                    - fk_soc
                    - filtre
        add_form_values:
            callback:
                method: getFieldFiltre
                params:
                    - fk_soc
                    - form_value
                    
    client: 
        extends: default
        n: 10
        cols: 
            fk_soc: unset                
                
fields_tables: 
    infos:
        footer_extra_btn: 
              callback: getActionsButtons
        title: Infos FI
        icon: id-card
        rows: 
            - field: ref 
            - field: di
            - field: fk_statut 
              edit: 1
            - field: description 
              edit: 1
            - field: natureInter
              edit: 1
            - field: extra35
              edit: 1
            - field: note_public
              edit: 1
            - field: note_private
              edit: 1
    horaire:
        title: Horaire
        icon: fas_calendar-check
        rows: 
            - field: datei 
              edit: 1
            - field: date_valid 
            - field: duree 
#            - label: Horaire arrivé AM
#              value:
#                  callback:
#                      method: displayExtra
#                      params:
#                          - extra24
#                          - time
            - field: extra24
              edit: 1
            - field: extra26
              edit: 1
            - field: extra25
              edit: 1
            - field: extra27
              edit: 1
            - field: extra17
              edit: 1
            - field: extra18
              edit: 1
    lien:
        title: Objets liées
        icon: link
        rows:
            - field: fk_soc 
              display: card
            - field: fk_commande
              display: nom_url
              edit: 1
            - field: fk_contrat 
              display: nom_url
              edit: 1
            - custom: 1
              label: Facture
              value: 
                  callback: display_fact
            - field: fk_facture
              custom: 1
              callback: display_fact
              display: nom_url
              edit: 1
            - field: fk_user_author
              display: nom_url 
    price:
        title: Prix
        icon: money
        rows:
            - field: total_ht 
            - field: total_tva 
            - field: total_ttc 
        show: 
            callback:
                method: canViewPrice    
        
views: 
    default: 
        objects_change_reload: Bimp_Fichinterdet
        rows: 
            - cols: 
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: infos
            
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: horaire
            
            - cols: 
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: lien
                      

            
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: price
            - cols: 
                - type: list
                  list: 
                      name: default
                      children: lines
                      title: Lignes
        

