dol_object: 
    instance: 
        dol_object: synopsisdemandeinterv
        
        
        
table: synopsisdemandeinterv
primary: rowid
controller: demandinter
list_page_url:
    controller: di
header_list_name: default
icon: fas_ambulance

labels: 
    name: Demande d'intervention
    is_female: 1
    
   
     
objects:  
    lines: 
        relation: hasMany
        delete: 1
        instance: 
            bimp_object: 
                module: bimpfichinter
                name: Bimp_Demandinterdet         
    commande: 
        instance: 
            bimp_object: 
                module: bimpcommercial
                name: Bimp_Commande
                
    propal: 
        instance: 
            bimp_object: 
                module: bimpsupport
                name: BS_SavPropal
    contrat:
        card: 
            title: 
                object_prop: ref
            view_btn: 1
    client:
        instance:
            id_object:
                field_value: fk_soc
            
    
                
fields: 
    description:
        label: Description
        type: text
    fk_soc:
        label: Client
        type: id_object
        object: client
        create_form: client_light
        input: 
            type: search_societe
            societe_type: customer
            help: Entrez le nom ou la référence d'un client pour effectuer une recherche
        search:
            input: 
                type: search_societe
                societe_type: customer 
        dol_prop: socid
    fk_commande: 
        label: Commande
        object: commande
        type: id_object
        values:
            array: list_commande
        default_value: 0
    ref:
        label: Ref
        type: string
    model_pdf:
        label: Model PDF
        type: string
    fk_contrat:
        label: Contrat
        type: id_object
        object: contrat
        values:
            array: list_contrat
    fk_statut:
        label: Statut
        type: int
        values: 
            array: status_list
        dol_prop: statut
        
    datei:
        label: Date d'intervention
        type: date
        dol_prop: date
        required: 1
    date_valid:
        label: Date de validation
        type: date
    fk_user_author:
        label: Créateur
        type: id_object
        object: user
        input: 
            type: search_user
        dol_prop: author
    fk_user_prisencharge:
        label: Intervenant
        type: id_object
        object: user
        input: 
            type: search_user
            include_empty: 1
        default_value: 0
#    fk_user_modif:
#        label: User modif
#        type: id_object
#        object: user
#        search:
#            input: 
#                type: search_user
    fk_user_valid:
        label: Valideur
        type: id_object
        object: user
        search:
            input: 
                type: search_user
                
    duree:
        label: Durée
        type: time_last
        input: 
            type: timer
        display:
            default: 
                type: timer
        
    note_public:
        label: Note Public
        type: text
    note_private:
        label: Note Privée
        type: text
    total_ht:
        label: Total Ht
        type: money
        show: 
            callback:
                method: canViewPrice
    total_tva:
        label: Total Tva
        type: money
        show: 
            callback:
                method: canViewPrice
    total_ttc:
        label: Total Ttc
        type: money
        show: 
            callback:
                method: canViewPrice
    extra37:
        label: Type d'inter
        type: int
        extra: 1
        values: 
            array: extra37_list
    fi:
        label: Fiche
        type: string
        extra: 1
    action:
        label: Event agenda
        type: string
        extra: 1
    extra24:
        label: Heure d'arrivé AM
        type: string
        extra: 1
    extra26:
        label: Heure de départ AM
        type: string
        extra: 1
    extra25:
        label: Heure d'arrivé PM
        type: string
        extra: 1
    extra27:
        label: Heure de départ PM
        type: string
        extra: 1
    extra38:
        label: Confirmé
        type: bool
        extra: 1
        default_value: 0
# fields manquant :
#    fk_projet
#    entity
#    tms
#    datec
#    dateo
#    datee
#    datet
#    extraparams
#    ref_ext
#    last_main_doc
#    Import_key
        

        
forms:
    default: 
        rows:
            - field: fk_soc
            - field: datei
            - field: description
            - field: note_public
            - field: note_private
            - field: extra37
    
        
filters_panels: 
    default: 
        filters: 
            10:
                field: fk_statut
            20: 
                field: ref
            21: 
                field: fk_commande
            210: 
                field: fk_contrat
            30: 
                field: datei
            31: 
                field: date_valid
            23: 
                field: total_ht
            24: 
                field: total_tva
            25: 
                field: total_ttc
            26: 
                field: fk_user_author
            27:
                field: fk_user_prisencharge
                edit: 1
            
lists_cols: 
    id: 
        field: id
    fk_commande:
        field: fk_commande
        display: nom_url
    ref:
        field: ref
    fk_contrat:
        field: fk_contrat
        display: nom_url
    fk_soc:
        field: fk_soc
        display: nom_url
    datei:
        field: datei
    date_valid:
        field: date_valid
    fk_user_author:
        field: fk_user_author
        display: nom_url
    fk_user_author:
        field: fk_user_prisencharge
        display: nom_url
    fk_user_modif:
        field: fk_user_modif
        display: nom_url
    fk_user_valid:
        field: fk_user_valid
        display: nom_url
    fk_statut:
        field: fk_statut
    duree:
        field: duree
    description:
        field: description
    note_public:
        field: note_public
    note_private:
        field: note_private
    total_ht:
        field: total_ht
    total_tva:
        field: total_tva
    total_ttc:
        field: total_ttc
    typeInter:
        field: extra37
    commercial: 
        label: Commercial
        value: 
            callback: displayCommercial
        search: 
            input: 
                type: search_user
                
lists:
    defaultAbstract: 
        checkboxes: 1
        configurable: 1
        sort_field: id
        sort_way: desc
        n: 25
        delete_btn: 0
        modal_view: default
        add_form_name: default
        filters_panel: default
        page_btn: 1
        edit_btn: 1
        cols:
            ref:
            fk_soc:
            fk_commande:
            fk_contrat:
            datei:
            date_valid:
            fk_user_author:
            fk_statut:
            duree:
            total_ht:
            typeInter:
            commercial:  
    default: 
        extends: defaultAbstract     
        cols:
            fk_soc:
                show:
                    callback:
                        method: getFieldFiltre
                        params:
                            - fk_soc
                            - show
        list_filters:
            callback:
                method: getFieldFiltre
                params:
                    - fk_soc
                    - filtre
        add_form_values:
            callback:
                method: getFieldFiltre
                params:
                    - fk_soc
                    - form_value
fields_tables: 
    infos:
        footer_extra_btn: 
              callback: getActionsButtons
        title: Infos FI
        icon: id-card
        rows: 
            - field: ref 
            - field: fk_statut 
              edit: 1
            - field: description 
              edit: 1
            - field: extra37
              edit: 1
            - field: note_public
              edit: 1
            - field: note_private
              edit: 1
    horaire:
        title: Horaire
        icon: fas_calendar-check
        rows: 
            - field: datei 
              edit: 1
            - field: extra38
              edit: 1
            - field: date_valid 
            - field: duree 
#            - label: Horaire arrivé AM
#              value:
#                  callback:
#                      method: displayExtra
#                      params:
#                          - extra24
#                          - time
            - field: extra24
              edit: 1
            - field: extra26
              edit: 1
            - field: extra25
              edit: 1
            - field: extra27
              edit: 1
    lien:
        title: Objets liées
        icon: link
        rows:
            - field: fk_soc 
              display: card
            - field: fk_commande
              display: nom_url
              edit: 1
            - field: fk_contrat 
              display: nom_url
              edit: 1
            - field: fk_user_author
              display: nom_url 
            - field: fk_user_prisencharge
              display: nom_url
              edit: 1
            - field: fi
            - field: action
    price:
        title: Prix
        icon: money
        rows:
            - field: total_ht 
            - field: total_tva 
            - field: total_ttc 
        show: 
            callback:
                method: canViewPrice    
            
        
views: 
    default: 
        objects_change_reload: Bimp_Demandinterdet
        rows: 
            - cols: 
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: infos
            
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: horaire
            
            - cols: 
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: lien
            
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: price
            - cols: 
                - type: list
                  list: 
                      name: default
                      children: lines
                      title: Lignes DI
                      
                     
        
cards:
    default: 
        type: user_card
        

