<?php
//
// File generated by Dolibarr installer 3.2.2 on 2012-10-31 15:00:57
//
// Take a look at conf.php.example file for an example of conf.php file
// and explanations for all possibles parameters.
//
$dolibarr_main_url_root='http://localhost/gle4';
$dolibarr_main_document_root='/var/www/gle4';
//$dolibarr_main_url_root_alt='http://localhost/gle4/custom';
//$dolibarr_main_document_root_alt='/var/www/gle4/custom';
$dolibarr_main_data_root='/var/www/documents/gle4';
$dolibarr_main_db_host='localhost';
$dolibarr_main_db_port='';
$dolibarr_main_db_name='gleNewB';
$dolibarr_main_db_prefix='llx_';
$dolibarr_main_db_user='root';
$dolibarr_main_db_pass='freeparty';
$dolibarr_main_db_type='mysqli';
$dolibarr_main_db_character_set='';
$dolibarr_main_db_collation='';
$dolibarr_main_authentication='dolibarr';

// Specific settings
$dolibarr_main_prod='0';
$dolibarr_nocsrfcheck='0';
$dolibarr_main_force_https='0';
$dolibarr_main_cookie_cryptkey='cfd9bdc064cc26c819e42b0bf8ecdbf5';
$dolibarr_mailing_limit_sendbyweb='0';

//$dolibarr_lib_ADODB_PATH='';
//$dolibarr_lib_GEOIP_PATH='';
//$dolibarr_lib_NUSOAP_PATH='';
//$dolibarr_lib_FPDI_PATH='';
//$dolibarr_lib_PHPEXCEL_PATH='';
//$dolibarr_lib_ODTPHP_PATH='';
//$dolibarr_lib_ODTPHP_PATHTOPCLZIP='';
//$dolibarr_lib_TCPDF_PATH='';
//$dolibarr_js_CKEDITOR='';
//$dolibarr_js_JQUERY='';
//$dolibarr_js_JQUERY_UI='';
//$dolibarr_js_JQUERY_FLOT='';

//$dolibarr_font_DOL_DEFAULT_TTF='';
//$dolibarr_font_DOL_DEFAULT_TTF_BOLD='';
?>