<?php
//
// File generated by Dolibarr installer 3.3.0-alpha on 2013-01-21 23:46:14
//
// Take a look at conf.php.example file for an example of conf.php file
// and explanations for all possibles parameters.
//
global $dolibarr_main_url_root;
$dolibarr_main_url_root="https://erp2.bimp.fr/doli16";
$dolibarr_main_document_root="/usr/local/www/test_tommy/doli16/htdocs/";
//$dolibarr_main_url_root_alt='http://192.168.1.10/newGle/htdocs/custom';
//$dolibarr_main_document_root_alt='/Library/WebServer/Documents/newGle/htdocs/custom';
$dolibarr_main_data_root='/usr/local/www/test_tommy/doli16/doc/';


define('BIMP_EXTENDS_ENTITY', 'bimp');
define('MOD_DEV', 1);
$dolibarr_main_db_port='3306';
$dolibarr_main_db_host='10.192.20.11';
$dolibarr_main_db_pass='IswAivwifCjOMZqASClegLWpBTGBuujW';
$dolibarr_main_db_name='TEST_DOLI16';
$dolibarr_main_db_user='root';

/*
$dolibarr_main_db_port='3306';
$dolibarr_main_db_host='10.192.20.221';
$dolibarr_main_db_host='10.192.20.111';
//$dolibarr_main_db_host='10.192.20.203';
$dolibarr_main_db_pass='JSpUuwRgQ5R768h';
$dolibarr_main_db_name='ERP_PROD_BIMP';
$dolibarr_main_db_user='root';*/

//define("USE_BDD_FOR_SESSION", 1);


/*define('CLOSE_DATE', '2018-07-01 20:30:00');
define('IP_ADMIN', '91.164.189.142');
*/

/*$dolibarr_main_db_port='3306';
$dolibarr_main_db_host='127.0.0.1';
$dolibarr_main_db_pass='admin@synopsis';
$dolibarr_main_db_name='GLE_PROD_BIMP';
$dolibarr_main_db_user='root';*/



/*$dolibarr_main_db_port='3307';
$dolibarr_main_db_pass='roland2007';
$dolibarr_main_db_name='gle360';*/
$dolibarr_main_db_prefix='llx_';
$dolibarr_main_db_type='mysqli';
$dolibarr_main_db_character_set='';
$dolibarr_main_db_collation='';
$dolibarr_main_authentication='dolibarr';
/*
$dolibarr_main_authentication='ldap';
$dolibarr_main_auth_ldap_host='ldaps://91.211.164.250';  // Plusieurs serveurs peuvent _tre ajouter en s_parant par une virgule.
$dolibarr_main_auth_ldap_port='636';    // Port
$dolibarr_main_auth_ldap_version='3';
$dolibarr_main_auth_ldap_servertype='activedirectory';  // openldap, activedirectory or egroupware
$dolibarr_main_auth_ldap_login_attribute='userPrincipalName';   // Ex: uid or samaccountname for active directory
$dolibarr_main_auth_ldap_dn='OU=Olys,OU=Filiales,OU=Groupe LDLC.COM,DC=siege,DC=ldlc,DC=com'; // Ex: ou=users,dc=my-domain,dc=com
$dolibarr_main_auth_ldap_filter = '(&(|(userPrincipalName=%1%)(sAMAccountName=%1%))(!(userAccountControl:1.2.840.113556.1.4.803:=2)))';
$dolibarr_main_auth_ldap_admin_login='CN=LDAP ERP GLE,CN=Users,DC=siege,DC=ldlc,DC=com';
$dolibarr_main_auth_ldap_admin_pass='4@8{4cuGJd';
$dolibarr_main_auth_ldap_debug='false';
define('LDAP_MOD_AD', 1);
*/
define('_ID_GROUP_NON_LDAP_', array(61));

//define('FORCE_NOT_CRYPT_PASS', 1);
//define('CLOSE_DATE', '2018-05-14 01:30:00');
define('IP_ADMIN', '78.217.11.123');

/*define('CLOSE_DATE', '2019-05-03 11:15');
define('IP_ADMIN', '91.164.189.142');*/


//define('DIR_SYNCH', '/var/GLE/XRAIDAUTO/GLE_8sens/');

//define("DIR_SYNCH", "/data/synchro/bimp/");

//define("MYSQL_SLOW_LOG", "/var/lib/mysql/hbg-pa41-slow.log");
define('MAX_TIME_LOG', 6);

define ("OLD_PRICE_FOURN", 1);
define('PRODUCTION_APPLE', true);

define("MOD_DEV_SYN", false);

//define('PORT_INTERNE', '443');

define('LIST_DOMAINE_VALID', serialize (array("divers-bimp.local", "synopsis-erp.com", "bimp-partners.fr", "bimp.fr", "finapro.fr", "reseaunance.com")));
define('DOMAINE_GROUP_ID', 3);

define('CHAINE_CALDAV', 'fgfjfhjfytcrt');

define('TAB_IP_INTERNE', '78.217.11.123, 88.125.45.38, 79.141.2.247, 82.239.30.139, 79.141.2.249,88.177.112.5,193.251.68.25,78.244.4.41,79.141.2.248,82.247.120.103,79.141.2.240,79.141.2.241,88.176.75.29,85.171.69.57');

//define('IMPORT_BDD_HOST', '127.0.0.1');
//define('IMPORT_BDD_USER', 'root');
//define('IMPORT_BDD_PASSE', 'roland2007');
//define('IMPORT_BDD_NAME', 'gle1main');

define('MOD_DEV_SYN_MAIL', 'tommy@bimp.fr');

// Specific settings
$dolibarr_main_prod='0';
$dolibarr_nocsrfcheck='1';
// $dolibarr_main_force_https='https://erp2.bimp.fr';
$dolibarr_main_force_https='0';
// define("REDIRECT_DOMAINE", $dolibarr_main_force_https);
$dolibarr_main_cookie_cryptkey='e2154149d51f59d1d79f5dc0ed6c5df2';
$dolibarr_mailing_limit_sendbyweb='0';

//$dolibarr_lib_ADODB_PATH='';
//$dolibarr_lib_GEOIP_PATH='';
//$dolibarr_lib_NUSOAP_PATH='';
//$dolibarr_lib_FPDI_PATH='';
//$dolibarr_lib_PHPEXCEL_PATH='';
//$dolibarr_lib_ODTPHP_PATH='';
//$dolibarr_lib_ODTPHP_PATHTOPCLZIP='';
//$dolibarr_lib_TCPDF_PATH='';
//$dolibarr_js_CKEDITOR='';
//$dolibarr_js_JQUERY='';
//$dolibarr_js_JQUERY_UI='';
//$dolibarr_js_JQUERY_FLOT='';

//$dolibarr_font_DOL_DEFAULT_TTF='';
//$dolibarr_font_DOL_DEFAULT_TTF_BOLD='';
?>
