<?php
//
// File generated by Dolibarr installer 3.4.2 on 20 nov. 2013
//
// Take a look at conf.php.example file for an example of conf.php file
// and explanations for all possibles parameters.
//
$dolibarr_main_url_root='http://localhost/gle_dev2';
$dolibarr_main_document_root='/var/www/html/gle_dev2';
//$dolibarr_main_url_root_alt='http://localhost/gle_dev/custom';
//$dolibarr_main_document_root_alt='/var/www/gle_dev/custom';
$dolibarr_main_data_root='/var/www/html/documents/capsim';
$dolibarr_main_db_host='127.0.0.1';
$dolibarr_main_db_port='3306';
$dolibarr_main_db_name='capsim_150921';
//$dolibarr_main_db_name = 'bimp_1505067';
//$dolibarr_main_db_name='capsim_150513';
$dolibarr_main_db_prefix='llx_';
$dolibarr_main_db_user='root';
$dolibarr_main_db_pass='x';
$dolibarr_main_db_type='mysqli';
$dolibarr_main_db_character_set='latin1';
$dolibarr_main_db_collation='latin1_swedish_ci';
$dolibarr_main_authentication='dolibarr';


//define('IMPORT_BDD_HOST', $dolibarr_main_db_host);
//define('IMPORT_BDD_USER', $dolibarr_main_db_user);
//define('IMPORT_BDD_PASSE', $dolibarr_main_db_pass);
//define('IMPORT_BDD_NAME', 'synopsis_oldBimp2');


define('MOD_DEV_SYN', 3);
define('MOD_DEV_SYN_MAIL', 'teufheur@outlook.fr');

define('PRODUCTION_APPLE', false);

//define('DIR_SYNCH', $dolibarr_main_data_root);

define('MAX_TIME_LOG', 4);

//define('CLOSE_DATE', '2014-09-06 06:00:00');
define('IP_ADMIN', '127.0.0.1');
//define('URL_REDIRECT', 'http://synopsis-erp.com/bimp');

define('TAB_IP_INTERNE', '127.0.0.11, 192.168.1.104');


define('PORT_INTERNE', '80');
// Specific settings
$dolibarr_main_prod='0';
$dolibarr_nocsrfcheck='0';
$dolibarr_main_force_https='0';
$dolibarr_main_cookie_cryptkey='24faebaabcdabac8b167f85dcfa3b2f7';
$dolibarr_mailing_limit_sendbyweb='0';

//$dolibarr_lib_TCPDF_PATH='';
//$dolibarr_lib_FPDF_PATH='';
//$dolibarr_lib_FPDI_PATH='';
//$dolibarr_lib_ADODB_PATH='';
//$dolibarr_lib_GEOIP_PATH='';
//$dolibarr_lib_NUSOAP_PATH='';
//$dolibarr_lib_PHPEXCEL_PATH='';
//$dolibarr_lib_ODTPHP_PATH='';
//$dolibarr_lib_ODTPHP_PATHTOPCLZIP='';
//$dolibarr_js_CKEDITOR='';
//$dolibarr_js_JQUERY='';
//$dolibarr_js_JQUERY_UI='';
//$dolibarr_js_JQUERY_FLOT='';

//$dolibarr_font_DOL_DEFAULT_TTF='';
//$dolibarr_font_DOL_DEFAULT_TTF_BOLD='';
?>
