table: bl_commande_shipment
common_fields: 1
icon: fas_shipping-fast

parent_module: bimpcommercial
parent_object: Bimp_Commande
parent_id_property: id_commande_client

labels: 
    name: expédition
    is_female: 1
        
objects: 
    commande_client:
        extends: commande
        instance: 
            id_object: 
                field_value: id_commande_client
    
    user_resp: 
        extends: user
        instance: 
            id_object: 
                field_value: id_user_resp
                
    avoir: 
        extends: facture
        instance: 
            id_object: 
                field_value: id_avoir
                
fields: 
    id_commande_client: 
        label: Commande client
        type: id_parent
        object: commande_client
        required: 1
        input: 
            type: hidden
        search: 
            input: 
                type: search_list
                search_list: 
                    table: commande
                    fields_search: rowid,ref
                    field_return_label: ref
                    field_return_value: rowid
        
    id_entrepot: 
        label: Entrepôt de départ
        type: id_object
        object: bimp_entrepot
        input: 
#            type: search_entrepot
             type: hidden
        search: 
            input: 
                type: search_entrepot
        
    num_livraison:
        label: Numéro de livraison
        type: int
        default_value: 1
        unsigned: 1
        
    ref: 
        label: Référence
        
    status: 
        label: Statut
        type: int
        values: 
            array: status_list
        default_value: 1
        
    date_shipped: 
        label: Date d'expédition
        type: datetime
        input: 
            display_now: 1
        
    id_contact:
        label: Destinataire
        type: id_object
        object: contact
        default_value: 0
        values: 
            array: contacts
        create_form: default
        create_form_values: 
            fields: 
                fk_soc: 
                    field_value: 
                        field_name: fk_soc
                        object: commande_client
            
    id_facture: 
        label: Facture
        type: id_object
        object: facture
        default_value: 0
        displays: 
            card_light: 
                type: card
                card: light
                
    id_avoir: 
        label: Avoir
        type: id_object
        object: avoir
        default_value: 0
        displays: 
            card_light: 
                type: card
                card: light
        
    signed: 
        label: Signé
        type: int
        values: 
            array: signed_values
        default_value: 0
        
    info: 
        label: Informations
        type: text        
        input: 
            note: 1
            auto_expand: 1
            rows: 3
            
    total_ht: 
        label: Total HT
        type: money
        default_value: 0
        
    total_ttc: 
        label: Total TTC
        type: money
        default_value: 0
        
    id_user_resp: 
        label: Responsable
        type: id_object
        object: user_resp
        required: 1
        input: 
            type: search_user
        default_value: 
            prop: 
                name: id
                object: 
                    global: user
        
forms: 
    default: 
        rows: 
            - field: ref
            - field: date_shipped
              show: 
                  callback: isShipped
            - field: id_commande_client
            - field: id_user_resp
            - field: id_entrepot
            - field: id_contact
            - field: info
            - custom: 1
              label: Lignes de commande
              show: 
                  callback: isNotLoaded
              input_name: lines
              content: 
                  callback: renderCommandeLinesForm
            
    edit: 
        rows: 
            - field: ref
            - field: date_shipped
              show: 
                  callback: isShipped
            - field: id_user_resp
            - field: id_contact
            - field: signed
            - field: info
            - field: id_facture
            
    validation: 
        rows: 
            - custom: 1
              hidden: 1
              input_name: validation
              input:
                  type: hidden
              value: 1
            - field: date_shipped
            - custom: 1
              label: Produits / Services inclus
              input_name: lines
              content: 
                  callback: renderLinesQties
                  
    facture: 
        modal_format: large
        rows: 
            replaced_ref: 
                custom: 1
                label: Ref facture remplacée
                input_name: replaced_ref
                input: 
                    type: text
                    help: Utiliser ce champ si perte des données de la facture remplacée
            client:
                custom: 1
                label: Client
                input_name: id_client
                data_type: id_object
                object: client
                card: default
                input: 
                    type: search_societe
                    societe_type: customer
            contact: 
                custom: 1
                label: Contact
                input_name: id_contact
                data_type: id
                input: 
                    type: select
                    options: 
                        callback: 
                            method: getClientContactsArray
                            object: commande
                depends_on: id_client
            libelle: 
                custom: 1
                show: 1
                label: Libellé
                input_name: libelle
                input: 
                    type: text
            id_entrepot: 
                custom: 1
                show: 0
                label: Entrepôt
                input_name: id_entrepot
                data_type: id
                input: 
                    type: search_entrepot
                value: 
                    field_value: id_entrepot
            ef_type: 
                custom: 1
                show: 0
                label: Secteur
                input_name: ef_type
                input: 
                    type: select
                    options: 
                        array: secteurs
            cond_reglement: 
                custom: 1
                label: Conditions de réglement
                input_name: cond_reglement
                value: 
                    callback: getCommandeCondReglement
                input: 
                    type: select_cond_reglement
            account:
                custom: 1
                label: Compte bancaire
                input_name: id_account
                data_type: id_object
                input: 
                    type: select_mysoc_account
                value: 
                    conf: bimpcaisse_id_default_account
            remises:
                custom: 1
                label: Avoirs client à utiliser
                input_name: id_remises_list
                input: 
                    multiple: 1
                    type: select_remises
                    id_client:
                        request_field: id_client
                depends_on: id_client
            public_note: 
                custom: 1
                label: Note publique
                input_name: note_public
                data_type: html
                input: 
                    type: html
            private_note: 
                custom: 1
                label: Note privée
                input_name: note_private
                data_type: html
                input: 
                    type: html
            lines: 
                custom: 1
                label: Quantités et équipements
                input_name: lines
                content: 
                    callback: renderFactureFormLinesInputs
        
    bulk_facture: 
        extends: facture
        rows: 
            client: 
                value: 
                    callback: 
                        method: getBulkFactureValue
                        params: 
                            - id_client
                required: 1
            contact: 
                value: 
                    callback: 
                        method: getBulkFactureValue
                        params: 
                            - id_contact
                input: 
                    options: 
                        callback: getBulkFactureClientContactsArray
            libelle: 
                value: 
                    callback:
                        method: getBulkFactureValue
                        params: 
                            - libelle
            id_entrepot: 
                show: 1
                required: 1
                value: 
                    field_value: unset
                    callback:
                        method: getBulkFactureValue
                        params: 
                            - id_entrepot
            ef_type: 
                show: 1
                required: 1
                value: 
                    callback:
                        method: getBulkFactureValue
                        params: 
                            - ef_type
            cond_reglement: 
                value: 
                    callback:
                        method: getBulkFactureValue
                        params: 
                            - cond_reglement
            public_note: 
                value: 
                    callback:
                        method: getBulkFactureValue
                        params: 
                            - note_public
            private_note: 
                value: 
                    callback:
                        method: getBulkFactureValue
                        params: 
                            - note_private
            lines: 
                content: 
                    callback: renderBulkFactureFormLinesInputs
    
    facture_edit: 
        rows: 
            - custom: 1
              label: Facture
              input_name: text
              content: 
                  callback: 
                      method: displayData
                      params: 
                          - id_facture
                          - card_light
            - custom: 1
              label: Quantités et équipements
              input_name: lines
              content: 
                  callback: renderFactureFormLinesInputs
                  
    vignettes: 
        rows: 
            - custom: 1
              label: Nombre de vignettes à générer
              data_type: qty
              input_name: qty
              input: 
                  type: qty
              value: 1
              
    pdf: 
        rows: 
            - custom: 1
              label: Chiffré
              data_type: bool
              input_name: chiffre
              input: 
                  type: toggle
              value: 1
            - custom: 1
              label: Detail
              data_type: bool
              input_name: detail
              input: 
                  type: toggle
              value: 1
                  
fields_tables: 
    data: 
        panel_header: 0
        rows: 
            - field: num_livraison
            - field: status
            - field: id_entrepot
              display: nom_url
            - field: id_user_resp
              edit: 1
            - field: id_contact
            - field: signed
              edit: 1
            - field: date_shipped
            - field: info
              edit: 1
            - field: id_facture
              display: card
              show: 
                  field_value: id_facture
            - field: id_avoir
              display: card
              show: 
                  field_value: id_avoir
            - field: total_ht
            - field: total_ttc
            
views: 
    default: 
        rows: 
            - cols: 
                - type: object_header
            - cols: 
                - type: fields_table
                  col_lg: 8
                  col_md: 7
                  col_sm: 12
                  fields_table: 
                      name: data
                      
    lines: 
        title: Produits / services inclus dans l'expédition
        rows: 
            - cols: 
                - type: custom
                  custom: 
                      callback: renderShipmentLines
             
filters: 
    id_commercial:
        label: Commercial
        data_type: id_object
        type: value
        input: 
          type: search_user
          
    id_product:
        label: Produit
        data_type: id_object
        type: value
        input: 
              type: search_product
          
    billed: 
        label: Facturée
        type: check_list
        items: 
            1: OUI
            0: NON
        exclude_btn: 0
        
filters_panels: 
    default: 
        filters: 
            parent:fk_soc:
            id_entrepot:
            parent:ef_type:
            id_commercial:
            user_create:
            id_product:
            num_livraison:
            ref:
            id_commande_client:
            status:
            date_shipped:
            parent:id_user_resp:
            total_ht:
            total_ttc:
            info:
            parent:fk_statut:
            parent:logistique_status:
            parent:shipment_status:
            parent:invoice_status:
            parent:date_commande:
            id_facture:
            billed:
              
lists_cols: 
    num_livraison:
        label: N°
        min_width: 30
    contact: 
        label: Destinataire
        value: 
            callback: displayContact
    commercial: 
        label: Commercial
        value: 
            callback: displayCommercial
    date_shipped: 
        label: Expédiée le
    signed: 
        edit: 1
        min_width: 45px
    pdf:
        label: Fichiers PDF
        value: 
            callback: 
                method: displayPdfButtons
                params: 
                    - 1
    parent:fk_statut: 
        label: St. Cmd
        display: icon
        min_width: 45
    parent:logistique_status: 
        label: Log. Cmd
        display: icon
        min_width: 45
    parent:shipment_status: 
        label: Exp. Cmd
        display: icon
        min_width: 45
    parent:invoice_status: 
        label: Fac. Cmd
        display: icon
        min_width: 45
        
lists: 
    default: 
        configurable: 1
        checkboxes: 1
        bulk_actions: 
            callback: getCommandesListbulkActions
        filters_panel: default
        sort_field: id
        sort_way: desc
        pagination: 1
        n: 10
        edit_btn: 1
        update_btn: 1
        edit_form: edit
        modal_view: default
        objects_change_reload: BR_Reservation
        extra_btn: 
            callback: getExtraBtn
        cols:
            ref:
            id_commande_client: 
            num_livraison:
            id_entrepot:
            status: 
            contact: 
            commercial: 
            total_ht: 
            date_shipped: 
            signed: 
            pdf:
            user_create:
        
    client: 
        extends: default
                    
    commandes: 
        configurable: 1
        checkboxes: 1
        bulk_actions: 
            callback: getCommandesListbulkActions
        enable_search: 0
        pagination: 0
        sort_field: id
        sort_way: asc
        n: 0
        edit_btn: 1
        update_btn: 1
        add_btn: 1
        add_btn_label: Nouvelle expédition
        add_form_name: default
        edit_form: default
        modal_view: default
        objects_change_reload: BR_Reservation,Bimp_CommandeLine,Bimp_Commande
        extra_btn: 
            callback: getExtraBtn
        cols:
            ref:
            num_livraison:
            id_entrepot:
            status: 
            contact: 
            date_shipped: 
            total_ht: 
            signed: 
            id_facture: 
            pdf:
                    
cards: 
    default: 
        title: nom
        status: status
        fields: 
            - label: Destinataire
              field: id_contact
              display: default
            - label: Entrepôt de départ
              field: id_entrepot
              display: nom_url
            - label: Infos
              field: info

searches:
    default: 
        fields_search: 
            - a.ref
            - c.ref
            - s.nom
        joins:
            commande: 
                table: commande
                on: c.rowid = a.id_commande_client
                alias: c
            s: 
                table: societe
                on: c.fk_soc = s.rowid
                alias: s
