table: br_commande_shipment
common_fields: 1
icon: fas_shipping-fast

parent_module: bimpcommercial
parent_object: Bimp_Commande
parent_id_property: id_commande_client

labels: 
    name: expédition
    is_female: 1
        
objects: 
    commande_client:
        extends: commande
        instance: 
            id_object: 
                field_value: id_commande_client
    
fields: 
    id_commande_client: 
        label: Commande client
        type: id_parent
        object: commande_client
        required: 1
        input: 
            type: hidden
        
    id_entrepot: 
        label: Entrepôt de départ
        type: id_object
        object: entrepot
        input: 
            type: search_entrepot
        
    num_livraison:
        label: Numéro de livraison
        type: int
        default_value: 1
        unsigned: 1
        
    status: 
        label: Statut
        type: int
        values: 
            array: status_list
        default_value: 1
        
    date_shipped: 
        label: Date d'expédition
        type: datetime
        
    id_contact:
        label: Destinataire
        type: id_object
        object: contact
        default_value: 0
        values: 
            array: contacts
            
    id_facture: 
        label: Facture
        type: id_object
        object: facture
        default_value: 0
        display: 
            card_light: 
                type: card
                card: light
        
    signed: 
        label: Signé
        type: int
        values: 
            array: signed_values
        default_value: 0
        
    info: 
        label: Informations
        type: text        
        input: 
            note: 1
            auto_expand: 1
            rows: 3
        
forms: 
    default: 
        rows: 
            - field: id_commande_client
            - field: id_entrepot
            - field: id_contact
            - field: info
            - custom: 1
              label: Lignes de commande
              show: 
                  callback: isNotLoaded
              input_name: lines
              content: 
                  callback: renderCommandeLinesForm
            
    edit: 
        rows: 
            - field: id_contact
            - field: signed
            - field: info
            
    validation: 
        rows: 
            - custom: 1
              hidden: 1
              input_name: validation
              input:
                  type: hidden
              value: 1
            - custom: 1
              label: Produits / Services inclus
              input_name: lines
              content: 
                  callback: renderLinesQties
                  
    facture: 
        rows: 
            - custom: 1
              label: Client
              input_name: id_client
              data_type: id_object
              object: client
              card: default
              input: 
                  type: search_societe
                  societe_type: customer
            - custom: 1
              label: Contact
              input_name: id_contact
              data_type: id
              input: 
                  type: select
                  options: 
                      callback: 
                          method: getClientContactsArray
                          object: commande
              depends_on: id_client
            - custom: 1
              label: Conditions de réglement
              input_name: cond_reglement
              value: 
                  callback: getCommandeCondReglement
              input: 
                  type: select_cond_reglement
            - custom: 1
              label: Compte financier
              input_name: id_account
              data_type: id_object
              input: 
                  type: select_mysoc_account
              required: 1
            - custom: 1
              label: Avoirs client à utiliser
              input_name: id_remises_list
              input: 
                  multiple: 1
                  type: select_remises
                  id_client:
                      request_field: id_client
              depends_on: id_client
            - custom: 1
              label: Note publique
              input_name: note_public
              data_type: text
              input: 
                  type: textarea
                  rows: 3
                  auto_expand: 1
            - custom: 1
              label: Note privée
              input_name: note_private
              data_type: text
              input: 
                  type: textarea
                  rows: 3
                  auto_expand: 1
            - custom: 1
              label: Quantités et équipements
              input_name: lines
              content: 
                  callback: renderFactureFormLinesInputs
                  
    facture_edit: 
        rows: 
            - custom: 1
              label: Facture
              content: 
                  callback: 
                      method: displayData
                      params: 
                          - id_facture
                          - card_light
            - custom: 1
              label: Quantités et équipements
              input_name: lines
              content: 
                  callback: renderFactureFormLinesInputs
                  
    vignettes: 
        rows: 
            - custom: 1
              label: Nombre de vignettes à générer
              data_type: qty
              input_name: qty
              input: 
                  type: qty
              value: 1
                  
fields_tables: 
    data: 
        panel: 0
        rows: 
            - field: num_livraison
            - field: status
            - field: id_contact
            - field: signed
              edit: 1
            - field: date_shipped
            - field: info
              edit: 1
            - field: id_facture
              display: card
              show: 
                  field_value: id_facture
            
views: 
    default: 
        rows: 
            - cols: 
                - type: object_common_fields
                  col_lg: 4
                  col_md: 5
                  col_sm: 12
                     
                - type: fields_table
                  col_lg: 8
                  col_md: 7
                  col_sm: 12
                  fields_table: 
                      name: data
                      
    lines: 
        title: Produits / services inclus dans l'expédition
        rows: 
            - cols: 
                - type: custom
                  custom: 
                      callback: renderShipmentLines
                      
lists_cols: 
    commande: 
        field: id_commande_client
        display: nom_url
    entrepot: 
        field: id_entrepot
        display: nom_url
    num_livraison:
        label: N°
        field: num_livraison
        max_width: 30px
    status: 
        field: status
    contact: 
        label: Destinataire
        value: 
            callback: displayContact
    commercial: 
        label: Commercial
        value: 
            callback: displayCommercial
    date: 
        label: Expédiée le
        field: date_shipped
    signed: 
        field: signed
        edit: 1
        max_width: 45px
    pdf:
        label: Fichiers
        value: 
            callback: 
                method: displayPdfButtons
                params: 
                    - 1
    facture: 
        field: id_facture
        display: nom_url
    total_ht: 
        label: Total HT
        value: 
            callback: displayTotalHT
    total_ttc: 
        label: Total TTC
        value: 
            callback: displayTotalTTC
                    
lists: 
    default: 
        configurable: 1
        sort_field: id
        sort_way: desc
        n: 25
        edit_btn: 1
        update_btn: 1
        edit_form: edit
        modal_view: default
        objects_change_reload: BR_Reservation,BR_ReservationShipment,BR_Service,BR_ServiceShipment
        extra_btn: 
            callback: getExtraBtn
        cols:
            commande: 
            num_livraison:
            entrepot:
            status: 
            contact: 
            commercial: 
            total_ht: 
            date: 
            signed: 
            pdf:
                    
    commandes: 
        configurable: 1
        checkboxes: 1
        bulk_actions: 
            callback: getCommandesListbulkActions
        enable_search: 0
        pagination: 0
        sort_field: id
        sort_way: asc
        n: 0
        edit_btn: 1
        update_btn: 1
        add_btn: 1
        add_btn_label: Nouvelle expédition
        add_form_name: default
        edit_form: default
        modal_view: default
        objects_change_reload: BR_Reservation,BR_ReservationShipment,BR_Service,BR_ServiceShipment
        extra_btn: 
            callback: getExtraBtn
        cols:
            num_livraison:
            entrepot:
            status: 
            contact: 
            date: 
            total_ht: 
            signed: 
            facture: 
            pdf:
                    
cards: 
    default: 
        title: nom
        status: status
        fields: 
            - label: Destinataire
              field: id_contact
              display: default
            - label: Entrepôt de départ
              field: id_entrepot
              display: nom_url
            - label: Infos
              field: info