table: bl_commande_fourn_reception
common_fields: 1
icon: fas_arrow-circle-down

parent_module: bimpcommercial
parent_object: Bimp_CommandeFourn
parent_id_property: id_commande_fourn

labels: 
    name: réception
    is_female: 1
        
objects:     
    user_resp: 
        extends: user
        instance: 
            id_object: 
                field_value: id_user_resp
                
    facture_fourn: 
        instance: 
            id_object: 
                field_value: id_facture
                
fields: 
    id_commande_fourn: 
        label: Commande fournisseur
        type: id_parent
        object: commande_fourn
        required: 1
        input: 
            type: hidden
        search: 
            input: 
                type: search_list
                search_list: 
                    table: commande_fournisseur
                    fields_search: rowid,ref
                    field_return_label: ref
                    field_return_value: rowid
        
    id_entrepot: 
        label: Entrepôt d'arrivée
        type: id_object
        object: entrepot
        input: 
#            type: search_entrepot
           type: hidden
        required: 1
        display: 
            default: 
                type: nom_url
                
    ref: 
        label: Référence BR
        required: 1
    
    status: 
        label: Statut
        type: int
        values: 
            array: status_list
        default_value: 0
            
    num_reception:
        label: Numéro de réception
        type: int
        default_value: 1
        unsigned: 1
        
    date_received: 
        label: Date de réception
        type: date
        input:
            type: date
            display_now: 1
        
    info: 
        label: Informations
        type: text        
        input: 
            auto_expand: 1
            rows: 1
            
    assign_lines_to_commandes_client:
        label: Assigner les équipements reçus aux commandes client d'origine
        type: bool
        default_value: 1
        
    total_ht: 
        label: Total HT
        type: money
        default_value: 0
        
    total_ttc: 
        label: Total TTC
        type: money
        default_value: 0
        
    id_user_resp: 
        label: Responsable
        type: id_object
        object: user_resp
        required: 1
        input: 
            type: search_user
        default_value: 
            prop: 
                name: id
                object: 
                    global: user
                    
    id_facture: 
        label: Facture
        type: id_object
        object: facture_fourn
        default_value: 0
        
forms: 
    default: 
        rows: 
            - field: id_commande_fourn
              hidden: 1
            - field: id_user_resp
            - field: id_entrepot
            - field: ref
            - field: assign_lines_to_commandes_client
            - field: info
            - field: date_received
                
#            - custom: 1
#              label: Lignes commande fournisseur
#              show: 
#                  callback: isNotLoaded
#              input_name: lines
#              content: 
#                  callback: renderCommandeFournLinesForm
                  
    validate: 
        rows: 
            - field: date_received
            - custom: 1
              label: Unités réceptionnées
              input_name: lines
              content: 
                  callback: renderDetailsView
                 
fields_tables: 
    data: 
        title: Infos
        panel: 1
        rows: 
            - field: id_commande_fourn
              display: card
            - field: ref
            - field: status
            - field: id_user_resp
              edit: 1
            - field: num_reception
            - field: id_entrepot
            - field: date_received
            - field: info
              edit: 1
            - field: total_ht
            - field: total_ttc
            - field: id_facture
              display: card
            
views: 
    default: 
        rows: 
            - cols: 
                - type: object_header
            
            - cols: 
                - type: fields_table
                  col_lg: 6
                  col_md: 8
                  fields_table: 
                      name: data
                      
    details: 
        modal_format: medium
        rows: 
            - cols: 
                - type: custom
                  custom: 
                      callback: renderDetailsView
                      
filters_panel: 
    default: 
        filters: 
            - field: fk_soc
              child: parent
            - field: ref
            - field: num_reception
            - field: id_entrepot
            - field: id_commande_fourn
            - field: status
            - field: date_received
            - field: total_ht
            - field: total_ttc
            - field: info
            - field: fk_statut
              child: parent
            - field: invoice_status
              child: parent
            
lists_cols: 
    user_resp: 
        field: id_user_resp
        display: nom_url
    commande: 
        field: id_commande_fourn
        display: nom_url
    num_reception:
        label: N°
        field: num_reception
        max_width: 30px
    ref: 
        field: ref
    entrepot: 
        field: id_entrepot
        display: nom_url
    status: 
        field: status
    date: 
        label: Reçue le
        field: date_received
    info: 
        field: info
        edit: 1
    total_ht: 
        field: total_ht
    total_ttc: 
        field: total_ttc
    fk_soc: 
        label: Fournisseur
        field: fk_soc
        child: parent
        display: nom_url
    commande_status: 
        label: Statut commande
        field: fk_statut
        child: parent
    commande_invoice_status: 
        label: Statut facturation commande
        field: invoice_status
        child: parent
    facture: 
        field: id_facture
        display: nom_url
                    
lists: 
    default: 
        checkboxes: 1
        item_checkbox: 
            callback: isFacturable
        configurable: 1
        filters_panel: default
        sort_field: id
        sort_way: desc
        pagination: 1
        n: 20
        edit_btn: 1
        delete_btn: 1
        update_btn: 1
        edit_form: edit
        modal_view: default
        objects_change_reload: Bimp_CommandeFourn,Bimp_FactureFourn,Bimp_CommandeFournLine,Bimp_FactureFournLine
        extra_btn: 
            callback: getListsExtraBtn
        bulk_actions: 
            - label: Créer une facture unique
              icon: fas_file-invoice-dollar
              onclick: selectedReceptionsFactureFourn($(this), 'list_id') 
        cols:
            commande: 
            num_reception:
            fk_soc:
            ref:
            date: 
            total_ht: 
            entrepot:
            facture:
                    
    commandes_fourn: 
        configurable: 1
        enable_search: 0
        pagination: 0
        sort_field: id
        sort_way: asc
        n: 0
        edit_btn: 1
        update_btn: 1
        add_btn: 1
        add_btn_label: Nouvelle réception
        add_form_name: default
        delete_btn: 1
        edit_form: default
        modal_view: default
        objects_change_reload: Bimp_CommandeFourn,Bimp_FactureFourn,Bimp_CommandeFournLine,Bimp_FactureFournLine
        extra_btn: 
            callback: getListsExtraBtn
        cols:
            num_reception:
            ref:
            status:
            date: 
            total_ht: 
            entrepot:
            info: 
            facture:
                    
cards: 
    default: 
        title: nom
        fields: 
            - label: N°
              field: num_reception
            - label: Ref. BR
              field: ref
            - label: Entrepôt
              field: id_entrepot
              display: nom_url
            - label: Infos
              field: info
