table: bl_commande_shipment
common_fields: 1
icon: fas_shipping-fast

parent_module: bimpcommercial
parent_object: Bimp_Commande
parent_id_property: id_commande_client

labels: 
    name: expédition
    is_female: 1
        
objects: 
    commande_client:
        extends: commande
        instance: 
            id_object: 
                field_value: id_commande_client
    
    user_resp: 
        extends: user
        instance: 
            id_object: 
                field_value: id_user_resp
                
    avoir: 
        extends: facture
        instance: 
            id_object: 
                field_value: id_avoir
                
fields: 
    id_commande_client: 
        label: Commande client
        type: id_parent
        object: commande_client
        required: 1
        input: 
            type: hidden
        search: 
            input: 
                type: search_list
                search_list: 
                    table: commande
                    fields_search: rowid,ref
                    field_return_label: ref
                    field_return_value: rowid
        
    id_entrepot: 
        label: Entrepôt de départ
        type: id_object
        object: entrepot
        input: 
#            type: search_entrepot
             type: hidden
        search: 
            input: 
                type: search_entrepot
        
    num_livraison:
        label: Numéro de livraison
        type: int
        default_value: 1
        unsigned: 1
        
    ref: 
        label: Référence
        
    status: 
        label: Statut
        type: int
        values: 
            array: status_list
        default_value: 1
        
    date_shipped: 
        label: Date d'expédition
        type: datetime
        input: 
            display_now: 1
        
    id_contact:
        label: Destinataire
        type: id_object
        object: contact
        default_value: 0
        values: 
            array: contacts
        create_form: default
        create_form_values: 
            fields: 
                fk_soc: 
                    field_value: 
                        field_name: fk_soc
                        object: commande_client
            
    id_facture: 
        label: Facture
        type: id_object
        object: facture
        default_value: 0
        display: 
            card_light: 
                type: card
                card: light
                
    id_avoir: 
        label: Avoir
        type: id_object
        object: avoir
        default_value: 0
        display: 
            card_light: 
                type: card
                card: light
        
    signed: 
        label: Signé
        type: int
        values: 
            array: signed_values
        default_value: 0
        
    info: 
        label: Informations
        type: text        
        input: 
            note: 1
            auto_expand: 1
            rows: 3
            
    total_ht: 
        label: Total HT
        type: money
        default_value: 0
        
    total_ttc: 
        label: Total TTC
        type: money
        default_value: 0
        
    id_user_resp: 
        label: Responsable
        type: id_object
        object: user_resp
        required: 1
        input: 
            type: search_user
        default_value: 
            prop: 
                name: id
                object: 
                    global: user
        
forms: 
    default: 
        rows: 
            - field: ref
            - field: date_shipped
              show: 
                  callback: isShipped
            - field: id_commande_client
            - field: id_user_resp
            - field: id_entrepot
            - field: id_contact
            - field: info
            - custom: 1
              label: Lignes de commande
              show: 
                  callback: isNotLoaded
              input_name: lines
              content: 
                  callback: renderCommandeLinesForm
            
    edit: 
        rows: 
            - field: ref
            - field: date_shipped
              show: 
                  callback: isShipped
            - field: id_user_resp
            - field: id_contact
            - field: signed
            - field: info
            
    validation: 
        rows: 
            - custom: 1
              hidden: 1
              input_name: validation
              input:
                  type: hidden
              value: 1
            - field: date_shipped
            - custom: 1
              label: Produits / Services inclus
              input_name: lines
              content: 
                  callback: renderLinesQties
                  
    facture: 
        rows: 
            client:
                custom: 1
                label: Client
                input_name: id_client
                data_type: id_object
                object: client
                card: default
                input: 
                    type: search_societe
                    societe_type: customer
            contact: 
                custom: 1
                label: Contact
                input_name: id_contact
                data_type: id
                input: 
                    type: select
                    options: 
                        callback: 
                            method: getClientContactsArray
                            object: commande
                depends_on: id_client
            libelle: 
                custom: 1
                show: 1
                label: Libellé
                input_name: libelle
                input: 
                    type: text
            id_entrepot: 
                custom: 1
                show: 0
                label: Entrepôt
                input_name: id_entrepot
                data_type: id
                input: 
                    type: search_entrepot
                value: 
                    field_value: id_entrepot
            ef_type: 
                custom: 1
                show: 0
                label: Secteur
                input_name: ef_type
                input: 
                    type: select
                    options: 
                        array: secteurs
            cond_reglement: 
                custom: 1
                label: Conditions de réglement
                input_name: cond_reglement
                value: 
                    callback: getCommandeCondReglement
                input: 
                    type: select_cond_reglement
            account:
                custom: 1
                label: Compte financier
                input_name: id_account
                data_type: id_object
                input: 
                    type: select_mysoc_account
                required: 1
            remises:
                custom: 1
                label: Avoirs client à utiliser
                input_name: id_remises_list
                input: 
                    multiple: 1
                    type: select_remises
                    id_client:
                        request_field: id_client
                depends_on: id_client
            public_note: 
                custom: 1
                label: Note publique
                input_name: note_public
                data_type: text
                input: 
                    type: textarea
                    rows: 3
                    auto_expand: 1
            private_note: 
                custom: 1
                label: Note privée
                input_name: note_private
                data_type: text
                input: 
                    type: textarea
                    rows: 3
                    auto_expand: 1
            lines: 
                custom: 1
                label: Quantités et équipements
                input_name: lines
                content: 
                    callback: renderFactureFormLinesInputs
        
    bulk_facture: 
        extends: facture
        rows: 
            client: 
                value: 
                    callback: getBulkFactureIdClient
                required: 1
            libelle: 
                value: 
                    callback: getBulkFactureLibelle
            id_entrepot: 
                show: 1
                required: 1
            ef_type: 
                show: 1
                required: 1
            lines: 
                content: 
                    callback: renderBulkFactureFormLinesInputs
    
    facture_edit: 
        rows: 
            - custom: 1
              label: Facture
              content: 
                  callback: 
                      method: displayData
                      params: 
                          - id_facture
                          - card_light
            - custom: 1
              label: Quantités et équipements
              input_name: lines
              content: 
                  callback: renderFactureFormLinesInputs
                  
    vignettes: 
        rows: 
            - custom: 1
              label: Nombre de vignettes à générer
              data_type: qty
              input_name: qty
              input: 
                  type: qty
              value: 1
                  
fields_tables: 
    data: 
        panel_header: 0
        rows: 
            - field: num_livraison
            - field: status
            - field: id_entrepot
              display: nom_url
            - field: id_user_resp
              edit: 1
            - field: id_contact
            - field: signed
              edit: 1
            - field: date_shipped
            - field: info
              edit: 1
            - field: id_facture
              display: card
              show: 
                  field_value: id_facture
            - field: id_avoir
              display: card
              show: 
                  field_value: id_avoir
            - field: total_ht
            - field: total_ttc
            
views: 
    default: 
        rows: 
            - cols: 
                - type: object_header
            - cols: 
                - type: fields_table
                  col_lg: 8
                  col_md: 7
                  col_sm: 12
                  fields_table: 
                      name: data
                      
    lines: 
        title: Produits / services inclus dans l'expédition
        rows: 
            - cols: 
                - type: custom
                  custom: 
                      callback: renderShipmentLines
                      
lists_cols: 
    ref: 
        field: ref
    user_resp: 
        field: id_user_resp
        display: nom_url
    commande: 
        field: id_commande_client
        display: nom_url
    client: 
        label: Client
        field: fk_soc
        child: parent
        display: nom_url
    entrepot: 
        field: id_entrepot
        display: nom_url
    secteur: 
        field: ef_type
        child: parent
    num_livraison:
        label: N°
        field: num_livraison
        max_width: 30px
    status: 
        field: status
    contact: 
        label: Destinataire
        value: 
            callback: displayContact
    commercial: 
        label: Commercial
        value: 
            callback: displayCommercial
    date: 
        label: Expédiée le
        field: date_shipped
    signed: 
        field: signed
        edit: 1
        max_width: 45px
    pdf:
        label: Fichiers PDF
        value: 
            callback: 
                method: displayPdfButtons
                params: 
                    - 1
    facture: 
        field: id_facture
        display: nom_url
    avoir: 
        field: id_avoir
        display: nom_url
    total_ht: 
        field: total_ht
    total_ttc: 
        field: total_ttc
    commande_status: 
        label: St. Cmd
        field: fk_statut
        child: parent
        display: icon
        min_width: 45px
        max_width: 45px
    commande_logistique_status: 
        label: Log. Cmd
        field: logistique_status
        child: parent
        display: icon
        min_width: 45px
        max_width: 45px
    commande_shipment_status: 
        label: Exp. Cmd
        field: shipment_status
        child: parent
        display: icon
        min_width: 45px
        max_width: 45px
    commande_invoice_status: 
        label: Fac. Cmd
        field: invoice_status
        child: parent
        display: icon
        min_width: 45px
        max_width: 45px
                    
filters_panels: 
    default: 
        filters: 
            - field: fk_soc
              child: parent
            - field: id_entrepot
            - field: ef_type
              child: parent
            - field: id_commercial
              custom: 1
              field: id_commercial
              label: Commercial
              data_type: id_object
              type: value
              input: 
                type: search_user
            - field: line_product
              custom: 1
              field: id_product
              label: Produit
              data_type: id_object
              type: value
              input: 
                    type: search_product
            - field: num_livraison
            - field: ref
            - field: id_commande_client
            - field: status
            - field: date_shipped
            - field: id_user_resp
              child: parent
            - field: total_ht
            - field: total_ttc
            - field: info
            - field: fk_statut
              child: parent
            - field: logistique_status
              child: parent
            - field: shipment_status
              child: parent
            - field: invoice_status
              child: parent
            - field: date_commande
              child: parent
            - field: id_facture
            
lists: 
    default: 
        configurable: 1
        checkboxes: 1
        bulk_actions: 
            callback: getCommandesListbulkActions
        filters_panel: default
        sort_field: id
        sort_way: desc
        pagination: 1
        n: 10
        edit_btn: 1
        update_btn: 1
        edit_form: edit
        modal_view: default
        objects_change_reload: BR_Reservation,BR_ReservationShipment,BR_Service,BR_ServiceShipment
        extra_btn: 
            callback: getExtraBtn
        cols:
            ref:
            commande: 
            num_livraison:
            entrepot:
            status: 
            contact: 
            commercial: 
            total_ht: 
            date: 
            signed: 
            pdf:
                    
    commandes: 
        configurable: 1
        checkboxes: 1
        bulk_actions: 
            callback: getCommandesListbulkActions
        enable_search: 0
        pagination: 0
        sort_field: id
        sort_way: asc
        n: 0
        edit_btn: 1
        update_btn: 1
        add_btn: 1
        add_btn_label: Nouvelle expédition
        add_form_name: default
        edit_form: default
        modal_view: default
        objects_change_reload: BR_Reservation,Bimp_CommandeLine,Bimp_Commande
        extra_btn: 
            callback: getExtraBtn
        cols:
            ref:
            num_livraison:
            entrepot:
            status: 
            contact: 
            date: 
            total_ht: 
            signed: 
            facture: 
            pdf:
                    
cards: 
    default: 
        title: nom
        status: status
        fields: 
            - label: Destinataire
              field: id_contact
              display: default
            - label: Entrepôt de départ
              field: id_entrepot
              display: nom_url
            - label: Infos
              field: info
