table: bl_commande_fourn_reception
common_fields: 1
icon: fas_arrow-circle-down

parent_module: bimpcommercial
parent_object: Bimp_CommandeFourn
parent_id_property: id_commande_fourn

labels: 
    name: réception
    is_female: 1
        
objects: 
    user_resp: 
        extends: user
        instance: 
            id_object: 
                field_value: id_user_resp
                
    facture_fourn: 
        instance: 
            id_object: 
                field_value: id_facture
                
fields: 
    id_commande_fourn: 
        label: Commande fournisseur
        type: id_parent
        object: commande_fourn
        required: 1
        input: 
            type: hidden
        search: 
            input: 
                type: search_list
                search_list: 
                    table: commande_fournisseur
                    fields_search: rowid,ref
                    field_return_label: ref
                    field_return_value: rowid
        
    id_entrepot: 
        label: Entrepôt d'arrivée
        type: id_object
        object: bimp_entrepot
        input: 
           type: hidden
        search: 
            input: 
                type: search_entrepot
                
        required: 1
        displays: 
            default: 
                type: nom_url
                
    ref: 
        label: Référence BR
        required: 1
    
    status: 
        label: Statut
        type: int
        values: 
            array: status_list
        default_value: 0
            
    num_reception:
        label: Numéro de réception
        type: int
        default_value: 1
        unsigned: 1
        
    date_received: 
        label: Date de réception
        type: date
        input:
            type: date
            display_now: 1
        
    info: 
        label: Informations
        type: text        
        input: 
            auto_expand: 1
            rows: 1
            
    assign_lines_to_commandes_client:
        label: Assigner les équipements reçus aux commandes client d'origine
        type: bool
        default_value: 1
        
    total_ht: 
        label: Total HT
        type: money
        default_value: 0
        
    total_ttc: 
        label: Total TTC
        type: money
        default_value: 0
        
    id_user_resp: 
        label: Responsable
        type: id_object
        object: user_resp
        required: 1
        input: 
            type: search_user
        default_value: 
            prop: 
                name: id
                object: 
                    global: user
                    
    id_facture: 
        label: Facture
        type: id_object
        object: facture_fourn
        default_value: 0
        
    stock_out: 
        label: Stock boutique
        type: bool
        default_value: 0
        
forms: 
    default: 
        rows: 
            - field: id_commande_fourn
              hidden: 1
            - field: id_user_resp
            - field: id_entrepot
            - field: ref
            - field: assign_lines_to_commandes_client
            - field: info
            - field: date_received
                
#            - custom: 1
#              label: Lignes commande fournisseur
#              show: 
#                  callback: isNotLoaded
#              input_name: lines
#              content: 
#                  callback: renderCommandeFournLinesForm
    split: 
        title: Scinder en deux réceptions
        icon: fas_object-ungroup
        rows: 
            - field: ref
            - field: date_received
            - field: info
            - custom: 1
              label: Quantités et équipements à déplacer dans la nouvelle réception
              input_name: lines
              content: 
                  callback: renderSplitDetailForm
            
    validate: 
        rows: 
            - field: date_received
            
#           *** Temporaire: 
            - custom: 1
              label: S'agit-il d'une réception de DECEMBRE ? 
              input_type: string
              input_name: is_sept
              input: 
                  type: select
                  options:
                      '': ''
                      oui: OUI
                      non: NON
              required: 1
#          ****************

            - custom: 1
              show: 
                  callback: canEditStockOut
              label: Stocks boutiques
              input_name: stock_out
              input: 
                  type: select
                  options:
                      '': ''
                      oui: OUI
                      non: NON
              required: 1
              value: ''

            - custom: 1
              label: Unités réceptionnées
              input_name: lines
              content: 
                  callback: renderDetailsView
                 
fields_tables: 
    data: 
        title: Infos
        panel: 1
        rows: 
            - field: id_commande_fourn
              display: card
            - field: ref
            - field: status
            - field: id_user_resp
              edit: 1
            - field: num_reception
            - field: id_entrepot
            - field: date_received
            - field: info
              edit: 1
            - field: total_ht
            - field: total_ttc
            - field: id_facture
              display: card
            
views: 
    default: 
        rows: 
            - cols: 
                - type: object_header
            
            - cols: 
                - type: fields_table
                  col_lg: 6
                  col_md: 8
                  fields_table: 
                      name: data
                      
    details: 
        modal_format: medium
        rows: 
            - cols: 
                - type: custom
                  custom: 
                      callback: renderDetailsView
              
filters: 
    billed:
        label: Facturée
        type: check_list
        items: 
            1: OUI
            0: NON
        exclude_btn: 0
        
    id_facture:
        label: Facture fournisseur
        
filters_panel: 
    default: 
        filters: 
            parent:fk_soc:
            ref:
            num_reception:
            id_entrepot:
            id_commande_fourn:
            status:
            date_received:
            billed:
            id_facture:
            total_ht:
            total_ttc:
            info:
            parent:fk_statut:
            parent:invoice_status:
            
lists_cols: 
    num_reception:
        label: N°
        min_width: 30
    date_received: 
        label: Reçue le
    info: 
        edit: 1
    parent:fk_soc: 
        label: Fournisseur
    parent:fk_statut:
        label: Statut commande
    parent:invoice_status: 
        label: Statut facturation commande
                    
lists: 
    default: 
        checkboxes: 1
        item_checkbox: 
            callback: isFacturable
        configurable: 1
        filters_panel: default
        sort_field: id
        sort_way: desc
        pagination: 1
        n: 20
        edit_btn: 1
        delete_btn: 1
        update_btn: 1
        edit_form: edit
        modal_view: default
        objects_change_reload: Bimp_CommandeFourn,Bimp_FactureFourn,Bimp_CommandeFournLine,Bimp_FactureFournLine
        extra_btn: 
            callback: getListsExtraBtn
        bulk_actions: 
            - label: Créer une facture unique
              icon: fas_file-invoice-dollar
              onclick: selectedReceptionsFactureFourn($(this), 'list_id') 
        cols:
            id_commande_fourn: 
            num_reception:
            parent:fk_soc:
            ref:
            date_received: 
            total_ht: 
            id_entrepot:
            id_facture:
                    
    fourn: 
        extends: default
        cols: 
            parent:fk_soc: unset
            
    commandes_fourn: 
        checkboxes: 1
        item_checkbox: 
            callback: isFacturable
        bulk_actions: 
            - label: Créer une facture unique
              icon: fas_file-invoice-dollar
              onclick: selectedReceptionsFactureFourn($(this), 'list_id') 
        configurable: 1
        enable_search: 0
        pagination: 0
        sort_field: id
        sort_way: asc
        n: 0
        edit_btn: 1
        update_btn: 1
        add_btn: 1
        add_btn_label: Nouvelle réception
        add_form_name: default
        delete_btn: 1
        edit_form: default
        modal_view: default
        objects_change_reload: Bimp_CommandeFourn,Bimp_FactureFourn,Bimp_CommandeFournLine,Bimp_FactureFournLine
        extra_btn: 
            callback: getListsExtraBtn
        cols:
            num_reception:
            ref:
            status:
            date_received: 
            total_ht: 
            id_entrepot:
            info: 
            id_facture:
                    
cards: 
    default: 
        title: nom
        fields: 
            - label: N°
              field: num_reception
            - label: Ref. BR
              field: ref
            - label: Entrepôt
              field: id_entrepot
              display: nom_url
            - label: Infos
              field: info

searches:
    default: 
        fields_search: 
            - a.ref
            - cf.ref
            - s.nom
        joins:
            commande_fourn: 
                table: commande_fournisseur
                on: cf.rowid = a.id_commande_fourn
                alias: cf
            s: 
                table: societe
                on: cf.fk_soc = s.rowid
                alias: s
