
table: bl_inventory_2
controller: inventory2
icon: fas_clipboard-list

header_btn:
    callback: getActionsButtons

header_list_name: default
header_edit_form: change_filter


list_page_url: 
    controller: index

nom_url: 
    syntaxe: Inventaire #<ref>
    card: default
    
labels:
    name: inventaire

objects:
    lines:
        relation: hasMany
        instance: 
            bimp_object: InventoryLine2
        delete: 
            callback: isAdmin
            
    warehouse_type: 
        relation: hasMany
        instance: 
            bimp_object: InventoryWarehouse
        delete: 
            callback: isAdmin
           
    entrepot: 
        instance: 
            id_object: 
                field_value: fk_warehouse
                
    bimp_entrepot: 
        instance: 
            id_object: 
                field_value: fk_warehouse
                
    package: 
        instance: 
            id_object: unset
            
    package_nouveau: 
        extends: package
        instance: 
            id_object: 
                field_value: id_package_nouveau
                
    package_vol: 
        extends: package
        instance: 
            id_object: 
                field_value: id_package_vol

fields: 
    fk_warehouse:
        label: Entrepôt
        type: id_object
        object: bimp_entrepot
        default_value: 0
        input:
            type: search_entrepot 

    date_opening: 
        label: Date d'ouverture
        type: datetime
        required: 0
        search:
            type: date_range
            
    date_closing: 
        label: Date de fermeture
        type: datetime
        required: 0
        search:
            type: date_range
            
    status:
        label: Statut
        type: int
        values: 
            array: status_list
        edit: 0
        
    type: 
        label: Type
        type: int
        values: 
            array: types
        edit: 0

    id_package_nouveau:
        label: Package nouveau
        type: id_object
        object: package_nouveau
        default_value: 0
                
    id_package_vol:
        label: Package vol
        type: id_object
        object: package_vol
        default_value: 0
                
    filter_inventory:
        label: Inventaire partiel
        type: bool
             
    incl_categorie:
        label: Categorie inclu
        type: items_list

    excl_categorie:
        label: Categorie exclu
        type: items_list

    incl_collection:
        label: Collection inclu
        type: items_list

    excl_collection:
        label: Collection exclu
        type: items_list

    incl_nature:
        label: Nature inclu
        type: items_list
                    
    excl_nature:
        label: Nature exclu
        type: items_list
                    
    incl_famille:
        label: Famille inclu
        type: items_list
                    
    excl_famille:
        label: Famille exlu
        type: items_list
                    
    incl_gamme:
        label: Gamme inclu
        type: items_list
                    
    excl_gamme:
        label: Gamme exclu
        type: items_list
                   
    incl_product:
        label: Produit inclu
        type: items_list
        
    excl_product:
        label: Produit exclu
        type: items_list

        
fields_tables: 
    default: 
#        footer_extra_btn:
#            callback: getActionsButtons
#        panel: 1
        title: Informations
        icon: info-circle
        objects_change_reload: Inventory2
        rows:
            - field: fk_warehouse
              display: nom_url
            - field: type
            - field: date_opening
            - field: date_closing
            - label: Complétion
              value:
                callback: displayCompletion
            - field: user_create
            
            - label: Mouvements
              value: 
                  callback: renderMouvementTrace
                  
            - label: Package vol
              value: 
                  callback: renderPackageVol
                  
            - label: Package nouveau
              value: 
                  callback: renderPackageNouveau
                  
            # Cat
            - label: Catégorie inclu
              value:
                callback:
                      method: displayCats
                      params:
                          - incl_categorie
                          - categorie
                          
            - label: Catégorie exclu
              value:
                callback:
                      method: displayCats
                      params:
                          - excl_categorie
                          - categorie
                          
            # Collection
            - label: Collection inclu
              value:
                callback:
                      method: displayCats
                      params:
                          - incl_collection
                          - collection
                          
            - label: Collection exclu
              value:
                callback:
                      method: displayCats
                      params:
                          - excl_collection
                          - collection
                          
            # Nature              
            - label: Nature inclu
              value:
                callback:
                      method: displayCats
                      params:
                          - incl_nature
                          - nature
                          
            - label: Nature exclu
              value:
                callback:
                      method: displayCats
                      params:
                          - excl_nature
                          - nature
                          
            # Famille
            - label: Famille inclu
              value:
                callback:
                      method: displayCats
                      params:
                          - incl_famille
                          - famille
                          
            - label: Famille exclu
              value:
                callback:
                      method: displayCats
                      params:
                          - excl_famille
                          - famille
                          
            # Gamme
            - label: Gamme inclu
              value:
                callback:
                      method: displayCats
                      params:
                          - incl_gamme
                          - gamme
                          
            - label: Gamme exclu
              value:
                callback:
                      method: displayCats
                      params:
                          - excl_gamme
                          - gamme
                          
            # Produit
            - label: Produit inclu
              value:
                callback:
                      method: displayProduct
                      params:
                          - incl_product
                          
            - label: Produit exclu
              value:
                callback:
                      method: displayProduct
                      params:
                          - excl_product
            
views:
    default:
        objects_change_reload: lines
        edit_form: change_filter
        delete_btn: 1
        rows:
            - cols: 
                  - type: fields_table
                    col_lg: 7
                    col_md: 8
                    col_sm: 12
                    fields_table:
                        name: default  
                        
forms:
    default:
        title: Création inventaire
        rows: 
            warehouse_and_type:
              custom: 1
              label: Entrepôt / Type
              input_name: warehouse_and_type
              input: 
                  type: custom
                  content: 
                      callback: 
                          method: renderWarehouseAndType
                  multiple: 1
              edit: 1
              
            filter_inventory:
              custom: 1
              label: Inventaire partiel
              input_name: filter_inventory
              input: 
                  type: toggle
              
              # Produits
            inclu_product:
              custom: 1
              label: Produit inclu
              input_name: inut
              content: 
                callback:
                    method: renderAddProduct
                    params:
                        - incl_product
              display_if:
                  field_name: filter_inventory
                  show_values: 1
                  
            exclu_product:
              custom: 1
              label: Produit exclu
              input_name: inut2
              content: 
                callback:
                    method: renderAddProduct
                    params:
                        - excl_product
              display_if:
                  field_name: filter_inventory
                  show_values: 1
                        
#            Categorie
            incl_categorie:
              custom: 1
              label: Catégorie inclu
              input_name: incl_categorie
              input: 
                  type: custom
                  content:
                      callback: 
                          method: renderCats
                          params:
                              - incl_categorie
                              - categorie
                  multiple: 1
              display_if:
                  field_name: filter_inventory
                  show_values: 1
                  
            excl_categorie :
              custom: 1
              label: Catégorie exclu
              input_name: excl_categorie
              input: 
                  type: custom
                  content:
                      callback: 
                          method: renderCats
                          params:
                              - excl_categorie
                              - categorie
                  multiple: 1
              display_if:
                  field_name: filter_inventory
                  show_values: 1
                  
 #            Collection
            incl_collection:
              custom: 1
              label: Collection inclu
              input_name: incl_collection
              input: 
                  type: custom
                  content:
                      callback: 
                          method: renderCats
                          params:
                              - incl_collection
                              - collection
                  multiple: 1
              display_if:
                  field_name: filter_inventory
                  show_values: 1
                  
            excl_collection:
              custom: 1
              label: Collection exclu
              input_name: excl_collection
              input: 
                  type: custom
                  content:
                      callback: 
                          method: renderCats
                          params:
                              - excl_collection
                              - collection
                  multiple: 1
              display_if:
                  field_name: filter_inventory
                  show_values: 1
                
 #            Nature
            incl_nature:
              custom: 1
              label: Nature inclu
              input_name: incl_nature
              input: 
                  type: custom
                  content:
                      callback: 
                          method: renderCats
                          params:
                              - incl_nature
                              - nature
                  multiple: 1
              display_if:
                  field_name: filter_inventory
                  show_values: 1
                  
            excl_nature:
              custom: 1
              label: Nature exclu
              input_name: excl_nature
              input: 
                  type: custom
                  content:
                      callback: 
                          method: renderCats
                          params:
                              - excl_nature
                              - nature
                  multiple: 1
              display_if:
                  field_name: filter_inventory
                  show_values: 1                
                
 #            Famille
            incl_famille:
              custom: 1
              label: Famille inclu
              input_name: incl_famille
              input: 
                  type: custom
                  content:
                      callback: 
                          method: renderCats
                          params:
                              - incl_famille
                              - famille
                  multiple: 1
              display_if:
                  field_name: filter_inventory
                  show_values: 1
                  
            excl_famille:
              custom: 1
              label: Famille exclu
              input_name: excl_famille
              input: 
                  type: custom
                  content:
                      callback: 
                          method: renderCats
                          params:
                              - excl_famille
                              - famille
                  multiple: 1
              display_if:
                  field_name: filter_inventory
                  show_values: 1      
                
 #            Gamme
            incl_gamme:
              custom: 1
              label: Gamme inclu
              input_name: incl_gamme
              input: 
                  type: custom
                  content:
                      callback: 
                          method: renderCats
                          params:
                              - incl_gamme
                              - gamme
                  multiple: 1
              display_if:
                  field_name: filter_inventory
                  show_values: 1
                  
            excl_gamme:
              custom: 1
              label: Gamme exclu
              input_name: excl_gamme
              input: 
                  type: custom
                  content:
                      callback: 
                          method: renderCats
                          params:
                              - excl_gamme
                              - gamme
                  multiple: 1
              display_if:
                  field_name: filter_inventory
                  show_values: 1     
              

    confirm_close: 
        rows: 
            - custom: 1
              label: Date du mouvement de stock
              input_name: date_mouvement
              type: datetime
              input:
                type: datetime
                display_now: 1
            - custom: 1
              label: Opérations produits sérialisés
              input_name: inut
              content: 
                callback: renderDifferenceEquipments
            - custom: 1
              label: Opérations produits non sérialisés
              input_name: inut
              content: 
                callback: renderDifferenceProduct
                
    change_filter:
        extends: default
        rows: 
            warehouse_and_type: unset
            
            delete_scan_and_exp:
              custom: 1
              label: Forcer l'édition
              input_name: delete_scan_and_exp
              input: 
                  type: toggle
                  help: Option pour confirmer la suppression de ligne de scan et d'attendus. Il est recommandé de l'activer <strong>uniquement</strong> quand l'erreur apparait.
    csv: 
        rows: 
            - custom: 1
              label: Fichier CSV
              input_name: csv_file
              required: 1
              input: 
                  type: file_upload
                  help: '1ère colonne: ref<br/>2ème colonne: qtés'
            - custom: 1
              label: Délimiteur
              input_name: separator
              required: 1
              value: ';'
              input: 
                  type: text
            - custom: 1
              label: Tester seulement le fichier (aucune insertion en base)
              input_name: test_only
              data_type: bool
              input: 
                  type: toggle
              value: 0
            
lists_cols: 
    displayCompletion:
        label: Complétion
        value:
            callback: displayCompletion
            
lists:
    default:
        checkboxes: 1
        sort_field: id
        sort_way: desc
        n: 10
        add_form_name: default
        view_btn: 1
        page_btn: 1
        delete_btn: 1
        modal_view: default
        cols:
            id:
            status:
            fk_warehouse:
            date_opening:
            date_closing:
            displayCompletion:
        
cards: 
    default: 
        title: nom
        status: status
        fields: 
            - label: Ouvert le
              field: date_opening
            - label: Fermé le
              field: date_closing
            - label: Package vol
              field: id_package_vol
            - label: Package nouveau
              field: id_package_nouveau
        view_btn: 1
        
searches: 
    default: 
        fields_search: 
            - a.id
            - e.ref
            - e.lieu
        fields_return: 
            - a.id
            - e.ref
            - e.lieu
        label_syntaxe: 'Inventaire #<a.id> - Entrepôt: <e.ref> <e.lieu>'