extends: 
    module: bimpcore
    object_name: Bimp_Product
    
lists:
    inventory_stock:
        extends: default
        add_btn: 0
        sort_field: ref
        sort_way: asc
        cols:
            type: unset
            stock: unset
            price: unset
            tva: unset
            
            nb_scanned:
                label: Nombre scanné
                value:
                    callback: renderNbScanned
            stock_entrepot:
                show: 
                    callback:
                        method: isAdmin
                label: Stock
                value: 
                    callback: renderStock