table: bs_apple_part
common_fields: 0

parent_object: BS_SAV
parent_id_property: id_sav

labels: 
    name: pièce Apple
    name_plur: pièces Apple
    is_female: 1
    
objects: 
    issue: 
        relation: hasOne
        delete: 0
        instance: 
            bimp_object: 
                module: bimpsupport
                name: BS_Issue
            id_object: 
                field_value: id_issue
            
fields: 
    id_sav: 
        label: SAV
        type: id_parent
    id_issue: 
        label: Problème
        type: id_object
        objec: issue
    label: 
        label: Libellé
    part_number:
        label: Référence
    new_part_number: 
        label: Nouvelle ref. 
    comptia_code: 
        label: Code CompTIA
        values: 
            array: comptia_codes
    comptia_modifier: 
        label: Modificateur CompTIA
        values: 
            array: comptia_modifiers
        default_value: A
#    qty: 
#        label: Quantité
#        type: qty
#        unsigned: 1
#        min: 1
#        default_value: 1
    component_code: 
        label: Code pièce
        values: 
            array: componentsTypes
    stock_price: 
        label: Prix stock
        type: money
    exchange_price: 
        label: Prix d'échange
        type: money
    warranty:
        label: Garantie
        type: select
        default_value: 0
        values:
            0: Hors Garantie
            1: Garantie Apple
            2: Garantie LDLC
    no_order: 
        label: Commande de stock
        type: bool
        default_value: 0
    price_options: 
        label: Prix Spéciaux
        type: json
    price_type: 
        label: Prix applicable
        values: 
            array: price_types
        default_value: EXCHANGE
    is_tier: 
        label: Composant tiers
        type: bool
        default_value: 0
    not_invoiced: 
        label: Non facturé
        type: bool
        default_value: 0

forms: 
    select_issue: 
        title: Attribution à un problème composant
        rows: 
            - custom: 1
              label: Problème composant
              input_name: id_issue
              data_type: id
              required: 1
              input: 
                  type: select
                  options: 
                      callback: getSavIssuesArray
                      
fields_tables: 
    default: 
        panel: 1
        panel_header: 0
        rows: 
            - field: part_number
            - field: new_part_number
            - field: label
#            - field: qty
#              edit: 1
            - field: price_type
              edit: 1
            - field: warranty
              edit: 1
            - field: no_order
              edit: 1
            - field: is_tier
            - field: not_invoiced
            - field: type_for_price
            - custom: 1
              label: Type pour tarification
              value: 
                callback: getThisCategProdApple

views: 
    default: 
        modal_format: small
        rows: 
            - cols: 
                - type: fields_table
                  fields_table: default
                  
lists: 
    default: 
        title: Panier de composants Apple
        icon: shopping-basket
        checkboxes:
            callback: isCartEditable
        bulk_actions:
            - label: supprimer les composants sélectionnés
              icon: fas_trash-alt
              onclick: deleteSelectedObjects('list_id', $(this))
        enable_search: 0
        sort_field: id
        sort_way: asc
        n: 25
        delete_btn: 
            callback: isCartEditable
        update_btn: 1
        cols: 
            label: 
                label: Nom
            part_number: 
                label: Réf.
            comptia_code: 
                edit: 1
                max_width: 250
            comptia_modifier: 
                max_width: 180
                edit: 1
#            qty: 
#                label: Qté
#                edit: 
#                    callback: isCartEditable
            warranty: 
                edit: 
                    callback: isCartEditable
            price_type: 
                edit: 
                    callback: isCartEditable
            no_order: 
                edit: 
                    callback: isCartEditable
                    
    gsx_v2:
        title: Composants Apple
        icon: shopping-basket
        checkboxes:
            callback: isCartEditable
        bulk_actions:
            - label: supprimer les composants sélectionnés
              icon: fas_trash-alt
              onclick: deleteSelectedObjects('list_id', $(this))
        enable_search: 0
        sort_field: id
        sort_way: asc
        n: 25
        delete_btn: 
            callback: isCartEditable
        update_btn: 1
        cols: 
            label: 
                label: Nom
            part_number: 
                label: Réf.
#            qty: 
#                label: Qté
#                edit: 
#                    callback: isCartEditable
            warranty: 
                edit: 
                    callback: isCartEditable
            price_type: 
                edit: 
                    callback: isCartEditable
            no_order: 
                edit: 
                    callback: isCartEditable
        
    no_issue: 
        extends: gsx_v2
        title: Composants Apple (ancienne version)
        extra_btn: 
            callback: getNoIssueExtaButtons
        