table: bs_centre_sav
icon: fas_store
labels:
    name: centre SAV
    name_plur: centres SAV
    
fields:
    label:
        label: Libellé
        required: 1
    tel:
        label: Téléphone
        required: 1
    email:
        label: E-mail
        required: 1
    shipTo:
        label: Ship To
        required: 1
    zip:
        label: Code Postal
        required: 1
    address:
        label: Adresse
        required: 1
        type: text
    id_entrepot:
        label: Entrepot
        required: 1
        type: id_object
        object: entrepot
        default_value: 0
        input:
            type: search_entrepot

lists:
    default:
        title: Liste des centres SAV
        configurable: 1
        checkboxes: 1
        bulk_actions:
            -   label: Supprimer les centres SAV sélectionnés
                icon: fas_trash-alt
                onclick: deleteSelectedObjects('list_id', $(this))
        sort_field: date_create
        sort_way: desc
        n: 0
        add_form_name: default
        add_btn_label: Nouveau centre SAV
        edit_btn: 1
        edit_form: edit
        delete_btn: 1
        page_btn: 1
        modal_view: default
        cols:
            label:
            id_entrepot:
            address:
            zip:
            shipTo:
            email:
            tel:

fields_tables:
    infos:
        title: Informations
        icon: info-circle
        rows:
            label:
                field: label
            id_entrepot:
                field: id_entrepot
            address:
                field: address
            zip:
                field: zip
            shipTo:
                field: shipTo
            email:
                field: email
            tel:
                field: tel
views:
    default:
        title:
            callback: getRef
        objects_change_reload: BS_CentreSav
        rows:
            - cols:
                  - type: object_header
            - cols:
                  - type: fields_table
                    col_lg: 12
                    col_mg: 12
                    fields_table:
                        name: infos
#    infos:
#        panel: 0
#        objects_change_reload: BS_CentreSav
#        rows:
#            - type: fields_table
#              col_lg: 12
#              col_mg: 12
#              fields_table:
#                  name: infos

