table: bs_centre_sav
icon: fas_store
controller: centre
in_cache_serveur: 1
entity_name: entrepot

nom_url:
    syntaxe: <code> - <label>

name_syntaxe: <code> - <label>

labels:
    name: centre SAV
    name_plur: centres SAV

objects:
    centre_rattachement:
        instance:
            bimp_object:
                module: bimpsupport
                name: BS_CentreSav
            id_object:
                field_value: id_centre_rattachement
    groupe_associe:
        instance:
            bimp_object:
                module: bimpcore
                name: Bimp_UserGroup
            id_object:
                field_value: id


fields:
    code:
        label: Code
        required: 1
    label:
        label: Libellé
        required: 1
    tel:
        label: Téléphone
        required: 1
    email:
        label: E-mail
        required: 1
    shipTo:
        label: Ship To
        required: 1
    zip:
        label: Code Postal
        required: 1
    town:
        label: Ville
        required: 1

    address:
        label: Adresse
        required: 1
        type: text
    id_entrepot:
        label: Entrepot
        required: 1
        type: id_object
        object: entrepot
        default_value: 0
        input:
            type: search_entrepot
    active:
        label: Actif
        type: bool
        default_value: 1
    id_centre_rattachement:
        label: Centre de rattachement
        type: id_object
        object: centre_rattachement
        default_value: 0
    token:
        label: Token Ecologic
    id_group:
        label: Groupe associé au centre
        type: id_object
        object: groupe_associe
        default_value: 0
        input:
            type: search_group
    warning:
        label: Warning
        type: text
        
    rdv_allowed: 
        label: RDV SAV autorisés
        type: bool
        default_value: 1

lists:
    default:
        title: Liste des centres SAV
        configurable: 1
        checkboxes: 1
        bulk_actions:
            -   label: Supprimer les centres SAV sélectionnés
                icon: fas_trash-alt
                onclick: deleteSelectedObjects('list_id', $(this))
        sort_field: date_create
        sort_way: desc
        n: 0
        add_form_name: default
        add_btn_label: Nouveau centre SAV
        edit_btn: 1
        edit_form: edit
        delete_btn: 1
        page_btn: 1
        modal_view: default
        cols:
            code:
            label:
            id_entrepot:
            address:
            zip:
            town:
            shipTo:
            email:
            tel:
            active:
                edit: 1
            rdv_allowed: 
                edit: 1

fields_tables:
    infos:
        title: Informations
        icon: info-circle
        rows:
            code:
                field: code
            label:
                field: label
            id_entrepot:
                field: id_entrepot
            id_centre_rattachement:
                field: id_centre_rattachement
            address:
                field: address
            zip:
                field: zip
            town:
                field: town
            shipTo:
                field: shipTo
            email:
                field: email
            tel:
                field: tel
            active:
                field: active
                edit: 1
            rdv_allowed: 
                field: rdv_allowed
                edit: 1
            token:
                field: token
            id_group:
                field: id_group
            warning:
                field: warning

views:
    default:
        title:
            callback: getName
#            callback: getCode

        objects_change_reload: BS_CentreSav
        rows:
            - cols:
                  - type: object_header
            - cols:
                  - type: fields_table
                    col_lg: 12
                    col_mg: 12
                    fields_table:
                        name: infos


list_page_url:
    controller: index
    url_params:
        tab: centre

header_list_name: default
