table: bs_inter
parent_id_property: id_ticket
parent_object: BS_Ticket

icon: fas_user-clock
labels:
    name: intervention
    is_female: 1

objects: 
    ticket: 
        relation: hasOne
        delete: 0
        instance: 
            bimp_object: BS_Ticket
            id_object: 
                field_value: id_ticket
                
    tech_user: 
        relation: hasOne
        delete: 0
        instance: 
            bimp_object:
                module: bimpcore
                name: Bimp_User
            id_object: 
                field_value: tech_id_user
                
fields:
    id_ticket:
        label: Ticket
        type: id_parent
        object: ticket
        input: 
            type: hidden
        required: 1
            
    tech_id_user:
        label: Technicien
        type: id_object
        input: 
            type: search_user
        object: tech_user
        sort_option: 
            default: 
                label: nom utilisateur
                join_field: lastname
                
    timer:
        label: Durée
        type: time_last
        input: 
            type: timer
        default_value: 0
        display: 
            default: 
                type: timer
        searchable: 0
        
    priorite:
        label: Priorité
        type: int
        values: 
            array: priorities
        required: 1
    
    status: 
        label: Statut
        type: int
        values: 
            array: status
        required: 1
                    
    description:
        label: Description
        type: text
        input:
            rows: 3
            auto_expand: 1
        sortable: 1
        searchable: 1
    
list:
    title: Interventions
    checkboxes: 1
    bulk_actions: 
        - label: Supprimer les interventions sélectionnées
          icon: trash
          onclick: deleteSelectedObjects('list_id', $(this));
          btn_class: deleteSelectedObjects
    sort_field: id
    sort_way: desc
    n: 10
    cols:
        id:
            label: ID
            field: id
        user_create:
            label: Créé par
            field: user_create
        date_create:
            label: Début
            field: date_create
        description:
            field: description
        tech_user: 
            label: Technicien
            field: tech_id_user
        duree:
            field: timer
        priorite:
            field: priorite
            edit: 1
        status:
            field: status
            edit: 1
    add_form_name: default
    edit_btn: 1
    update_btn: 1
    delete_btn: 1
    inline_view: default
    page_btn: 1

fields_tables: 
    infos: 
        panel_header: 0
        rows:
            - field: id_ticket
              display: card
            - field: tech_id_user
              display: card
            - field: timer
            - field: priorite
              edit: 1
            - field: status
              edit: 1
            - field: description
              edit: 1
                
views:
    default: 
        title: nom
        edit_form: default
        delete_btn: 1
        panel_header: 0
        rows: 
            - cols:
                - type: object_header
            - cols: 
                - type: fields_table
                  col_lg: 8
                  col_md: 12
                  fields_table:
                      name: infos
                - type: custom
                  col_lg: 4
                  col_md: 12
                  custom:
                      callback: renderChronoView
                      
    card:
        rows:
            - cols:
                  - type: fields_table
                    col_lg: 12
                    fields_table:
                        panel: 1
                        name: infos
        
views_lists: 
    user_currents:
        title: Vos interventions en cours
        item_view: card
        view_btn: 1
        add_btn: 0
        edit_form: default
        item_col_lg: 4
        item_col_md: 6
        item_modal_view: default
        list_filters: 
            callback: getUserCurrentIntersFilters
        