table: bs_inter
parent_id_property: id_ticket
parent_object: BS_Ticket

icon: fas_user-clock
labels:
    name: intervention
    is_female: 1

objects:                 
    tech_user: 
        extends: user
        instance: 
            id_object: 
                field_value: tech_id_user
                
fields:
    id_ticket:
        label: Ticket
        type: id_parent
        object: ticket
        input: 
            type: hidden
        required: 1
            
    tech_id_user:
        label: Technicien
        type: id_object
        input: 
            type: search_user
        default_value: 
            prop: 
                name: id
                object: 
                    global: user
        object: tech_user
        sort_option: 
            default: 
                label: nom utilisateur
                join_field: lastname
                
    timer:
        label: Durée
        type: time_last
        input: 
            type: timer
        default_value: 0
        display: 
            default: 
                type: timer
        searchable: 0
        
#    priorite:
#        label: Priorité
#        type: int
#        values: 
#            array: priorities
#        required: 1
    
    status: 
        label: Statut
        type: int
        values: 
            array: status
        default_value: 1
                    
    description:
        label: Description problème
        type: text
        input:
            rows: 3
            auto_expand: 1
        sortable: 0
        searchable: 0
        
    resolution: 
        label: Résolution
        type: text
        input: 
            rows: 3
            auto_expand: 1

forms: 
    default:
        rows: 
            - field: tech_id_user
              show: 
                  callback: isNotLoaded
#            - field: priorite
            - field: description
            - custom: 1
              show: 
                  callback: isNotLoaded
              label: Déclencher le chrono
              data_type: bool
              input_name: start_timer
              value: 1
              input:
                  type: toggle
            - field: status
              show: 
                  callback: isLoaded
            - field: timer
              show: 
                  callback: isLoaded
                  
    resolution: 
        rows: 
            - field: resolution
                  
list:
    title: Liste des interventions
    checkboxes: 1
    bulk_actions: 
        - label: Supprimer les interventions sélectionnées
          icon: fas_trash-alt
          onclick: deleteSelectedObjects('list_id', $(this));
          btn_class: deleteSelectedObjects
    objects_change_reload: BS_Ticket
    sort_field: id
    sort_way: desc
    n: 10
    cols:
        id:
            label: ID
            field: id
        user_create:
            label: Créé par
            field: user_create
        date_create:
            label: Début
            field: date_create
        description:
            field: description
        tech_user: 
            label: Technicien
            field: tech_id_user
        duree:
            field: timer
#        priorite:
#            field: priorite
#            edit: 1
        status:
            field: status
            edit: 1
    add_form_name: default
    add_btn: 
        callback: isCreatable
    edit_btn: 1
    update_btn: 1
    delete_btn: 1
    inline_view: default
    inline_view_item: 
        request: id_inter
    page_btn: 1

fields_tables: 
    infos: 
        panel_header: 0
        rows:
            - field: id_ticket
              display: card
            - field: tech_id_user
              display: card
            - field: timer
#            - field: priorite
#              edit: 1
            - field: status
              edit: 1
            - field: description
              edit: 1
            - field: resolution
              edit: 1
                
views:
    default: 
        title: nom
        edit_form: default
        delete_btn: 1
        objects_change_reload: BS_Ticket
        rows: 
            - cols:
                - type: object_header
            - cols: 
                - type: fields_table
                  col_lg: 8
                  col_md: 12
                  fields_table:
                      name: infos
                - type: custom
                  col_lg: 4
                  col_md: 12
                  custom:
                      callback: renderChronoView
                      
    card:
        rows:
            - cols:
                  - type: fields_table
                    col_lg: 12
                    fields_table:
                        panel: 1
                        name: infos
        
views_lists: 
    user_currents:
        objects_change_reload: BS_Ticket
        title: Vos interventions en cours
        item_view: card
        view_btn: 1
        add_btn: 0
        edit_form: default
        item_col_lg: 4
        item_col_md: 6
        item_modal_view: default
        list_filters: 
            callback: getUserCurrentIntersFilters
        
