table: bs_pret
icon: mobile

parent_module: bimpcore
parent_object: Bimp_Client
parent_id_property: id_client

labels: 
    name: prêt de matériel
    name_plur: prêts de matériel
    
objects: 
    equipment:
        instance: 
            id_object: unset
            
    sav: 
        relation: hasOne
        delete: 0
        instance: 
            bimp_object: BS_SAV
            id_object: 
                field_value: id_sav
                
    products: 
        relation: hasMany
        delete: 1
        instance: 
            bimp_object: BS_PretProduct

associations: 
    equipments:
        object: equipment
        label: Equipements concernés
        display: 
            default: 
                type: callback
        input: 
            type: select
            options: 
                array: equipments

fields: 
    id_client: 
        label: Client
        type: id_parent
        input: 
            type: search_societe
            societe_type: customer
        display_if: 
            field_name: id_sav
            show_values: 0
    id_sav: 
        label: SAV
        type: id_object
        object: sav
        input: 
            type: search_list
            search_list:
                table: bs_sav s
                field_return_value: s.id
                field_return_label: s.ref
                fields_search: s.id,s.ref
        default_value: 0
    id_entrepot: 
        label: Entrepot
        type: id_object
        object: entrepot
        input: 
            type: search_entrepot
    code_centre: 
        label: Centre
        values: 
            array: centres
    ref: 
        label: Référence
    date_begin: 
        label: Début du prêt
        type: date
        required: 1
    date_end: 
        label: Fin du prêt
        type: date
        required: 1
    returned: 
        label: Restitué
        type: bool
        default_value: 0
    caution: 
        label: Chèque de caution
        type: bool
        default_value: 0
        
forms: 
    default: 
        rows: 
            - field: id_sav
            - field: id_entrepot
              display_if: 
                  field_name: id_sav
                  show_values: 0,
            - field: id_client
              display_if: 
                  field_name: id_sav
                  show_values: 0,
            - field: date_begin
            - field: date_end
            - field: caution
            - association: equipments
#            - object: products
#              multiple: 1

    sav: 
        rows: 
            - field: id_sav
              hidden: 1
            - field: date_begin
            - field: date_end
            - field: caution
            - association: equipments
#            - object: products
#              multiple: 1

fields_tables: 
    default: 
        panel: 1
        panel_header: 0
        rows: 
            - field: id_client
              display: nom_url
            - field: id_sav
              display: nom_url
              show: 
                  field_value: id_sav
            - field: id_entrepot
              display: nom_url
            - field: code_centre
              show: 
                  field_value: id_sav
            - association: equipments
            - field: date_begin
            - field: date_end
            - field: returned
              edit: 1
            - field: caution
              edit: 1

views: 
    default:
        rows: 
            - cols: 
                - type: object_header
            - cols: 
                - type: fields_table
                  fields_table: 
                      name: default
#            - cols: 
#                - type: list
#                  list: 
#                      name: default
#                      children: products
                
lists: 
    default: 
        title: Matériels prêtés
        icon: mobile
        checkboxes: 1
        list_filters: 
            callback: getListFilters
        add_form_values: 
            fields: 
                id_entrepot: 
                    request: id_entrepot
        bulk_actions:
            - label: Supprimer les prêts sélectionnés
              icon: fas_trash-alt
              onclick: deleteSelectedObjects('list_id', $(this))
        sort_field: id
        sort_way: desc
        n: 25
        add_form_name: default
        delete_btn: 1
        update_btn: 1
        edit_btn: 1
        modal_view: default
        cols: 
            entrepot: 
                field: id_entrepot
                display: nom_url
            ref: 
                field: ref
            client: 
                field: id_client
                display: nom_url
            sav: 
                field: id_sav
                display: nom_url
            date_end: 
                field: date_end
            returned: 
                field: returned
                edit: 1
            caution: 
                field: caution
                
    sav: 
        title: Matériels prêtés pour ce SAV
        icon: mobile
        checkboxes: 1
        bulk_actions:
            - label: Supprimer les prêts sélectionnés
              icon: fas_trash-alt
              onclick: deleteSelectedObjects('list_id', $(this))
        enable_search: 0
        sort_field: id
        sort_way: desc
        n: 25
        delete_btn: 1
        update_btn: 1
        add_form_name: sav
        modal_view: default
        edit_btn: 1
        extra_btn: 
            callback: getListExtraBtn
        cols: 
            ref: 
                field: ref
            date_begin: 
                field: date_begin
            date_end: 
                field: date_end
            caution: 
                field: caution
            returned: 
                field: returned
                edit: 1
    