table: bs_sav_pret
icon: mobile

parent_object: BS_SAV
parent_id_property: id_sav

labels: 
    name: prêt
    
objects: 
    equipment:
        relation: hasOne
        delete: 0
        instance: 
            bimp_object: 
                module: bimpequipment
                name: Equipment
            id_object: 
                field_value: id_equipment
    client: 
        relation: hasOne
        delete: 0
        instance: 
            bimp_object: 
                module: bimpcore
                name: Bimp_Societe
            id_object: 
                field_value: id_client

associations: 
    equipments:
        object: equipment
        label: Equipements concernés
        display: 
            default: 
                type: callback
        input: 
            type: select
            options: 
                array: equipments

fields: 
    id_sav: 
        label: SAV
        type: id_parent
        input: 
            type: search_list
            search_list:
                table: bs_sav s
                field_return_value: s.id
                field_return_label: s.ref
                fields_search: s.id,s.ref
    code_centre: 
        label: Centre
        values: 
            array: centres
    ref: 
        label: Référence
    id_client: 
        label: Client
        type: id_object
        object: client
        input: 
            type: hidden
        search: 
            input: 
                type: search_societe
                societe_type: customer
    date_begin: 
        label: Début du prêt
        type: datetime
        required: 1
    date_end: 
        label: Fin du prêt
        type: datetime
        required: 1
    returned: 
        label: Restitué
        type: bool
        default_value: 0
        
forms: 
    default: 
        rows: 
            - field: id_sav
              hidden: 1
            - association: equipments
              required: 1
            - field: date_begin
            - field: date_end
          
fields_tables: 
    default: 
        rows: 
            - field: id_sav
              display: nom_url
            - field: code_centre
            - association: equipments
            - field: id_client
              display: nom_url
            - field: date_begin
            - field: date_end
            - field: returned

views: 
    default:
        rows: 
            - cols: 
                - type: object_header
            - cols: 
                - type: fields_table
                  fields_table: 
                      name: default
                      panel: 0
                
lists: 
    default: 
        title: Matériels prêtés
        icon: mobile
        checkboxes: 1
        bulk_actions:
            - label: Supprimer les prêts sélectionnés
              icon: fas_trash-alt
              onclick: deleteSelectedObjects('list_id', $(this))
        sort_field: id
        sort_way: desc
        n: 25
        delete_btn: 1
        update_btn: 1
        edit_btn: 1
        modal_view: default
        cols: 
            centre: 
                field: code_centre
            ref: 
                field: ref
            sav: 
                field: id_sav
                display: nom_url
            client: 
                field: id_client
                display: nom_url
            date_end: 
                field: date_end
            returned: 
                field: returned
                edit: 1
                
    sav: 
        title: Matériels prêtés pour ce SAV
        icon: mobile
        checkboxes: 1
        bulk_actions:
            - label: Supprimer les prêts sélectionnés
              icon: fas_trash-alt
              onclick: deleteSelectedObjects('list_id', $(this))
        enable_search: 0
        sort_field: id
        sort_way: desc
        n: 25
        delete_btn: 1
        update_btn: 1
        add_form_name: default
        modal_view: default
        edit_btn: 1
        extra_btn: 
            callback: getListExtraBtn
        cols: 
            ref: 
                field: ref
            date_begin: 
                field: date_begin
            date_end: 
                field: date_end
            returned: 
                field: returned
                edit: 1
    