table: bs_ticket
controller: ticket

icon: fas_headset
header_list_name: default
header_btn: 
    callback: getHeaderButtons
    
list_page_url: 
    controller: index
    url_params: 
        tab: default
            
labels:
    name: ticket hotline
    name_plur: tickets hotline

objects:
    contrat:
        card: 
            title: 
                object_prop: ref
            view_btn: 1
                
    user_resp: 
        extends: user
        instance: 
            id_object: 
                field_value: id_user_resp
                
    inters:
        relation: hasMany
        delete: 1
        instance: 
            bimp_object: BS_Inter
        
    notes:
        relation: hasMany
        delete: 0
        instance:
            bimp_object: BS_Note
                
    files:
        instance:
            bimp_object:
                module: bimpcore
                name: BimpFile
                
        list: 
            filters:
                parent_module: bimpsupport
                parent_object_name: BS_Ticket
                
        add_form: 
            name: upload
            values:
                fields: 
                    parent_module: bimpsupport
                    parent_object_name: BS_Ticket
            
associations:
    equipments:
        object: equipment
        depends_on: id_contrat
        label: Equipements concernés
        display: 
            default: 
                type: callback
        list: 
            array: equipments

fields:    
    id_contrat:
        label: Contrat
        type: id_object
        object: contrat
        input: 
            type: search_list
            search_list:
                table: contrat
                field_return_value: a.rowid
                field_return_label: a.ref
                join: societe s
                join_on: a.fk_soc s.rowid
                join_return_label: s.nom
                filters: 
                    callback: getContratInputFilters
                options:    
                    default:
                        label: Recherche par client
                        fields_search: s.nom,s.code_client
                        join: societe s
                        join_on: a.fk_soc = s.rowid
                        join_return_label: s.nom
                        help: Entrez le nom ou le code d'un client
                    by_ref:
                        label: Recherche par référence contrat
                        fields_search: a.ref,a.rowid
                        join: societe s
                        join_on: a.fk_soc = s.rowid
                        join_return_label: s.nom
                        help: Entrez la référence ou l'ID d'un contrat
        display_if: 
            field_name: no_contrat
            hide_values: 1
    id_client:
        label: Client
        type: id_object
        object: client
        create_form: client_light
        input: 
            type: search_societe
            societe_type: customer
            help: Entrez le nom ou la référence d'un client pour effectuer une recherche
        display_if:
            fields_names: no_contrat,no_client
            no_contrat:
                show_values: 1
            no_client:
                hide_values: 1
        depends_on: id_contrat
        search:
            input: 
                type: search_societe
                societe_type: customer       
    id_contact:
        label: Contact
        type: id_object
        object: contact
        create_form: default
        create_form_values: 
            fields: 
                fk_soc: 
                    callback: getPostIdClient
                
        values: 
            array: client_contacts
        depends_on: id_client_contrat,id_client
        display_if: 
            field_name: no_client
            hide_values: 1
        search:
            input:
                type: search_list
                search_list:
                    table: socpeople
                    field_return_value: rowid
                    field_return_label: lastname,firstname
                    fields_search: lastname,firstname
                    label_syntaxe: <label_1> <label_2>               
    id_user_resp: 
        label: Responsable
        type: id_object
        object: user_resp
        input: 
            type: hidden
        default_value:
            prop:
                name: id
                object: 
                    global: user
        search:
            input: 
                type: search_user
    ticket_number:
        label: N° ticket
        type: string
        required: 0
        search:
            input: 
                type: text
            type: value_part
            search_on_key_up: 1
        input: 
            type: hidden
    priorite: 
        label: Priorité
        type: int
        default_value: 1
        values: 
            array: priorities
        display: 
            icon:
                icon_only: 1
    impact:
        label: Impact
        type: int
        values: 
            array: impacts
        default_value: 1
        display: 
            icon:
                icon_only: 1
    cover:
        label: Type de couverture
        type: int
        values: 
            array: cover_types
        input: 
            options:
                array: coverTypesInput
        depends_on: no_contrat
        display: 
            icon:
                icon_only: 1
    status: 
        label: Statut
        type: int
        values: 
            array: status_list
        default_value: 1
    appels_timer:
        label: Durée totale des appels payants
        type: time_last
        input: 
            type: timer
        default_value: 0
        display: 
            default: 
                type: timer
        searchable: 0 
    sujet:
        label: Sujet ticket
        
forms: 
    default:
        rows: 
            - custom: 1
              label: Client sans contrat
              input_name: no_contrat
              data_type: bool
              input: 
                  type: toggle
              value:
                  callback: hasNoContrat
            - custom: 1
              label: Pas de client
              input_name: no_client
              data_type: bool
              input: 
                  type: toggle
              value:
                  callback: hasNoClient
              display_if: 
                  field_name: no_contrat
                  show_values: 1
            - field: id_contrat
            - custom: 1
              input_name: id_client_contrat
              content: 
                  callback: getClientContratInput
              label: Client 
              depends_on: id_contrat,id_client,no_contrat,no_client
              display_if: 
                  fields_names: no_contrat,id_contrat
                  no_contrat: 
                      show_values: 0
                  id_contrat: 
                      hide_values: 0,
              value: 0
            - field: id_client
            - field: id_contact
            - field: sujet
            - field: priorite
            - field: status
            - field: impact
            - field: cover
#            - association: equipments
#              label: Equipements concernés
#              display_if: 
#                  field_name: id_contrat
#                  hide_values: 0,
#              depends_on: id_contrat
            - custom: 1
              label: Notifier par e-mail
              input_name: mails_to
              input: 
                  type: check_list
                  items: 
                      callback:
                          method: getNotificationsList
                          params: 
                              operation: create
                  value: 
                      array: comm,client,tech
#            - custom: 1
#              label: Appel payant du client en cours
#              data_type: bool
#              input_name: start_timer
#              input:
#                  type: toggle
            - object: inters
              multiple: 1
    
#    edit:
#        rows:
#            - field: id_contact
#            - field: status
#            - field: impact
#            - field: cover
#            - field: appels_timer
#            - association: equipments
#              label: Equipements concernés
#              display_if: 
#                  field_name: id_contrat
#                  hide_values: 0,
#              depends_on: id_contrat
              
    close_inters: 
        rows: 
            - custom: 1
              label: Interventions à fermer
              input_name: inters_to_close
              input: 
                  type: check_list
                  items: 
                      array: openInters
              value: 
                  callback: 
                      method: getChildrenList
                      params: 
                          name: inters
                          filters: 
                              status: 
                                  operator: !=
                                  value: 2
                                                
fields_tables: 
    infos: 
        title: Informations
        icon: info-circle
        rows: 
            - field: ticket_number
            - label: Durée totale interventions
              value:
                  callback: displayDureeTotale
#            - field: appels_timer
            - field: priorite
              edit: 1
            - field: impact
              edit: 1
            - field: cover
              edit: 1
            - field: status
              edit: 1
            - field: sujet
              edit: 1
              
    objects:
        title: Elements liés
        icon: share-alt
        rows:
            - field: id_user_resp
              display: card
            - field: id_contrat
              display: card
            - label: Client
              field: id_client
              display: card
            - field: id_contact
              display: card
            - association: equipments
              label: Equipements concernés
              display: card
              
views: 
    default:
        delete_btn: 1
        edit_form: default
        objects_change_reload: BS_Inter
        rows:
            - cols: 
#                  - type: rows
#                    col_lg: 5
#                    col_md: 6
#                    col_sm: 12
#                    rows: 
#                        - cols:
                  - type: fields_table
                    col_lg: 6
                    col_md: 6
                    fields_table: 
                        name: infos
#                        - cols: 
#                            - type: custom
#                              col_lg: 12
#                              custom:
#                                  callback: renderChronoView
                  - type: fields_table
                    col_lg: 6
                    col_md: 6
                    fields_table:
                        name: objects
                        
    full: 
        objects_change_reload: BS_Inter
        rows: 
            - cols: 
                - type: object_header
            - cols: 
#                - type: rows
#                  col_lg: 5
#                  col_md: 6
#                  col_sm: 12
#                  rows: 
#                      - cols:
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  fields_table: 
                      name: infos
#                      - cols: 
#                          - type: custom
#                            col_lg: 12
#                            custom:
#                                callback: renderChronoView
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  fields_table:
                      name: objects
            - cols: 
                - type: list
                  list: 
                      children: inters
            - cols: 
                - type: list
                  list: 
                      children: notes
            - cols: 
                - type: list
                  list: 
                      children: files
            
lists_cols:
    id: 
        label: N°
        field: id
        min_width: 40px
    ticket:
        field: ticket_number
    status:
        field: status
    priorite:
        label: Prio.
        field: priorite
        display: icon
        max_width: 40px
        min_width: 40px
    impact:
        label: Imp.
        field: impact
        display: icon
        max_width: 40px
        min_width: 40px
    sujet:
        field: sujet
    date_create:
        field: date_create
    resp:
        field: id_user_resp
        display: nom_url
    contrat:
        field: id_contrat
        display: nom_url
    client: 
        field: id_client
        display: nom_url
    timer: 
        field: appels_timer
        label: Chrono appels
    timer_inters:
        label: Chrono inters
        value:
            callback: displayDureeTotale
    cover: 
        field: cover
        label: Couvert
        display: icon
        min_width: 60px
                
lists:
    default: 
        title: Tickets Hotline
        configurable: 1
        checkboxes: 1
        bulk_actions:
            - label: supprimer les tickets sélectionnés
              icon: fas_trash-alt
              onclick: deleteSelectedObjects('list_id', $(this))
        objects_change_reload: BS_Inter
        sort_field: date_create
        sort_way: desc
        n: 10
        add_form_name: default
        add_btn_label: Nouveau ticket hotline
        edit_btn: 1
        edit_form: default
        delete_btn: 1
        page_btn: 1
        modal_view: full
        cols:
            id:
            status:
            priorite:
            impact:
            sujet:
            date_create:
            resp:
            contrat:
            client: 
                
cards:
    default:
        title: nom
        fields: 
            - label: Contrat
              field: id_contrat
              display: nom_url
            - label: Client
              field: id_client
              display: nom_url
        view_btn: 1
