## Contrat hérite de bimpComm
#extends: 
#    module: bimpcommercial
#    object_name: BimpComm

primary: rowid

header_btn: 
    callback: getActionsButtons

# Utilisation de l'object dolibarr contrat
dol_object: 
    instance: 
        dol_object: 
            module: contrat
            file: contrat

objects:
    client:
        instance:
            dol_object:
                module: societe
                file: societe
            id_object:
                field_value: fk_soc
    
    lines:
        instance:
            bimp_object: BContract_contratLine
    
    files:
        relation: hasMany
        delete: 1
        instance:
            bimp_object:
                module: bimpcore
                name: BimpFile
        list: 
            filters:
                parent_module: bimpcontract
                parent_object_name: BContract_contrat
                deleted: 0
        add_form: 
            name: upload
            values:
                fields: 
                    parent_module: bimpcontract
                    parent_object_name: BContract_contrat
        
    echeancier:
        instance:
            bimp_object: BContract_echeancier
          
force_extrafields_update: 1

table: contrat
controller: contrat
icon: fas_file
list_page_url: 
    controller: contrat

labels: 
    name: contrat

fields:
    # Champs du contrat
    ref: 
        label: Référence
        type: string
    fk_soc:
        label: Client
        type: id_object
        object: client
        dol_prop: socid
        required: 1
        input: 
            type: search_societe
            societe_type: customer
            help: Entrez le nom ou la référence d'un client pour effectuer une recherche
            card: default
        search:
            input: 
                type: search_societe
                societe_type: customer    
        create_form: light
    datec:
        label: Date du contrat
        type: date
    date_contrat:
        label: Date de signature
        type: date
    statut:
        label: Statut
        type: int
        values:
            array: status_list
        
            
    # Extrafields
    date_start:
        label: Date d'effet du contrat
        type: date
        dol_extra_field: 1
        required: 1
    duree_mois:
        label: Durée en mois
        type: qty
        dol_extra_field: 1
        default_value: 12
        required: 1
    periodicity:
        label: Périodicité de facturation
        type: int
        dol_extra_field: 1
        values:
            array: period
    gti:
        label: Delais d'intervention
        type: int
        dol_extra_field: 1
        require: 1
        values:
            array: gti
    syntec:
        label: Indice SYNTEC en vigueur à la signature
        type: float
        dol_extra_field: 1
        input:
            help: 
                callback: getSyntecSite
        display_if:
            field_name: use_syntec
            show_values: 1
    tacite:
        label: Renouvellement
        type: int
        dol_extra_field: 1
        values:
            array: renouvellement
        default_value: 12
    denounce:
        label: Contrat dénoncé
        type: int
        dol_extra_field: 1
        values:
            array: denounce
        default_value: 0
    moderegl:
        label: Mode de règlement
        type: int
        dol_extra_field: 1
        default_value: 
            callback: getModeReglementClient
        values:
            array: mode_reglement

    objet_contrat:
        label: Objet du contrat
        type: string
        dol_extra_field: 1
        required: 1
        
    fk_commercial_signature:
        label: Commercial signataire
        dol_prop: commercial_signature_id
        required: 1
        input: 
            type: search_user
            help: Choisir le commercial responssable de la signature du contrat
            card: default 
        default_value: 
           prop:
               name: id
               object:
                   global: user
    
    fk_commercial_suivi:
        label: Commercial suivi
        dol_prop: commercial_suivi_id
        required: 1
        input: 
            type: search_user
            help: Choisir le commercial responssable du suivi du contrat
            card: default 
        default_value: 
           prop:
               name: id
               object:
                   global: user
        
fields_tables:
    infos:
        panel: 0
        rows:
            - field: ref
              label: Référence du contrat
              edit: 0
            - field: objet_contrat
              edit: 0
            - field: datec
              edit: 0
            - field: date_contrat
              edit: 0
            - field: date_start
              edit: 0
            - field: duree_mois
              edit: 0
            - label: Date de fin du contrat
              value: 
                  callback:
                      method: displayEndDate
                      params:
                          - value:
                              callback:
                                  method: getData
                                  params:
                                      - date_start
                          - value:
                              callback:
                                  method: getData
                                  params:
                                      - duree_mois
            - field: periodicity
              edit: 0
            - field: moderegl
              edit: 0
            - field: gti
              edit: 0
            - field: syntec
              edit: 0
            - field: tacite
              edit: 0
            - field: denounce
              edit: 0
    client: 
        panel: 0
        rows: 
            - field: fk_soc
              display: card
            - label: Fichier PDF
              value: 
                  callback: displayPDFButton
   
              
                              
lists: 
    default:
        title: Contrat
        icon: fas_file-contract
        list_filters: 
            callback: getListFilters
        sort_field: datec
        sort_way: desc
        n: 20
        add_form_name: add_contrat
        add_btn_label: Créer un nouveau contrat
        edit_btn: 1
        edit_form: edit_contrat
        delete_btn: 0
        modal_view: fiche_contrat
        page_btn: 1
        cols: 
            ref: 
                field: ref
            statut:
                field: statut
            fk_soc:
                field: fk_soc
                display: nom_url
            datec:
                field: datec
            date_contrat:
                field: date_contrat

forms:
    edit_contrat:
        rows:
            - field: ref
              edit: 0
            - field: objet_contrat
            - field: fk_soc
              edit: 0
            - field: date_start
            - field: duree_mois
            - field: periodicity
            - field: moderegl
            - field: gti
            - field: syntec
            - field: tacite
            - field: denounce
    
    add_contrat:
        rows:
            - field: datec
              edit: 0
              show: 0
            - field: objet_contrat
            - field: fk_soc
            - field: date_start
            - field: duree_mois
            - field: periodicity
            - field: gti
            - field: tacite
            - custom: 1
              label: Utiliser l'indice SYNTEC
              input_name: use_syntec
              input: 
                  type: toggle
            - field: syntec
              
            - field: denounce
              edit: 0
            - field: moderegl
            - field: fk_commercial_signature
            - field: fk_commercial_suivi
            
    clone_contrat:
        edit: 1
        msgs:
            - content: <h4>Merci de confirmer le clone du contrat</h4>
              type: warning
    contact:
        title: Ajouter un contact
        rows: 
            - custom: 1
              label: Type
              input_name: type
              input: 
                  type: select
                  options: 
                      1: Contact tiers
                      2: Utilisateur
            - custom: 1
              label: Tiers
              input_name: id_client
              input: 
                  type: search_societe
                  societe_type: customer
              value: 
                  field_value: fk_soc
              display_if: 
                  field_name: type
                  show_values: 1
            - custom: 1
              label: Contact
              input_name: id_contact
              data_type: id_object
              object: contact
              create_form: default
              create_form_values:
                  fields: 
                      fk_soc: 
                          callback: getAddContactIdClient
              value: 
                  request: fields/id_contact
              input: 
                  type: select
                  options: 
                      array: clientContacts
              display_if: 
                  field_name: type
                  show_values: 1
              depends_on: id_client
            - custom: 1
              label: Utilisateur
              input_name: id_user
              input: 
                  type: search_user
              value: 
                  prop:
                      object: 
                          global: user
                      name: id
              display_if: 
                  field_name: type
                  show_values: 2
            - custom: 1
              label: Type de contact
              input_name: tiers_type_contact
              input: 
                  type: select
                  options: 
                      array: externalContactTypes
              display_if: 
                  field_name: type
                  show_values: 1
            - custom: 1
              label: Type de contact
              input_name: user_type_contact
              input: 
                  type: select
                  options: 
                      array: internalContactTypes
              display_if: 
                  field_name: type
                  show_values: 2 
            
        
views:
    fiche_contrat:
        objects_change_reload: BContract_echeancier, BContract_contrat
        title:
            callback: displayRef
        objects_change_reload: BContract_contract
        delete_btn: 1
        edit_form: edit_contrat
        footer_extra_btn: 
            callback: getActionsButtons
        rows:
            - cols: 
                - type: rows
                  col_lg: 6
                  col_md: 6
                  rows:                        
                      - cols: 
                          - type: fields_table
                            col_lg: 12
                            fields_table: 
                                name: infos
                - type: rows
                  col_lg: 6
                  col_md: 6
                  rows:
                      - cols:
                          - type: fields_table
                            col_lg: 12
                            fields_table:
                                name: client
            - cols: 
                - type: custom
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  custom:
                      callback:
                            method: renderLinkedObjectsTable

                - type: custom
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  custom: 
                    callback:
                        method: renderFilesTable
    interface_client:
        title:
            callback: displayRef
        objects_change_reload: BContract_contract
        delete_btn: 1
        edit_form: edit_contrat
        footer_extra_btn: 
            callback: getActionsButtons
        rows:
            - cols: 
                - type: rows
                  col_lg: 12
                  col_md: 12
                  rows:                        
                      - cols: 
                          - type: fields_table
                            col_lg: 12
                            fields_table: 
                                name: infos

    
    file:
        title: Fichiers joint
        rows:
            - cols: 
                - type: rows
                  col_md: 12
                  col_lg: 12
                  rows:
                      - cols:
                          - type: list
                            list: 
                               children: files
                               
    echeancier:
        objects_change_reload: BContract_echeancier, BContract_contrat
        title:
            callback: getTitleEcheancier
        panel: 1
        rows:
            - cols:
                - type: custom
                  col_lg: 18
                  col_md: 12
                  custom:
                      callback: renderEcheancier
                      
    lines:
        objects_change_reload: BContract_echeancier, BContract_contrat
        title: Contenu du contrat
        panel: 0
        rows:
            - cols:
                - type: list
                  list:
                      children: lines
