bootstrap: 1
table: contratdet

parent_module: bimpcontract
parent_id_property: fk_contrat
parent_object: BContract_contrat

header_btn: 
    callback: getActionsButtons

dol_object: 
    instance: 
        dol_object: 
            module: contrat
            file: contrat
            class: ContratLigne

primary: rowid
force_extrafields_update: 1
labels: 
    name: ligne du contrat
    name_plur: lignes du contrat
    is_female: 1

objects:
    produit:
        instance: 
            bimp_object:
                module: bimpcore
                name: Bimp_Product
            id_object:
                field_value: fk_product

fields:
    rowid:
        label: N°
        type: int
    description:
        label: Description de la ligne
        type: string
        input:
            help: Laisse vide pour mettre la description du service
    statut:
        label: Etat du service
        type: int
        values:
            array: list_statut
    fk_contrat:
        label: Contrat
        type: id_parent
    fk_product:
        label: Produit
        type: id_object
        object: produit
        required: 1
        input: 
            type: search_product
            help: Entrez le nom ou la référence d'un produit pour effectuer une recherche
            card: default
    qty:
        label: Qté
        type: qty
        default_value: 1
    serials:
        label: N° de série
    subprice:
        label: P.U HT
        type: money
    price_ht:
        label: P.U HT (Avec remise)
        type: money
    tva_tx: 
        label: Taux de TVA
        type: percent
        default_value: 20
    total_ttc: 
        label: Total TTC
        type: money
    total_tva:
        label: Total TVA
        type: money
    total_ht:
        label: Total HT
        type: money
    remise_percent:
        label: Remise
        type: percent
        default_value: 0
    buy_price_ht:
        label: Prix d'achat HT
        type: money
        required: 1
    remise:
        label: Total remise
        type: money
    logs:
        label: Suivi du remplacement des numéros de séries
    date_ouverture_prevue:
        label: Date start
        type: date
    date_fin_validite:
        label: Date End
        type: date
    product_type:
        label: Type
        type: int
        values:
            array: type_p
    renouvellement:
        label: Appartenance
        type: int
        
lists: 
    default: 
        title: Lignes du contrat
        sort_field: tms
        sort_way: desc
        n: 20
        checkbox: 1
        edit_btn: 1
        edit_form: default
        add_form_name: add
        delete_btn: 1
        page_btn: 1
        modal_view: default
        extra_btn:
            callback: getListExtraButtons
        cols: 
            statut:
            description:
            fk_product:
            subprice:
            qty:
            tva_tx:
            remise_percent:
            remise:
            total_ht:
            total_tva:
            total_ttc:
            buy_price_ht:
            product_type:
            renouvellement_renew:
                label: Appartenance
                value:
                    callback: displayRenouvellementIn
#            date_ouverture_prevue:
    global: 
        title: Lignes du contrat
        filters_panel: default
        sort_field: tms
        sort_way: desc
        n: 20
        checkbox: 1
        edit_btn: 1
        edit_form: default
        add_form_name: add
        delete_btn: 1
        page_btn: 1
        modal_view: default
        extra_btn:
            callback: getListExtraButtons
        cols: 
            parent:fk_soc:
            fk_contrat:
            statut:
            description:
            fk_product:
            subprice:
            qty:
            tva_tx:
            remise_percent:
            remise:
            total_ht:
            total_tva:
            total_ttc:
            buy_price_ht:
            product_type:
    
    fi:
        extends: default
        delete_btn: 0
        page_btn: 0
        edit_form: 0
        edit_btn: 0
        add_form_name: 0
        modal_view: 0
        extra_btn:
            callback: extraBtnFi
        
    product: 
        extends: default
        add_form_name: unset
        cols: 
            fk_product: unset
        
    interface_client:
        edit_btn: 0
        extends: default
        cols:
            fk_product: unset
            qty: unset
        list_filters: 
            callback: getListFilters
        show: 0
        
forms:
    default:
        rows:
            - field: rowid
              edit: 0
              show: 0
            - field: description
              input_name: desc
            - field: fk_product
              edit: 0
            - field: tva_tx
            - field: qty
            - field: remise_percent
            
    add:
        rows:
            - field: fk_product
              input_name: nb_materiel
            - field: qty
            - field: remise_percent
            - field: tva_tx
    add_serial:
        rows:
            - custom: 1
              label: Numéros de séries
              input_name: serials
              value:
                  callback: 
                      method: displaySerialsList
                      params:
                          - 1
              input:
                  type: textarea
                  help: Merci de séparer les numéros de séries par un saut de ligne
    rebase_serial:
        rows:
            - custom: 1
              label: Numéro de série à remplacer
              input_name: old_serial
              input: 
                  type: select
              values: 
                  array: 
                    callback: getArraySerials
            - custom: 1
              label: Nouveau numéro de série
              input_name: new_serial
              required: 1
              input: 
                  type: text
              

fields_tables:
    infos:
        panel: 0
        rows:
            - field: fk_product
              display: nom
              label: Service
            - field: logs
#            - field: subprice
#              label: Prix unitaire hors-taxe
#            - field: qty
#              label: Quantitée dans le contrat
#            - field: nb_materiel
#              label: Nombre de matériels couverts par ce service
            - label: Numéro(s) de série lié(s) à cette ligne de service
              value: 
                  callback: displaySerialsList

views:
    default: 
        title: Détails de la ligne
        delete_btn: 1
        objects_change_reload: Bcontract_contrat
        rows: 
            - cols:
                - type: object_header
            - cols: 
                - type: fields_table
                  col_lg: 8
                  col_md: 12
                  fields_table:
                      name: infos

                        
filters_panels: 
    default: 
        filters: 
            parent:date_contrat:
            fk_product:
            parent:secteur:
            