bootstrap: 1

table: bcontract_prelevement

parent_id_property: id_contrat
parent_object: BContract_contrat

objects:
    contrat:
        instance:
            bimp_object: BContract_contrat
            id_object:
                field_value: id_contrat
            
fields:
    id_contrat:
        label: Numéro de contrat
        type: id_object
        object: contrat
    next_facture_date:
        label: Date de la prochaine facture
        type: datetime
    next_facture_amount:
        label: Montant de la prochaine facture
        type: money
    validate:
        label: Validation automatique des factures
        type: bool
        
lists:
    default:
        title: Récapitulatif des échéanciers contrat
        icon: fas_euro
        sort_field: id
        sort_way: desc
        n: 25
        delete_btn: 0
        edit_btn: 0
        update_btn: 1
        add_object_row: 0
        modal_view: fiche_contrat
        #page_btn: 1
        cols: 
            id_contrat:
                field: id_contrat
                display: nom_url
            next_facture_date:
                field: next_facture_date
                edit: 1
            next_facture_amount:
                field: next_facture_amount
                edit: 1
            validate:
                field: validate
                edit: 1
                
forms:
    create_perso:
        rows:
            - field: next_facture_date
              edit: 0
            - custom: 1
              label: Fin de la periode de facturation
              input_name: nombre_periode
              data_type: int
              required: 1
              value: 1
              input:
                  type: qty
              options:
                  data:
                      min: 1
            - custom: 1
              label: Montant HT
              data_type: money
              input_name: montant_ht
              required: 1
              input:
                  type: text
              value:
                  callback: renderMontantInput

views:
    fiche_contrat:
        title: echeancier
        rows:
            - cols: 
                - type: rows
                  col_lg: 12
                  col_md: 12
                  rows:                        
                      - cols: 
                          - type: view
                            col_lg: 12
                            view: 
                                name: echeancier
                                object: contrat