bootstrap: 1

table: bcontract_prelevement

parent_id_property: id_contrat
parent_object: BContract_contrat

objects:
    contrat:
        instance:
            bimp_object: BContract_contrat
            id_object:
                field_value: id_contrat
    commercial:
        instance:
            bimp_object:
                module: bimpcore
                name: Bimp_User
            id_object:
                field_value: commercial
    client:
        instance:
            bimp_object:
                module: bimpcore
                name: Bimp_Societe
            id_object:
                field_value: client
filters_panels: 
    default: 
        filters:
            ref:
                field: id_contrat
                show: 1
            client:
                field: client
            commercial:
                field: commercial

fields:
    id_contrat:
        label: Numéro de contrat
        type: id_object
        object: contrat
    next_facture_date:
        label: Date de la prochaine facture
        type: datetime
    next_facture_amount:
        label: Montant de la prochaine facture
        type: money
    validate:
        label: Validation automatique des factures
        type: bool
    statut:
        label: Statut
        type: int
        values:
            array: statut_list
    commercial:
        label: Commercial du contrat
        type: id_object
        object: commercial
        input:
            type: search_user
    client:
        label: Client
        type: id_object
        object: client
    

lists:
    default:
        filters_panel: default
        title: Récapitulatif des échéanciers contrat
        icon: fas_euro
        list_filters: 
            callback: getListFilter
        sort_field: next_facture_date
        sort_way: desc
        n: 25
        delete_btn: 0
        edit_btn: 0
        update_btn: 1
        add_object_row: 0
        modal_view: fiche_contrat
        #page_btn: 1
        cols: 
            id_contrat:
                field: id_contrat
                display: nom_url
            client:
                field: client
                display: nom_url
            facture_send:
                label: Factures émisent
                value:
                    callback: displayFactureEmises
            next_facture_date:
                label: Date de la prochaine facture
                field: next_facture_date
                type: date
            etat_facturation:
                label: Etat facturation
                value:
                    callback: displayRetard
            commercial:
                field: commercial
                display: nom_url
            statut:
                field: statut
    client:
        extends: default
        cols:
            client: unset
                
forms:
    create_perso:
        rows:
            - field: validate
            - field: next_facture_date
              edit: 0
            - custom: 1
              label: Fin de la periode de facturation
              input_name: fin_periode
              data_type: text
              input:
                  type: select
                  options:
                      array:
                        callback: renderlistEndPeriod
            - custom: 1
              label: Montant HT
              data_type: money
              input_name: montant_ht
              input:
                  type: text
                  help: Laisser vide pour la facturation normale des périodes
                  

views:
    fiche_contrat:
        title: echeancier
        rows:
            - cols: 
                - type: rows
                  col_lg: 12
                  col_md: 12
                  rows:                        
                      - cols: 
                          - type: view
                            col_lg: 12
                            view: 
                                name: echeancier
                                object: contrat