<?php
//
// File generated by Dolibarr installer 3.3.0-alpha on 2013-01-21 23:46:14
//
// Take a look at conf.php.example file for an example of conf.php file
// and explanations for all possibles parameters.
//
global $dolibarr_main_url_root;
$dolibarr_main_url_root="https://gle.synopsis-erp.com/bimp";
$dolibarr_main_document_root='/var/BIMP-ERP/bimp/htdocs/';
//$dolibarr_main_url_root_alt='http://192.168.1.10/newGle/htdocs/custom';
//$dolibarr_main_document_root_alt='/Library/WebServer/Documents/newGle/htdocs/custom';
$dolibarr_main_data_root='/var/BIMP-ERP/DOCUMENTS/bimp';
$dolibarr_main_db_host='127.0.0.1';
$dolibarr_main_db_port='3306';
$dolibarr_main_db_pass='admin@synopsis';
$dolibarr_main_db_name='BIMP-ERP_PROD_BIMP';
/*$dolibarr_main_db_port='3307';
$dolibarr_main_db_pass='roland2007';
$dolibarr_main_db_name='gle360';*/
$dolibarr_main_db_prefix='llx_';
$dolibarr_main_db_user='root';
$dolibarr_main_db_type='mysqli';
$dolibarr_main_db_character_set='';
$dolibarr_main_db_collation='';
$dolibarr_main_authentication='dolibarr';


/*define('CLOSE_DATE', '2015-06-09 23:30:00');
define('IP_ADMIN', '78.217.11.123');
*/

//define('DIR_SYNCH', '/var/BIMP-ERP/XRAIDAUTO/BIMP-ERP_8sens/');

define('MAX_TIME_LOG', 6);

define('PRODUCTION_APPLE', true);

define("MOD_DEV_SYN", false);

define('PORT_INTERNE', '443');

define('LIST_DOMAINE_VALID', serialize (array("divers-bimp.local", "synopsis-erp.com", "bimp.fr")));
define('DOMAINE_GROUP_ID', 1);


define('TAB_IP_INTERNE', '78.217.11.123, 88.125.45.38, 79.141.2.247, 82.239.30.139, 79.141.2.249,88.177.112.5,193.251.68.25,78.244.4.41,79.141.2.248,82.247.120.103,79.141.2.240,79.141.2.241,88.176.75.29,85.171.69.57');

//define('IMPORT_BDD_HOST', '127.0.0.1');
//define('IMPORT_BDD_USER', 'root');
//define('IMPORT_BDD_PASSE', 'roland2007');
//define('IMPORT_BDD_NAME', 'gle1main');

//define('MOD_DEV_SYN_MAIL', 'tommy@drsi.fr, j.fronteau@bimp.fr, tysauron@outlook.fr');

// Specific settings
$dolibarr_main_prod='0';
$dolibarr_nocsrfcheck='1';
$dolibarr_main_force_https='https://gle.synopsis-erp.com/';
$dolibarr_main_cookie_cryptkey='e2154149d51f59d1d79f5dc0ed6c5df2';
$dolibarr_mailing_limit_sendbyweb='0';

//$dolibarr_lib_ADODB_PATH='';
//$dolibarr_lib_GEOIP_PATH='';
//$dolibarr_lib_NUSOAP_PATH='';
//$dolibarr_lib_FPDI_PATH='';
//$dolibarr_lib_PHPEXCEL_PATH='';
//$dolibarr_lib_ODTPHP_PATH='';
//$dolibarr_lib_ODTPHP_PATHTOPCLZIP='';
//$dolibarr_lib_TCPDF_PATH='';
//$dolibarr_js_CKEDITOR='';
//$dolibarr_js_JQUERY='';
//$dolibarr_js_JQUERY_UI='';
//$dolibarr_js_JQUERY_FLOT='';

//$dolibarr_font_DOL_DEFAULT_TTF='';
//$dolibarr_font_DOL_DEFAULT_TTF_BOLD='';
?>
