table: bimp_gsx_shipment
primary: rowid
common_fields: 1
icon: fas_shipping-fast
controller: shipment
    
nom_url: 
    syntaxe: <name>
    
entity_name: AppleShipment
    
list_page_url: 
    module: bimpsupport
    controller: index
    url_params: 
        tab: shipments

header_btn: 
    callback: getActionsButtons
    
header_list_name: default
header_edit_form: default
header_delete_btn: 1

labels: 
    name: retour groupé
    name_plur: retours groupés
    
objects: 
    parts: 
        relation: hasMany
        delete: 1
        instance: 
            bimp_object: 
                module: bimpapple
                name: AppleShipmentPart 
                
    files:
        relation: hasMany
        delete: 1
        instance:
            bimp_object:
                module: bimpcore
                name: BimpFile
        list: 
            filters:
                parent_module: bimpapple
                parent_object_name: AppleShipment
                deleted: 0
        add_form: 
            name: upload
            values:
                fields: 
                    parent_module: bimpapple
                    parent_object_name: AppleShipment
                
fields: 
    ship_to: 
        label: N° ShipTo
        required: 1
        values: 
            array: shiptos
    status: 
        label: Statut
        type: int
        values: 
            array: status_list
        default_value: 0
    carrier_code: 
        label: Transporteur
        values: 
            array: carriers
        required: 1
    length: 
        label: Longueur colis
        type: int
        min: 0
        input: 
            help: En centimètres (cm)
    width: 
        label: Largeur colis
        type: int
        min: 0
        input: 
            help: En centimètres (cm)
    height: 
        label: Hauteur colis
        type: int
        min: 0
        input: 
            help: En centimètres (cm)
    weight: 
        label: Poids colis
        type: int
        min: 0
        input: 
            help: En kilogrammes (kg)
    gsx_note: 
        label: Note GSX
        type: text
    transportation_charges: 
        label: Frais de transport
        type: money
    options_charges: 
        label: Frais optionnels
        type: money
    total_charges: 
        label: Frais totaux
        type: money
    billing_weight: 
        label: Poids facturé
        type: float
    tracking_number: 
        label: N° de suivi
    identification_number: 
        label: N° d'identification
    gsx_tracking_url: 
        label: URL de suivi
    gsx_confirmation: 
        label: Confirmation GSX
    gsx_return_id: 
        label: N° de retour GSX
        
forms: 
    default: 
        rows: 
            shipto: 
                field: ship_to
                show: 
                    callback: isNotLoaded
            carrier: 
                field: carrier_code
            length: 
                field: length
            width: 
                field: width
            height: 
                field: height
            weight: 
                field: weight
            note: 
                field: gsx_note
            
    create_gsx_return: 
        extends: default
        rows: 
            shipto: unset
            tracking_number: 
                field: tracking_number
            gsx_tracking_url: 
                field: gsx_tracking_url
                
    update_gsx_return: 
        extends: create_gsx_return
        force_edit: 1
                
    parts_labels: 
        rows: 
            - custom: 1
              label: N° boîte de suremballage
              input_name: pack_number
              value: 0
              input: 
                  type: select
                  options: 
                      array: packsNumbers
                      
    ups_file: 
        title: Envoi fichier UPS
        rows: 
            - custom: 1
              hidden: 1
              input_name: ups_file_upload
              value: 1
              input: 
                  type: hidden
            - custom: 1
              label: Fichier
              input_name: file
              input: 
                  type: file_upload
            
fields_tables: 
    infos: 
        title: Infos expédition
        icon: fas_info
        rows: 
            - field: ship_to
            - field: carrier_code
              edit: 1
            - field: length
              edit: 1
            - field: width
              edit: 1
            - field: height
              edit: 1
            - field: weight
              edit: 1
            
    charges: 
        title: Frais
        icon: fas_euro-sign
        rows: 
            - field: billing_weight
            - field: transportation_charges
            - field: options_charges
            - field: total_charges
        
    tracking: 
        title: Info suivi et GSX
        icon: fas_truck
        rows: 
            - field: tracking_number
              edit: 1
            - field: gsx_tracking_url
              edit: 1
#            - field: gsx_confirmation
            - field: gsx_return_id
            - field: gsx_note
              edit: 1
            
views: 
    default: 
        objects_change_reload: AppleShipmentPart
        rows:
            - cols: 
                - type: object_header
            - cols: 
                - type: fields_table
                  col_lg: 6
                  col_md: 6                  
                  fields_table: 
                      name: infos
                - type: rows
                  col_lg: 6
                  col_md: 6
                  rows: 
                      - cols:   
#                          - type: fields_table          
#                            fields_table: 
#                                name: charges
                          - type: fields_table         
                            fields_table: 
                                name: tracking                
                      
    full: 
        rows: 
            - cols: 
                - type: view
                  view: 
                      name: default
            - cols: 
                - type: list
                  list: 
                      name: shipment
                      children: parts
            - cols: 
                - type: list
                  list: 
                      name: default
                      children: files
                                           
lists_cols: 
    ship_to: 
        field: ship_to
    status: 
        field: status
    total_charges: 
        field: total_charges
    tracking_number: 
        field: tracking_number
    identification_number: 
        field: identification_number
    gsx_confirmation: 
        field: gsx_confirmation
    gsx_return_id: 
        field: gsx_return_id
    transportation_charges: 
        field: transportation_charges
    options_charges:
        field: options_charges
    billing_weight: 
        field: billing_weight
                      
lists: 
    default: 
        title: Liste des expéditions UPS
        configurable: 1
        sort_field: rowid
        sort_way: desc
        n: 10
        add_form_name: default
        edit_btn: 1
        edit_form: default
        page_btn: 1
        delete_btn: 1
        modal_view: full
        extra_btn: 
            callback: getListButtons
        cols: 
            ship_to:
            status: 
            total_charges: 
            tracking_number: 
            identification_number: 
            gsx_confirmation: 
            gsx_return_id:
          
searches: 
    default: 
        fields_search: 
            - a.rowid
            - a.ship_to
            - a.tracking_number
            - a.gsx_return_id
        fields_return: 
            - a.rowid
            - a.ship_to
            - a.tracking_number
            - a.gsx_return_id
        label_syntaxe: 'Retour #<a.rowid> - Shipto: <a.ship_to> - N° de suivi: <a.tracking_number> - N° de retour: <a.gsx_return_id>'