table: bimp_gsx_repair

labels: 
    name: réparation GSX
    name_plur: réparations GSX
    is_female: 1
                
fields: 
    serial: 
        label: N° de série
    id_sav: 
        label: SAV
        type: id_object
        object: sav
    repair_number: 
        label: N° de réparation
    repair_confirm_number: 
        label: N° de confirmation
    new_serial:
        label: Nouveau n° de série
    repair_type: 
        label: Type de réparation
    total_from_order: 
        label: Total De la commande
        type: money
    ready_for_pick_up: 
        label: Prêt pour enlèvement
        type: bool
        default_value: 0
    repair_complete: 
        label: Réparation terminée
        type: bool
        default_value: 0
    closed: 
        label: Fermée par BIMP-ERP
        type: bool
        default_value: 0
    date_closed: 
        label: Date de fermeture
        type: date
    reimbursed: 
        label: Remboursée
        type: bool
        default_value: 0
    total_from_order_changed: 
        label: Total commande mis à jour
        type: bool
        default_value: 0
    canceled: 
        label: Annulée
        type: bool
        default_value: 0
        
forms: 
    import: 
        title: Importer depuis GSX
        icon: dowload
        rows: 
            - custom: 1
              label: Identifiant
              input_name: import_number
              data_type: string
              input: 
                  type: text
            - custom: 1
              label: De type
              data_type: string
              input_name: import_number_type
              input: 
                  type: select
                  options: 
                      prop: 
                          name: lookupNumbers
                          is_static: 1
            
fields_tables:
    infos: 
        title: Informations
        icon: info-circle
        rows: 
            - field: date_create
            - field: repair_number
            - field: repair_confirm_number
            - field: serial
              label: N° de série initial
            - field: new_serial
            - label: Statut dans GSX
              value: 
                  callback: displayGsxStatus
            - label: Sous garantie
              value: 
                  callback: displayGarantie
            - field: total_from_order
            - field: ready_for_pick_up
            - field: repair_complete
            - field: closed
            - field: canceled
            - field: date_closed
            - field: reimbursed
            
views: 
    default:
        title: nom
        rows:
            - cols: 
                  - type: fields_table
                    col_lg: 6
                    col_md: 6
                    fields_table: 
                        name: infos
                  - type: custom
                    col_lg: 6
                    col_md: 6
                    custom: 
                        callback: renderPartsPendingReturn
            - cols: 
                  - type: custom
                    custom:
                        callback: renderActions