table: bimp_gsx_repair
icon: fas_tools
header_delete_btn: 0
header_btn: 
    callback: getActionsButtons

labels: 
    name: réparation GSX
    name_plur: réparations GSX
    is_female: 1
                
fields: 
    serial: 
        label: N° de série
    id_sav: 
        label: SAV
        type: id_object
        object: sav
    repair_number: 
        label: N° de réparation
    repair_confirm_number: 
        label: N° de confirmation
    new_serial:
        label: Nouveau n° de série
    repair_type: 
        label: Type de réparation
    total_from_order: 
        label: Total De la commande
        type: money
    ready_for_pick_up: 
        label: Prêt pour enlèvement
        type: bool
        default_value: 0
    repair_complete: 
        label: Réparation terminée
        type: bool
        default_value: 0
    closed: 
        label: Fermée par BIMP-ERP
        type: bool
        default_value: 0
    date_closed: 
        label: Date de fermeture
        type: date
    reimbursed: 
        label: Remboursée
        type: bool
        default_value: 0
    total_from_order_changed: 
        label: Total commande mis à jour
        type: bool
        default_value: 0
    canceled: 
        label: Annulée
        type: bool
        default_value: 0
        
forms: 
    import: 
        title: Importer depuis GSX
        icon: dowload
        rows: 
            - custom: 1
              label: Identifiant
              input_name: import_number
              data_type: string
              input: 
                  type: text
            - custom: 1
              label: De type
              data_type: string
              input_name: import_number_type
              input: 
                  type: select
                  options: 
                      prop: 
                          name: lookupNumbers
                          is_static: 1
                          
    part_update: 
        title: Mise à jour du numéro de série
        icon: fas_pen
        rows: 
            - custom: 1
              hidden: 1
              label: Sequence number
              input_name: sequence_number
              data_type: int
              input: 
                  type: hidden
            - custom: 1
              label: Numéro de série actuel (KBB)
              input_name: kbb_number
              input: 
                  type: text
            - custom: 1
              label: Nouveau numéro de série (KGB)
              input_name: kgb_number
              input: 
                  type: text
              required: 1
            
fields_tables:
    infos: 
        title: Informations
        icon: info-circle
        rows: 
            - field: date_create
            - field: repair_number
            - label: type
              value: 
                  callback: displayRepairType
            - field: repair_confirm_number
              show: 
                  callback: is_v1
            - field: serial
              label: N° de série initial
            - field: new_serial
            - label: Statut dans GSX
              value: 
                  callback: displayGsxStatus
            - label: Sous garantie
              value: 
                  callback: displayGarantie
            - field: total_from_order
            - field: ready_for_pick_up
            - field: repair_complete
            - field: closed
            - field: canceled
            - field: date_closed
            - field: reimbursed
            
    gsx_v2_infos: 
        title: Informations
        icon: info-circle
        rows: 
            - label: type
              value: 
                  callback: displayRepairType
            - field: serial
              label: N° de série initial
            - field: new_serial
            - field: total_from_order
            - field: ready_for_pick_up
            - field: repair_complete
            - field: closed
            - field: canceled
            - field: date_closed
            - field: reimbursed
            
views: 
    default:
        panel: 0
        title: nom
        rows:
            - cols: 
                  - type: object_header
            - cols: 
                  - type: custom
                    custom: 
                        callback: displayViewMsgs
            - cols: 
                  - type: fields_table
                    col_lg: 6
                    col_md: 6
                    fields_table: 
                        name: infos
                  - type: custom
                    col_lg: 6
                    col_md: 6
                    custom: 
                        callback: renderPartsPendingReturn
            - cols: 
                  - type: custom
                    custom:
                        callback: renderActions
                        
    gsx_v2: 
        panel: 0
        objects_change_reload: BS_SAV,BS_SavPropalLine,BS_ApplePart
        rows: 
            - cols: 
                  - type: object_header
            - cols: 
                - type: custom
                  custom: 
                      callback: renderPropalReviewInfos
            - cols: 
                  - type: fields_table
                    col_lg: 6
                    col_md: 6
                    fields_table: 
                        name: gsx_v2_infos
                  - type: custom
                    col_lg: 6
                    col_md: 6
                    custom: 
                        callback: renderLookupInfos
            - cols: 
                  - type: custom
                    custom: 
                        callback: renderRepairParts