table: bimp_apple_part_stock_mvt
primary: id
icon: fas_exchange-alt
common_fields: 0

list_page_url: 
    module: bimpsupport
    controller: index
    url_params: 
        tab: part_stocks
        navtab-maintabs: parts_mvts
        
header_list_name: default

entity_name: PartStockMvt

labels: 
    name: mouvement de stock composants
    name_plur: mouvements de stock composants
            
fields: 
    stock_type: 
        label: Type de stock
        required: 1
        values: 
            array: stock_types
            
    id_stock: 
        label: Stock consigné
        type: id
        required: 1
        displays: 
            default: 
                type: callback
                method: displayStockObject
    id_user: 
        label: Utilisateur
        type: id_object
        object: user
        
    code_centre: 
        label: Centre
        required: 1
        values: 
            array: centres
            
    part_number: 
        label: Réf. composant
        required: 1
        
    date: 
        label: Date
        type: datetime
        
    qty: 
        label: Qté
        type: int
        displays: 
            badge: 
                label: avec code couleur
                type: callback
                method: displayBadgeQty
        
    serial: 
        label: N° de série
        
    code_mvt: 
        label: Code
        
    description: 
        label: Description
        type: text
        
    cancelled: 
        label: Annulation effectuée
        type: bool
        default_value: 0
        
fields_tables: 
    infos: 
        rows: 
            - field: code_centre
            - field: stock_type
            - field: id_stock
            - field: date
            - field: qty
            - field: serial
            - field: code_mvt
            - field: description
            - field: cancelled
            
views: 
    default: 
        rows: 
            - cols: 
                - type: fields_table
                  fields_table: 
                      name: infos
                  col_lg: 6
                  col_md: 6
                  col_sm: 6
                  
filters_panel: 
    default: 
        filters: 
            code_centre:
            part_number:
            date: 
            id_user:
            code_mvt: 
            description: 
            
lists: 
    default: 
        title: Mouvements stocks des composants Apple
        icon: fas_exchange-alt
        checkboxes:
            callback: isUserAdmin
        filters_panel: default
        sort_field: id
        sort_way: desc
        n: 50
        extra_btn: 
            callback: getListExtraButtons
        bulk_actions: 
            callback: getListsBulkActions
        list_actions: 
            - label: Annuler
              icon: fas_times-circle
              action: cancel
              confirm_msg: Veuillez confirmer l\'annulation de tous les mouvements de stock filtrés
        cols: 
            id: 
            stock_type: 
            code_centre:
            part_number:
            date: 
            qty: 
                display: badge
            serial: 
            code_mvt: 
            description: 
            id_user: