bootstrap: 1
title: Interface développeurs

js:
    - /bimpcore/views/js/dev.js

css:
    - /bimpcore/views/css/dev.css

objects:
    log:
        instance:
            bimp_object:
                module: bimpcore
                name: Bimp_Log
    
    process:
        instance:
            bimp_object:
                module: bimpdatasync
                name: BDS_Process
    
    bds_report:
        instance:
            bimp_object:
                module: bimpdatasync
                name: BDS_Report
    
    bds_report_line:
        instance:
            bimp_object:
                module: bimpdatasync
                name: BDS_ReportLine
    
    api:
        instance:
            bimp_object:
                module: bimpapi
                name: API_Api
    
    api_user:
        instance:
            bimp_object:
                module: bimpapi
                name: API_UserAccount
    
    bws_profiles:
        instance:
            bimp_object:
                module: bimpwebservice
                name: BWS_Profile
    
    bws_user:
        instance:
            bimp_object:
                module: bimpwebservice
                name: BWS_User
    
    bws_profile_right:
        instance:
            bimp_object:
                module: bimpwebservice
                name: BWS_ProfileRight
                
    notification:
        instance:
            bimp_object:
                module: bimpcore
                name: BimpNotification
                
    dictionnary:
        instance:
            bimp_object:
                module: bimpcore
                name: BimpDictionnary

sections:
    -   type: tabs
        tabs:
            default:
                label: Dashboard
                icon: fas_tachometer-alt
                sections:
                    -   type: custom
                        custom:
                            callback: renderDashboardTab
            modules_conf:
                label: Config modules
                icon: fas_cog
                sections:
                    -   type: custom
                        custom:
                            callback: renderModulesConfTab
            yml:
                label: Gestionnaire YML
                icon: fas_stream
                sections:
                    -   type: custom
                        custom:
                            callback: renderYmlTab
            
            logs:
                label: Logs
                icon: fas_book-medical
                show:
                    conf:
                        name: use_bimp_logs
                sections:
                    -   type: nav_tabs
                        nav_tabs:
                            tabs_id: logs
                            tabs:
                                -   id: bimp_logs
                                    title: Logs BimpCore
                                    struct:
                                        type: rows
                                        rows:
                                            -   cols:
                                                    -   type: list
                                                        list:
                                                            panel: 1
                                                            object: log
                                            -   cols:
                                                    -   type: graph
                                                        graph:
                                                            object: log
                                -   id: pulls_logs
                                    title: Logs pulls
                                    content:
                                        callback: renderPullTab
            
            processes:
                label: Processus
                icon: fas_cogs
                show:
                    conf:
                        name: module_version_bimpdatasync
                        def: 0
                sections:
                    -   type: nav_tabs
                        nav_tabs:
                            tabs_id: processes
                            tabs:
                                -   id: processes_list
                                    title: Liste des processus
                                    icon: fas_cogs
                                    struct:
                                        type: list
                                        list:
                                            object: process
                                -   id: bds_reports_list
                                    icon: fas_file-alt
                                    title: Rapports
                                    struct:
                                        type: list
                                        list:
                                            object: bds_report
                                -   id: bds_report_lines_list
                                    title: Lignes de rapport
                                    icon: fas_bars
                                    struct:
                                        type: list
                                        list:
                                            object: bds_report_line
                                -   id: scripts_tab
                                    title: Scripts
                                    icon: fas_code
                                    content:
                                        callback: renderScriptsTabContent
            
            apis:
                label: APIs
                icon: fas_project-diagram
                show:
                    conf:
                        name: module_version_bimpapi
                        def: 0
                sections:
                    -   type: nav_tabs
                        nav_tabs:
                            tabs_id: processes
                            tabs:
                                -   id: processes_list
                                    title: Liste des APIs
                                    struct:
                                        type: list
                                        list:
                                            object: api
                                -   id: apis_users
                                    title: Comptes utilisateurs APIs
                                    struct:
                                        type: list
                                        list:
                                            object: api_user
            
            ws:
                label: Webservice
                icon: fas_globe
                show:
                    conf:
                        name: module_version_bimpwebservice
                        def: 0
                sections:
                    -   type: nav_tabs
                        nav_tabs:
                            tabs_id: ws
                            tabs:
                                -   id: profiles
                                    title: Profiles
                                    struct:
                                        type: list
                                        list:
                                            object: bws_profiles
                                -   id: users
                                    title: Utilisateurs
                                    struct:
                                        type: list
                                        list:
                                            object: bws_user
                                -   id: rights
                                    title: Tous les droits
                                    struct:
                                        type: list
                                        list:
                                            object: bws_profile_right
            notification:
                label: Notifications
                icon: fas_bell
                sections:
                    -   type: nav_tabs
                        nav_tabs:
                            tabs_id: notifs
                            tabs:
                                -   id: users_notifs
                                    title: Notifications utilisateurs
                                    icon: fas_bell
                                    struct:
                                        type: list
                                        list:
                                            panel: 1
                                            object: notification
                                            name: default
                                -   id: users_msgs
                                    title: Messages utilisateurs
                                    icon: fas_mail-bulk
                                    content:
                                        callback:
                                            method: renderMailerTab
                                            params:
                                                - metier
                                -   id: mailerp_dev
                                    title: Messages dévs
                                    icon: fas_mail-bulk
                                    struct:
                                        type: custom
                                        custom:
                                            callback:
                                                method: renderMailerTab
                                                params:
                                                    - devs
            
            menu:
                label: Menu BimpTheme
                icon: fas_bars
                sections:
                    -   type: custom
                        custom:
                            callback: renderBimpThemeMenuList
                            
            dictionnary:
                label: Dictionnaires
                icon: fas_book
                sections:
                    -   type: list
                        list:
                            object: dictionnary
                            panel: 1
                            name: default
