boostrap: 1

title: 
    callback: 
        object: produit
        method: getPageTitle
        
objects:
    product:
        instance:
            bimp_object: Bimp_Product
            id_object:
                request: id

js: 
    callback: 
        object: product
        method: getJs
css: 
    - /bimpcore/views/css/product.css
    
sections:
    - type: object_header
      object_header: 
          object: product
    - type: nav_tabs
      nav_tabs:
          - id: fiche
            title: Fiche
            struct:
                type: view
                view:
                    object: product
                    name: fiche
          - id: price
            title: Prix (Vente/Achat)
            struct:
                type: view
                view:
                    object: product
                    name: product_price
          - id: stock
            title: Stocks
            struct:
                type: view
                view:
                    object: product
                    name: stock
          - id: commercial
            title: Commercial
            struct:
                type: view
                view:
                    object: product
                    name: product_history
          - id: equipments
            title: Equipements
            struct: 
                type: custom
                custom: 
                    callback: 
                        method: renderLinkedObjectsList
                        object: product
                        params: 
                            - equipments
          - id: notes
            title: Notes
            struct:
                type: view
                view:
                    object: product
                    name: product_note
          - id: files
            title: Fichiers joints
            struct: 
                type: rows
                rows:                                                   
                    - cols: 
                        - type: list
                          list: 
                              title: Fichier joints
                              name: default
                              panel: 1
                              object: product
                              children: files
          - id: divers
            title: Divers (admin)
            show: 
                callback:
                    method: iAmAdmin
                    object: client
            struct: 
                type: custom
                custom: 
                    callback: 
                        method: renderBimpOjectDivers
                        object: product
#          - id: Categoriser
#            show:
#                callback: 
#                    object: product
#                    method: productBrowserIsActif
#            title: Catégoriser