boostrap: 1

title: 
    callback: 
        object: produit
        method: getPageTitle
        
objects:
    produit:
        instance:
            bimp_object: Bimp_Product
            id_object:
                request: id

js: 
    callback: 
        object: produit
        method: getJs
css: 
    - /bimpcore/views/css/product.css
    
sections:
    - type: object_header
      object_header: 
          object: produit
    - type: nav_tabs
      nav_tabs:
          - id: fiche
            title: Fiche
            struct:
                type: view
                view:
                    object: produit
                    name: fiche
          - id: prix
            title: Prix (Vente/Achat)
            struct:
                type: view
                view:
                    object: produit
                    name: product_price
          - id: stats
            title: Statistiques
            show: 0
          - id: object_referent
            title: Objets référents
            show: 0
          - id: product_stock
            title: Stock
            struct:
                type: view
                view:
                    object: produit
                    name: stock
#            show: 0
          - id: Categoriser
            show:
                callback: 
                    object: produit
                    method: productBrowserIsActif
            title: Catégoriser
            struct:
                type: view
                view:
                    object: produit
                    name: product_categorize
          - id: history
            title: Object référents
            struct:
                type: view
                view:
                    object: produit
                    name: product_history
          - id: notes
            title: Notes
            struct:
                type: view
                view:
                    object: produit
                    name: product_note
          - id: files
            title: Fichiers joints
            struct: 
                type: rows
                rows:                                                   
                    - cols: 
                        - type: list
                          list: 
                              title: Fichier joints
                              name: default
                              panel: 1
                              object: produit
                              children: files
          - id: divers
            title: Divers (admin)
            show: 
                callback:
                    method: iAmAdmin
                    object: client
            struct: 
                type: custom
                custom: 
                    callback: 
                        method: renderBimpOjectDivers
                        object: produit
                              
    - type: buttons
      buttons:
          - label: Retour à la liste des produits
            url: 
                controller: index
            icon_before: chevron-left
            classes: 
                array: btn,btn-primary