bootstrap: 1
title: Produits

objects:
    productentrepot: 
        instance: 
            bimp_object: 
                module: bimpcommercial
                name: Bimp_Product_Entrepot
            
    products: 
        instance: 
            bimp_object: Bimp_Product
            
    equipment: 
        instance: 
            bimp_object: 
                module: bimpequipment
                name: Equipment
            
    vente:
        instance: 
            bimp_object: 
                module: bimpcommercial
                name: Bimp_Vente
    package: 
        instance: 
            bimp_object: 
                module: bimpequipment
                name: BE_Package
            
    immos: 
        instance: 
            bimp_object: 
                module: bimpequipment
                name: BE_ProductImmos
    inventory:
        instance: 
            bimp_object:
                module: bimplogistique
                name: Inventory
    
    BimpProductMouvement:
        instance:
            bimp_object: BimpProductMouvement
            
sections:
    - type: tabs
      tabs: 
        default: 
            label: Produits
            sections: 
                - type: list
                  list: 
                      panel: 1
                      object: products
                      name: default
        equipments: 
            label: Equipements
            sections:
                - type: list
                  list: 
                      panel: 1
                      object: equipment
        productentrepot: 
            label: Stock / Entrepot
            sections: 
                - type: list
                  list: 
                      panel: 1
                      object: productentrepot
                      name: default
        ventes: 
              label: Stats ventes
              sections: 
                  - type: list
                    list: 
                        panel: 1
                        object: vente
        packages: 
            label: Packages
            sections: 
                - type: list
                  list: 
                      object: package  
        immos: 
            label: Equipements + Package
            sections: 
                - type: list
                  list: 
                      object: immos
                      name: immos
        inventory:
            label: Inventaires
            sections:
                - type: list
                  list: 
                      panel: 1
                      object: inventory
                      
        mouvement:
            label: Mouvements de stock
            sections:
                - type: list
                  list: 
                      panel: 1
                      object: BimpProductMouvement  