bootstrap: 1
title: Produits

js: 
    - /bimplogistique/views/js/create_inventory2.js
    
objects:
    productentrepot: 
        instance: 
            bimp_object: 
                module: bimpcommercial
                name: Bimp_Product_Entrepot
                
    productldlc:
        instance: 
            bimp_object: 
                module: bimpcore
                name: Bimp_Product_Ldlc
            
    product: 
        instance: 
            bimp_object: Bimp_Product
            
    equipment: 
        instance: 
            bimp_object: 
                module: bimpequipment
                name: Equipment
                
    package: 
        instance: 
            bimp_object: 
                module: bimpequipment
                name: BE_Package
            
    immos: 
        instance: 
            bimp_object: 
                module: bimpequipment
                name: BE_ProductImmos
    
    values8sens: 
        instance: 
            bimp_object: BimpValues8Sens     
            
    productfourn: 
        instance: 
            bimp_object: Bimp_ProductFournisseurPrice 
            
sections:
    - type: tabs
      tabs: 
        default: 
            label: Produits
            sections: 
                - type: list
                  list: 
                      panel: 1
                      object: product
                      name: default
        equipments:
            label: Equipements
            show: 
                is_module_active: bimpequipment
            sections:
                - type: list
                  list: 
                      panel: 1
                      object: equipment
        productfourn:
            label: Produits Fournisseurs
            show: 
                conf: 
                    module: bimpcore
                    name: use_imports_fournisseurs
            sections: 
                - type: list
                  list: 
                      panel: 1
                      object: productfourn
                      name: default
                      
        productldlc:
            label: Imports produits Fournisseurs
            show: 
                conf: 
                    module: bimpcore
                    name: use_imports_fournisseurs
            sections: 
                - type: list
                  list: 
                      panel: 1
                      object: productldlc
                      name: default
                        
        packages:
            label: Packages
            show: 
                is_module_active: bimpequipment
            sections: 
                - type: list
                  list: 
                      object: package  
        immos:
            label: Equipements + Package
            show: 
                is_module_active: bimpequipment
            sections: 
                - type: list
                  list: 
                      object: immos
                      name: immos
                      
        values8sens: 
            label: Tags 8sens
            sections: 
                - type: list
                  list: 
                      panel: 1
                      object: values8sens
                      name: default
