boostrap: 1

title: 
    callback: 
        object: product
        method: getPageTitle
        
objects:
    product:
        instance:
            bimp_object: Bimp_Product
            id_object:
                request: id

js: 
    callback: 
        object: product
        method: getJs
css: 
    - /bimpcore/views/css/product.css
    
sections:
    - type: object_header
      object_header: 
          object: product
    - type: nav_tabs
      nav_tabs:
          - id: fiche
            title: Fiche
            struct:
                type: custom
                custom: 
                    callback: 
                        method: renderCardView
                        object: product
          - id: bundle
            title: Bundle
            struct: 
                type: rows
                rows:                                                   
                    - cols: 
                        - type: view
                          view:
                            object: product
                            name: product_price_bundle
                        - type: list
                          list: 
                              title: Produits composé
                              name: parent
                              panel: 1
                              object: product
                              children: child_products
            show:
                callback:
                    object: product
                    method: isBundle
          - id: price
            title: Prix (Vente/Achat)
            struct:
                type: view
                view:
                    object: product
                    name: product_price
          - id: stock
            title: Stocks
            show: 
                callback: 
                    object: product
                    method: hasStock
            struct:
                type: view
                view:
                    object: product
                    name: stock
          - id: commercial
            title: Commercial
            show: 
                is_module_active: bimpcommercial
            struct: 
                type: custom
                custom: 
                    callback: 
                        method: renderCommercialView
                        object: product
          - id: equipments
            title: Equipements
            show: 
                callback: 
                    method: isSerialisable
                    object: product
            struct: 
                type: custom
                custom: 
                    callback: 
                        method: renderLinkedObjectsList
                        object: product
                        params: 
                            - equipments
          - id: notes
            title: Notes
            struct:
                type: view
                view:
                    object: product
                    name: product_note
          - id: files
            title: Fichiers joints
            struct: 
                type: rows
                rows:                                                   
                    - cols: 
                        - type: list
                          list: 
                              title: Fichier joints
                              name: default
                              panel: 1
                              object: product
                              children: files
          - id: divers
            title: Divers (admin)
            icon: fas_tools
            show: 
                callback:
                    method: iAmAdmin
                    object: client
            struct: 
                type: custom
                custom: 
                    callback: 
                        method: renderBimpOjectDivers
                        object: product
