table: br_commande_shipment
common_fields: 1

parent_module: bimpcore
parent_object: Bimp_Commande
parent_id_property: id_commande_client

labels: 
    name: expédition
    is_female: 1
        
objects: 
    commande_client:
        relation: hasOne
        delete: 0
        instance: 
            bimp_object:
                module: bimpcore
                name: Bimp_Commande
            id_object: 
                field_value: id_commande_client
                
    entrepot:
        relation: hasOne
        delete: 0
        instance: 
            dol_object: 
                module: product/stock
                file: entrepot
            id_object:
                field_value: id_entrepot
                
    contact: 
        relation: hasOne
        delete: 0
        instance: 
            bimp_object: 
                module: bimpcore
                name: Bimp_Contact
            id_object: 
                field_value: id_contact
                
    reservation_shipments: 
        relation: hasMany
        delete: 1
        instance: 
            bimp_object: BR_ReservationShipment
            
    service_shipments:
        relation: hasMany
        delete: 1
        instance: 
            bimp_object: BR_ServiceShipment
            
    facture: 
        relation: hasOne
        delete: 0
        instance: 
            bimp_object: 
                module: bimpcore
                name: Bimp_Facture
            id_object: 
                field_value: id_facture
        cards: 
            default: 
                type: facture_card
    
fields: 
    id_commande_client: 
        label: Commande client
        type: id_parent
        object: commande_client
        required: 1
        input: 
            type: hidden
        
    id_entrepot: 
        label: Centre
        type: id_object
        object: entrepot
        input: 
            type: hidden
        
    num_livraison:
        label: Numéro de livraison
        type: int
        default_value: 1
        unsigned: 1
        
    status: 
        label: Statut
        type: int
        values: 
            array: status_list
        default_value: 1
        
    date_shipped: 
        label: Date d'expédition
        type: datetime
        
    id_contact:
        label: Destinataire
        type: id_object
        object: contact
        default_value: 0
        values: 
            array: contacts
            
    id_facture: 
        label: Facture
        type: id_object
        object: facture
        default_value: 0
        
    signed: 
        label: Signé
        type: int
        values: 
            array: signed_values
        default_value: 0
    info: 
        label: Informations
        type: text        
        input: 
            note: 1
            auto_expand: 1
            rows: 3
        
forms: 
    default: 
        rows: 
            - field: id_commande_client
              hidden: 1
            - field: id_contact
            - field: signed
            - field: info
            
            
    validation: 
        rows: 
            - custom: 1
              hidden: 1
              input_name: validation
              input:
                  type: hidden
              value: 1
            - custom: 1
              label: Produits inclus
              input_name: products
              content: 
                  callback: renderProductsQties
              value: 1
            - label: Services à inclure
              custom: 1
              input_name: services
              content: 
                  callback: renderServicesQties
                  
    facture: 
        rows: 
            - custom: 1
              label: Conditions de réglement
              input_name: cond_reglement
              value: 
                  callback: getCommandeCondReglement
              input: 
                  type: select_cond_reglement
                  
fields_tables: 
    data: 
        panel: 0
        rows: 
            - field: num_livraison
            - field: status
            - field: id_contact
            - field: signed
              edit: 1
            - field: date_shipped
            - field: info
              edit: 1
            - field: id_facture
              display: card
              show: 
                  field_value: id_facture
            
views: 
    default: 
        rows: 
            - cols: 
                - type: object_common_fields
                  col_lg: 4
                  col_md: 5
                  col_sm: 12
                     
                - type: fields_table
                  col_lg: 8
                  col_md: 7
                  col_sm: 12
                  fields_table: 
                      name: data
    lines: 
        title: Produits / services inclus dans l'expédition
        rows: 
            - cols: 
                - type: list
                  list: 
                      name: default
                      children: reservation_shipments
            - cols: 
                - type: list
                  list: 
                      name: default
                      children: service_shipments
                      
lists: 
    default: 
        sort_field: id
        sort_way: desc
        n: 25
        edit_btn: 1
        update_btn: 1
        edit_form: default
        modal_view: default
        objects_change_reload: BR_Reservation,BR_ReservationShipment,BR_Service,BR_ServiceShipment
        extra_btn: 
            callback: getExtraBtn
        cols:
            commande: 
                field: id_commande_client
                display: nom_url
            num_livraison:
                label: N°
                field: num_livraison
                max_width: 30px
            status: 
                field: status
            contact: 
                label: Destinataire
                value: 
                    callback: displayContact
            date: 
                label: Expédiée le
                field: date_shipped
            signed: 
                field: signed
                edit: 1
            pdf:
                label: Fichiers
                value: 
                    callback: 
                        method: displayPdfButtons
                        params: 
                            - 1
                    
    commandes: 
        enable_search: 0
        pagination: 0
        sort_field: id
        sort_way: asc
        n: 0
        edit_btn: 1
        update_btn: 1
        add_btn: 1
        add_form_name: default
        edit_form: default
        modal_view: default
        objects_change_reload: BR_Reservation,BR_ReservationShipment,BR_Service,BR_ServiceShipment
        extra_btn: 
            callback: getExtraBtn
        cols:
            num_livraison:
                label: N°
                field: num_livraison
                max_width: 30px
            status: 
                field: status
            contact: 
                label: Destinataire
                value: 
                    callback: displayContact
            qty_articles: 
                label: Articles
                value: 
                    callback: getNbArticles
            qty_services: 
                label: Services
                value: 
                    callback: getNbServices
#            create:
#                label: Créée le
#                field: date_create
            date: 
                label: Expédiée le
                field: date_shipped
            signed: 
                field: signed
                edit: 1
            pdf:
                label: Fichiers
                value: 
                    callback: displayPdfButtons