table: br_reservation

common_fields: 1

labels: 
    name: réservation
    is_female: 1

objects: 
    entrepot:
        relation: hasOne
        delete: 0
        instance: 
            dol_object: 
                module: product/stock
                file: entrepot
            id_object:
                field_value: id_entrepot
                
    commercial: 
        relation: hasOne
        delete: 0
        instance: 
            bimp_object: 
                module: bimpcore
                name: Bimp_User
            id_object: 
                field_value: id_commercial
                
    client: 
        relation: hasOne
        delete: 0
        instance: 
            bimp_object: 
                module: bimpcore
                name: Bimp_Societe
            id_object: 
                field_value: id_client
                
    product: 
        relation: hasOne
        delete: 0
        instance: 
            bimp_object:
                module: bimpcore
                name: Bimp_Product
            id_object: 
                field_value: id_product
                
    equipment: 
        relation: hasOne
        delete: 0
        instance: 
            bimp_object: 
                module: bimpequipment
                name: Equipment
            id_object: 
                field_value: id_equipment
                
    commande_client: 
        relation: hasOne
        delete: 0
        instance: 
            dol_object: commande
            id_object: 
                field_value: id_commande_client
        cards: 
            default: 
                type: commande_client_card

    commande_fournisseur:
        relation: hasOne
        delete: 0
        instance: 
            dol_object: 
                module: fourn
                file: fournisseur.commande
                class: CommandeFournisseur
            id_object: 
                field_value: id_commande_fournisseur
        cards: 
            default: 
                type: commande_fournisseur_card
                
fields: 
    id_entrepot:
        label: Centre
        type: id_object
        object: entrepot
        required: 1
        input: 
            type: search_entrepot
            
    type:
        label: Type de réservation
        type: int
        values:
            array: types
        required: 1
        default_value: 1
        
    status: 
        label: Statut
        type: int
        values: 
            array: status_list
        input: 
            options: 
                array: statusList
        required: 1
        depends_on: type
    
    id_commercial: 
        label: Commercial
        type: id_object
        object: commercial
        default_value: 0
        input: 
            type: search_user
        display: 
            nom_url: 
                type: nom_url
                modal_view: default
    
    id_client: 
        label: Client
        type: id_object
        object: client
        input: 
            type: search_societe
            societe_type: customer
            help: Entrez un nom ou un code client pour effectuer une recherche
        display_if: 
            field_name: type
            hide_values: 2
    
    id_equipment: 
        label: Equipement
        type: id_object
        object: equipment
        input: 
            type: search_list
            search_list: 
                table: be_equipment
                fields_search: id,serial
                field_return_label: id,serial
                field_return_value: id
                label_syntaxe: Equipement <label_1> - serial "<label_2>"
            help: Entrez un id d\équipement ou un numéro de série pour effectuer une recherche
        display_if: 
            field_name: status
            hide_values: 100
                
    id_product: 
        label: Produit
        type: id_object
        object: product
        input: 
            type: search_product
            help: Entrez un nom ou une référence pour effectuer une recherche
        display_if: 
            field_name: id_equipment
            show_values: 0,
        display: 
            card: 
                type: card
                card: default
                
    id_commande_client:
        label: Commande Client
        type: id_object
        object: commande_client
        input: 
            type: search_commande_client
            id_client: 
                field_value: id_client
        display_if: 
            field_name: type
            hide_values: 2,3
        depends_on: id_client
        
    id_commande_client_line: 
        label: Ligne commande client
        type: id
        values: 
            array: commandeClientLines
        display_if: 
            field_name: id_commande_client
            hide_values: 0,
        depends_on: id_commande_client,id_product
        
    id_commande_fournisseur: 
        label: Commande Fournisseur
        type: id_object
        object: commande_fournisseur
        input: 
            type: search_commande_fournisseur
        display_if: 
            field_name: status
            show_values: 100
        display_if: 
            field_name: type
            hide_values: 2,3
            
    id_commande_fournisseur_line:
        label: Ligne de commande fournisseur
        type: id
        values: 
            array: commandeFournisseurLines
        display_if: 
            field_name: id_commande_fournisseur
            hide_values: 0,
        depends_on: id_commande_fournisseur
    
    id_transfert: 
        label: Transfert
        type: id
        input: 
            type: text
        display_if: 
            field_name: type
            show_values: 2
            
    qty: 
        label: Quantité
        type: int
        decimals: 0
        min: 1
        default_value: 1
        display_if: 
            field_name: id_equipment
            show_values: 0,
            
    date_from: 
        label: A partir du
        type: datetime
        input: 
            display_now: 1
        required: 1
        
    date_to: 
        label: Jusqu'au
        type: datetime
        display_if: 
            field_name: type
            show_values: 3
        
    note: 
        label: Note
        type: text
        input: 
            note: 1
            auto_expand: 1
            
forms: 
    equipment:
        title: 
            callback: getEquipmentFormTitle
        rows: 
            - field: status
            - field: id_user_origin
            - field: id_equipment
              hidden: 1
            - field: date_from
            - field: date_to
            - field: origin_element
            - field: origin_id_element
            - field: note
            
    new_status: 
        title: Réception d'une livraison
        rows: 
            - custom: 1
              hidden: 1
              input_name: status
              data_type: bool
              input: 
                  type: hidden
              value: 
                  field_value: status
            - field: id_equipment
              show: 
                  callback: isProductSerialisable
            - field: qty
              show:
                  callback: isProductNotSerialisable
            - custom: 1
              hidden: 1
              input_name: new_status
              data_type: bool
              content: <input type="hidden" name="new_status" value="1"/>
            
fields_tables: 
    default: 
        rows: 
            - field: id_entrepot
            - field: type
            - field: status
            - field: id_product
              display: card
            - field: id_equipment
              display: card
              show: 
                  callback: isEquipment
            - field: qty
              show: 
                  callback: isProduct
            - field: date_from
              edit: 1
            - field: date_to
              edit: 1
            - field: note
              edit: 1       
              
    commande: 
        title: Commande Client
        rows: 
            - field: id_client
              display: card
            - field: id_commande_client
              display: card
            - field: id_commande_client_line
              
views: 
    default: 
        edit_form: default
        delete_btn: 1
        rows:
            - cols: 
                  - type: object_common_fields
                    col_lg: 3
                    col_sm: 12
                  - type: fields_table
                    col_lg: 9
                    fields_table:
                        name: default  
            
lists: 
    default: 
        checkboxes: 1
        bulk_actions: 
            - label: Supprimer les réservations sélectionnées
              icon: trash
              onclick: deleteSelectedObjects('list_id', $(this));
              btn_class: deleteSelectedObjects
        objects_change_reload: BR_ReservationCmdFourn
        add_form_name: default
        edit_btn: 1
        update_btn: 1
        delete_btn: 1
        modal_view: default
        sort_field: id
        sort_way: desc
        n: 10
        extra_btn: 
            callback: getListExtraBtn
        cols:
            entrepot: 
                field: id_entrepot
                display: nom_url
            product: 
                field: id_product
                display: nom_url
            equipment: 
                field: id_equipment
                display: nom_url
            client: 
                field: id_client
                display: nom_url
            commercial: 
                field: id_commercial
                display: nom_url
            date_from:
                label: Du
                field: date_from
            date_to: 
                label: Au
                field: date_to
            qty: 
                field: qty
            status:
                field: status
                
    commandes: 
        checkboxes: 1
        bulk_actions: 
            - label: Marquer comme livré au client
              icon: sign-out
              onclick: setSelectedReservationStatus($(this), 'list_id', 300);
            - label: Annuler
              icon: times-circle
              onclick: setSelectedReservationStatus($(this), 'list_id', 303);
        objects_change_reload: BR_ReservationCmdFourn
        modal_view: default
        sort_field: id_product
        sort_way: asc
        n: 25
        extra_btn: 
            callback: getListExtraBtn
        cols:
            date_from:
                label: Date de début
                field: date_from
            product: 
                field: id_product
                display: nom_url
            equipment: 
                field: id_equipment
                display: nom_url
            commercial: 
                field: id_commercial
                display: nom_url
            qty: 
                field: qty
            status:
                field: status