table: be_reservation

common_fields: 1

labels: 
    name: réservation
    is_female: 1

objects: 
    user_origin: 
        extends: user
        instance: 
            id_object: 
                field_value: id_user_origin
    product: 
        instance:
            bimp_object: unset
            dol_object: product
        cards: 
            default: 
                type: product_card

fields: 
    id_user_origin: 
        label: Utilisateur à l'origine de la réservation
        type: id_object
        object: user_origin
        default_value: 
            prop: 
                name: id
                object:
                    global: user
        input: 
            type: search_user
        display: 
            nom_url: 
                type: nom_url
                modal_view: default
    id_equipment: 
        label: Equipement
        type: id_object
        object: equipment
        input: 
            type: search_list
            search_list: 
                table: be_equipment
                fields_search: id,serial
                field_return_label: id,serial
                field_return_value: id
                label_syntaxe: Equipement <label_1> - serial "<label_2>"
    id_product: 
        label: produit
        type: id_object
        object: product
        input: 
            type: search_product
        display_if: 
            field_name: id_equipment
            show_values: 0,
        display: 
            card: 
                type: card
                card: default
    qty: 
        label: Quantité
        type: int
        decimals: 0
        min: 1
        default_value: 1
        display_if: 
            field_name: id_equipment
            show_values: 0,
    date_from: 
        label: A partir du
        type: datetime
        input: 
            display_now: 1
    date_to: 
        label: Jusqu'au
        type: datetime
    
    active: 
        label: Actif
        type: bool
        default_value: 1
        
    origin_element:
        label: Type d'objet lié
        type: int
        values:
            array: origin_elements
        default_value: 0
            
    origin_id_element:
        label: Objet lié
        type: int
        default_value: 0
        display_if: 
            field_name: origin_element
            hide_values: 0,
        input: 
            type: custom
            content: 
                callback: getOriginIdElementInput
        depends_on: origin_element
        display: 
            default: 
                type: callback
                method: displayOriginElement
        
    note: 
        label: Note
        type: text
        input: 
            note: 1
            auto_expand: 1

fields_tables: 
    default: 
        rows: 
            - field: id_user_origin
              display: nom_url
            - field: origin_element
            - field: origin_id_element
            - field: id_product
              display: card
            - field: id_equipment
              display: card
              show: 
                  callback: isEquipment
            - field: qty
              show: 
                  callback: isProduct
            - field: date_from
              edit: 1
            - field: date_to
              edit: 1
            - field: active
              edit: 1
            - field: note
              edit: 1
              
views: 
    default: 
        edit_form: default
        delete_btn: 1
        rows:
            - cols: 
                  - type: object_common_fields
                    col_lg: 3
                    col_sm: 12
                  - type: fields_table
                    col_lg: 9
                    fields_table:
                        name: default  
            
lists: 
    default: 
        checkboxes: 1
        bulk_actions: 
            - label: Supprimer les réservations sélectionnées
              icon: fas_trash-alt
              onclick: deleteSelectedObjects('list_id', $(this));
              btn_class: deleteSelectedObjects
        add_form_name: default
        edit_btn: 1
        update_btn: 1
        delete_btn: 1
        modal_view: default
        sort_field: id
        sort_way: desc
        n: 10
        cols:
            product: 
                field: id_product
                display: nom_url
            equipment: 
                field: id_equipment
                display: nom_url
            user: 
                label: Responsable
                field: id_user_origin
                display: nom_url
            date_from:
                label: Du
                field: date_from
            date_to: 
                label: Au
                field: date_to
            qty: 
                field: qty
            active:
                field: active
                edit: 1