# Entité RDC

table: societe
controller: client_rdc

header_edit_form: form_client_rdc

nom_url:
    syntaxe: <name>
    
    
labels:
    name: Marchand
    is_female: 0
        
objects:
    user_attr:
        extends: user
        instance:
            id_object:
                request: fk_user
    concurrence:
        relation: hasMany
        delete: 1
        instance:
            bimp_object: Bimp_Concurrence
    chiffre_affaire:
        relation: hasMany
        delete: 1
        instance:
            bimp_object: Bimp_ChiffreAffaire
        list:
            filters:
                type_obj: Bimp_Societe
                id_obj:
                    callback:
                        method: getData
                        params:
                            - rowid

fields:
    zip:
        required: 0
    town:
        required: 0
    fournisseur: unset
    code_compta: unset
    nom:
        label: Raison sociale
    shopid:
        label: Shop ID
    
    date_der_contact:
        label: Dernier contact
        type: date
    date_debut_prospect:
        label: Début prospection
        type: date
    date_ouverture:
        label: Ouverture
        type: date
    fk_priorite:
        label: Priorité
        type: int
        values:
            dict: societe_rdc_priorities                    
    fk_statut_rdc:
        label: Prospection
        type: int
        values:
            array: statusRdc
    date_changement_statut_rdc:
        label: Changement de statut
        type: date
    delai_ouverture:
        label: Délai ouverture
        type: int
    fk_source_rdc:
        label: Source
        type: int
        values:
            dict: societe_rdc_sources
    fk_statut_kyc:
        label: Statut KYC
        type: int
        values:
            array: statut_kyc_list
    contrefacon:
        label: Problème qualité
        type: int
        values:
            array: valuesContrefacon
    comment_quality:
        label: Commentaire qualité
        type: text
    
    fk_group_rdc:
        label: Groupe
        values:
            array:
                callback:
                    method: getUserGroupsArray
    fk_user_attr_rdc:
        label: Attribué à
        type: id_object
        object: user_attr
        input:
            type: select
            options:
                callback:
                    method: getUserAttrByGroupArray
        depends_on: fk_group_rdc
    commentaire_rdc:
        label: Commentaires
        type: text
    url:
        label: Site internet marchand
    date_maj_mirakl:
        label: Date de mise à jour Mirakl
        type: datetime
    commentaire_statut_ko:
        label: Commentaire statut KO
    potentiel_catalogue:
        label: Potentiel catalogue
        type: qty
        unsigned: 0
    fk_categorie_maitre:
        label: Catégorie Maitre
        type: items_list
        values:
            dict: societe_rdc_cat_maitre
        items_data_type: int
        items_braces: 1

    presta_source:
        label: Prestataire/Agrégateur
        input:
            extra_content: '<p style="margin-top:1em; color: red;">Obligatoire si la source est "Prestataire/Agrégateur"</p>'
    quality_score:
        label: Qualité
        type: float
    name_alias:
        label: Nom de la boutique
    
        
    outstanding_limit: unset
    outstanding_limit_credit_check: unset
    outstanding_limit_manuel: unset
    outstanding_limit_manuel_old: unset
    outstanding_limit_atradius: unset
    date_atradius: unset
    date_rappel_atradius: unset
    date_demande_atradius: unset
    status_atradius: unset
    outstanding_limit_icba: unset
    date_depot_icba: unset
    id_atradius: unset
    id_contact_relances: unset
    filters: unset
    fk_pays:
        default_value: 0
    code_client: unset

fields_tables:
    identity_rdc:
        title: Identité
        icon: id-card
        rows:
            - field: nom
            - field: code_compta
              show:
                  callback: isClient
            - field: code_compta_fournisseur
              show:
                  callback: isFournisseur
            - field: is_subsidiary
            - label: Infos contact
              value:
                  callback: displayFullContactInfosNoWeb
            - label: Adresse
              value:
                  callback: displayFullAddress
            - label: Site internet Marchand
              value:
                  callback: getUrlMarchand
            - field: commentaire_rdc
    
    param_rdc:
        title: Paramètres RDC
        icon: fas_briefcase
        rows:
            - field: shopid
            - field: date_maj_mirakl
            - field: name_alias
            - label: Lien Mirakl
              value:
                  callback: getMiraklLink
            - field: date_der_contact
            - field: date_debut_prospect
            - field: date_ouverture
            - field: fk_priorite
#            - field: fk_statut_rdc
#            - field: date_changement_statut_rdc
#            - field: fk_statut_kyc
            - field: delai_ouverture
            - field: fk_source_rdc
            - field: presta_source
#            - field: quality_score
            - field: contrefacon
            - field: comment_quality
            - field: fk_user_attr_rdc
            - field: fk_categorie_maitre
            - field: potentiel_catalogue
    
    commentaires:
        title: Commentaires
        icon: fas_comment
        rows:
            - field: commentaire_rdc
    
    infos_comm:
        show: 0
    encours:
        show: 0
    encours_infos:
        show: 0
    contact:
        show: 0
    identifiers:
        show: 0
    infos:
        show: 0
    notes:
        show: 0

views:
    default:
        title: nom
        rows:
            - cols:
                  - type: fields_table
                    col_lg: 6
                    col_md: 6
                    col_sm: 12
                    fields_table:
                        name: identity_rdc
                  
                  - type: fields_table
                    col_lg: 6
                    col_md: 6
                    col_sm: 12
                    fields_table:
                        name: param_rdc
                  
                  - type: custom
                    col_lg: 6
                    col_md: 6
                    col_sm: 12
                    custom:
                        callback:
                            method: renderChildrenList
                            params:
                                - concurrence
                                - default
                  
    ca:
        title: CA
        rows:
              - cols:
                  - type: custom
                    col_lg: 12
                    col_md: 12
                    col_sm: 12
                    custom:
                      callback:
                          method: renderChildrenList
                          params:
                              - chiffre_affaire
                              - default
                  - type: custom
                    col_lg: 6
                    col_md: 12
                    col_sm: 12
                    custom:
                        callback:
                            method: renderChildrenGraph
                            params:
                                - chiffre_affaire
                                - evol
                  - type: custom
                    col_lg: 6
                    col_md: 12
                    col_sm: 12
                    custom:
                        callback:
                            method: renderChildrenGraph
                            params:
                                - chiffre_affaire
                                - evol2
                  - type: custom
                    col_lg: 6
                    col_md: 12
                    col_sm: 12
                    custom:
                        callback:
                            method: renderChildrenGraph
                            params:
                                - chiffre_affaire
                                - rep
                  - type: custom
                    col_lg: 6
                    col_md: 12
                    col_sm: 12
                    custom:
                        callback:
                            method: renderChildrenGraph
                            params:
                                - chiffre_affaire
                                - rep2
                  - type: custom
                    col_lg: 6
                    col_md: 12
                    col_sm: 12
                    custom:
                        callback:
                            method: renderChildrenGraph
                            params:
                                - chiffre_affaire
                                - rep3
                  - type: custom
                    col_lg: 6
                    col_md: 12
                    col_sm: 12
                    custom:
                        callback:
                            method: renderChildrenGraph
                            params:
                                - chiffre_affaire
                                - rep4

forms:
    default:
        extends: form_client_rdc
        
    form_client_rdc:
        title: Ajout d'un client
        rows:
            Nom:
                field: nom
            boutique:
                field: name_alias
            Filiale:
                field: is_subsidiary
            Téléphone:
                field: phone
            Email:
                field: email
            Adresse:
                field: address
            Code postal:
                field: zip
            Ville:
                field: town
            Pays:
                field: fk_pays
            Site internet marchand:
                field: url
            Shop ID:
                field: shopid
            Priorité:
                field: fk_priorite
            Prospection:
                field: fk_statut_rdc
            Commentaire statut KO:
                field: commentaire_statut_ko
                required:
                    callback: isCommentaireStatutKoRequired
            fk_categorie_maitre:
                field: fk_categorie_maitre
            Source:
                field: fk_source_rdc
            Agrégateur:
                field: presta_source
                display_if:
                    field_name: fk_source_rdc
                    show_values:
                        callback:
                            method: getIdSourcePresta                
            contrefacon:
                field: contrefacon
            comment_quality:
                field: comment_quality
            Groupe:
                field: fk_group_rdc
            Attribué à:
                field: fk_user_attr_rdc
            Commentaires:
                field: commentaire_rdc
            Potenitel catalogue:
                field: potentiel_catalogue
                
                
    formActionRdc:
        title: Choisir une action
        rows:
            - custom: 1
              label: Actions
              input_name: status
              input:
                  type: select
                  options:
                      callback: getListButtons

filters_panels:
    default:
        filters:
            fk_statut_rdc:
            fk_statut_kyc:
            date_der_contact:
            date_debut_prospect:
            date_ouverture:
            fk_priorite:
            fk_source_rdc:
            contrefacon:
            fk_categorie_maitre:
            fk_pays:
            fk_typent: unset
            code_compta: unset
            code_client: unset
            siret: unset
            siren: unset
            ape: unset
            rpps: unset
            commerciaux: unset
            secteuractivite: unset
            marche: unset
            address: unset
            zip: unset
            town: unset
            email: unset
            phone: unset
            status: unset
            solvabilite_status: unset
            
                

lists_cols:
    flag_import:
        label: Flag
        value:
            callback: getFlagImport

lists:
    default:
        title: Liste des clients
        object: client
        add_btn_label: Nouvelle société
        add_form_name: form_client_rdc

    rdc:
        configurable: 1
        checkboxes: 1
        title: Liste des Marchands
        filters_panel: default
        bulk_actions:
            -   label: supprimer les société sélectionnées
                icon: fas_trash-alt
                onclick: deleteSelectedObjects('list_id', $(this))
        object: client
        add_btn_label: Nouveau marchand
        header_buttons:
            callback: getDefaultListExtraHeaderButtons
        add_form_name: form_client_rdc
        sort_field: name_alias
        sort_way: ASC
        page_btn: 1
        modal_view: default
        edit_btn: 1
        cols:
            shopid:
            nom:
            name_alias:
            fk_statut_rdc:
            fk_statut_kyc:
#            full_address:
#            infos_contact:
            date_der_contact:
            date_debut_prospect:
            fk_priorite:
            flag_import:
                label: Flag
            contrefacon:

stats_lists:
    default:
        group_by_options:
            - fk_categorie_maitre
            - fk_statut_rdc
            - fk_priorite
            - fk_source_rdc
            - fk_statut_kyc
            - fk_group_rdc
            - fk_user_attr_rdc
                

searches:
    default:
        fields_search:
            4: a.shopid
            # desactivation recherche sur codes unitiliser par RDC
            3: unset
            6: unset
            7: unset
