# Entité RDC

table: societe
controller: client_rdc

header_edit_form: form_client_rdc

objects:
    user_attr:
        extends: user
        instance:
            id_object:
                request: fk_user
    concurrence:
        relation: hasMany
        delete: 1
        instance:
            bimp_object: Bimp_Concurrence
    chiffre_affaire:
        relation: hasOne
        delete: 1
        instance:
            bimp_object: Bimp_ChiffreAffaire
        list:
            filters:
                type_obj: 0
                id_obj:
                    callback:
                        method: getData
                        params:
                            - rowid

fields:
    zip:
        required: 0
    town:
        required: 0
    fournisseur: unset
    code_compta: unset
    shopid:
        label: Shop ID
    
    date_der_contact:
        label: Dernier contact
        type: date
    date_debut_prospect:
        label: Début prospection
        type: date
    date_ouverture:
        label: Ouverture
        type: date
    fk_priorite:
        label: Priorité
        type: int
        values:
            dict: societe_rdc_priorities                    
    fk_statut_rdc:
        label: Prospection
        type: int
        values:
            array: statusRdc
    date_changement_statut_rdc:
        label: Changement de statut
        type: date
    delai_ouverture:
        label: Délai ouverture
        type: int
    fk_source_rdc:
        label: Source
        type: int
        values:
            dict: societe_rdc_sources
    fk_statut_kyc:
        label: Statut KYC
        type: int
        values:
            array: statut_kyc_list
    contrefacon:
        label: Suspition de contrefaçon
        type: bool
    
    fk_group_rdc:
        label: Groupe
        values:
            array:
                callback:
                    method: getUserGroupsArray
    fk_user_attr_rdc:
        label: Attribué à
        type: id_object
        object: user_attr
        input:
            type: select
            options:
                callback:
                    method: getUserAttrByGroupArray
        depends_on: fk_group_rdc
    commentaire_rdc:
        label: Commentaires
        type: text
    url:
        label: Site internet marchand
    date_maj_mirakl:
        label: Date de mise à jour Mirakl
        type: datetime
    commentaire_statut_ko:
        label: Commentaire statut KO
    potentiel_catalogue:
        label: Potentiel catalogue
        type: qty
        unsigned: 0
    fk_categorie_maitre:
        label: Catégorie Maitre
        values:
            array: categorieMaitreRdc
    presta_source:
        label: Prestataire/Agrégateur
        input:
            extra_content: '<p style="margin-top:1em; color: red;">Obligatoire si la source est "Prestataire/Agrégateur"</p>'
    quality_score:
        label: Qualité
        type: float
    name_alias:
        label: Nom de la boutique
    
        
    outstanding_limit: unset
    outstanding_limit_credit_check: unset
    outstanding_limit_manuel: unset
    outstanding_limit_manuel_old: unset
    outstanding_limit_atradius: unset
    date_atradius: unset
    date_rappel_atradius: unset
    date_demande_atradius: unset
    status_atradius: unset
    outstanding_limit_icba: unset
    date_depot_icba: unset
    id_atradius: unset
    id_contact_relances: unset
    filters: unset

fields_tables:
    identity_rdc:
        title: Identité
        icon: id-card
        rows:
            - field: nom
            - field: code_compta
              show:
                  callback: isClient
            - field: code_compta_fournisseur
              show:
                  callback: isFournisseur
            - field: is_subsidiary
            - label: Infos contact
              value:
                  callback: displayFullContactInfos
            - label: Adresse
              value:
                  callback: displayFullAddress
            - field: url
            - field: commentaire_rdc
    
    param_rdc:
        title: Paramètres RDC
        icon: fas_briefcase
        rows:
            - field: shopid
            - field: date_maj_mirakl
            - field: name_alias
            - label: Lien Mirakl
              value:
                  callback: getMiraklLink
            - field: date_der_contact
            - field: date_debut_prospect
            - field: date_ouverture
            - field: fk_priorite
              edit:
                  callback:
                      method: isUserBDKAM
#            - field: fk_statut_rdc
#            - field: date_changement_statut_rdc
#            - field: fk_statut_kyc
            - field: delai_ouverture
            - field: fk_source_rdc
            - field: presta_source
#            - field: quality_score
            - label: Suspition de contrefaçon
              value:
                  callback: getContrefacon
            - field: fk_group_rdc
            - field: fk_user_attr_rdc
            - field: fk_categorie_maitre
            - field: potentiel_catalogue
    
    commentaires:
        title: Commentaires
        icon: fas_comment
        rows:
            - field: commentaire_rdc
    
    infos_comm:
        show: 0
    encours:
        show: 0
    encours_infos:
        show: 0
    contact:
        show: 0
    identifiers:
        show: 0
    infos:
        show: 0
    notes:
        show: 0

views:
    default:
        title: nom
        rows:
            - cols:
                  - type: fields_table
                    col_lg: 6
                    col_md: 6
                    col_sm: 12
                    fields_table:
                        name: identity_rdc
                  
                  - type: fields_table
                    col_lg: 6
                    col_md: 6
                    col_sm: 12
                    fields_table:
                        name: param_rdc
                  
                  - type: custom
                    col_lg: 6
                    col_md: 6
                    col_sm: 12
                    custom:
                        callback:
                            method: renderChildrenList
                            params:
                                - concurrence
                                - default
                  
    ca:
        title: CA
        rows:
              - cols:
                  - type: custom
                    col_lg: 12
                    col_md: 12
                    col_sm: 12
                    custom:
                      callback:
                          method: renderChildrenList
                          params:
                              - chiffre_affaire
                              - default
                  - type: custom
                    col_lg: 6
                    col_md: 12
                    col_sm: 12
                    custom:
                        callback:
                            method: renderChildrenGraph
                            params:
                                - chiffre_affaire
                                - rep
                  - type: custom
                    col_lg: 6
                    col_md: 12
                    col_sm: 12
                    custom:
                        callback:
                            method: renderChildrenGraph
                            params:
                                - chiffre_affaire
                                - rep2
                  - type: custom
                    col_lg: 6
                    col_md: 12
                    col_sm: 12
                    custom:
                        callback:
                            method: renderChildrenGraph
                            params:
                                - chiffre_affaire
                                - rep3
                  - type: custom
                    col_lg: 6
                    col_md: 12
                    col_sm: 12
                    custom:
                        callback:
                            method: renderChildrenGraph
                            params:
                                - chiffre_affaire
                                - rep4
                  - type: custom
                    col_lg: 6
                    col_md: 12
                    col_sm: 12
                    custom:
                        callback:
                            method: renderChildrenGraph
                            params:
                                - chiffre_affaire
                                - evol
                  - type: custom
                    col_lg: 6
                    col_md: 12
                    col_sm: 12
                    custom:
                        callback:
                            method: renderChildrenGraph
                            params:
                                - chiffre_affaire
                                - evol2

forms:
    default:
        extends: form_client_rdc
        
    form_client_rdc:
        title: Ajout d'un client
        rows:
            Nom:
                field: nom
            boutique:
                field: name_alias
            Filiale:
                field: is_subsidiary
            Téléphone:
                field: phone
            Email:
                field: email
            Adresse:
                field: address
            Code postal:
                field: zip
            Ville:
                field: town
            Pays:
                field: fk_pays
            Site internet marchand:
                field: url
            Shop ID:
                field: shopid
                edit:
                    callback: isShopIdEditable
            Priorité:
                field: fk_priorite
                edit:
                    callback: isUserBDKAM
            Prospection:
                field: fk_statut_rdc
                edit: 0
            Commentaire statut KO:
                field: commentaire_statut_ko
                required:
                    callback: isCommentaireStatutKoRequired
            
            Catégorie Maitre:
                field: fk_categorie_maitre
                edit:
                    callback: isUserBDKAM
            Source:
                field: fk_source_rdc
                edit:
                    callback: isUserBD
            Agrégateur:
                field: presta_source
                display_if:
                    field_name: fk_source_rdc
                    show_values:
                        callback:
                            method: getIdSourcePresta                
            Suspition de contrefaçon:
                field: contrefacon
            Groupe:
                field: fk_group_rdc
                edit:
                    callback: isUserBDKAM
            Attribué à:
                field: fk_user_attr_rdc
                edit:
                    callback: isUserBDKAM
            Commentaires:
                field: commentaire_rdc
            Potenitel catalogue:
                field: potentiel_catalogue
                edit:
                    callback: isUserBDKAM
                
                
    formActionRdc:
        title: Choisir une action
        rows:
            - custom: 1
              label: Actions
              input_name: status
              input:
                  type: select
                  options:
                      callback: getListButtons

lists:
    default:
        title: Liste des clients
        object: client
        add_btn_label: Nouvelle société
        add_form_name: form_client_rdc


stats_lists:
    default:
        group_by_options:
            - fk_categorie_maitre
            - fk_statut_rdc
            - fk_priorite
            - fk_source_rdc
            - fk_statut_kyc
            - fk_group_rdc
            - fk_user_attr_rdc
