table: ca_rdc
icon: fas_euro-sign

header_list_name: default

labels:
    name: Chiffre d'affaire
    name_plur: Chiffres d'affaire

parent_module: bimpcore
parent_object:
    field_value: type_obj
parent_id_property: id_obj

objects:
    chiffre_affaire:
        relation: hasMany
        delete: 1
        instance:
            bimp_object:
                module: bimpcore
                name: Bimp_ChiffreAffaire
    
    parent_obj:
        relation: hasOne
        delete: 0
        instance:
            bimp_object:
                module: bimpcore
                name:
                    callback:
                        method: getObjectParentName
                        params:
                            - type_obj

fields:
    id_obj:
        label: ID Objet
        object: parent_obj
        type: id_object
        depends_on: type_obj
        
    type_obj:
        label: Type
        values:
            array:
                callback:
                    method: getTypesObjetsRdc
                    
    ca:
        label: Chiffre d'Affaire
        type: money
        history: 1
    
    fk_category:
        label: Catégorie CA 1
        values:
            dict:
                code: ca_categories
                include_empty: 1
                empty_value: 0
                active_only: 0
            input:
                type: select
                options:
                    dict:
                        code: ca_categories
                        include_empty: 1
                        empty_value: 0
                        active_only: 1
    
    fk_category2:
        label: Catégorie CA 2
        values:
            dict:
                code: ca_categories
                include_empty: 1
                empty_value: 0
                active_only: 0
            input:
                type: select
                options:
                    dict:
                        code: ca_categories
                        include_empty: 1
                        empty_value: 0
                        active_only: 1
    
    fk_category3:
        label: Catégorie CA 3
        values:
            dict:
                code: ca_categories
                include_empty: 1
                empty_value: 0
                active_only: 0
            input:
                type: select
                options:
                    dict:
                        code: ca_categories
                        include_empty: 1
                        empty_value: 0
                        active_only: 1
    
    fk_category4:
        label: Catégorie CA 4
        values:
            dict:
                code: ca_categories
                include_empty: 1
                empty_value: 0
                active_only: 0
            input:
                type: select
                options:
                    dict:
                        code: ca_categories
                        include_empty: 1
                        empty_value: 0
                        active_only: 1
    fk_period:
        label: Période
        values:
            array:
                callback:
                    method: getPeriodsRdc
    
    debut_period:
        label: Début Période
        type: date
        depends_on: fk_period
        input:
            format:
                callback:
                    method: getParamsPeriode

forms:
    default:
        rows:
            id_obj:
                field: id_obj
                hidden: 1
            type_obj:
                field: type_obj
                hidden: 1
            fk_category:
                field: fk_category
            fk_category2:
                field: fk_category2
            fk_category3:
                field: fk_category3
            fk_category4:
                field: fk_category4
            ca:
                field: ca
            fk_period:
                field: fk_period
            debut_period:
                field: debut_period



lists:
    default:
        title: liste des chiffres d'affaire
        n: 10
        add_form_name: default
        add_btn: 1
        delete_btn: 1
        modal_view: default
        edit_btn: 1
        cols:
            fk_category:
            fk_category2:
            fk_category3:
            fk_category4:
            ca:
            fk_period:
            period:
                custom: 1
                label: Période
                value:
                    callback:
                        method: displayPeriode
                
                
views:
    default:
        title: nom
        rows:
            - cols:
                  - type: fields_table
                    col_lg: 6
                    col_md: 6
                    col_sm: 12
                    fields_table:
                        name: default
                        

fields_tables:
    default:
        title: Info
        icon: id-card
        rows:
            - field: fk_category
            - field: fk_category2
            - field: fk_category3
            - field: fk_category4
            - field: ca
            - field: fk_period
            - field: debut_period
                
                
graph:
    rep:
        mode: doughnut
        title: Repartition Categories 1
        options:
            fk_period:
                name: Période
                type: select
                values:
                    callback: getPeriodsRdc
                value: 0
        xDateConfig:
            field: debut_period
            date1: 1
            date2: 2
            def: 5year
            params: unset
        y: €
        use_k: 1
        yConfig:
            fields:
                callback: getCategForGrpah
    rep2:
        mode: doughnut
        title: Repartition Categories 2
        options:
            fk_category:
                name: Categories
                type: select
                values:
                    callback:
                        method: getCategCa
                        params:
                            - 1
                            - 1
                value: -1
            fk_period:
                name: Période
                type: select
                values:
                    callback: getPeriodsRdc
                value: 0
        xDateConfig:
            field: debut_period
            date1: 1
            date2: 2
            def: 5year
            params: unset
        y: €
        use_k: 1
        yConfig:
            fields:
                callback:
                    method: getCategForGrpah
                    params:
                        - 2
    rep3:
        mode: doughnut
        title: Repartition Categories 3
        options:
            fk_category:
                name: Categories
                type: select
                values:
                    callback:
                        method: getCategCa
                        params:
                            - 1
                            - 1
                        
                value: -1
            fk_category2:
                name: Categories 2
                type: select
                values:
                    callback:
                        method: getCategCa
                        params:
                            - 2
                            - 1
                value: -1
            fk_period:
                name: Période
                type: select
                values:
                    callback: getPeriodsRdc
                value: 0
        xDateConfig:
            field: debut_period
            date1: 1
            date2: 2
            def: 5year
            params: unset
        y: €
        use_k: 1
        yConfig:
            fields:
                callback:
                    method: getCategForGrpah
                    params:
                        - 3
    rep4:
        mode: doughnut
        title: Repartition Categories 4
        options:
            fk_category:
                name: Categories
                type: select
                values:
                    callback:
                        method: getCategCa
                        params:
                            - 1
                            - 1
                value: -1
            fk_category2:
                name: Categories 2
                type: select
                values:
                    callback: 
                        method: getCategCa
                        params:
                            - 2
                            - 1
                value: -1
            fk_category3:
                name: Categories 3
                type: select
                values:
                    callback:
                        method: getCategCa
                        params:
                            - 3
                            - 1
                value: -1
            fk_period:
                name: Période
                type: select
                values:
                    callback: getPeriodsRdc
                value: 0
        xDateConfig:
            field: debut_period
            date1: 1
            date2: 2
            def: 5year
            params: unset
        y: €
        use_k: 1
        yConfig:
            fields:
                callback:
                    method: getCategForGrpah
                    params:
                        - 4
    evol:
        title: Evolution CA
        mode: splineArea
        options:
            fk_category:
                name: Categories
                type: select
                values:
                    callback: getCategCa
                value: 0
            fk_period:
                name: Période
                type: select
                values:
                    callback: getPeriodsRdc
                value: 3
        xDateConfig:
            field: debut_period
            date1: 1
            date2: 2
            def: 5year
        y: €
        use_k: 1
        yConfig:
            fields:
                total_ht:
                    title: CA ht
                    field: ca
                    calc: SUM
    evol2:
        title: Evolution CA / cat 1
#        mode: splineArea
        options:
            inut_for_align:
                name: ''
                type: select
                values:
                    - ''
            fk_period:
                name: Période
                type: select
                values:
                    callback: getPeriodsRdc
                value: 3
        xDateConfig:
            field: debut_period
            date1: 1
            date2: 2
            def: 5year
        y: €
        use_k: 1
        yConfig:
            fields:
                callback: getCategForGrpah
