dol_object:
    instance:
        dol_object:
            module: ticket
            file: ticket

table: ticket
primary: rowid
controller: ticket
icon: fas_ticket-alt
common_fields: 0

nom_url:
    syntaxe: <ref>

header_list_name: default
header_edit_form: default
header_btn:
    callback: getHeaderButtons

list_page_url:
    controller: index
    url_params:
        tab: default

labels:
    name: ticket

objects:
    client:
        extends: client
        instance:
            id_object:
                field_value: fk_soc
    
    user_create:
        extends: user
        instance:
            id_object:
                field_value: fk_user_create
    
    user_update:
        extends: user
        instance:
            id_object:
                field_value: fk_user_update
    
    user_assigned:
        extends: user
        instance:
            id_object:
                field_value: id_user_assigned
    
    files:
        instance:
            bimp_object:
                module: bimpcore
                name: BimpFile
        
        list:
            filters:
                parent_module: bimpticket
                parent_object_name: Bimp_Ticket
        
        add_form:
            name: upload
            values:
                fields:
                    parent_module: bimpticket
                    parent_object_name: Bimp_Ticket

fields:
    ref:
        label: Référence
    
    fk_statut:
        label: Statut
        dol_prop: status
        type: int
        values:
            array: status_list
        default_value: 0
    
    progress:
        label: Progression
        type: percent
        default_value: 0
    
    type:
        label: Type
        values: 
            dict: 
                code: bimp_ticket_types
                include_empty: 1
    
    origin_email:
        label: Adresse Email source
    
    fk_soc:
        label: Client
        type: id_object
        object: client
        create_form: client_light
        input:
            card: default
    
    fk_user_create:
        label: Créé par
        type: id_object
        object: user_create
        default_value: 0
    
    fk_user_update:
        label: Mis à jour par
        type: id_object
        object: user_update
        default_value: 0
    
    fk_user_assign:
        label: Attribué à
        type: id_object
        object: user_assigned
        input:
            type: search_user
        default_value: 0
    
    track_id:
        label: Identifiant public
    
    subject:
        label: Sujet ticket
        type: html
        required: 1
        hashtags: 1
    
    message:
        label: Description
        type: html
        hashtags: 1
    
    timing:
        label: Timing
        
        
    resolution:
        label: Résolution
        type: text
        hashtags: 1
    
    delai_resolution:
        label: Délai de résolution (en jours)
        type: int
        default_value: 0
        
        
    datec:
        label: Date de création
        type: datetime
    
    date_update:
        label: Date de mise à jour
        type: datetime
    
    date_close:
        label: Date de clôture
        type: datetime
        
forms:
    default:
        rows:
            -   field: fk_user_assign
            -   field: type
            -   field: fk_soc
            -   field: id_contact
            -   field: subject
            -   field: message

fields_tables:
    infos:
        title: Informations
        icon: info-circle
        rows:
            -   field: type
            -   field: subject
            -   field: message
    
    client_infos:
        title: Infos client
        icon: info-circle
        rows:
            -   field: fk_soc
                display: card

views:
    default:
        rows:
            -   cols:
                    -   type: object_header
            -   cols:
                    -   type: fields_table
                        fields_table:
                            name: infos
                        col_lg: 6
                        col_md: 6
                    
                    -   type: fields_table
                        fields_table:
                            name: client_infos
                        col_lg: 6
                        col_md: 6
            -   cols:
                    -   type: list
                        list:
                            name: default
                            children: files
            -   cols:
                    -   type: custom
                        custom:
                            callback: renderNotesList

filters_panels:
    default:
        filters:
            type: 
            fk_soc:
            fk_statut:
            fk_user_assigned:
            datec:

lists:
    default:
        title: Tickets
        configurable: 1
        checkboxes: 1
        filters_panel: default
        bulk_actions:
            -   label: supprimer les tickets sélectionnés
                icon: fas_trash-alt
                onclick: deleteSelectedObjects('list_id', $(this))
        sort_field: date_create
        sort_way: desc
        n: 10
        add_form_name: default
        add_btn_label: Nouveau ticket
        edit_btn: 1
        edit_form: default
        delete_btn: 1
        page_btn: 1
        modal_view: default
        cols:
            ref:
            fk_statut:
            type:
            subject:
            datec:
            fk_soc:
            fk_user_assigned:
