dol_object:
    instance:
        dol_object:
            module: ticket
            file: ticket

table: ticket
primary: rowid
controller: ticket
icon: fas_ticket-alt
common_fields: 0

nom_url:
    syntaxe: <ref>

header_list_name: default
header_edit_form: default
header_btn:
    callback: getHeaderButtons

list_page_url:
    controller: index
    url_params:
        tab: default

labels:
    name: ticket

objects:
    client:
        extends: client
        instance:
            id_object:
                field_value: fk_soc
    
    user_create:
        extends: user
        instance:
            id_object:
                field_value: fk_user_create
    
    user_update:
        extends: user
        instance:
            id_object:
                field_value: fk_user_update
    
    user_assign:
        extends: user
        instance:
            id_object:
                field_value: fk_user_assign
    
    files:
        instance:
            bimp_object:
                module: bimpcore
                name: BimpFile
        
        list:
            filters:
                parent_module: bimpticket
                parent_object_name: Bimp_Ticket
        
        add_form:
            name: upload
            values:
                fields:
                    parent_module: bimpticket
                    parent_object_name: Bimp_Ticket

fields:
    ref:
        label: Référence
    
    fk_statut:
        label: Statut
        type: int
        values:
            array: status_list
        default_value: 0
    
    progress:
        label: Progression
        type: percent
        default_value: 0
    
    type_code:
        label: Type
        values:
            dict: bimp_ticket_types
    
    origin_email:
        label: Adresse Email source
    
    fk_soc:
        label: Client
        type: id_object
        object: client
        create_form: client_light
        input:
            card: default
    
    fk_user_create:
        label: Créé par
        type: id_object
        object: user_create
        default_value: 0
    
    fk_user_update:
        label: Mis à jour par
        type: id_object
        object: user_update
        default_value: 0
    
    fk_user_assign:
        label: Assigné à
        type: id_object
        object: user_assign
        input:
            type: search_user
        default_value: 0
    
    track_id:
        label: Identifiant public
    
    subject:
        label: Sujet ticket
        type: html
        required: 1
        hashtags: 1
    
    message:
        label: Description
        type: html
        hashtags: 1
    
    timing:
        label: Timing
    
    resolution:
        label: Délai de résolution (en jours)
        type: int
        default_value: 0
    
    datec:
        label: Date de création
        type: datetime
    
    date_update:
        label: Date de mise à jour
        type: datetime
    
    date_close:
        label: Date de clôture
        type: datetime

forms:
    default:
        rows:
            -   field: type_code
            -   field: fk_soc
            -   field: subject
            -   field: message
    
    create:
        rows:
            -   field: fk_user_assign
                label: Assigner à
            -   field: type_code
            -   field: fk_soc
            -   custom: 1
                label: Contact client suivi
                input_name: id_contact_suivi
                data_type: id
                input:
                    type: select
                    options:
                        callback:
                            method: getClientContactsArray
                            params:
                                - 1
                                - 1
                depends_on: fk_soc
            -   field: subject
            -   field: message
    
    new_status:
        rows:
            -   custom: 1
                label: Nouveau Statut
                input_name: new_status
                data_type: int
                input: 
                    type: select
                    options:
                        callback: getNewStatusOptionsArray
            -   custom: 1
                label: Motif
                input_name: reason
                input: 
                    type: textarea
                    hashtags: 1
                display_if: 
                    field_name: new_status
                    show_values: 7,9,11
    
    contact:
        title: Ajouter un contact
        rows:
            -   custom: 1
                label: Type
                input_name: type
                input:
                    type: select
                    options:
                        1: Contact tiers
                        2: Utilisateur
            -   custom: 1
                label: Tiers
                input_name: id_client
                input:
                    type: search_object
                    object: client
                value:
                    field_value: fk_soc
                display_if:
                    field_name: type
                    show_values: 1
            -   custom: 1
                label: Contact
                input_name: id_contact
                data_type: id_object
                object: contact
                edit_form: default
                create_form: default
                create_form_values:
                    fields:
                        fk_soc:
                            callback: getAddContactIdClient
                value:
                    request: fields/id_contact
                input:
                    type: select
                    options:
                        array: clientContacts
                display_if:
                    field_name: type
                    show_values: 1
                depends_on: id_client
            -   custom: 1
                label: Utilisateur
                input_name: id_user
                input:
                    type: search_user
                value:
                    prop:
                        object:
                            global: user
                        name: id
                display_if:
                    field_name: type
                    show_values: 2
            -   custom: 1
                label: Type de contact
                input_name: tiers_type_contact
                input:
                    type: select
                    options:
                        array: externalContactTypes
                display_if:
                    field_name: type
                    show_values: 1
            -   custom: 1
                label: Type de contact
                input_name: user_type_contact
                input:
                    type: select
                    options:
                        array: internalContactTypes
                display_if:
                    field_name: type
                    show_values: 2
                    
    assign: 
        rows:
            -   field: fk_user_assign
                label: Assigner à

fields_tables:
    infos:
        title: Informations
        icon: info-circle
        rows:
            -   field: type_code
            -   field: subject
            -   field: message
    
    client_infos:
        title: Infos client
        icon: info-circle
        rows:
            -   field: fk_soc
                display: card

views:
    default:
        rows:
            -   cols:
                    -   type: object_header
            -   cols:
                    -   type: view
                        view:
                            name: fiche
            -   cols:
                    -   type: custom
                        custom:
                            callback: renderNotesList
    
    fiche:
        rows:
            -   cols:
                    -   type: fields_table
                        fields_table:
                            name: infos
                        col_lg: 6
                        col_md: 6
                    
                    -   type: fields_table
                        fields_table:
                            name: client_infos
                        col_lg: 6
                        col_md: 6
            -   cols:
                    -   type: custom
                        custom:
                            callback: renderContacts
            -   cols:
                    -   type: list
                        list:
                            name: default
                            children: files

filters_panels:
    default:
        filters:
            type_code:
            fk_soc:
            fk_statut:
            fk_user_assigned:
            datec:

lists:
    default:
        title: Tickets
        configurable: 1
        checkboxes: 1
        filters_panel: default
        bulk_actions:
            -   label: supprimer les tickets sélectionnés
                icon: fas_trash-alt
                onclick: deleteSelectedObjects('list_id', $(this))
        sort_field: date_create
        sort_way: desc
        n: 10
        add_form_name: create
        add_btn_label: Nouveau ticket
        edit_btn: 1
        edit_form: default
        delete_btn: 1
        page_btn: 1
        modal_view: default
        cols:
            ref:
            fk_statut:
            type_code:
            subject:
            datec:
            fk_soc:
            fk_user_assign:
                
    client: 
        extends: default
        cols:
            fk_soc: unset
