
CREATE TABLE IF NOT EXISTS `llx_bs_sav_product` (
  `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `id_sav` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `id_product` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `qty` int(10) UNSIGNED NOT NULL DEFAULT '0'
) ENGINE=InnoDB;
