ALTER TABLE `llx_entrepot` ADD `code_journal_compta` VARCHAR(3) NOT NULL;
ALTER TABLE `llx_entrepot` ADD `compte_comptable_banque` VARCHAR(11) NOT NULL;
ALTER TABLE `llx_entrepot` ADD `compte_comptable` VARCHAR(11) NOT NULL;
ALTER TABLE `llx_entrepot` ADD `compte_aux` VARCHAR(100) NOT NULL;
ALTER TABLE `llx_facture_fourn` ADD `exported` INT(1) NOT NULL DEFAULT 0;
ALTER TABLE `llx_societe` ADD `exported` INT(1) NOT NULL DEFAULT 0;
ALTER TABLE `llx_paiement` ADD `exported` INT(10) NOT NULL DEFAULT 0;
ALTER TABLE `llx_bank_account` ADD `cegid_journal` VARCHAR(3) DEFAULT NULL;
ALTER TABLE `llx_bank_account` ADD `compte_compta` VARCHAR(20) DEFAULT NULL;

-- UPDATE `llx_bank_account` SET `cegid_journal` = 'SGO', `compte_compta` = '51263000' WHERE `rowid` = 1;
-- UPDATE `llx_bank_account` SET `cegid_journal` = 'LEP', `compte_compta` = '51264100' WHERE `rowid` = 6;
-- UPDATE `llx_bank_account` SET `cegid_journal` = '52', `compte_compta` = '51261000' WHERE `rowid` = 9;
-- UPDATE `llx_bank_account` SET `cegid_journal` = 'BEP', `compte_compta` = '51240500' WHERE `rowid` = 12;
-- UPDATE `llx_bank_account` SET `cegid_journal` = 'BP', `compte_compta` = '51240800' WHERE `rowid` = 15;
-- UPDATE `llx_bank_account` SET `cegid_journal` = 'BPS', `compte_compta` = '51240400' WHERE `rowid` = 18;
-- UPDATE `llx_bank_account` SET `cegid_journal` = 'BV', `compte_compta` = '51240600' WHERE `rowid` = 21;
-- UPDATE `llx_bank_account` SET `cegid_journal` = 'CC', `compte_compta` = '51290000' WHERE `rowid` = 27;
-- UPDATE `llx_bank_account` SET `cegid_journal` = 'CCE', `compte_compta` = '51293000' WHERE `rowid` = 30;
-- UPDATE `llx_bank_account` SET `cegid_journal` = 'LCL', `compte_compta` = '51200000' WHERE `rowid` = 33;
-- UPDATE `llx_bank_account` SET `cegid_journal` = 'SB', `compte_compta` = '51261000' WHERE `rowid` = 36;
-- UPDATE `llx_bank_account` SET `cegid_journal` = 'SGE', `compte_compta` = '51263000' WHERE `rowid` = 39;
