table: bnf_period
common_fields: 0
controller: period
icon: far_calendar-alt

list_page_url: 
    controller: user
    url_params: 
        id: 
            field_value: id_user
            
labels: 
    name: quinzaine
    is_female: 1
    
objects:                
    frais: 
        relation: hasMany
        delete: 0
        instance: 
            bimp_object: BRH_Frais
        list: 
            filters: 
                callback: getFraisFilters
                
fields: 
    id_user: 
        label: Utilisateur
        type: id_object
        object: user
        required: 1
    date_from: 
        label: Du
        type: date
        required: 1
    date_to: 
        label: Au
        type: date
        required: 1
        
fields_tables: 
    default: 
        panel: 0
        rows: 
            - field: id_user
              display: card
            - field: date_from
            - field: date_to
    frais: 
        title: Notes de frais
        icon: fas_sticky-note
        rows: 
            - label: Total (non refusées)
              value: 
                  callback: displayTotalAmount
            - label: En Attente de validation
              value: 
                  callback:
                        method: displayFraisNumber
                        params: 
                            - 1
            - label: En Attente de remboursement
              value: 
                  callback:
                        method: displayFraisNumber
                        params: 
                            - 2
        
            
views: 
    default: 
        objects_change_reload: BRH_Frais
        panel: 0
        rows: 
            - cols: 
                - type: object_header
            - cols: 
                - type: fields_table
                  col_lg: 6
                  col_sm: 12
                  fields_table: 
                      name: default
                - type: fields_table
                  col_lg: 6
                  col_sm: 12
                  fields_table: 
                      name: frais
            - cols: 
                - type: list
                  list: 
                      name: user
                      children: frais
lists: 
    default: 
        title: Notes de frais
        checkboxes: 1
        objects_change_reload: BRH_Frais,BRH_FraisMontant,BRH_FraisKilometers
        sort_field: id
        sort_way: desc
        n: 25
        modal_view: default
        page_btn: 1
        cols:
            user: 
                field: id_user
            date_from: 
                field: date_from
            date_to: 
                field: date_to
            nb_notes: 
                label: Nb notes
                value: 
                    callback: displayFraisNumber
            amount: 
                label: Total TTC
                value: 
                    callback: displayTotalAmount
            att_validation: 
                label: Att. valid.
                value: 
                    callback:
                        method: displayFraisNumber
                        params: 
                            - 1
            att_rbt:
                label: Att. rbt
                value: 
                    callback: 
                        method: displayFraisNumber
                        params: 
                            - 2
                            
    user: 
        title: Notes de frais
        checkboxes: 1
        objects_change_reload: BRH_Frais,BRH_FraisMontant,BRH_FraisKilometers
        sort_field: id
        sort_way: desc
        n: 10
        modal_view: default
        page_btn: 1
        cols:
            date_from: 
                field: date_from
            date_to: 
                field: date_to
            nb_notes: 
                label: Nb notes
                value: 
                    callback: displayFraisNumber
            amount: 
                label: Total TTC
                value: 
                    callback: displayTotalAmount
            att_validation: 
                label: Att. valid.
                value: 
                    callback:
                        method: displayFraisNumber
                        params: 
                            - 1
            att_rbt:
                label: Att. rbt
                value: 
                    callback: 
                        method: displayFraisNumber
                        params: 
                            - 2
        
                
                