table: bt_transfer
controller: transfer
icon: far_arrow-alt-circle-right

header_btn:
    callback: getActionsButtons

header_list_name: default
header_edit_form: default

list_page_url: 
    controller: index
            
labels:
    name: transfert

objects:
    lines: 
        relation: hasMany
        label: Lignes de transfert
        delete: 1
        instance: 
            bimp_object: TransferLine
        
        
    entrepot_src: 
        extends: entrepot
        instance: 
            id_object: 
                field_value: id_warehouse_source
                
    entrepot_dest: 
        extends: entrepot
        instance: 
            id_object: 
                field_value: id_warehouse_dest
                
    user: 
        instance: 
            id_object: 
                field_value: user_valid
        
fields:     
    id_warehouse_source:
        label: Entrepôt de départ
        type: id_object
        object: entrepot_src
        default_value: 0
        required: 1
        input: 
            type: search_entrepot
                
    id_warehouse_dest:
        label: Entrepôt d'arrivée
        type: id_object
        object: entrepot_dest
        default_value: 0
        input:
            type: search_entrepot
        
    date_opening: 
        label: Date d'ouverture
        type: datetime
        required: 0
        search:
            type: date_range
        
    date_closing: 
        label: Date de fermeture
        type: datetime
        required: 0
        search:
            type: date_range
            
    status:
        label: Statut
        type: int
        values: 
            array: status_list
        edit: 0
        
    user_valid: 
        label: Validée par
        type: id_object
        object: user
        
        
fields_tables: 
    default: 
        footer_extra_btn:
            callback: getActionsButtons
        panel: 1
        title: Informations
        icon: info-circle
        rows:
            - field: id_warehouse_source
              display: nom_url
            - field: id_warehouse_dest
              display: nom_url
            - field: date_opening
            - field: date_closing
            - field: user_create
            - label: Terminée
              value: 
                  callback: displayIsGood
            - field: user_valid
              display: nom_url

            
views:
    default:
        objects_change_reload: lines
        edit_form: default
        delete_btn: 1
        rows:
            - cols: 
                  - type: fields_table
                    col_lg: 7
                    col_md: 8
                    col_sm: 12
                    fields_table:
                        name: default
                        
    full: 
        objects_change_reload: lines
        edit_form: default
        delete_btn: 1
        rows:
            - cols: 
                  - type: object_header
                  - type: fields_table
                    col_lg: 7
                    col_md: 8
                    col_sm: 12
                    fields_table:
                        name: default
                  - type: list
                    list: 
                        name: default
                        children: lines
forms:
    add:
        on_save: redirect
        rows: 
            - field: id_warehouse_source
            - field: id_warehouse_dest
            
    default:
        rows: 
            - field: id_warehouse_dest
            
lists:
    default:
        checkboxes: 1
        configurable: 1
#        bulk_actions: 
    # TODO reset with right admin
    #        - label: Supprimer les transferts sélectionnés
    #          icon: fas_trash-alt
    #          onclick: deleteSelectedObjects('list_id', $(this));
    #          btn_class: deleteSelectedObjects
        sort_field: id
        sort_way: desc
        n: 10
#        list_filters:  => Le callback n'existe pas!
#            callback:
#                method: getListFilters
        add_form_name: add
        edit_btn: 
            callback: userIsAdminOrStatusSending
        delete_btn:
            callback: userIsAdmin
        view_btn: 1
        page_btn: 1
        modal_view: full
        extra_btn: 
            callback: getListExtraButtons
        cols:
            id:
            status:
            id_warehouse_source:
            id_warehouse_dest: 
            date_opening:
            date_closing:
                
    dash_board_reception:
       extends: default
       cols:
        status: unset
        id_warehouse_dest: unset
        
    dash_board_send:
       extends: default
       cols:
        status: unset
        id_warehouse_source: unset
        
cards: 
    default: 
        title: nom
        status: status
        fields: 
            - label: Ouvert le
              field: date_opening
            - label: Fermé le
              field: date_closing
        view_btn: 1
