table: bt_transfer
controller: transfer
icon: far_arrow-alt-circle-right

header_btn:
    callback: getActionsButtons

header_list_name: default
header_edit_form: default

list_page_url: 
    controller: index
            
labels:
    name: transfert

objects:
    lines: 
        instance: 
            bimp_object: TransferLine
        delete: 1
#    product:
#        instance:
#            bimp_object: unset
#            dol_object: product
#        cards: 
#            default: 
#                type: product_card
                
fields: 
    # ces champs sont insérés de base par BimpObject (Ici, les paramètres suivants sont de toute manière écrasés) 
#    user_create: 
#        label: Auteur
#        type: id_object
#        object: user
#        input: 
#            type: search_user
#            include_empty: 1
#        default_value: 0
#    user_update: 
#        label: Utilisateur MAJ
#        type: id_object
#        object: user
#        default_value: 0        
    id_warehouse_source:
        label: Entrepôt de départ
        type: id_object
        object: entrepot
        default_value: 0
        input:
            # On utilise ce type d'input partout ailleurs...
            type: search_entrepot 
#            type: search_list
#            search_list: 
#                table: entrepot e
#                field_return_value: e.rowid
#                field_return_label: e.lieu
#                fields_search: e.rowid,e.lieu
                
    id_warehouse_dest:
        label: Entrepôt d'arrivée
        type: id_object
        object: entrepot
        default_value: 0
        input:
            type: search_entrepot
#            type: search_list
#            search_list: 
#                table: entrepot e
#                field_return_value: e.rowid
#                field_return_label: e.lieu
#                fields_search: e.rowid,e.lieu
        
    date_opening: 
        label: Date d'ouverture
        type: datetime
        required: 0
        search:
            type: date_range
        
    date_closing: 
        label: Date de fermeture
        type: datetime
        required: 0
        search:
            type: date_range
            
    status:
        label: Statut
        type: int
        values: 
            array: status_list
        edit: 0

fields_tables: 
    default: 
        footer_extra_btn:
            callback: getActionsButtons
        panel: 1
        title: Informations
        icon: info-circle
        rows:
#            - label: Auteur
#              value: 
#                  callback: 
#                    method: displayAuthor
##                    method: displayProduct
#                    params: 
#                          - card
            - field: id_warehouse_source
              display: nom_url
            - field: id_warehouse_dest
              display: nom_url
            - field: date_opening
            - field: date_closing
            - field: user_create
            
views:
    default:
        objects_change_reload: lines
        edit_form: default
        delete_btn: 1
        rows:
            - cols: 
                  - type: fields_table
                    col_lg: 7
                    col_md: 8
                    col_sm: 12
                    fields_table:
                        name: default  
                        
                    # object_common_fields => c'était l'ancienne méthode, maintenant les infos sont dans le header 
#                  - type: rows
#                    col_lg: 4
#                    col_md: 5
#                    col_sm: 12
#                    rows: 
#                        - cols: 
#                            - type: object_common_fields
            
forms:
    add:
        rows: 
            - field: id_warehouse_source
            - field: id_warehouse_dest
            - field: status
            
    default:
        rows: 
            - field: id_warehouse_dest
            - field: status
            
list:
    checkboxes: 1
    bulk_actions: 
# TODO reset with right admin
#        - label: Supprimer les transferts sélectionnés
#          icon: fas_trash-alt
#          onclick: deleteSelectedObjects('list_id', $(this));
#          btn_class: deleteSelectedObjects
    sort_field: id
    sort_way: desc
    n: 10
    list_filters: 
        callback:
            method: getListFilters
    add_form_name: add
    edit_btn: 
        callback: userIsAdmin
    delete_btn:
        callback: userIsAdmin
    view_btn: 1
    page_btn: 1
    modal_view: default
    cols:
        id:
            label: ID
            field: id
            min_width: 60px
        status:
            field: status
        id_warehouse_source:
            field: id_warehouse_source
            display: nom_url
        id_warehouse_dest: 
            field: id_warehouse_dest
            display: nom_url
        date_opening:
            field: date_opening
        date_closing:
            field: date_closing
            
cards: 
    default: 
        title: nom
        status: status
        fields: 
            - label: Ouvert le
              field: date_opening
            - label: Fermé le
              field: date_closing
        view_btn: 1