table: bimp_task
controller: task

icon: fas_tasks
header_list_name: default
header_btn:
    callback: getButtons
list_page_url: 
    controller: index
    
    
#nom_url: 
#    with_status: 1
#    syntaxe: #<id> : <a.subj>
    
#parent_id_property: id_task
#parent_object: BIMP_Task
#parent_module: bimptask
        
labels:
    name: tâche
    name_plur: tâches
    is_female: 1    

objects: 
    task_fille:
        relation: hasMany
        instance:
            bimp_object:
                module: bimptask
                name: BIMP_Task
#                
    task_mere:
        relation: hasOne
        delete: 0
        instance:
            bimp_object:
                module: bimptask
                name: BIMP_Task
            id_object:
                field_value: id_task
                
    user_owner:
        extends: user
        instance:
            id_object:
                field_value: id_user_owner
                
    files:
        instance:
            bimp_object:
                module: bimpcore
                name: BimpFile
        list: 
            filters:
                parent_module: bimptask
                parent_object_name: BIMP_Task
        add_form: 
            name: upload
            values:
                fields: 
                    parent_module: bimptask
                    parent_object_name: BIMP_Task
                    
fields: 
    src:
        label: Source email
        type: text
    dst:
        label: Destinataire email
        type: text
    subj:
        label: Sujet
        type: text
    txt:
        label: Description
        type: html
        hashtags: 1
    comment:
        label: Commentaire
        type: text
        hashtags: 1
    status:
        label: Statut
        type: int
        values: 
            array: status_list_task
    prio:
        label: Priorité
        type: int
        values: 
            array: prio_list_task
    id_user_owner:
        label: Attribuer à
        type: id_object
        object: user_owner
        input:
            type: search_user
            include_empty: 1
    test_ferme:
        label: Test pour Fermeture
        type: text
        
    auto:
        label: Tâche automatique
        type: bool
        
    type_manuel:
        label: Type de tache manuel
        type: text
        values: 
            array: types_manuel
            
    id_task:
        label: Tache mére
        type: id_object
        object: task_mere
 
fields_tables:
    default: 
        title: Tâche
        footer_extra_btn: 
            callback: getInfosExtraBtn
        icon: fas_tasks
        rows: 
            - field: status
            - field: prio
              edit: 0
            - field: id_task
            - field: src
            - field: dst
            - label: Type de tâche
              value: 
                  callback: displayType
            - field: subj
            - field: txt
            - field: comment
              edit: 1
            - field: id_user_owner
              edit: 1
            - label: Notifier
              value:
                callback: displayUserNotif
        
forms:
    default: 
        rows: 
            - field: status
            - field: prio
            - field: src
              show: 
                 callback: canEditAll
            - field: dst
              edit: 0
            - field: subj
            - field: txt
            - field: comment
            - field: id_user_owner
            
    add:
        rows:
            - field: id_task
            - field: type_manuel
            - field: prio
            - field: subj
            - field: txt
            - field: comment
            - field: id_user_owner
            - object: files
              form_name: upload
              form_label: Ajouter
              form_values: 
                  fields: 
                      id_parent: 1
                  
              multiple: 1
              
    addUser:
        extends: add
        rows:
            6: unset
            
    newMail:
        rows:
            - custom: 1
              input_name: email
              data_type: text
              label: Email
              input:
                  type: textarea
            - custom: 1
              input_name: include_file
              data_type: bool
              label: Inclure les fils de conversations
              input: 
                  type: toggle
              value: 1
    attribute:
        rows:
            - field: id_user_owner
            
    changeStatut:
        rows:
            - custom: 1
              input_name: status
              input: 
                  type: select
              label: Statut
              values:
                  callback: getStatusPossible
            - custom: 1
              input_name: text
              input: 
                  type: textarea
              hashtags: 1
              label: Commentaire
            - custom: 1
              input_name: notif
              data_type: bool
              label: Notifier
              input: 
                  type: toggle
              value: 1
           
lists_cols: 
    typeTache:
        label: Type de tâche
        value:
            callback: displayType
        search:
          input:
              type: select
              options:
                options:
                    callback: getTypeArray
#                    array: valSrc
                            
lists:
    default:
        checkboxes: 1
        configurable: 1
        bulk_actions:
            - label: supprimer les tâches sélectionnées
              icon: fas_trash-alt
              onclick: deleteSelectedObjects('list_id', $(this))
        sort_field: id
        sort_way: desc
        filters_panel: default
        n: 10
        add_form_name: add
        delete_btn: 1
        page_btn: 1
        edit_btn: 1
        modal_view: default
        edit_form: default
        update_btn: 1
        extra_btn: 
            callback: getButtons
        cols:
            id:
            src:
            dst:
            typeTache:                    
            subj:
            txt:
            comment:
            status:
                edit: 1
            id_user_owner:
                
    sousTache:
        extends: default

views:
    default: 
#        title: nom
        objects_change_reload: BIMP_Task,BimpNote
        edit_form: default
        delete_btn: 1
        rows:    
            - cols: 
                  - type: fields_table
                    col_lg: 12
                    col_md: 12
                    col_sm: 12
                    fields_table:
                        name: default
          
            - cols:
                - type: custom
                  custom: 
                      callback: displaySousTache
            - cols:
                  - type: custom
                    custom: 
                        callback: renderNotesList
            - cols: 
                - type: list
                  list: 
                      children: files
#            - cols: 
#                - type: list
#                  list: 
#                      children: task_fille
#            - cols: 
#                - type: custom
#                  custom: 
#                      callback: 
#                          method: renderAssociatesList
#                          params: 
#                              - files
#                              - associates
    notes: 
#        title: nom
        edit_form: 0
        delete_btn: 0
        rows:    
            - cols:
                  - type: custom
                    custom: 
                        callback: renderNotesList

searches: 
    default: 
        fields_search: 
            - a.id
            - u.firstname
            - u.lastname
            - a.subj
        fields_return: 
            - a.id
            - u.firstname
            - u.lastname
            - a.subj
        label_syntaxe: 'Tâche #<a.id> (<a.subj>) - Utilisateur: <u.firstname> <u.lastname>'
        joins: 
            - table: user
              on: a.id_user_owner = u.rowid
              alias: u
              
filters_panels:
    default:
        filters: 
            type_manuel:
            subj:
            status:
        