table: bimp_task
controller: task

icon: fas_tasks
header_list_name: default
header_btn:
    callback: getButtons
list_page_url: 
    controller: index
        
labels:
    name: tache
    name_plur: taches
    is_female: 1

    
            
associations:
    

fields:            
    src:
        label: Source email
        type: text
    dst:
        label: Destinataire email
        type: text
    subj:
        label: Sujet email
        type: text
    txt:
        label: Email originel
        type: html
    comment:
        label: Commentaire
        type: text
    status:
        label: Statut
        type: int
        values: 
            array: status_list_task
    id_user_owner:
        label: Attribué a
        type: id_object
        object: user_owner
        input:
            type: search_user
                
objects:
    user_owner:
        relation: hasOne
        delete: 0
        instance:
            bimp_object:
                module: bimpcore
                name: Bimp_User
            id_object:
                fiels_value: id_user_owner
 
fields_tables:
    default: 
        title: Tache
        footer_extra_btn: 
            callback: getInfosExtraBtn
        icon: fas_tasks
        rows: 
            - field: status
              edit: 1
            - field: src
            - field: dst
            - field: subj
            - field: txt
            - field: comment
              edit: 1
            - field: id_user_owner
              edit: 1
        
forms:
    default: 
        rows: 
            - field: status
            - field: src
              show: 
                 callback: canEditAll
            - field: dst
              edit: 0
            - field: subj
            - field: txt
            - field: comment
            - field: id_user_owner
            
    newMail:
        rows:
            - custom: 1
              input_name: email
              data_type: html
              label: Email
              input:
                  type: html
            - custom: 1
              input_name: include_file
              data_type: bool
              label: Inclure les fils de conversations
              input: 
                  type: toggle
              value: 1
    attribute:
        rows:
            - field: id_user_owner
            
lists:
    default:
        checkboxes: 1
        bulk_actions:
            - label: supprimer les taches sélectionnées
              icon: fas_trash-alt
              onclick: deleteSelectedObjects('list_id', $(this))
        sort_field: src
        sort_way: desc
        n: 10
        add_form_name: default
        delete_btn: 1
        page_btn: 1
        edit_btn: 1
        modal_view: default
        edit_form: default
        update_btn: 1
        cols:
            id:
                label: ID
                field: id
            src:
                field: src
            dst:
                field: dst
            subj:
                field: subj
            txt:
                field: txt
            comment:
                field: comment
            status:
                field: status
                edit: 1
            id_user_owner:
                field: id_user_owner

  
views:
    default: 
        title: nom
        edit_form: default
        delete_btn: 1
        rows:    
            - cols: 
                  - type: fields_table
                    col_lg: 12
                    col_md: 12
                    col_sm: 12
                    fields_table:
                        name: default
            - cols:
                  - type: custom
                    custom: 
                        callback: renderNotesList
