<?php

/* Copyright (C) 2007      Laurent Destailleur  <eldy@users.sourceforge.net>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */
/*
 * GLE by Synopsis et DRSI
 *
 * Author: Tommy SAURON <tommy@drsi.fr>
 * Licence : Artistic Licence v2.0
 *
 * Version 1.1
 * Create on : 4-1-2009
 *
 * Infos on http://www.finapro.fr
 *
 */
/*
 *
 * $Id: modSynopsisProcess.class.php,v 1.5 2008/01/13 22:48:28 eldy Exp $
 */

/**
  \defgroup   SSLCert     Module SSLCert
  \brief      Module pour gerer une base de noms de SSLCertes
 */
/**
  \file       htdocs/core/modules/modSynopsisProcess.class.php
  \ingroup    adherent
  \brief      Fichier de description et activation du module SSLCert
 */
include_once(DOL_DOCUMENT_ROOT . "/core/modules/DolibarrModules.class.php");

/**
  \class      modAdherent
  \brief      Classe de description et activation du module Adherent
 */
class modSynopsisProcess extends DolibarrModules {

    /**
     *   \brief      Constructeur. Definit les noms, constantes et boites
     *   \param      DB      handler d'acces base
     */
    function modSynopsisProcess($DB) {
        $this->db = $DB;
        $this->numero = 229200;

        $this->family = "Synopsis";
        $this->name = "Process";
        $this->description = "Gestion des process";
        $this->version = '0.1';            // 'development' or 'experimental' or 'dolibarr' or version
        $this->const_name = 'MAIN_MODULE_SYNOPSISPROCESS';
        $this->special = 0;
        $this->picto = 'process@Synopsis_Process';



        $this->const[$r][0] = "PROCESS_ADDON";
        $this->const[$r][1] = "chaine";
        $this->const[$r][2] = "Demantoide";
        $this->const[$r][3] = 'Nom du gestionnaire de numerotation des propales';
        $this->const[$r][4] = 0;
        $r++;

        // Dir
        //----
        $this->dirs = array();

        // Config pages
        //-------------
        $this->config_page_url = array("Synopsis_Process.php");

        // Dependances
        //------------
        $this->depends = array("modSynopsisTools");
        $this->requiredby = array("modSynopsisChrono");
        $this->langfiles = array("process");

        // Constantes
        //-----------
        $this->const = array();

        // Boites
        //-------
        $this->boxes = array();

        // Permissions
        //------------
        $this->rights = array();
        $this->rights_class = 'process';
        $r = 0;

//        $r++;
        $this->rights[$r][0] = 229201;
        $this->rights[$r][1] = 'Lire les process';
        $this->rights[$r][2] = 'r';
        $this->rights[$r][3] = 1;
        $this->rights[$r][4] = 'lire';

        $r++;
        $this->rights[$r][0] = 229202;
        $this->rights[$r][1] = 'Creer / modifier les process';
        $this->rights[$r][2] = 'w';
        $this->rights[$r][3] = 0;
        $this->rights[$r][4] = 'creer';

        $r++;
        $this->rights[$r][0] = 229203;
        $this->rights[$r][1] = 'Effacer des process';
        $this->rights[$r][2] = 'd';
        $this->rights[$r][3] = 0;
        $this->rights[$r][4] = 'effacer';

        $r++;
        $this->rights[$r][0] = 229204;
        $this->rights[$r][1] = 'Valider des process';
        $this->rights[$r][2] = 'd';
        $this->rights[$r][3] = 0;
        $this->rights[$r][4] = 'valider';

        $r++;
        $this->rights[$r][0] = 229205;
        $this->rights[$r][1] = 'Configurer des process';
        $this->rights[$r][2] = 'd';
        $this->rights[$r][3] = 0;
        $this->rights[$r][4] = 'configurer';

        $r++;
        $this->rights[$r][0] = 229206;
        $this->rights[$r][1] = 'Modifier des process';
        $this->rights[$r][2] = 'd';
        $this->rights[$r][3] = 0;
        $this->rights[$r][4] = 'modifier';

        // Exports
        //--------
        $r = 0;

        // $this->export_code[$r]          Code unique identifiant l'export (tous modules confondus)
        // $this->export_label[$r]         Libelle par defaut si traduction de cle "ExportXXX" non trouvee (XXX = Code)
        // $this->export_permission[$r]    Liste des codes permissions requis pour faire l'export
        // $this->export_fields_sql[$r]    Liste des champs exportables en codif sql
        // $this->export_fields_name[$r]   Liste des champs exportables en codif traduction
        // $this->export_sql[$r]           Requete sql qui offre les donnees a l'export
//         Top menu
        $r = 0;
        $this->menu[$r] = array('fk_menu' => 0,
            'type' => 'top',
            'titre' => 'Process',
            'mainmenu' => 'Process',
            'leftmenu' => '1', // To say if we can overwrite leftmenu
            'url' => '/Synopsis_Process/liste.php',
            'langs' => 'synopsisGene@synopsistools',
            'position' => 1,
            'perms' => '$user->rights->process->lire',
            'target' => '',
            'user' => 0);
        $r++;

//
        $this->menu[$r] = array('fk_menu' => 'r=0',
            'type' => 'left',
            'titre' => 'Process',
            'mainmenu' => 'Process',
            'url' => '/Synopsis_Process/index.php',
            'langs' => 'synopsisGene@synopsistools',
            'position' => 1,
            'perms' => '$user->rights->process->lire',
            'target' => '',
            'user' => 0);
        $r++;
        $this->menu[$r] = array('fk_menu' => 'r=1',
            'type' => 'left',
            'titre' => 'Liste',
            'mainmenu' => 'Process',
            'url' => '/Synopsis_Process/liste.php',
            'langs' => 'synopsisGene@synopsistools',
            'position' => 1,
            'perms' => '$user->rights->process->lire',
            'target' => '',
            'user' => 0);
        $r++;






        $this->menu[$r] = array('fk_menu' => 'r=0',
            'type' => 'left',
            'titre' => 'Validation',
            'mainmenu' => 'Process',
            'url' => '/Synopsis_Process/listValidation.php',
            'langs' => 'synopsisGene@synopsistools',
            'position' => 2,
            'perms' => '',
            'target' => '',
            'user' => 0);
        $s = $r;
        $r++;
        $this->menu[$r] = array('fk_menu' => 'r=' . $s,
            'type' => 'left',
            'titre' => 'Liste',
            'mainmenu' => 'Process',
            'url' => '/Synopsis_Process/listValidation.php',
            'langs' => 'synopsisGene@synopsistools',
            'position' => 1,
            'perms' => '',
            'target' => '',
            'user' => 0);

        $r++;
        $this->menu[$r] = array('fk_menu' => 'r=' . $s,
            'type' => 'left',
            'titre' => 'Mes validations',
            'mainmenu' => 'Process',
            'url' => '/Synopsis_Process/historyValidation.php?filterMyValid=1',
            'langs' => 'synopsisGene@synopsistools',
            'position' => 1,
            'perms' => '',
            'target' => '',
            'user' => 0);
        $r++;
        $this->menu[$r] = array('fk_menu' => 'r=' . $s,
            'type' => 'left',
            'titre' => 'Suivi validation',
            'mainmenu' => 'Process',
            'url' => '/Synopsis_Process/historyValidation.php?filterMyPossible=1',
            'langs' => 'synopsisGene@synopsistools',
            'position' => 1,
            'perms' => '',
            'target' => '',
            'user' => 0);
        
        
        
        
        

        $this->menu[$r] = array('fk_menu' => 'fk_mainmenu=SynopsisTools',
            'type' => 'left',
            'titre' => 'Process',
            'leftmenu' => 'Process',
            'mainmenu' => 'SynopsisTools',
            'url' => '/Synopsis_Process/index.php',
            'langs' => 'synopsisGene@synopsistools',
            'position' => 21,
            'perms' => '$user->rights->process->lire',
            'target' => '',
            'user' => 0);
        $r++;

        $this->menu[$r] = array('fk_menu' => 'fk_mainmenu=SynopsisTools,fk_leftmenu=Process',
            'type' => 'left',
            'titre' => 'Liste',
            'mainmenu' => 'SynopsisTools',
            'url' => '/Synopsis_Process/liste.php',
            'langs' => 'synopsisGene@synopsistools',
            'position' => 2001,
            'perms' => '$user->rights->process->lire',
            'target' => '',
            'user' => 0);
        $r++;

        $this->menu[$r] = array('fk_menu' => 'fk_mainmenu=SynopsisTools,fk_leftmenu=Process',
            'type' => 'left',
            'titre' => 'Config',
            'leftmenu' => 'ConfigProcess',
            'mainmenu' => 'SynopsisTools',
            'url' => '/Synopsis_Process/index.php',
            'langs' => 'synopsisGene@synopsistools',
            'position' => 2002,
            'perms' => '$user->rights->process->configurer',
            'target' => '',
            'user' => 0);
        $fkMen1 = 'fk_mainmenu=SynopsisTools,fk_leftmenu=ConfigProcess';
        $r++;
        $this->menu[$r] = array('fk_menu' => '' . $fkMen1,
            'type' => 'left',
            'titre' => 'Formulaires',
            'leftmenu' => 'ConfigProcessForm',
            'mainmenu' => 'SynopsisTools',
            'url' => '/Synopsis_Process/listForm.php',
            'langs' => 'synopsisGene@synopsistools',
            'position' => 2003,
            'perms' => '$user->rights->process->configurer',
            'target' => '',
            'user' => 0);
        $fkMen2 = 'fk_mainmenu=SynopsisTools,fk_leftmenu=ConfigProcessForm';
        $r++;
        $this->menu[$r] = array('fk_menu' => $fkMen2,
            'type' => 'left',
            'titre' => 'Ajouter un formulaire',
            'mainmenu' => 'SynopsisTools',
            'url' => '/Synopsis_Process/formBuilder.php?action=Create',
            'langs' => 'synopsisGene@synopsistools',
            'position' => 2004,
            'perms' => '$user->rights->process->configurer && $user->rights->process->creer',
            'target' => '',
            'user' => 0);
        $r++;
        $this->menu[$r] = array('fk_menu' => $fkMen1,
            'type' => 'left',
            'titre' => 'Liste des requ&ecirc;tes',
            'mainmenu' => 'SynopsisTools',
            'leftmenu' => 'ConfigProcessReq',
            'url' => '/Synopsis_Process/listQuery.php',
            'langs' => 'synopsisGene@synopsistools',
            'position' => 2005,
            'perms' => '$user->rights->process->configurer',
            'target' => '',
            'user' => 0);
        $fkMen2 = 'fk_mainmenu=SynopsisTools,fk_leftmenu=ConfigProcessReq';
        $r++;
        $this->menu[$r] = array('fk_menu' => $fkMen2,
            'type' => 'left',
            'titre' => 'Ajouter une requ&ecirc;te',
            'mainmenu' => 'SynopsisTools',
            'url' => '/Synopsis_Process/queryBuilder.php?action=Create',
            'langs' => 'synopsisGene@synopsistools',
            'position' => 2006,
            'perms' => '$user->rights->process->configurer && $user->rights->process->creer',
            'target' => '',
            'user' => 0);
        $r++;
        $this->menu[$r] = array('fk_menu' => $fkMen1,
            'type' => 'left',
            'titre' => 'Liste des listes',
            'mainmenu' => 'SynopsisTools',
            'leftmenu' => 'ConfigProcessListe',
            'url' => '/Synopsis_Process/listList.php',
            'langs' => 'synopsisGene@synopsistools',
            'position' => 2007,
            'perms' => '$user->rights->process->configurer',
            'target' => '',
            'user' => 0);
        $fkMen2 = 'fk_mainmenu=SynopsisTools,fk_leftmenu=ConfigProcessListe';
        $r++;
        $this->menu[$r] = array('fk_menu' => $fkMen2,
            'type' => 'left',
            'titre' => 'Ajouter une liste',
            'mainmenu' => 'SynopsisTools',
            'url' => '/Synopsis_Process/listBuilder.php?action=Create',
            'langs' => 'synopsisGene@synopsistools',
            'position' => 2008,
            'perms' => '$user->rights->process->configurer && $user->rights->process->creer',
            'target' => '',
            'user' => 0);
        $r++;
        $this->menu[$r] = array('fk_menu' => $fkMen1,
            'type' => 'left',
            'titre' => 'Liste des process',
            'mainmenu' => 'SynopsisTools',
            'leftmenu' => 'ConfigProcessProc',
            'url' => '/Synopsis_Process/listProcess.php',
            'langs' => 'synopsisGene@synopsistools',
            'position' => 2009,
            'perms' => '$user->rights->process->configurer',
            'target' => '',
            'user' => 0);
        $fkMen2 = 'fk_mainmenu=SynopsisTools,fk_leftmenu=ConfigProcessProc';
        $r++;
        $this->menu[$r] = array('fk_menu' => $fkMen2,
            'type' => 'left',
            'titre' => 'Ajouter un process',
            'mainmenu' => 'SynopsisTools',
            'url' => '/Synopsis_Process/processBuilder.php?action=Create',
            'langs' => 'synopsisGene@synopsistools',
            'position' => 2010,
            'perms' => '$user->rights->process->configurer && $user->rights->process->creer',
            'target' => '',
            'user' => 0);
        $r++;

        $this->menu[$r] = array('fk_menu' => $fkMen1,
            'type' => 'left',
            'titre' => 'Liste des fonctions',
            'mainmenu' => 'SynopsisTools',
            'leftmenu' => 'ConfigProcessFunc',
            'url' => '/Synopsis_Process/listFct.php',
            'langs' => 'synopsisGene@synopsistools',
            'position' => 2011,
            'perms' => '$user->rights->process->configurer',
            'target' => '',
            'user' => 0);
        $fkMen2 = 'fk_mainmenu=SynopsisTools,fk_leftmenu=ConfigProcessFunc';
        $r++;
        $this->menu[$r] = array('fk_menu' => $fkMen2,
            'type' => 'left',
            'titre' => 'Ajouter une fonction',
            'mainmenu' => 'SynopsisTools',
            'url' => '/Synopsis_Process/fctBuilder.php?action=Create',
            'langs' => 'synopsisGene@synopsistools',
            'position' => 2012,
            'perms' => '$user->rights->process->configurer && $user->rights->process->creer',
            'target' => '',
            'user' => 0);
        $r++;
    }

    /**
     *   \brief      Fonction appelee lors de l'activation du module. Insere en base les constantes, boites, permissions du module.
     *               Definit egalement les repertoires de donnees a creer pour ce module.
     */
    function init() {
        global $conf;

        // Permissions
        $this->remove();
        $sql = array('CREATE TABLE IF NOT EXISTS `' . MAIN_DB_PREFIX . 'Synopsis_Process` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `label` varchar(50) DEFAULT NULL,
  `description` longtext,
  `fk_statut` int(11) DEFAULT NULL,
  `bloquant` tinyint(4) DEFAULT NULL,
  `formulaire_refid` int(11) DEFAULT NULL,
  `pretraitement` longtext,
  `posttraitement` longtext,
  `validAction` longtext,
  `askValidAction` longtext,
  `reviseAction` longtext,
  `PROCESS_MASK` varchar(150) DEFAULT NULL,
  `ADDON_PDF` varchar(150) DEFAULT NULL,
  `PROCESS_ADDON` varchar(150) DEFAULT NULL,
  `typeElement_refid` int(11) DEFAULT NULL,
  `trigger_refid` int(11) DEFAULT NULL,
  `revision_model_refid` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `typeElement_refid` (`typeElement_refid`),
  KEY `trigger_refid` (`trigger_refid`),
  KEY `formulaire_refid` (`formulaire_refid`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=3 ;',
            'INSERT IGNORE INTO `' . MAIN_DB_PREFIX . 'Synopsis_Process` (`id`, `label`, `description`, `fk_statut`, `bloquant`, `formulaire_refid`, `pretraitement`, `posttraitement`, `validAction`, `askValidAction`, `reviseAction`, `PROCESS_MASK`, `ADDON_PDF`, `PROCESS_ADDON`, `typeElement_refid`, `trigger_refid`, `revision_model_refid`) VALUES
(1, \'TR15\', \'FICHE ANALYSE FAISABILITE\', NULL, 1, 1, \'\', \'\', \'\', \'\', \'\', \'{yy}TR15{0000@1}\', \'\', \'demantoide\', 1, 49, 2),
(2, \'FORM_TEST\', \'TESTONS CES PROCESS\', NULL, 0, 1, \'\', \'\', \'\', \'\', \'\', \'FORM/{00000@}\', \'pholos\', \'demantoide\', 1, 47, 1),
(3, \'Validation Propal\', \'Process de validation des propal\', 1, 1, 3, \'\', \'\', \'\', \'\', \'\', \'VALID{0000}\', \'\', \'demantoide\', 1, 48, NULL),
(4, \'Calendrier DI\', \'Proposition de date pour les DI de contrat\', 1, 1, 4, \'\', \'require_once(DOL_DOCUMENT_ROOT."/Synopsis_Contrat/class/autoDi.class.php");\n$autoDi = new autoDi($processDet);\n$autoDi->verif();\', \'require_once(DOL_DOCUMENT_ROOT.\'\'/Synopsis_Contrat/class/autoDi.class.php\'\'); $autoDi = new autoDi(NULL, $element_id); $autoDi->creerFi();\', \'\', \'\', \'CALDI{00000}\', \'\', \'demantoide\', 9, 23, NULL);',
            'CREATE TABLE IF NOT EXISTS `' . MAIN_DB_PREFIX . 'Synopsis_Processdet` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ref` varchar(50) DEFAULT NULL,
  `process_refid` int(11) DEFAULT NULL,
  `fk_statut` int(11) DEFAULT \'0\',
  `date_create` datetime DEFAULT NULL,
  `date_modify` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `element_refid` int(11) DEFAULT NULL,
  `validation_number` int(11) DEFAULT \'1\',
  `revision` int(11) DEFAULT NULL,
  `orig_ref` varchar(50) DEFAULT NULL,
  `entity` int(11) NOT NULL DEFAULT \'1\',
  PRIMARY KEY (`id`),
  KEY `process_refid` (`process_refid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;',
            'CREATE TABLE IF NOT EXISTS `' . MAIN_DB_PREFIX . 'Synopsis_Processdet_active` (
  `type_refid` int(11) DEFAULT NULL,
  `process_refid` int(11) DEFAULT NULL,
  `element_refid` int(11) DEFAULT NULL,
  `processdet_refid` int(11) DEFAULT NULL,
  KEY `type_refid` (`type_refid`),
  KEY `process_refid` (`process_refid`),
  KEY `element_refid` (`element_refid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;',
            'CREATE TABLE IF NOT EXISTS `' . MAIN_DB_PREFIX . 'Synopsis_Processdet_validation` (
  `user_refid` int(11) DEFAULT NULL,
  `process_refid` int(11) DEFAULT NULL,
  `processdet_refid` int(11) DEFAULT NULL,
  `validation_type_refid` int(11) DEFAULT NULL,
  `element_refid` int(11) DEFAULT NULL,
  `valeur` int(11) DEFAULT NULL,
  `validation_number` int(11) DEFAULT NULL,
  `note` longtext,
  `dateValid` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `' . MAIN_DB_PREFIX . 'Synopsis_Processdet_validation_uniq_key` (`validation_type_refid`,`validation_number`,`element_refid`,`processdet_refid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;',
            'CREATE TABLE IF NOT EXISTS `' . MAIN_DB_PREFIX . 'Synopsis_Processdet_value` (
  `processDet_refid` int(11) DEFAULT NULL,
  `nom` varchar(150) DEFAULT NULL,
  `valeur` longtext,
  `model_refid` int(11) DEFAULT NULL,
  UNIQUE KEY `uniq_processdet_value` (`processDet_refid`,`nom`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;',
            'CREATE TABLE IF NOT EXISTS `' . MAIN_DB_PREFIX . 'Synopsis_Process_form` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `label` varchar(50) DEFAULT NULL,
  `description` longtext,
  `fk_statut` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=3 ;',
            'INSERT IGNORE INTO `' . MAIN_DB_PREFIX . 'Synopsis_Process_form` (`id`, `label`, `description`, `fk_statut`) VALUES
(1, \'Form-TR15\', \'Formulaire TR15\', 1),
(2, \'FORM_TEST\', \'FORMULAIRE DE TEST\', 1),
(3, \'Validation Propale\', \'Validation après accord client\', 1),
(4, \'Calendrier DI\', \'Validation des dates DI proposé.\', 1);',
            'CREATE TABLE IF NOT EXISTS `' . MAIN_DB_PREFIX . 'Synopsis_Process_form_fct` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `fct` longtext,
  `params` text,
  `label` varchar(50) DEFAULT NULL,
  `description` longtext,
  `class` varchar(150) DEFAULT NULL,
  `fileClass` text,
  `printVarInsteadOdReturn` tinyint(4) DEFAULT NULL,
  `VarToBePrinted` varchar(150) DEFAULT NULL,
  `paramsForHtmlName` varchar(50) DEFAULT NULL,
  `paramsForHtmlSelect` varchar(50) DEFAULT NULL,
  `postTraitementValue` longtext,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=6 ;',
            'INSERT IGNORE INTO `' . MAIN_DB_PREFIX . 'Synopsis_Process_form_fct` (`id`, `fct`, `params`, `label`, `description`, `class`, `fileClass`, `printVarInsteadOdReturn`, `VarToBePrinted`, `paramsForHtmlName`, `paramsForHtmlSelect`, `postTraitementValue`) VALUES
(1, \'form_conditions_reglement\', \'PHP_SELF||SELECTED||ID||SHOW_EMPTY\', \'Conditions Reglement\', \'Conditions Reglement\', \'form\', \'/core/class/html.form.class.php\', 0, \'\', \'ID\', \'SELECTED\', \'\'),
(2, \'select_users\', \'SELECTED||ID||SHOWEMPTY||EXCLUDE||DISABLED||DISPLAY\', \'Utilisateurs\', \'Liste des utilisateurs\', \'form\', \'/core/class/html.form.class.php\', 1, \'tmpReturn\', \'ID\', \'SELECTED\', \'$requete = "SELECT * FROM ' . MAIN_DB_PREFIX . 'user WHERE rowid=[[valeur]]";\n$sql = $db->query($requete);\n$res = $db->fetch_object($sql);\nreturn($res->name." ".$res->firstname);\'),
(3, \'selectyesno\', \'ID||SELECTED||OPTION||CLASS\', \'Oui/Non\', \'Choix Oui / Non\', \'form\', \'/core/class/html.form.class.php\', NULL, NULL, \'ID\', \'SELECTED\', NULL),
(4, \'fct_select_users\', \'SELECTED||ID||SHOWEMPTY||EXCLUDE||DISABLED||DISPLAY\', \'Utilisateurs\', \'Liste des utilisateurs\', \'user_fct\', \'/' . MAIN_DB_PREFIX . 'Synopsis_Process/user_fct.class.php\', 1, \'tmpReturn\', \'ID\', \'SELECTED\', \'$requete = "SELECT * FROM ' . MAIN_DB_PREFIX . 'user WHERE rowid=[[valeur]]";\n$sql = $this->db->query($requete);\n$res = $this->db->fetch_object($sql);\nreturn($res->name." ".$res->firstname);\');',
            'CREATE TABLE IF NOT EXISTS `' . MAIN_DB_PREFIX . 'Synopsis_Process_form_fct_value` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `fct_refid` int(11) DEFAULT NULL,
  `label` varchar(50) DEFAULT NULL,
  `model_refid` int(11) DEFAULT NULL,
  `valeur` longtext,
  PRIMARY KEY (`id`),
  KEY `model_refid` (`model_refid`),
  KEY `fct_refid` (`fct_refid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;',
            'CREATE TABLE IF NOT EXISTS `' . MAIN_DB_PREFIX . 'Synopsis_Process_form_global` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `global` longtext,
  `label` varchar(50) DEFAULT NULL,
  `description` longtext,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=6 ;',
            'INSERT IGNORE INTO `' . MAIN_DB_PREFIX . 'Synopsis_Process_form_global` (`id`, `global`, `label`, `description`) VALUES
(1, \'$user->id\', \'ID Utilisateur\', \'ID Utilisateur\'),
(2, \'$user->getFullName($langs)\', \'Nom complet\', \'Nom complet de l\'\'utilisateur courant\'),
(3, \'$user->lastname\', \'Nom utilisateur\', \'Nom de l\'\'utilisateur courant\'),
(4, \'$user->firstname\', \'Prénom Utilisateur\', \'Prénom de l\'\'utilisateur courant\'),
(5, \'$mysoc->nom\', \'Ma société - désignation\', \'Ma société - Nom commercial\');',
            'CREATE TABLE IF NOT EXISTS `' . MAIN_DB_PREFIX . 'Synopsis_Process_form_list` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `label` varchar(50) DEFAULT NULL,
  `description` longtext,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=5 ;',
            'INSERT IGNORE INTO `' . MAIN_DB_PREFIX . 'Synopsis_Process_form_list` (`id`, `label`, `description`) VALUES
(1, \'TypeCourrier\', \'Type de courrier / document départ\'),
(2, \'Oui/Non\', \'Oui/Non\'),
(3, \'Origine FNC\', \'liste des acteurs pouvant être à  l\'\'origine de la création d\'\'une FNC\'),
(4, \'Origine ACP\', \'Liste des entités pouvant être à l\'\'origine de la création d\'\'une ACP\');',
            'CREATE TABLE IF NOT EXISTS `' . MAIN_DB_PREFIX . 'Synopsis_Process_form_list_members` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `label` varchar(150) DEFAULT NULL,
  `valeur` varchar(150) DEFAULT NULL,
  `list_refid` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `list_refid` (`list_refid`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=41 ;',
            'INSERT IGNORE INTO `' . MAIN_DB_PREFIX . 'Synopsis_Process_form_list_members` (`id`, `label`, `valeur`, `list_refid`) VALUES
(1, \'Courrier\', \'Courrier\', 1),
(2, \'Fiche collecte données\', \'Fiche collecte données\', 1),
(3, \'S.Courrier\', \'S.Courrier\', 1),
(4, \'CR\', \'CR\', 1),
(5, \'MAIL\', \'MAIL\', 1),
(6, \'Convention de formation\', \'Convention de formation\', 1),
(7, \'Note de calcul\', \'Note de calcul\', 1),
(8, \'Oui\', \'1\', 2),
(9, \'Non\', \'0\', 2),
(12, \'Analyse Note de calcul\', \'Analyse Note de calcul\', 1),
(10, \'Courrier AR\', \'Courrier AR\', 1),
(11, \'Note d\'\'analyse\', \'Note d\'\'analyse\', 1),
(13, \'Audit\', \'Audit\', 3),
(14, \'Agent\', \'Agent\', 3),
(15, \'Partenaire\', \'Partenaire\', 3),
(40, \'ACP\', \'ACP\', 4),
(39, \'RdD\', \'revue de direction\', 4),
(37, \'FNC\', \'FNC\', 4),
(38, \'Codir\', \'Codir\', 4),
(36, \'Audit\', \'Audit\', 4);',
            'CREATE TABLE IF NOT EXISTS `' . MAIN_DB_PREFIX . 'Synopsis_Process_form_model` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `type_refid` int(20) DEFAULT NULL,
  `label` varchar(500) DEFAULT NULL,
  `description` longtext,
  `dflt` varchar(500) DEFAULT NULL,
  `src_refid` int(11) DEFAULT NULL,
  `form_refid` int(11) DEFAULT NULL,
  `rang` int(11) DEFAULT NULL,
  `rights` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `type_refid` (`type_refid`),
  KEY `src_refid` (`src_refid`),
  KEY `form_refid` (`form_refid`)
);',
            "INSERT IGNORE INTO `" . MAIN_DB_PREFIX . "Synopsis_Process_form_model` (`id`, `type_refid`, `label`, `description`, `dflt`, `src_refid`, `form_refid`, `rang`, `rights`) VALUES
(1, 15, '', '', '', NULL, 1, 4, ''),
(2, 17, '', '', '', NULL, 1, 5, NULL),
(3, 21, '', '', '', NULL, 1, 6, ''),
(4, 17, '', '', '', NULL, 1, 24, NULL),
(5, 21, '', '', '', NULL, 1, 25, ''),
(6, 21, '', '', '', NULL, 1, 27, ''),
(7, 21, '', '', '', NULL, 1, 29, ''),
(21, 11, 'Commentaires', '', '', NULL, 1, 30, NULL),
(9, 17, '', '', '', NULL, 1, 31, NULL),
(10, 18, '', '', '', NULL, 1, 32, ''),
(11, 17, '', '', '', NULL, 1, 34, NULL),
(12, 21, '', '', '', NULL, 1, 35, ''),
(13, 18, '', '', '', NULL, 1, 37, ''),
(15, 18, '', '', '', NULL, 1, 39, ''),
(17, 11, '', 'FICHE ANALYSE FAISABILITE', '', NULL, 1, 7, ''),
(18, 11, 'Analyse faisabilité technique et moyens :', '', '', NULL, 1, 33, ''),
(19, 11, 'Items', '', '', NULL, 1, 26, NULL),
(20, 11, 'OUI/NON', '', '', NULL, 1, 28, NULL),
(22, 14, '', '', '', NULL, 1, 2, ''),
(23, 22, '', '', '', NULL, 1, 1, ''),
(24, 23, '', '', '', NULL, 1, 3, NULL),
(25, 11, 'Sujet similaire déjà traité / type d''étude connu :', '', '', NULL, 1, 36, NULL),
(26, 9, '', '', '', 2, 1, 38, ''),
(27, 16, '', '', '', NULL, 1, 204, NULL),
(28, 4, '', '', '', NULL, 1, 40, ''),
(29, 17, '', '', '', NULL, 1, 41, NULL),
(30, 21, '', '', '', NULL, 1, 42, ''),
(31, 11, 'Nécessite autoformation / recherche de documents', '', '', NULL, 1, 43, NULL),
(32, 18, '', '', '', NULL, 1, 44, NULL),
(33, 4, '', '', '', NULL, 1, 47, NULL),
(34, 18, '', '', '', NULL, 1, 46, NULL),
(35, 9, '', '', '', 2, 1, 45, NULL),
(36, 17, '', '', '', NULL, 1, 48, NULL),
(37, 21, '', '', '', NULL, 1, 49, NULL),
(38, 11, 'Peut être traité par tout ingénieur de l''équipe,', '', '', NULL, 1, 50, NULL),
(39, 18, '', '', '', NULL, 1, 51, NULL),
(40, 4, '', '', '', NULL, 1, 54, NULL),
(41, 18, '', '', '', NULL, 1, 53, NULL),
(42, 9, '', '', '', 2, 1, 52, NULL),
(43, 17, '', '', '', NULL, 1, 55, NULL),
(44, 21, '', '', '', NULL, 1, 56, NULL),
(45, 11, 'Réalisable avec moyens techniques actuels (logiciels/modules, puissance calcul)', '', '', NULL, 1, 57, NULL),
(46, 18, '', '', '', NULL, 1, 58, NULL),
(47, 9, '', '', '', 2, 1, 59, NULL),
(48, 18, '', '', '', NULL, 1, 60, NULL),
(49, 4, '', '', '', NULL, 1, 61, NULL),
(50, 17, '', '', '', NULL, 1, 62, NULL),
(51, 21, '', '', '', NULL, 1, 63, NULL),
(52, 11, 'Nécessite de la sous-traitance', '', '', NULL, 1, 64, NULL),
(53, 18, '', '', '', NULL, 1, 65, NULL),
(54, 9, '', '', '', 2, 1, 66, NULL),
(55, 18, '', '', '', NULL, 1, 67, NULL),
(56, 4, '', '', '', NULL, 1, 68, NULL),
(57, 17, '', '', '', NULL, 1, 69, NULL),
(58, 21, '', '', '', NULL, 1, 70, ''),
(59, 11, 'Disponibilité des données d\'entrée/pas d\'hypothèse à prendre', '', '', NULL, 1, 71, NULL),
(60, 18, '', '', '', NULL, 1, 72, NULL),
(61, 9, '', '', '', 2, 1, 73, NULL),
(62, 18, '', '', '', NULL, 1, 74, NULL),
(63, 4, '', '', '', NULL, 1, 75, NULL),
(64, 17, '', '', '', NULL, 1, 76, NULL),
(65, 21, '', '', '', NULL, 1, 77, ''),
(66, 11, 'Absence de risque technique identifié', '', '', NULL, 1, 78, NULL),
(67, 18, '', '', '', NULL, 1, 79, NULL),
(68, 9, '', '', '', 2, 1, 80, NULL),
(69, 18, '', '', '', NULL, 1, 81, NULL),
(70, 4, '', '', '', NULL, 1, 82, NULL),
(71, 17, '', '', '', NULL, 1, 83, NULL),
(72, 21, '', '', '', NULL, 1, 84, ''),
(73, 11, 'Document spécifique à produire (plan,?),', '', '', NULL, 1, 85, NULL),
(74, 18, '', '', '', NULL, 1, 86, NULL),
(75, 9, '', '', '', 2, 1, 87, NULL),
(76, 18, '', '', '', NULL, 1, 88, NULL),
(77, 4, '', '', '', NULL, 1, 89, NULL),
(78, 17, '', '', '', NULL, 1, 90, NULL),
(79, 21, '', '', '', NULL, 1, 91, NULL),
(80, 11, 'Prestation en Français', '', '', NULL, 1, 92, NULL),
(81, 18, '', '', '', NULL, 1, 93, NULL),
(82, 9, '', '', '', 2, 1, 94, NULL),
(83, 18, '', '', '', NULL, 1, 95, NULL),
(84, 4, '', '', '', NULL, 1, 96, NULL),
(85, 17, '', '', '', NULL, 1, 97, NULL),
(86, 18, '', '', '', NULL, 1, 98, ''),
(87, 11, 'Analyse profil client ', '', '', NULL, 1, 99, NULL),
(88, 17, '', '', '', NULL, 1, 100, NULL),
(89, 21, '', '', '', NULL, 1, 101, NULL),
(90, 11, 'Client déjà connu', '', '', NULL, 1, 102, NULL),
(91, 18, '', '', '', NULL, 1, 103, NULL),
(92, 9, '', '', '', 2, 1, 104, NULL),
(93, 18, '', '', '', NULL, 1, 105, NULL),
(94, 4, '', '', '', NULL, 1, 106, NULL),
(228, 21, '', '', '', NULL, 1, 153, NULL),
(229, 11, 'Prestige/référence technique exploitable commercialement', '', '', NULL, 1, 154, NULL),
(227, 17, '', '', '', NULL, 1, 152, NULL),
(226, 4, '', '', '', NULL, 1, 151, NULL),
(219, 17, '', '', '', NULL, 1, 138, NULL),
(221, 21, '', '', '', NULL, 1, 146, NULL),
(222, 11, 'Enrichissement Base de Données Modèles', '', '', NULL, 1, 147, NULL),
(223, 18, '', '', '', NULL, 1, 148, NULL),
(224, 9, '', '', '', 2, 1, 149, NULL),
(225, 18, '', '', '', NULL, 1, 150, NULL),
(211, 4, '', '', '', NULL, 1, 144, NULL),
(209, 9, '', '', '', 2, 1, 142, NULL),
(210, 18, '', '', '', NULL, 1, 143, NULL),
(208, 18, '', '', '', NULL, 1, 141, NULL),
(207, 11, 'Possibilité de revendre la prestation', '', '', NULL, 1, 140, NULL),
(206, 21, '', '', '', NULL, 1, 139, NULL),
(220, 17, '', '', '', NULL, 1, 145, NULL),
(202, 11, 'Analyse stratégique prestation pour CAPSIM : ', '', '', NULL, 1, 137, ''),
(201, 18, '', '', '', NULL, 1, 136, ''),
(200, 17, '', '', '', NULL, 1, 135, NULL),
(199, 4, '', '', '', NULL, 1, 134, NULL),
(197, 9, '', '', '', 2, 1, 132, NULL),
(198, 18, '', '', '', NULL, 1, 133, NULL),
(196, 18, '', '', '', NULL, 1, 131, NULL),
(195, 11, 'Passage par un acheteur (négociation de prix)', '', '', NULL, 1, 130, NULL),
(193, 17, '', '', '', NULL, 1, 128, NULL),
(194, 21, '', '', '', NULL, 1, 129, NULL),
(192, 4, '', '', '', NULL, 1, 127, NULL),
(191, 18, '', '', '', NULL, 1, 126, NULL),
(190, 9, '', '', '', 2, 1, 125, NULL),
(189, 18, '', '', '', NULL, 1, 124, NULL),
(188, 11, 'Niveau de détail standard pour l\'offre (client mature)', '', '', NULL, 1, 123, NULL),
(187, 21, '', '', '', NULL, 1, 122, NULL),
(186, 17, '', '', '', NULL, 1, 121, NULL),
(185, 4, '', '', '', NULL, 1, 120, NULL),
(184, 18, '', '', '', NULL, 1, 119, NULL),
(183, 9, '', '', '', 2, 1, 118, NULL),
(182, 18, '', '', '', NULL, 1, 117, NULL),
(181, 11, 'Volonté identifiée de récupération de savoir faire ou de concurrence par le client', '', '', NULL, 1, 116, NULL),
(179, 17, '', '', '', NULL, 1, 114, NULL),
(180, 21, '', '', '', NULL, 1, 115, NULL),
(178, 4, '', '', '', NULL, 1, 113, NULL),
(172, 17, '', '', '', NULL, 1, 107, NULL),
(173, 21, '', '', '', NULL, 1, 108, NULL),
(174, 11, 'Risque identifié de dérive du au profil du client', '', '', NULL, 1, 109, NULL),
(175, 18, '', '', '', NULL, 1, 110, NULL),
(176, 9, '', '', '', 2, 1, 111, NULL),
(177, 18, '', '', '', NULL, 1, 112, NULL),
(230, 18, '', '', '', NULL, 1, 155, NULL),
(231, 9, '', '', '', 2, 1, 156, NULL),
(232, 18, '', '', '', NULL, 1, 157, NULL),
(233, 4, '', '', '', NULL, 1, 158, NULL),
(234, 17, '', '', '', NULL, 1, 159, NULL),
(235, 21, '', '', '', NULL, 1, 160, NULL),
(236, 11, 'Possibilité publication travaux / communication internet', '', '', NULL, 1, 161, NULL),
(237, 18, '', '', '', NULL, 1, 162, NULL),
(238, 9, '', '', '', 2, 1, 163, NULL),
(239, 18, '', '', '', NULL, 1, 164, NULL),
(240, 4, '', '', '', NULL, 1, 165, NULL),
(241, 17, '', '', '', NULL, 1, 166, NULL),
(242, 18, '', '', '', NULL, 1, 167, ''),
(243, 11, 'Analyse stratégique prestation pour le CLIENT  / concurrence : ', '', '', NULL, 1, 168, ''),
(370, 11, '', '" . '".($element_obj->fk_project? getNomProjet($element_obj->fk_project) : "")."' . "', '', NULL, 1, 17, NULL),
(368, 11, '', '" . '".($element_obj->socid? getNomSoc($element_obj->socid) : "")."' . "', '', NULL, 1, 22, NULL),
(366, 4, '', '', '', NULL, 1, 203, NULL),
(365, 18, '', '', '', NULL, 1, 202, NULL),
(364, 9, '', '', '', 2, 1, 201, NULL),
(363, 18, '', '', '', NULL, 1, 200, NULL),
(362, 11, 'Volume de prestation supérieur à 3 jours', '', '', NULL, 1, 199, NULL),
(361, 21, '', '', '', NULL, 1, 198, NULL),
(360, 17, '', '', '', NULL, 1, 197, NULL),
(359, 4, '', '', '', NULL, 1, 196, NULL),
(358, 18, '', '', '', NULL, 1, 195, NULL),
(357, 9, '', '', '', 2, 1, 194, NULL),
(356, 18, '', '', '', NULL, 1, 193, NULL),
(355, 11, 'Exigences confidentialité spécifiques', '', '', NULL, 1, 192, NULL),
(354, 21, '', '', '', NULL, 1, 191, NULL),
(353, 17, '', '', '', NULL, 1, 190, NULL),
(352, 4, '', '', '', NULL, 1, 189, NULL),
(351, 18, '', '', '', NULL, 1, 188, NULL),
(350, 9, '', '', '', 2, 1, 187, NULL),
(349, 18, '', '', '', NULL, 1, 186, NULL),
(348, 11, 'Exigences délais spécifiques', '', '', NULL, 1, 185, NULL),
(346, 17, '', '', '', NULL, 1, 183, NULL),
(347, 21, '', '', '', NULL, 1, 184, NULL),
(345, 4, '', '', '', NULL, 1, 182, NULL),
(344, 18, '', '', '', NULL, 1, 181, NULL),
(343, 9, '', '', '', 2, 1, 180, NULL),
(342, 18, '', '', '', NULL, 1, 179, NULL),
(341, 11, 'Exigences qualité spécifiques', '', '', NULL, 1, 178, NULL),
(340, 21, '', '', '', NULL, 1, 177, NULL),
(339, 17, '', '', '', NULL, 1, 176, NULL),
(338, 4, '', '', '', NULL, 1, 175, NULL),
(337, 18, '', '', '', NULL, 1, 174, NULL),
(336, 9, '', '', '', 2, 1, 173, NULL),
(335, 18, '', '', '', NULL, 1, 172, NULL),
(334, 11, 'CGA en possession de CAPSIM', '', '', NULL, 1, 171, NULL),
(333, 21, '', '', '', NULL, 1, 170, NULL),
(332, 17, '', '', '', NULL, 1, 169, NULL),
(330, 11, '', 'Client :', '', NULL, 1, 20, NULL),
(329, 18, '', '', '', NULL, 1, 19, NULL),
(328, 18, '', '', '', NULL, 1, 21, NULL),
(327, 18, '', '', '', NULL, 1, 16, NULL),
(326, 18, '', '', '', NULL, 1, 14, NULL),
(325, 11, '', 'Nom du Projet :', '', NULL, 1, 15, NULL),
(324, 17, '', '', '', NULL, 1, 18, NULL),
(323, 17, '', '', '', NULL, 1, 13, NULL),
(322, 16, '', '', '', NULL, 1, 23, NULL),
(321, 15, '', '', '', NULL, 1, 12, NULL),
(320, 18, '', '', '', NULL, 1, 11, ''),
(319, 11, '" . '".($element_obj?$element_obj->getNomUrl(1): "")."' . "', '', '', NULL, 1, 10, NULL),
(318, 18, '', '', '', NULL, 1, 9, ''),
(317, 17, '', '', '', NULL, 1, 8, NULL),
(371, 22, '', '', '', NULL, 2, 1, NULL),
(372, 6, '', '', '', NULL, 2, 2, NULL),
(373, 4, 'Précision', '', '', NULL, 3, 1, ''),
(374, 11, '', '', '', NULL, 4, 1, NULL);",
            'CREATE TABLE IF NOT EXISTS `' . MAIN_DB_PREFIX . 'Synopsis_Process_form_requete` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `requete` longtext,
  `requeteValue` longtext,
  `params` longtext,
  `limite` int(11) DEFAULT \'100\',
  `label` varchar(50) DEFAULT NULL,
  `description` longtext,
  `showFields` varchar(500) DEFAULT NULL,
  `indexField` varchar(50) DEFAULT NULL,
  `tableName` longtext,
  `groupBy` longtext,
  `orderBy` longtext,
  `filter` longtext,
  `OptGroup` longtext,
  `OptGroupLabel` longtext,
  `postTraitement` longtext,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=16 ;',
            'INSERT IGNORE INTO `' . MAIN_DB_PREFIX . 'Synopsis_Process_form_requete` (`id`, `requete`, `requeteValue`, `params`, `limite`, `label`, `description`, `showFields`, `indexField`, `tableName`, `groupBy`, `orderBy`, `filter`, `OptGroup`, `OptGroupLabel`, `postTraitement`) VALUES
(1, \'SELECT lastname, firstname FROM llx_socpeople where name like \'\'%%%s\'\' order by name\', \'SELECT lastname, firstname FROM llx_socpeople where name like \'\'%%%s\'\' AND [[indexField]] order by name \', \'a\', 100, \'test query\', \'tezst query\', \'lastname, firstname\', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(9, \'SELECT * FROM llx_user\', \'\', NULL, 100, \'reqUser\', \'reqUser\', \'a:2:{i:0;s:4:"lastname";i:1;s:9:"firstname";}\', \'rowid\', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(10, \'SELECT rowid, lastname, firstname FROM llx_user WHERE rowid <> %s AND name like \'\'%%%s%%\'\' order by name\', \'SELECT rowid, lastname, firstname FROM llx_user WHERE rowid <> %s AND [[indexField]] AND name like \'\'%%%s%%\'\' order by name\', \'a:2:{i:0;s:13:"".$user->id."";i:1;s:1:"a";}\', 50, \'req14\', \'test\', \'N;\', \'rowid\', \'\', NULL, NULL, NULL, \'rowid\', \'rowid\', \'N;\'),
(11, \'SELECT llx_propal.rowid, ref, fk_soc, llx_societe.nom, llx_propal.total_ht FROM llx_propal, llx_societe where llx_societe.rowid = fk_soc order by llx_societe.nom, llx_propal.datec \', \'SELECT llx_propal.rowid, ref, fk_soc, llx_societe.nom, llx_propal.total_ht FROM llx_propal, llx_societe WHERE llx_societe.rowid = fk_soc AND [[indexField]] order by llx_societe.nom, llx_propal.datec  , llx_propal.ref     \', \'a:1:{i:0;s:0:"";}\', 100, \'requete propal/soc\', \'Toutes les propositions commerciales par société\', \'a:2:{i:0;s:3:"ref";i:1;s:8:"total_ht";}\', \'rowid\', \'llx_propal\', NULL, NULL, NULL, \'fk_soc\', \'nom\', \'a:2:{s:3:"ref";s:0:"";s:8:"total_ht";s:14:"price([VAL],1,";}\'),
(12, \'SELECT p.rowid, p.ref, p.fk_soc, s.nom  FROM llx_projet as p, llx_societe as s where s.rowid = p.fk_soc order by s.nom, p.dateo \', \'SELECT p.rowid, p.ref, p.fk_soc, s.nom  FROM  llx_projet as p, llx_societe as s WHERE s.rowid = fk_soc AND [[indexField]] order by s.nom, p.dateo  , p.ref\', \'a:1:{i:0;s:0:"";}\', 100, \'requete projet/soc\', \'Toutes les projets par société\', \'a:1:{i:0;s:5:"rowid";}\', \'ref\', \'p\', NULL, NULL, NULL, \'rowid\', \'rowid\', \'a:1:{s:3:"ref";s:0:"";}\'),
(15, \'SELECT concat(ref,\'\' - \'\',title) as texte FROM llx_projet ORDER BY ref desc\', \'\', \'a:1:{i:0;s:0:"";}\', 1000, \'req_projet\', \'liste des projets\', \'N;\', \'texte\', \'\', NULL, NULL, NULL, \'texte\', \'texte\', \'N;\'),
(1000, \'SELECT c.rowid, c.ref, fk_soc, s.nom FROM llx_contrat c, llx_societe s WHERE c.fk_soc = s.rowid ORDER BY s.nom\', \'SELECT c.rowid, c.ref, fk_soc, s.nom FROM llx_contrat c, llx_societe s WHERE c.fk_soc = s.rowid AND [[indexField]] ORDER BY s.nom\', \'a:1:{i:0;s:0:"";}\', 10000, \'requete Contrat/Soc\', \'contrat + soc\', \'a:1:{i:0;s:3:"ref";}\', \'rowid\', \'c\', NULL, NULL, NULL, \'fk_soc\', \'nom\', \'a:1:{s:3:"ref";s:0:"";}\'),
(1001, \'SELECT rowid, nom FROM llx_societe\', \'\', \'a:1:{i:0;s:0:"";}\', 10000, \'Sociétés\', \'Liste des sociétés\', \'a:1:{i:0;s:3:"nom";}\', \'rowid\', \'\', NULL, NULL, NULL, \'\', \'\', \'a:1:{s:3:"nom";s:0:"";}\'),
(1002, \'Select rowid, ref, Label FROM llx_product WHERE fk_product_type=0\', \'\', \'a:1:{i:0;s:0:"";}\', 100, \'Produits\', \'Liste des produits\', \'a:3:{i:0;s:5:"rowid";i:1;s:3:"ref";i:2;s:5:"Label";}\', \'rowid\', \'\', NULL, NULL, NULL, \'\', \'\', \'a:3:{s:5:"rowid";s:32:"lien(product/card.php?id=[VAL])";s:3:"ref";s:0:"";s:5:"Label";s:13:"finLien([VAL]";}\');
',
            'CREATE TABLE IF NOT EXISTS `' . MAIN_DB_PREFIX . 'Synopsis_Process_form_src` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `requete_refid` int(11) DEFAULT NULL,
  `fct_refid` int(11) DEFAULT NULL,
  `global_refid` int(11) DEFAULT NULL,
  `list_refid` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `requete_refid` (`requete_refid`),
  KEY `global_refid` (`global_refid`),
  KEY `fct_refid` (`fct_refid`),
  KEY `list_refid` (`list_refid`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=6 ;',
            'INSERT IGNORE INTO `' . MAIN_DB_PREFIX . 'Synopsis_Process_form_src` (`id`, `requete_refid`, `fct_refid`, `global_refid`, `list_refid`) VALUES
(1, NULL, NULL, NULL, 1),
(2, NULL, NULL, NULL, 2),
(3, 9, NULL, NULL, NULL),
(4, NULL, 1, NULL, NULL),
(5, NULL, 2, NULL, NULL);',
            'CREATE TABLE IF NOT EXISTS `' . MAIN_DB_PREFIX . 'Synopsis_Process_form_type` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `code` varchar(20) DEFAULT NULL,
  `label` varchar(50) DEFAULT NULL,
  `description` longtext,
  `cssClass` varchar(50) DEFAULT NULL,
  `endNedded` tinyint(1) DEFAULT NULL,
  `htmlTag` varchar(500) DEFAULT NULL,
  `htmlEndTag` varchar(50) DEFAULT NULL,
  `hasDescription` tinyint(11) DEFAULT NULL,
  `hasDflt` tinyint(11) DEFAULT NULL,
  `hasTitle` tinyint(4) DEFAULT NULL,
  `hasSource` tinyint(4) DEFAULT NULL,
  `isInput` tinyint(4) DEFAULT NULL,
  `descriptionInsideTag` tinyint(4) DEFAULT NULL,
  `titleInsideTag` tinyint(4) DEFAULT NULL,
  `sourceIsOption` tinyint(4) DEFAULT NULL,
  `sourceGroupByName` tinyint(4) DEFAULT NULL,
  `titleInLegend` tinyint(4) DEFAULT NULL,
  `cssScript` varchar(500) DEFAULT NULL,
  `jsScript` varchar(500) DEFAULT NULL,
  `jsCode` longtext,
  `isTabTitle` tinyint(4) DEFAULT NULL,
  `isStarRating` tinyint(4) DEFAULT NULL,
  `isHidden` tinyint(4) DEFAULT NULL,
  `isBegEndTab` tinyint(4) DEFAULT NULL,
  `repeatTag` tinyint(4) DEFAULT NULL,
  `valueInValueField` tinyint(4) DEFAULT NULL,
  `valueInTag` tinyint(4) DEFAULT NULL,
  `valueIsChecked` tinyint(4) DEFAULT NULL,
  `valueIsSelected` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=38 ;',
            'INSERT IGNORE INTO `' . MAIN_DB_PREFIX . 'Synopsis_Process_form_type` (`id`, `code`, `label`, `description`, `cssClass`, `endNedded`, `htmlTag`, `htmlEndTag`, `hasDescription`, `hasDflt`, `hasTitle`, `hasSource`, `isInput`, `descriptionInsideTag`, `titleInsideTag`, `sourceIsOption`, `sourceGroupByName`, `titleInLegend`, `cssScript`, `jsScript`, `jsCode`, `isTabTitle`, `isStarRating`, `isHidden`, `isBegEndTab`, `repeatTag`, `valueInValueField`, `valueInTag`, `valueIsChecked`, `valueIsSelected`) VALUES
(1, \'inpt\', \'Champs Texte\', \'Champs texte\', NULL, 0, \'<input>\', NULL, 1, 1, 1, 1, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL),
(2, \'inptRadio\', \'Radio\', \'Champs Radio\', NULL, 0, \'<input type="radio">\', NULL, 1, 1, 1, 2, 1, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL),
(3, \'inptChkBox\', \'Checkbox\', \'Champs checkbox\', NULL, 0, \'<input type="checkbox">\', NULL, 1, 1, 1, 2, 1, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL),
(4, \'textarea\', \'Description\', \'Champs commentaire\', NULL, 1, \'<textarea>\', \'</textarea>\', 1, 1, 1, 1, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL),
(5, \'inptDate\', \'Date\', \'Champs Date\', \'datePicker\', 0, \'<input>\', NULL, 1, 1, 1, 1, 1, NULL, NULL, NULL, NULL, NULL, NULL, \'/Synopsis_Common/jquery/ui/ui.datepicker.js\', \'jQuery(document).ready(function(){\n    jQuery(\'\'.datePicker\'\').datepicker({\n        showTime:false,\n    });\n});\', NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL),
(6, \'inptDateTime\', \'Date et Heure\', \'Champs Date et Heure\', \'dateTimePicker\', 0, \'<input>\', NULL, 1, 1, 1, 1, 1, NULL, NULL, NULL, NULL, NULL, NULL, \'/Synopsis_Common/jquery/ui/ui.datepicker.js\', \'jQuery(document).ready(function(){\n    jQuery(\'\'.dateTimePicker\'\').datepicker({\n        showTime:true,\n    });\n});\', NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL),
(7, \'3stars\', \'3 Etoiles\', \'3 Etoiles\', \'3stars star\', 0, \'<input type="radio">\', NULL, 1, 1, 1, 0, 1, NULL, NULL, NULL, 1, NULL, \'/Synopsis_Common/css/jquery.rating.css\', \'/Synopsis_Common/jquery/jquery.rating.pack.js\', \'jQuery(document).ready(function(){\n    jQuery(\'\'.starrating\'\').each(function(){\n	jQuery(this).find("input:radio.star").rating();\n    });\n});\', NULL, 1, NULL, NULL, 3, NULL, NULL, 1, NULL),
(8, \'5stars\', \'5 Etoiles\', \'5 Etoiles\', \'5stars star\', 0, \'<input type="radio">\', NULL, 1, 1, 1, 0, 1, NULL, NULL, NULL, 1, NULL, \'/Synopsis_Common/css/jquery.rating.css\', \'/Synopsis_Common/jquery/jquery.rating.pack.js\', \'jQuery(document).ready(function(){\n    jQuery(\'\'.starrating\'\').each(function(){\n	jQuery(this).find("input:radio.star").rating();\n    });\n});\', NULL, 1, NULL, NULL, 5, NULL, NULL, 1, NULL),
(9, \'Select\', \'Select\', \'Liste déroulante\', NULL, 1, \'<select>\', \'</select>\', 1, 1, 1, 2, 1, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1),
(10, \'fieldset\', \'Section de formulaire\', \'Section de formulaire\', NULL, 0, \'<fieldset>\', \'\', 0, 0, 1, 0, 0, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11, \'Texte\', \'Texte fixe\', \'Texte libre\', NULL, 1, \'<div>\', \'</div>\', 1, 0, 1, 0, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(13, \'TitreTab\', \'Saut + titre tab\', \'Saut + Titre tab\', \'titreTab\', 1, \'<div>\', \'</div>\', 0, 0, 1, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(14, \'Image\', \'Image\', \'Image\', \'image\', 1, \'<img>\', \'</img>\', 1, 0, 1, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15, \'table\', \'Tableau\', \'Début Tableau\', NULL, 0, \'<table>\', NULL, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16, \'finTable\', \'Fin Tableau\', \'Fin de Tableau\', NULL, 1, NULL, \'</table>\', 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17, \'tr\', \'Nouvelle Ligne\', \'Nouvelle Ligne de tableau\', NULL, 0, \'<tr>\', NULL, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(18, \'td\', \'Nouvelle Col.\', \'Nouvelle Colonne de tableau\', NULL, 0, \'<td>\', NULL, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(19, \'cache\', \'Champs caché\', \'Champs caché\', NULL, 0, \'<input type="hidden">\', NULL, 0, 1, 0, 1, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL),
(20, \'autocomplete\', \'Champs autocompleté\', \'Champs autocompleté\', \'autocomplete\', 0, \'<input type="text">\', NULL, 1, 1, 1, 2, 1, NULL, NULL, NULL, NULL, NULL, \'/Synopsis_Common/css/jquery.autocomplete.css\', \'/Synopsis_Common/jquery/jquery.autocomplete.js\', NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL),
(21, \'th\', \'Nouvelle Ent. Col.\', \'Nouvelle entête de colonne de tableau\', NULL, 0, \'<th>\', NULL, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(22, \'center\', \'Alignement centré\', \'Alignement centré\', NULL, 0, \'<center>\', NULL, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(23, \'finCenter\', \'Fin de l\'\'alignement centré\', \'Fin de l\'\'alignement centré\', NULL, 1, NULL, \'</center>\', 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(24, \'right\', \'Alignement à droite\', \'Alignement à droite\', NULL, 0, \'<right>\', NULL, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(25, \'finRight\', \'Fin d\'\'alignement à droite\', \'Fin d\'\'alignement à droite\', NULL, 1, NULL, \'</right>\', 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(26, \'left\', \'Alignement à gauche\', \'Alignement à gauche\', NULL, 0, \'<left>\', NULL, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(27, \'finLeft\', \'Fin d\'\'Alignement à gauche\', \'Fin d\'\'alignement à gauche\', NULL, 1, NULL, \'</left >\', 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(28, \'paragraphe\', \'Nouveau paragraphe\', \'Nouveau paragraphe\', NULL, 0, \'<p>\', NULL, 1, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(29, \'finParagraphe\', \'Fin de paragraphe\', \'Fin de paragraphe\', NULL, 0, NULL, \'</p>\', 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(30, \'finFieldset\', \'Fin de section de formulaire\', \'Fin de section de formulaire\', NULL, 1, NULL, \'</fieldset>\', 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(31, \'FinTab\', \'Fin de Tab\', \'Fin de tab\', \'\', 1, NULL, \'</div>\', 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL),
(32, \'debTab\', \'Début de Tab\', \'Début de tab\', \'tabs\', 0, \'<div>\', NULL, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, \'/Synopsis_Common/jquery/ui/ui.tabs.js\', \'jQuery(document).ready(function(){\n    jQuery(\'\'div.tabs\'\').tabs({\n	spinner: \'\'Chargement\'\',\n        cache: true,\n        fx: { opacity: \'\'toggle\'\' }\n    });\n});\', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL),
(33, \'debListeLi\', \'Début de liste à puce\', \'Début de liste à puce\', NULL, 0, \'<ul>\', NULL, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(34, \'finListeLI\', \'Fin de liste à puce\', \'Fin de liste à puce\', NULL, 1, NULL, \'</ul>\', 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(35, \'ListeElem\', \'Elément de liste\', \'Elément de liste\', NULL, 1, \'<li>\', \'</li>\', 0, 0, 1, 0, 0, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(36, \'debListeNum\', \'Début de liste numérotée\', \'Début de liste numérotée\', NULL, 0, \'<ol>\', NULL, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(37, \'finListeNum\', \'Fin de liste numérotée\', \'Fin de liste numérotée\', NULL, 1, NULL, \'</ol>\', 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);',
            'CREATE TABLE IF NOT EXISTS `' . MAIN_DB_PREFIX . 'Synopsis_Process_form_type_class_value` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `model_refid` int(11) DEFAULT NULL,
  `valeur` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_process_form_class_model_refid` (`model_refid`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=314 ;',
            'INSERT IGNORE INTO `' . MAIN_DB_PREFIX . 'Synopsis_Process_form_type_class_value` (`id`, `model_refid`, `valeur`) VALUES
(196, 44, \'ui-widget-header ui-state-default\'),
(195, 51, \'ui-widget-header ui-state-default\'),
(194, 79, \'ui-widget-header ui-state-default\'),
(193, 72, \'ui-widget-header ui-state-default\'),
(192, 65, \'ui-widget-header ui-state-default\'),
(191, 58, \'ui-widget-header ui-state-default\'),
(190, 30, \'ui-widget-header ui-state-default\'),
(177, 3, \'ui-widget-header ui-state-default\'),
(178, 10, \'ui-widget-header ui-state-hover\'),
(179, 22, \'\'),
(180, 26, \'\'),
(181, 28, \'\'),
(182, 1, \'\'),
(183, 5, \'ui-widget-header\'),
(184, 6, \'ui-widget-header\'),
(185, 7, \'ui-widget-header\'),
(186, 18, \'ui-widget-header ui-state-hover\'),
(187, 12, \'ui-widget-header ui-state-default\'),
(188, 13, \'ui-widget-content\'),
(189, 15, \'ui-widget-content\'),
(197, 37, \'ui-widget-header ui-state-default\'),
(198, 53, \'ui-widget-content\'),
(199, 55, \'ui-widget-content\'),
(200, 60, \'ui-widget-content\'),
(201, 62, \'ui-widget-content\'),
(202, 67, \'ui-widget-content\'),
(203, 69, \'ui-widget-content\'),
(204, 74, \'ui-widget-content\'),
(205, 76, \'ui-widget-content\'),
(206, 81, \'ui-widget-content\'),
(207, 83, \'ui-widget-content\'),
(208, 46, \'ui-widget-content\'),
(209, 48, \'ui-widget-content\'),
(210, 39, \'ui-widget-content\'),
(211, 41, \'ui-widget-content\'),
(212, 32, \'ui-widget-content\'),
(213, 34, \'ui-widget-content\'),
(214, 86, \'ui-widget-header ui-state-hover\'),
(252, 214, \'ui-widget-header ui-state-default\'),
(251, 216, \'ui-widget-content\'),
(250, 218, \'ui-widget-content\'),
(249, 206, \'ui-widget-header ui-state-default\'),
(248, 208, \'ui-widget-content\'),
(247, 210, \'ui-widget-content\'),
(246, 203, \'ui-widget-content\'),
(245, 201, \'ui-widget-header ui-state-hover\'),
(244, 198, \'ui-widget-content\'),
(243, 196, \'ui-widget-content\'),
(242, 194, \'ui-widget-header ui-state-default\'),
(241, 93, \'ui-widget-content\'),
(240, 91, \'ui-widget-content\'),
(239, 89, \'ui-widget-header ui-state-default\'),
(230, 177, \'ui-widget-content\'),
(231, 175, \'ui-widget-content\'),
(232, 173, \'ui-widget-header ui-state-default\'),
(233, 184, \'ui-widget-content\'),
(234, 182, \'ui-widget-content\'),
(235, 180, \'ui-widget-header ui-state-default\'),
(236, 191, \'ui-widget-content\'),
(237, 189, \'ui-widget-content\'),
(238, 187, \'ui-widget-header ui-state-default\'),
(253, 221, \'ui-widget-header ui-state-default\'),
(254, 223, \'ui-widget-content\'),
(255, 225, \'ui-widget-content\'),
(256, 228, \'ui-widget-header ui-state-default\'),
(257, 230, \'ui-widget-content\'),
(258, 232, \'ui-widget-content\'),
(259, 239, \'ui-widget-content\'),
(260, 237, \'ui-widget-content\'),
(261, 235, \'ui-widget-header ui-state-default\'),
(262, 242, \'ui-widget-header ui-state-hover\'),
(263, 249, \'ui-widget-content\'),
(264, 247, \'ui-widget-content\'),
(265, 245, \'ui-widget-header ui-state-default\'),
(266, 256, \'ui-widget-content\'),
(267, 254, \'ui-widget-content\'),
(268, 252, \'ui-widget-header ui-state-default\'),
(269, 263, \'ui-widget-content\'),
(270, 261, \'ui-widget-content\'),
(271, 259, \'ui-widget-header ui-state-default\'),
(272, 270, \'ui-widget-content\'),
(273, 268, \'ui-widget-content\'),
(274, 266, \'ui-widget-header ui-state-default\'),
(275, 277, \'ui-widget-content\'),
(276, 275, \'ui-widget-content\'),
(277, 273, \'ui-widget-header ui-state-default\'),
(278, 280, \'ui-widget-header ui-state-hover\'),
(279, 287, \'ui-widget-content\'),
(280, 285, \'ui-widget-content\'),
(281, 283, \'ui-widget-header ui-state-default\'),
(282, 294, \'ui-widget-content\'),
(283, 292, \'ui-widget-content\'),
(284, 290, \'ui-widget-header ui-state-default\'),
(285, 301, \'ui-widget-content\'),
(286, 299, \'ui-widget-content\'),
(287, 297, \'ui-widget-header ui-state-default\'),
(288, 308, \'ui-widget-content\'),
(289, 306, \'ui-widget-content\'),
(290, 304, \'ui-widget-header ui-state-default\'),
(291, 315, \'ui-widget-content\'),
(292, 313, \'ui-widget-content\'),
(293, 311, \'ui-widget-header ui-state-default\'),
(294, 17, \'titre\'),
(295, 337, \'ui-widget-content\'),
(296, 335, \'ui-widget-content\'),
(297, 333, \'ui-widget-header ui-state-default\'),
(298, 344, \'ui-widget-content\'),
(299, 342, \'ui-widget-content\'),
(300, 340, \'ui-widget-header ui-state-default\'),
(301, 351, \'ui-widget-content\'),
(302, 349, \'ui-widget-content\'),
(303, 347, \'ui-widget-header ui-state-default\'),
(304, 358, \'ui-widget-content\'),
(305, 356, \'ui-widget-content\'),
(306, 354, \'ui-widget-header ui-state-default\'),
(307, 365, \'ui-widget-content\'),
(308, 363, \'ui-widget-content\'),
(309, 361, \'ui-widget-header ui-state-default\'),
(310, 318, \'ui-widget-content\'),
(311, 320, \'ui-widget-content\'),
(312, 369, \'\'),
(313, 23, \'\'),
(314, 373, \'champGr\');',
            'CREATE TABLE IF NOT EXISTS `' . MAIN_DB_PREFIX . 'Synopsis_Process_form_type_prop` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `type_refid` int(11) DEFAULT NULL,
  `element_name` varchar(75) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_process_form_type_prop` (`type_refid`,`element_name`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=55 ;',
            'INSERT IGNORE INTO `' . MAIN_DB_PREFIX . 'Synopsis_Process_form_type_prop` (`id`, `type_refid`, `element_name`) VALUES
(4, 1, \'id\'),
(2, 1, \'length\'),
(3, 1, \'name\'),
(1, 1, \'size\'),
(5, 2, \'id\'),
(6, 2, \'name\'),
(7, 3, \'id\'),
(8, 3, \'name\'),
(9, 4, \'id\'),
(10, 4, \'name\'),
(11, 5, \'id\'),
(12, 5, \'name\'),
(14, 6, \'id\'),
(13, 6, \'name\'),
(15, 7, \'id\'),
(16, 7, \'name\'),
(17, 8, \'id\'),
(18, 8, \'name\'),
(19, 9, \'id\'),
(20, 9, \'name\'),
(21, 10, \'id\'),
(22, 10, \'name\'),
(23, 11, \'id\'),
(24, 11, \'name\'),
(27, 13, \'id\'),
(28, 13, \'name\'),
(29, 14, \'id\'),
(30, 14, \'name\'),
(52, 14, \'src\'),
(45, 15, \'border\'),
(44, 15, \'cellpadding\'),
(31, 15, \'id\'),
(32, 15, \'name\'),
(43, 15, \'width\'),
(33, 16, \'id\'),
(34, 16, \'name\'),
(35, 17, \'id\'),
(36, 17, \'name\'),
(49, 18, \'align\'),
(37, 18, \'id\'),
(38, 18, \'name\'),
(48, 18, \'valign\'),
(39, 19, \'id\'),
(40, 19, \'name\'),
(41, 20, \'id\'),
(42, 20, \'name\'),
(50, 21, \'align\'),
(46, 21, \'id\'),
(47, 21, \'name\'),
(51, 21, \'valign\'),
(53, 21, \'colspan\'),
(54, 18, \'colspan\');',
            'CREATE TABLE IF NOT EXISTS `' . MAIN_DB_PREFIX . 'Synopsis_Process_form_type_prop_value` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `prop_refid` int(11) DEFAULT NULL,
  `model_refid` int(11) DEFAULT NULL,
  `valeur` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `process_form_type_prop_value` (`prop_refid`,`model_refid`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=107 ;',
            'INSERT IGNORE INTO `' . MAIN_DB_PREFIX . 'Synopsis_Process_form_type_prop_value` (`id`, `prop_refid`, `model_refid`, `valeur`) VALUES
(1, 50, 3, \'\'),
(2, 53, 3, \'4\'),
(3, 46, 3, \'\'),
(4, 47, 3, \'\'),
(5, 51, 3, \'\'),
(6, 49, 10, \'\'),
(7, 54, 10, \'3\'),
(8, 37, 10, \'\'),
(9, 38, 10, \'\'),
(10, 48, 10, \'\'),
(11, 29, 22, \'\'),
(12, 30, 22, \'\'),
(13, 52, 22, \'/viewimage.php?modulepart=companylogo&file=capsim.png\'),
(14, 19, 26, \'dejatraite\'),
(15, 20, 26, \'dejatraite\'),
(16, 9, 28, \'comment_dejafait\'),
(17, 10, 28, \'comment_dejafait\'),
(18, 45, 1, \'\'),
(19, 44, 1, \'15\'),
(20, 31, 1, \'\'),
(21, 32, 1, \'\'),
(22, 43, 1, \'100%\'),
(23, 50, 5, \'\'),
(24, 53, 5, \'\'),
(25, 46, 5, \'\'),
(26, 47, 5, \'\'),
(27, 51, 5, \'\'),
(28, 50, 6, \'\'),
(29, 53, 6, \'\'),
(30, 46, 6, \'\'),
(31, 47, 6, \'\'),
(32, 51, 6, \'\'),
(33, 50, 7, \'\'),
(34, 53, 7, \'\'),
(35, 46, 7, \'\'),
(36, 47, 7, \'\'),
(37, 51, 7, \'\'),
(38, 23, 18, \'\'),
(39, 24, 18, \'\'),
(40, 50, 12, \'\'),
(41, 53, 12, \'\'),
(42, 46, 12, \'\'),
(43, 47, 12, \'\'),
(44, 51, 12, \'\'),
(45, 49, 13, \'\'),
(46, 54, 13, \'\'),
(47, 37, 13, \'\'),
(48, 38, 13, \'\'),
(49, 48, 13, \'\'),
(50, 49, 15, \'\'),
(51, 54, 15, \'\'),
(52, 37, 15, \'\'),
(53, 38, 15, \'\'),
(54, 48, 15, \'\'),
(55, 50, 30, \'\'),
(56, 53, 30, \'\'),
(57, 46, 30, \'\'),
(58, 47, 30, \'\'),
(59, 51, 30, \'\'),
(60, 50, 58, \'\'),
(61, 53, 58, \'\'),
(62, 46, 58, \'\'),
(63, 47, 58, \'\'),
(64, 51, 58, \'\'),
(65, 50, 65, \'\'),
(66, 53, 65, \'\'),
(67, 46, 65, \'\'),
(68, 47, 65, \'\'),
(69, 51, 65, \'\'),
(70, 50, 72, \'\'),
(71, 53, 72, \'\'),
(72, 46, 72, \'\'),
(73, 47, 72, \'\'),
(74, 51, 72, \'\'),
(75, 49, 86, \'\'),
(76, 54, 86, \'3\'),
(77, 37, 86, \'\'),
(78, 38, 86, \'\'),
(79, 48, 86, \'\'),
(80, 49, 201, \'\'),
(81, 54, 201, \'3\'),
(82, 37, 201, \'\'),
(83, 38, 201, \'\'),
(84, 48, 201, \'\'),
(85, 49, 242, \'\'),
(86, 54, 242, \'3\'),
(87, 37, 242, \'\'),
(88, 38, 242, \'\'),
(89, 48, 242, \'\'),
(90, 54, 280, \'3\'),
(91, 23, 17, \'\'),
(92, 24, 17, \'\'),
(93, 49, 318, \'\'),
(94, 54, 318, \'\'),
(95, 37, 318, \'\'),
(96, 38, 318, \'\'),
(97, 48, 318, \'\'),
(98, 49, 320, \'\'),
(99, 54, 320, \'2\'),
(100, 37, 320, \'\'),
(101, 38, 320, \'\'),
(102, 48, 320, \'\'),
(103, 4, 369, \'\'),
(104, 2, 369, \'\'),
(105, 3, 369, \'nomProjet\'),
(106, 1, 369, \'\');',
            'CREATE TABLE IF NOT EXISTS `' . MAIN_DB_PREFIX . 'Synopsis_Process_form_type_style` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `type_refid` int(11) DEFAULT NULL,
  `element_name` varchar(75) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_process_form_type_style` (`type_refid`,`element_name`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=157 ;',
            'INSERT IGNORE INTO `' . MAIN_DB_PREFIX . 'Synopsis_Process_form_type_style` (`id`, `type_refid`, `element_name`) VALUES
(4, 1, \'border\'),
(7, 1, \'clear\'),
(2, 1, \'color\'),
(6, 1, \'float\'),
(5, 1, \'margin\'),
(3, 1, \'padding\'),
(1, 1, \'text-align\'),
(18, 2, \'border\'),
(21, 2, \'clear\'),
(16, 2, \'color\'),
(20, 2, \'float\'),
(19, 2, \'margin\'),
(17, 2, \'padding\'),
(15, 2, \'text-align\'),
(25, 3, \'border\'),
(28, 3, \'clear\'),
(23, 3, \'color\'),
(27, 3, \'float\'),
(26, 3, \'margin\'),
(24, 3, \'padding\'),
(22, 3, \'text-align\'),
(32, 4, \'border\'),
(35, 4, \'clear\'),
(30, 4, \'color\'),
(34, 4, \'float\'),
(33, 4, \'margin\'),
(31, 4, \'padding\'),
(29, 4, \'text-align\'),
(39, 5, \'border\'),
(42, 5, \'clear\'),
(37, 5, \'color\'),
(41, 5, \'float\'),
(40, 5, \'margin\'),
(38, 5, \'padding\'),
(36, 5, \'text-align\'),
(46, 6, \'border\'),
(49, 6, \'clear\'),
(44, 6, \'color\'),
(48, 6, \'float\'),
(47, 6, \'margin\'),
(45, 6, \'padding\'),
(43, 6, \'text-align\'),
(53, 7, \'border\'),
(56, 7, \'clear\'),
(51, 7, \'color\'),
(55, 7, \'float\'),
(54, 7, \'margin\'),
(52, 7, \'padding\'),
(50, 7, \'text-align\'),
(60, 8, \'border\'),
(63, 8, \'clear\'),
(58, 8, \'color\'),
(62, 8, \'float\'),
(61, 8, \'margin\'),
(59, 8, \'padding\'),
(57, 8, \'text-align\'),
(67, 9, \'border\'),
(70, 9, \'clear\'),
(65, 9, \'color\'),
(69, 9, \'float\'),
(68, 9, \'margin\'),
(66, 9, \'padding\'),
(64, 9, \'text-align\'),
(155, 9, \'width\'),
(74, 10, \'border\'),
(77, 10, \'clear\'),
(72, 10, \'color\'),
(76, 10, \'float\'),
(75, 10, \'margin\'),
(73, 10, \'padding\'),
(71, 10, \'text-align\'),
(88, 11, \'border\'),
(91, 11, \'clear\'),
(86, 11, \'color\'),
(90, 11, \'float\'),
(89, 11, \'margin\'),
(87, 11, \'padding\'),
(85, 11, \'text-align\'),
(81, 12, \'border\'),
(84, 12, \'clear\'),
(79, 12, \'color\'),
(83, 12, \'float\'),
(82, 12, \'margin\'),
(80, 12, \'padding\'),
(78, 12, \'text-align\'),
(95, 13, \'border\'),
(98, 13, \'clear\'),
(93, 13, \'color\'),
(97, 13, \'float\'),
(96, 13, \'margin\'),
(94, 13, \'padding\'),
(92, 13, \'text-align\'),
(102, 14, \'border\'),
(105, 14, \'clear\'),
(100, 14, \'color\'),
(104, 14, \'float\'),
(103, 14, \'margin\'),
(101, 14, \'padding\'),
(99, 14, \'text-align\'),
(109, 15, \'border\'),
(112, 15, \'clear\'),
(107, 15, \'color\'),
(111, 15, \'float\'),
(110, 15, \'margin\'),
(108, 15, \'padding\'),
(106, 15, \'text-align\'),
(116, 16, \'border\'),
(119, 16, \'clear\'),
(114, 16, \'color\'),
(118, 16, \'float\'),
(117, 16, \'margin\'),
(115, 16, \'padding\'),
(113, 16, \'text-align\'),
(123, 17, \'border\'),
(126, 17, \'clear\'),
(121, 17, \'color\'),
(125, 17, \'float\'),
(124, 17, \'margin\'),
(122, 17, \'padding\'),
(120, 17, \'text-align\'),
(130, 18, \'border\'),
(133, 18, \'clear\'),
(128, 18, \'color\'),
(132, 18, \'float\'),
(131, 18, \'margin\'),
(129, 18, \'padding\'),
(127, 18, \'text-align\'),
(137, 19, \'border\'),
(140, 19, \'clear\'),
(135, 19, \'color\'),
(139, 19, \'float\'),
(138, 19, \'margin\'),
(136, 19, \'padding\'),
(134, 19, \'text-align\'),
(144, 20, \'border\'),
(147, 20, \'clear\'),
(142, 20, \'color\'),
(146, 20, \'float\'),
(145, 20, \'margin\'),
(143, 20, \'padding\'),
(141, 20, \'text-align\'),
(151, 21, \'border\'),
(154, 21, \'clear\'),
(149, 21, \'color\'),
(153, 21, \'float\'),
(152, 21, \'margin\'),
(150, 21, \'padding\'),
(148, 21, \'text-align\'),
(156, 22, \'background-color\');',
            'CREATE TABLE IF NOT EXISTS `' . MAIN_DB_PREFIX . 'Synopsis_Process_form_type_style_value` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `style_refid` int(11) DEFAULT NULL,
  `valeur` varchar(75) DEFAULT NULL,
  `model_refid` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `model_refid` (`model_refid`),
  KEY `style_refid` (`style_refid`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=171 ;',
            'INSERT IGNORE INTO `' . MAIN_DB_PREFIX . 'Synopsis_Process_form_type_style_value` (`id`, `style_refid`, `valeur`, `model_refid`) VALUES
(1, 151, \'\', 3),
(2, 154, \'\', 3),
(3, 149, \'\', 3),
(4, 153, \'\', 3),
(5, 152, \'\', 3),
(6, 150, \'\', 3),
(7, 148, \'\', 3),
(8, 130, \'\', 10),
(9, 133, \'\', 10),
(10, 128, \'\', 10),
(11, 132, \'\', 10),
(12, 131, \'\', 10),
(13, 129, \'\', 10),
(14, 127, \'\', 10),
(15, 102, \'\', 22),
(16, 105, \'\', 22),
(17, 100, \'\', 22),
(18, 104, \'\', 22),
(19, 103, \'\', 22),
(20, 101, \'\', 22),
(21, 99, \'\', 22),
(22, 67, \'\', 26),
(23, 70, \'\', 26),
(24, 65, \'\', 26),
(25, 69, \'\', 26),
(26, 68, \'\', 26),
(27, 66, \'\', 26),
(28, 64, \'\', 26),
(29, 155, \'\', 26),
(30, 32, \'\', 28),
(31, 35, \'\', 28),
(32, 30, \'\', 28),
(33, 34, \'\', 28),
(34, 33, \'\', 28),
(35, 31, \'\', 28),
(36, 29, \'\', 28),
(37, 109, \'\', 1),
(38, 112, \'\', 1),
(39, 107, \'\', 1),
(40, 111, \'\', 1),
(41, 110, \'\', 1),
(42, 108, \'\', 1),
(43, 106, \'\', 1),
(44, 151, \'\', 5),
(45, 154, \'\', 5),
(46, 149, \'\', 5),
(47, 153, \'\', 5),
(48, 152, \'\', 5),
(49, 150, \'\', 5),
(50, 148, \'\', 5),
(51, 151, \'\', 6),
(52, 154, \'\', 6),
(53, 149, \'\', 6),
(54, 153, \'\', 6),
(55, 152, \'\', 6),
(56, 150, \'\', 6),
(57, 148, \'\', 6),
(58, 151, \'\', 7),
(59, 154, \'\', 7),
(60, 149, \'\', 7),
(61, 153, \'\', 7),
(62, 152, \'\', 7),
(63, 150, \'\', 7),
(64, 148, \'\', 7),
(65, 88, \'\', 18),
(66, 91, \'\', 18),
(67, 86, \'\', 18),
(68, 90, \'\', 18),
(69, 89, \'\', 18),
(70, 87, \'\', 18),
(71, 85, \'\', 18),
(72, 151, \'\', 12),
(73, 154, \'\', 12),
(74, 149, \'\', 12),
(75, 153, \'\', 12),
(76, 152, \'\', 12),
(77, 150, \'\', 12),
(78, 148, \'\', 12),
(79, 130, \'\', 13),
(80, 133, \'\', 13),
(81, 128, \'\', 13),
(82, 132, \'\', 13),
(83, 131, \'\', 13),
(84, 129, \'\', 13),
(85, 127, \'\', 13),
(86, 130, \'\', 15),
(87, 133, \'\', 15),
(88, 128, \'\', 15),
(89, 132, \'\', 15),
(90, 131, \'\', 15),
(91, 129, \'\', 15),
(92, 127, \'\', 15),
(93, 151, \'\', 30),
(94, 154, \'\', 30),
(95, 149, \'\', 30),
(96, 153, \'\', 30),
(97, 152, \'\', 30),
(98, 150, \'\', 30),
(99, 148, \'\', 30),
(100, 151, \'\', 58),
(101, 154, \'\', 58),
(102, 149, \'\', 58),
(103, 153, \'\', 58),
(104, 152, \'\', 58),
(105, 150, \'\', 58),
(106, 148, \'\', 58),
(107, 151, \'\', 65),
(108, 154, \'\', 65),
(109, 149, \'\', 65),
(110, 153, \'\', 65),
(111, 152, \'\', 65),
(112, 150, \'\', 65),
(113, 148, \'\', 65),
(114, 151, \'\', 72),
(115, 154, \'\', 72),
(116, 149, \'\', 72),
(117, 153, \'\', 72),
(118, 152, \'\', 72),
(119, 150, \'\', 72),
(120, 148, \'\', 72),
(121, 130, \'\', 86),
(122, 133, \'\', 86),
(123, 128, \'\', 86),
(124, 132, \'\', 86),
(125, 131, \'\', 86),
(126, 129, \'\', 86),
(127, 127, \'\', 86),
(128, 130, \'\', 201),
(129, 133, \'\', 201),
(130, 128, \'\', 201),
(131, 132, \'\', 201),
(132, 131, \'\', 201),
(133, 129, \'\', 201),
(134, 127, \'\', 201),
(135, 130, \'\', 242),
(136, 133, \'\', 242),
(137, 128, \'\', 242),
(138, 132, \'\', 242),
(139, 131, \'\', 242),
(140, 129, \'\', 242),
(141, 127, \'\', 242),
(142, 88, \'\', 17),
(143, 91, \'\', 17),
(144, 86, \'\', 17),
(145, 90, \'\', 17),
(146, 89, \'\', 17),
(147, 87, \'\', 17),
(148, 85, \'\', 17),
(149, 130, \'\', 318),
(150, 133, \'\', 318),
(151, 128, \'\', 318),
(152, 132, \'\', 318),
(153, 131, \'\', 318),
(154, 129, \'\', 318),
(155, 127, \'\', 318),
(156, 130, \'\', 320),
(157, 133, \'\', 320),
(158, 128, \'\', 320),
(159, 132, \'\', 320),
(160, 131, \'\', 320),
(161, 129, \'\', 320),
(162, 127, \'\', 320),
(163, 4, \'\', 369),
(164, 7, \'\', 369),
(165, 2, \'\', 369),
(166, 6, \'\', 369),
(167, 5, \'\', 369),
(168, 3, \'\', 369),
(169, 1, \'\', 369),
(170, 156, \'#FFFFFF\', 23);',
            'CREATE TABLE IF NOT EXISTS `' . MAIN_DB_PREFIX . 'Synopsis_Process_group_rights` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `process_refid` int(11) DEFAULT NULL,
  `group_refid` int(11) DEFAULT NULL,
  `right_refid` int(11) DEFAULT NULL,
  `valeur` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=38 ;',
            'CREATE TABLE IF NOT EXISTS `' . MAIN_DB_PREFIX . 'Synopsis_Process_rights` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `process_refid` int(11) DEFAULT NULL,
  `user_refid` int(11) DEFAULT NULL,
  `right_refid` int(11) DEFAULT NULL,
  `valeur` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=7 ;',
            'INSERT IGNORE INTO `' . MAIN_DB_PREFIX . 'Synopsis_Process_rights` (`id`, `process_refid`, `user_refid`, `right_refid`, `valeur`) VALUES
(6, 1, 1, 1, 1);',
            'CREATE TABLE IF NOT EXISTS `' . MAIN_DB_PREFIX . 'Synopsis_Process_rights_def` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `label` varchar(50) DEFAULT NULL,
  `description` longtext,
  `dflt` int(11) DEFAULT \'0\',
  `code` varchar(50) DEFAULT NULL,
  `rang` int(11) DEFAULT NULL,
  `active` int(11) DEFAULT \'0\',
  `isValidationRight` tinyint(4) DEFAULT NULL,
  `isValidationForAll` tinyint(4) DEFAULT \'0\',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=8 ;',
            'INSERT IGNORE INTO `' . MAIN_DB_PREFIX . 'Synopsis_Process_rights_def` (`id`, `label`, `description`, `dflt`, `code`, `rang`, `active`, `isValidationRight`, `isValidationForAll`) VALUES
(1, \'Voir\', \'Voir le process\', 1, \'voir\', 1, 1, NULL, 0),
(2, \'Modifer\', \'Modifier le process\', 0, \'modifier\', 2, 1, NULL, 0),
(3, \'Valider\', \'Valider le process\', 0, \'valider\', 3, 1, 1, 1),
(4, \'Valider(Tech)\', \'Valider le process (Technicien)\', 0, \'validerTech\', 4, 1, 1, 0),
(5, \'Valider(Dir)\', \'Valider le process (Direction)\', 0, \'validerDir\', 5, 1, 1, 0),
(6, \'Valider(Com)\', \'Valider le process (Commercial)\', 0, \'validerCom\', 6, 1, 1, 0),
(7, \'Supprimer\', \'Supprimer le process\', 0, \'supprimer\', 7, 1, NULL, 0);',
            'CREATE TABLE IF NOT EXISTS `' . MAIN_DB_PREFIX . 'Synopsis_Process_type_element` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `label` varchar(50) DEFAULT NULL,
  `type` varchar(50) DEFAULT NULL,
  `rang` int(11) DEFAULT NULL,
  `ficheUrl` text,
  `_GET_id` varchar(50) DEFAULT NULL,
  `classFile` longtext,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=21 ;',
            'INSERT IGNORE INTO `' . MAIN_DB_PREFIX . 'Synopsis_Process_type_element` (`id`, `label`, `type`, `rang`, `ficheUrl`, `_GET_id`, `classFile`) VALUES
(1, \'Propale\', \'Propal\', 1, \'/comm/propal.php\', \'propalid\', \'/comm/propal/class/propal.class.php\'),
(2, \'Commande\', \'Commande\', 2, \'/commande/card.php\', \'id\', \'/commande/class/commande.class.php\'),
(3, \'Facture\', \'Facture\', 3, \'/compta/facture.php\', \'facid\', \'/compta/facture/class/facture.class.php\'),
(4, \'Exp&eacute;dition\', \'Expedition\', 4, \'/expedition/card.php\', \'id\', \'/expedition/class/expedition.class.php\'),
(5, \'Action co.\', \'ActionComm\', 5, \'/comm/action/card.php\', \'id\', \'/actioncomm.class.php\'),
(6, \'Affaire\', \'Affaire\', 6, \'/Synopsis_Affaire/card.php\', \'id\', \'/Synopsis_Affaire/Affaire.class.php\'),
(7, \'Facture fournisseur\', \'FactureFournisseur\', 7, \'/fourn/facture/card.php\', \'facid\', \'/fourn/class/fournisseur.facture.class.php\'),
(8, \'Commande fournisseur\', \'CommandeFournisseur\', 8, \'/fourn/commande/card.php\', \'id\', \'/fourn/class/fournisseur.commande.class.php\'),
(9, \'Contrat\', \'Contrat\', 9, \'/contrat/card.php\', \'id\', \'/contrat/class/contrat.class.php\'),
(10, \'Campagne\', \'Campagne\', 10, \'/BabelProspect/affichePropection.php\', \'action=list&campagneId=\', \'/BabelProspect/Campagne.class.php\'),
(11, \'Chrono\', \'Chrono\', 11, \'/synopsischrono/card.php\', \'id\', \'/synopsischrono/class/chrono.class.php\'),
(12, \'Tiers\', \'Societe\', 12, \'/soc.php\', \'socid\', \'/societe.class.php\'),
(13, \'Contact\', \'Contact\', 13, \'/contact/card.php\', \'id\', \'/contact.class.php\'),
(14, \'Demande intervention\', \'synopsisdemandeinterv\', 14, \'/synopsisdemandeinterv/card.php\', \'id\', \'/synopsisdemandeinterv/class/synopsisdemandeinterv.class.php\'),
(15, \'Fiche intervention\', \'Fichinter\', 15, \'/fichinter/card.php\', \'id\', \'/fichinter/class/fichinter.class.php\'),
(16, \'Livraison\', \'Livraison\', 16, \'/livraison/card.php\', \'id\', \'/livraison/class/livraison.class.php\'),
(17, \'Paiement\', \'Paiement\', 17, \'/compta/paiement/card.php\', \'id\', \'/paiement.class.php\'),
(18, \'Paiement fournisseur\', \'PaiementFourn\', 18, \'/fourn/paiement/card.php\', \'id\', \'/fourn/facture/paiementfourn.class.php\'),
(19, \'Product\', \'Product\', 19, \'/product/card.php\', \'id\', \'/product/class/product.class.php\'),
(20, \'Projet\', \'Project\', 20, \'/projet/card.php\', \'id\', \'/projet/class/project.class.php\');',
            'CREATE TABLE IF NOT EXISTS `' . MAIN_DB_PREFIX . 'Synopsis_Process_type_element_trigger` (
  `element_refid` int(11) DEFAULT NULL,
  `trigger_refid` int(11) DEFAULT NULL,
  UNIQUE KEY `uniq_process_type_element_trigger` (`element_refid`,`trigger_refid`),
  KEY `trigger_refid` (`trigger_refid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;',
            'INSERT IGNORE INTO `' . MAIN_DB_PREFIX . 'Synopsis_Process_type_element_trigger` (`element_refid`, `trigger_refid`) VALUES
(1, 47),
(1, 48),
(1, 49),
(1, 50),
(1, 51),
(1, 52),
(1, 68),
(2, 36),
(2, 37),
(2, 38),
(2, 41),
(3, 2),
(3, 3),
(3, 4),
(3, 5),
(3, 6),
(3, 7),
(3, 8),
(3, 10),
(3, 64),
(4, 69),
(4, 70),
(4, 71),
(4, 73),
(4, 74),
(5, 1),
(5, 61),
(5, 62),
(6, 63),
(7, 9),
(8, 39),
(8, 40),
(8, 113),
(8, 114),
(8, 115),
(8, 116),
(8, 117),
(8, 118),
(8, 191),
(8, 192),
(9, 17),
(9, 18),
(9, 19),
(9, 20),
(9, 21),
(9, 22),
(9, 23),
(9, 65),
(9, 66),
(9, 67),
(9, 111),
(9, 112),
(10, 96),
(10, 97),
(10, 98),
(10, 99),
(10, 100),
(10, 101),
(10, 102),
(10, 103),
(11, 107),
(11, 108),
(11, 109),
(11, 209),
(12, 11),
(12, 12),
(12, 13),
(13, 14),
(13, 15),
(13, 16),
(14, 89),
(14, 90),
(14, 91),
(14, 92),
(14, 93),
(14, 94),
(14, 95),
(14, 119),
(14, 120),
(14, 121),
(14, 122),
(14, 123),
(14, 124),
(14, 125),
(15, 24),
(15, 86),
(15, 87),
(15, 88),
(15, 181),
(15, 182),
(15, 183),
(15, 184),
(15, 185),
(15, 186),
(15, 187),
(16, 72),
(16, 75),
(16, 76),
(17, 42),
(18, 43),
(19, 44),
(19, 45),
(19, 46),
(20, 77),
(20, 78),
(20, 79),
(20, 80),
(20, 81),
(20, 82),
(20, 83),
(20, 84),
(20, 85),
(20, 193),
(20, 194),
(20, 195);',
            'CREATE TABLE IF NOT EXISTS `' . MAIN_DB_PREFIX . 'Synopsis_revision_model` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nom` varchar(50) DEFAULT NULL,
  `description` longtext,
  `phpClass` varchar(150) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=3 ;',
            "INSERT IGNORE INTO `" . MAIN_DB_PREFIX . "Synopsis_revision_model` (`id`, `nom`, `description`, `phpClass`) VALUES
(1, 'Aligote', 'Révision numérique sur 4 chiffres', 'revision_aligote'),
(2, 'Merlot', 'Révision alphabétique', 'revision_merlot');",
            "CREATE TABLE IF NOT EXISTS `" . MAIN_DB_PREFIX . "Synopsis_Process_lien` (
  `rowid` int(11) NOT NULL,
  `label` varchar(50) NOT NULL,
  `description` varchar(500) NOT NULL,
  `table` varchar(30) NOT NULL,
  `nomElem` varchar(30) NOT NULL,
  `where` varchar(80) NOT NULL,
  `ordre` tinyint(4) NOT NULL,
  `champId` varchar(30) NOT NULL,
  `champVueSelect` varchar(100) NOT NULL,
  `sqlFiltreSoc` varchar(100) NOT NULL,
  `urlObj` varchar(150) NOT NULL,
  `hasMultiValue` tinyint(4) NOT NULL,
  PRIMARY KEY (`rowid`));",
            "INSERT IGNORE INTO `".MAIN_DB_PREFIX."Synopsis_Process_lien` (`rowid`, `label`, `description`, `table`, `nomElem`, `where`, `ordre`, `champId`, `champVueSelect`, `sqlFiltreSoc`, `urlObj`, `hasMultiValue`) VALUES
(1, 'ContratLigne (N)', '', '".MAIN_DB_PREFIX."contratdet', 'contratdet', '', 1, 'rowid', 'description', 'fk_contrat IN (SELECT `rowid` FROM `".MAIN_DB_PREFIX."contrat` WHERE `fk_soc` = [id])', 'Synopsis_Contrat/contratDetail.php?id=', 1),
(2, 'Appel', '', '".MAIN_DB_PREFIX."synopsischrono', 'appel', 'model_refid = 100', 1, 'id', 'concat(ref,if(description != \"\", concat(\" \", description), \"\"))', 'fk_soc = [id]', 'synopsischrono/card.php?id=', 1),
(3, 'ProduitCli', '', '".MAIN_DB_PREFIX."synopsischrono', 'productCli', 'model_refid = 101', 0, 'id', 'concat(ref,if(description != \"\", concat(\" \", description), \"\"))', 'fk_soc = [id]', 'synopsischrono/card.php?id=', 1),
(4, 'Licence', '', '".MAIN_DB_PREFIX."synopsischrono', 'licence', 'model_refid = 102', 1, 'id', 'concat(ref,if(description != \"\", concat(\" \", description), \"\"))', '', 'synopsischrono/card.php?id=', 1),
(5, 'Compte Utilisateur', '', '".MAIN_DB_PREFIX."synopsischrono', 'compteUser', 'model_refid = 103', 1, 'id', 'concat(ref,if(description != \"\", concat(\" \", description), \"\"))', 'fk_soc = [id]', 'synopsischrono/card.php?id=', 1),
(6, 'Site', '', '".MAIN_DB_PREFIX."synopsischrono', 'site', 'model_refid = 104', 1, 'id', 'concat(ref,if(description != \"\", concat(\" \", description), \"\"))', 'fk_soc = [id]', 'synopsischrono/card.php?id=', 0);");
        $retour = $this->_init($sql);

        include_once(DOL_DOCUMENT_ROOT."/Synopsis_Process/class/process.class.php");
        process::majTabsProcess($this->db);

        return $retour;
    }

    /**
     *    \brief      Fonction appelee lors de la desactivation d'un module.
     *                Supprime de la base les constantes, boites et permissions du module.
     */
    function remove() {
//        $sql = array('DROP TABLE ' . MAIN_DB_PREFIX . 'Synopsis_Process, ' . MAIN_DB_PREFIX . 'Synopsis_Process_form, ' . MAIN_DB_PREFIX . 'Synopsis_Process_form_fct, ' . MAIN_DB_PREFIX . 'Synopsis_Process_form_global, ' . MAIN_DB_PREFIX . 'Synopsis_Process_form_list, ' . MAIN_DB_PREFIX . 'Synopsis_Process_form_list_members, ' . MAIN_DB_PREFIX . 'Synopsis_Process_form_model, ' . MAIN_DB_PREFIX . 'Synopsis_Process_form_requete, ' . MAIN_DB_PREFIX . 'Synopsis_Process_form_src, ' . MAIN_DB_PREFIX . 'Synopsis_Process_form_type, ' . MAIN_DB_PREFIX . 'Synopsis_Process_form_type_class_value, ' . MAIN_DB_PREFIX . 'Synopsis_Process_form_type_prop, ' . MAIN_DB_PREFIX . 'Synopsis_Process_form_type_prop_value, ' . MAIN_DB_PREFIX . 'Synopsis_Process_form_type_style, ' . MAIN_DB_PREFIX . 'Synopsis_Process_form_type_style_value, ' . MAIN_DB_PREFIX . 'Synopsis_Process_rights, ' . MAIN_DB_PREFIX . 'Synopsis_Process_rights_def, ' . MAIN_DB_PREFIX . 'Synopsis_Process_type_element, ' . MAIN_DB_PREFIX . 'Synopsis_Process_type_element_trigger, '. MAIN_DB_PREFIX . 'Synopsis_revision_model, '. MAIN_DB_PREFIX .'Synopsis_trigger');
        $sql = array();
        include_once(DOL_DOCUMENT_ROOT."/Synopsis_Process/class/process.class.php");
        process::deleteTabsProcess($this->db);

        return $this->_remove($sql);
    }

}

?>