table: bmp_event_montant
common_fields: 0

parent_object: BMP_Event
parent_id_property: id_event

labels:
    name: montant
    
objects: 
    category: 
        relation: hasOne
        delete: 0
        instance: 
            bimp_object: BMP_CategorieMontant
            id_object: 
                field_value: id_category_montant
    
    type_montant:
        relation: hasOne
        delete: 0
        instance: 
            bimp_object: BMP_TypeMontant
            id_object: 
                field_value: id_montant
                
    details: 
        relation: hasMany
        delete: 1
        instance:
            bimp_object: BMP_EventMontantDetail
            
fields: 
    id_event: 
        label: Evénement
        type: id_parent
        input: 
            type: hidden
    id_coprod:
        show:
            callback: 
                method: showCoprods
                object: 
                    callback: getParentInstance
        label: Payé/reçu par
        type: int
        default_value: 0
        values: 
            array: coprods
    id_category_montant: 
        label: Catégorie
        type: id_object
        object: category
        values: 
            array: categoriesBMP
        display: 
            default: 
                type: callback
                method: displayCategory
        search: 
            input: 
                type: select
                options:  
                    array: allCategories
        sort_options:
            default:
                label: Position
                join_field: position
        next_sort_field: id_montant
        depends_on: type,id_coprod
    id_montant:
        label: Type montant
        type: id_object
        object: type_montant
        values: 
            array: allTypes
        input: 
            type: select
            options: 
                array: types_montants
        display:
            type: nom
        search: 
            input: 
                type: select
                options:  
                    array: allTypes
        depends_on: id_category_montant,type,id_coprod
        display_if:
            field_name: id_category_montant
            hide_values: 0,
        sort_options:
            default:
                label: Nom
                join_field: name
    amount: 
        label: Montant HT
        type: money
        search:
            type: value_part
            part_type: beginning
            search_on_key_up: 1
        display_if: 
            field_name: has_details
            show_values: 0
    tva_tx:
        label: Tx TVA
        type: percent
        default_value: 0
    status:
        label: Statut
        type: int
        values:
            array: status_list
        default_value: 1
        display: 
            default: 
                type: array_value
            icon:
                type: array_value
                icon_only: 1
    type: 
        label: Type
        type: int
        values: 
            prop: 
                object: type_montant
                name: types
                is_static: 1
        input: 
            type: hidden
    comment: 
        label: Commentaire
        type: text
        input: 
            auto_expand: 1
            rows: 1
        searchable: 0   
    paiements: 
        label: Paiements
        type: json
        input: 
            type: hidden
     
forms: 
    default: 
        rows: 
            - field: type
            - field: id_coprod
            - field: id_category_montant
            - field: id_montant
            - custom: 1
              hidden: 1
              input_name: has_details
              data_type: bool
              input: 
                  type: hidden
              value: 
                  callback: hasDetails
              depends_on: id_montant
            - field: amount
            - field: status
            - field: comment
            - object: details
              multiple: 1
              display_if: 
                  field_name: has_details
                  show_values: 1
    edit: 
        rows: 
            - field: amount
            - field: tva_tx
            - field: status
            - field: comment
            
    paiement: 
        rows: 
            - field: id_event
            - field: type
            - field: id_coprod
              label: Payé/reçu intialement par
            - custom: 1
              label: Catégorie
              input_name: id_category_montant
              data_type: int
              input: 
                  type: select
                  options: 
                      array: paiementCategories
              depends_on: id_event,type,id_coprod
            - custom: 1
              label: Type de montant
              input_name: id_montant
              data_type: int
              input: 
                  type: select
                  options: 
                      array: paiementTypesMontants
              depends_on: id_event,type,id_coprod,id_category_montant
              display_if: 
                  field_name: id_category_montant
                  hide_values: 0,
            - custom: 1
              label: Paiements / Reçus
              input_name: paiements
              content: 
                  callback: renderPaiementInputs
              display_if: 
                  field_name: id_montant
                  hide_values: 0,
              depends_on: id_event,id_coprod,id_montant
              
    paiement_montant: 
        rows: 
            - field: id_event
            - field: type
            - field: id_coprod
              edit: 0
            - field: id_category_montant
              edit: 0
            - field: id_montant
              edit: 0
            - custom: 1
              label: Paiements / Reçus
              input_name: paiements
              content: 
                  callback: renderPaiementInputs
              
lists:
    default: 
        title: Montants
        checkboxes: 
            callback: isEventEditable
        objects_change_reload: BMP_EventMontantDetail,BMP_EventBillets
        row_style: 
            callback: renderListRowStyle
        bulk_actions:
            - label: supprimer les lignes sélectionnées
              icon: fas_trash-alt
              onclick: deleteSelectedObjects('list_id', $(this))
            - label: Confirmé
              icon: check-circle
              onclick: setSelectedObjectsNewStatus($(this), 'list_id', 2)
            - label: Optionnel
              icon: question-circle
              onclick: setSelectedObjectsNewStatus($(this), 'list_id', 3)
        sort_field: id_category_montant
        sort_way: asc
        n: 0
        update_btn: 1
        edit_btn: 1
        edit_form: edit
        add_form_name: 
            callback: getCreateForm
        delete_btn: 
            callback: isDeletable
        cols: 
            category:
                field: id_category_montant
            type: 
                field: id_montant
            coprod: 
                label: Payé par
                value: 
                    callback: displayPaidBy
                show:
                    callback: 
                        method: showCoprods
                        object: 
                            callback: getParentInstance
            amount: 
                field: amount
                edit: 
                    callback: isEditable
                max_width: 120px
            taxe:
                field: tva_tx
                max_width: 40px
            status: 
                field: status
                edit: 1
                max_width: 120px
            comment: 
                field: comment
                edit: 1
        extra_cols: 
            callback: getCoProdsCols
        extra_btn:
            callback: getDefaultListExtraButtons
            
    frais: 
        extends: default
        header_buttons: 
            callback: 
                method: getDefaultListExtraHeaderBtn
                params: 
                    - 1
        add_form_values:
            fields: 
                type: 1
            
    recettes: 
        extends: default
        header_buttons: 
            callback: 
                method: getDefaultListExtraHeaderBtn
                params: 
                    - 2
        add_form_values:
            fields: 
                type: 2
        cols: 
            coprod: 
                label: Reçu par
            
    recettes_bar: 
        title: Recette du bar
        objects_change_reload: BMP_EventMontantDetail,BMP_EventBillets
        row_style: 
            callback: renderListRowStyle
        sort_field: id_montant
        sort_way: asc
        n: 0
        update_btn: 1
        cols: 
            category:
                field: id_category_montant
            type: 
                field: id_montant
            coprod: 
                label: Reçu par
                value: 
                    callback: displayPaidBy
                show:
                    callback: 
                        method: showCoprods
                        object: 
                            callback: getParentInstance
            amount: 
                field: amount
                edit: 
                    callback: isEditable
            taxe:
                label: TVA
                field: tva_tx
            status: 
                field: status
                edit: 1
            comment: 
                field: comment
                edit: 1
        extra_cols: 
            callback: getCoProdsCols
        extra_btn:
            callback: getDefaultListExtraButtons
                    
#    bilan_comptable: 
#        title: Bilan comptable Le Fil
#        checkboxes: 0
#        row_style: 
#            callback: renderListRowStyle
#        list_filters:
#            - name: id_coprod
#              filter: 0
#        sort_field: id_category_montant
#        sort_way: asc
#        n: 0
#        cols:
#            status: 
#                field: status
#                display: icon
#                max_width: 32px
#                min_width: 32px
#            category: 
#                field: id_category_montant
#            montant:
#                field: id_montant
#            code_compta: 
#                label: Code Comptable
#                value: 
#                    field_value:
#                        field_name: code_compta
#                        object: type_montant
#            taxe: 
#                label: TVA
#                field: tva_tx
#           
#            frais:
#                label: Charges HT
#                value: 
#                    callback: 
#                        method: displayPaidAmountByType
#                        params: 
#                            type: 1
#                            
#            recette:
#                label: Recettes HT
#                value: 
#                    callback: 
#                        method: displayPaidAmountByType
#                        params: 
#                            type: 2
#        extra_btn:
#            callback: 
#                method: getDefaultListExtraButtons
#                params:
#                    - 0
#                    - 1
            
views:
    details_list:
        rows:
            - cols: 
                - col_lg: 12
                  type: list
                  list:
                      title: 
                          callback: getDetailsName
                      icon: far_file-alt
                      panel: 0
                      children: details