table: bmp_event_montant
common_fields: 0

parent_object: BMP_Event
parent_id_property: id_event

labels:
    name: montant
    
objects: 
    category: 
        relation: hasOne
        delete: 0
        instance: 
            bimp_object: BMP_CategorieMontant
            id_object: 
                field_value: id_category_montant
    
    type_montant:
        relation: hasOne
        delete: 0
        instance: 
            bimp_object: BMP_TypeMontant
            id_object: 
                field_value: id_montant
                
    details: 
        relation: hasMany
        delete: 1
        instance:
            bimp_object: BMP_EventMontantDetail
            
fields: 
    id_event: 
        label: Evénement
        type: id_parent
    
    id_category_montant: 
        label: Catégorie
        type: id_object
        object: category
        values: 
            array: categories
        display: 
            type: nom
        sortable: 1
        search: 1
            
    id_montant:
        label: Type montant
        type: id_object
        object: type_montant
        values: 
            array: types_montants
        display:
            type: nom
        sortable: 1
        search: 
            input: 
                type: select
                options:  
                    array: allTypes
        depends_on: id_category_montant,type
        input:
            display_if:
                input_name: id_category_montant
                hide_values: 0,
                
    amount: 
        label: Montant HT
        type: money
        sortable: 1
        search:
            type: value_part
            part_type: beginning
            search_on_key_up: 1
        
    status:
        label: Statut
        type: int
        values:
            array: status
        default_value: 1
        sortable: 1
        search: 1
            
    type: 
        label: Type
        type: int
        values: 
            prop: 
                object: type_montant
                name: types
                is_static: 1
        input: 
            type: hidden
            
    comment: 
        label: Commentaire
        type: text
        input: 
            auto_expand: 1
            rows: 1
            
list:
    title: Montants
    checkboxes: 1
    item_checkbox: 
        callback: isDeletable
    objects_change_reload: BMP_EventMontantDetail
    bulk_actions:
        - label: supprimer les lignes sélectionnées
          icon: trash
          onclick: deleteSelectedObjects('list_id', $(this))
    sort_col: id
    sort_way: desc
    n: 25
    update_btn: 1
    add_form: default
    delete_btn: 
        callback: isDeletable
    cols: 
        category:
            field: id_category_montant
        type: 
            field: id_montant
        amount: 
            field: amount
            edit: 
                callback: isEditable
        taxe:
            label: TVA
            value: 
                callback: getTva
        status: 
            field: status
            edit: 1
        comment: 
            field: comment
            edit: 1
    extra_cols: 
        callback: getCoProdsCols
    extra_buttons:
        callback: getDefaultListExtraButtons
            
views:
    details_list:
        rows:
            - cols: 
                - col_lg: 12
                  type: list
                  list:
                      title: 
                          callback: getDetailsName
                      icon: file-text-o
                      panel: 0
                      children: details