table: bmp_event
controller: event

labels: 
    name: événement

objects:
    tarifs: 
        relation: hasMany
        delete: 1
        instance:
            bimp_object: BMP_Tarif
            
    coprods: 
        relation: hasMany
        delete: 1
        instance: 
            bimp_object: BMP_EventCoProd
    
    coprod_def_parts:
        realtion: hasMany
        delete: 1
        instance: 
            bimp_object: BMP_EventCoProdDefPart
            
    frais: 
        relation: hasMany
        delete: 1
        instance: 
            bimp_object: BMP_EventMontant
        list: 
            title: Frais
            filters: 
                type: 1
            
    recettes: 
        relation: hasMany
        delete: 1
        instance: 
            bimp_object: BMP_EventMontant
        list: 
            title: Recettes
            filters: 
                type: 2
            
associations:
    
fields: 
    name: 
        label: Nom
        
    date_begin:
        label: Du
        type: datetime
        required: 1
        sortable: 1
        search: 1
        
    date_end: 
        label: Au
        type: datetime
        required: 1
        sortable: 1
        search: 1
    
lists:
    default: 
        checkboxes: 1
        bulk_actions:
            - label: supprimer les événements sélectionnées
              icon: trash
              onclick: deleteSelectedObjects('list_id', $(this))
        sort_col: date_begin
        sort_way: desc
        n: 10
        add_form: default
        delete_btn: 1
        view_btn: 1
        cols:
            begin:
                field: date_begin
            end: 
                field: date_end
            name: 
                field: name
                
views:
    default:
        title: nom
        edit_form: default
        delete_btn: 1
        rows:
            - cols: 
                - type: object_common_fields
                  col_lg: 6    
                  col_md: 6
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  fields_table: 
                      caption: 
                          label: Infos événement
                          icon: info-circle
                      rows:
                        - field: date_begin
                        - field: date_end
                
            - cols:
                - type: list
                  col_lg: 6
                  col_md: 6
                  list: 
                      children: tarifs
                      panel: 0
                      
                - type: list
                  col_lg: 6
                  col_md: 6
                  list: 
                      children: coprods
                      panel: 0
                  
    frais_totaux:
        title: Montants totaux
        icon: euro
        rows:
            - cols: 
                - type: custom
                  custom: 
                      callback: 
                          method: renderMontantsTotaux
                          params: 
                              type: 1
                              
    recettes_totaux:
        title: Montants totaux
        icon: euro
        rows:
            - cols: 
                - type: custom
                  custom: 
                      callback: 
                          method: renderMontantsTotaux
                          params: 
                              type: 2