table: bmp_event
controller: event
icon: far_calendar-alt

header_list_name: default

list_page_url: 
    controller: index
    url_params: 
        tab: default

labels: 
    name: événement

objects:
    groups: 
        relation: hasMany
        delete: 1
        instance: 
            bimp_object: BMP_EventGroup
            
    tarifs: 
        relation: hasMany
        delete: 1
        instance:
            bimp_object: BMP_EventTarif
            
    coprods: 
        relation: hasMany
        delete: 1
        instance: 
            bimp_object: BMP_EventCoProd
    
    coprod_def_parts:
        realtion: hasMany
        delete: 1
        instance: 
            bimp_object: BMP_EventCoProdDefPart
            
    montants: 
        relation: hasMany
        delete: 1
        instance: 
            bimp_object: BMP_EventMontant
            
    frais: 
        relation: hasMany
        delete: 0
        instance: 
            bimp_object: BMP_EventMontant
        list: 
            title: Charges
            filters: 
                type: 1
            
    recettes: 
        relation: hasMany
        delete: 0
        instance: 
            bimp_object: BMP_EventMontant
        list: 
            title: Recettes
            filters: 
                type: 2
    
    recettes_bar: 
        relation: none
        delete: 0
        instance:
            bimp_object: BMP_EventMontant
        list: 
            title: Recettes du bar
            filters: 
                type: 2
                id_category_montant:
                    prop: 
                        name: id_bar_category
                        is_static: 1
    
    billets:
        relation: hasMany
        delete: 1
        instance: 
            bimp_object: BMP_EventBillets
            
    calcs_montants:
        relation: hasMany
        delete: 1
        instance: 
            bimp_object: BMP_EventCalcMontant       
    
fields: 
    name: 
        label: Nom
        search: 
            type: value_part
            search_on_key_up: 1range
        required: 1
        
    date:
        label: Date
        type: datetime
        required: 1
            
    type: 
        label: Type
        type: int
        values: 
            array: types
        
    place: 
        label: Lieu
        type: int
        values: 
            array: places
            
    status: 
        label: Statut
        type: int
        values: 
            array: status
        default_value: 1
            
    tva_billets:
        label: Taux de TVA pour la vente de billets
        type: int
        values: 
            array: 
                1: 2,1%
                2: 5,5%
        default_value: 1
    
    ca_moyen_bar:
        label: CA moyen bar TTC
        type: money
        default_value: 0
        
    analytics: 
        label: Analytics
        values: 
            array: analytics
    
    frais_billet: 
        label: Frais d'édition d'un billet (HT)
        type: money
        default_value: 0
        
    default_dl_dist: 
        label: droits de location distributeur par défaut (TTC)
        type: money
        default_value: 0
    
    default_dl_prod: 
        label: droits de location producteur par défaut (TTC)
        type: money
        default_value: 0
        
    bar_20_save: 
        label: bar_20_save
        type: money
        default_value: 0
        
    bar_55_save: 
        label: bar_55_save
        type: money
        default_value: 0
        
    billets_loc: 
        label: Nombre de spectateurs locataires
        type: int
        min: 0
        default_value: 0
        
forms: 
    default: 
        rows: 
            - field: name
            - field: date
            - field: type
            - field: place
            - field: tva_billets
            - field: ca_moyen_bar
            - field: analytics
            - custom: 1
              show: 
                  callback: isNotLoaded
              label: Tarifs prédéfinis à insérer
              input_name: tarifs
              input: 
                  type: check_list
                  items: 
                      callback: getPredefTarifsArray
              value: 
                  callback: getDefaultTarifsValue
                  
filters_panels: 
    default: 
        filters: 
            - field: date
            - field: name
            - field: status
            - field: type
            - field: place
            - field: analytics
            
lists:
    default: 
        filters_panel: default
        checkboxes: 1
        bulk_actions:
            - label: supprimer les événements sélectionnés
              icon: fas_trash-alt
              onclick: deleteSelectedObjects('list_id', $(this))
        sort_field: date
        sort_way: desc
        n: 10
        add_form_name: default
        delete_btn: 1
        page_btn: 1
        edit_btn: 1
        cols:
            date:
                field: date
            name: 
                field: name
            type: 
                field: type
            place: 
                field: place
            status: 
                field: status
                
list_customs: 
    marge_prod: 
        title: Marge de production
        icon: fas_chart-line
        content_callback: renderEventsBilanComptable
        filters_panel: default
        filters_panel_open: 1
        n: 100
        sort_field: date
        sort_way: asc     
        
    synthese_events: 
        title: Synthèse événements
        icon: fas_chart-line
        content_callback: renderSyntheseEvents
        filters_panel: default
        filters_panel_open: 1
        n: 100
        sort_field: date
        sort_way: asc
             
fields_tables: 
    infos: 
        title: Infos événement
        icon: info-circle
        rows:
          - field: date
          - field: type
          - field: place
          - field: analytics
          - field: status
            edit: 1
          - field: tva_billets
            edit: 1
          - field: frais_billet
            edit: 1
          - field: ca_moyen_bar
            edit: 1
          - field: default_dl_dist
            edit: 1
          - field: default_dl_prod
            edit: 1
          
    billets_options: 
        title: Paramètres billetterie
        icon: cog
        rows: 
            - field: tva_billets
              edit: 1
            - field: frais_billet
              edit: 1
            - field: default_dl_dist
              edit: 1
            - field: default_dl_prod
              edit: 1
            - field: billets_loc
              edit: 1
              
    ca_bar:
        title: Prévisionnel bar
        icon: beer
        rows: 
            - field: ca_moyen_bar
              edit: 1
              
views:
    default:
        title: nom
        edit_form: default
        delete_btn: 1
        rows:
            - cols: 
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  fields_table: 
                      name: infos
                - type: list
                  show: 
                      callback: showCoprods
                  col_lg: 6
                  col_md: 6
                  list: 
                      children: coprods
                      panel: 0
                  
            - cols:
                - type: list
                  col_lg: 6
                  col_md: 6
                  list: 
                      children: groups
                      panel: 0
                - type: list
                  show: 
                      callback: showCoprods
                  col_lg: 6
                  col_md: 6
                  list: 
                      children: coprod_def_parts
        
    frais_recap: 
        objects_change_reload: BMP_EventMontant,BMP_EventMontantDetail
        panel: 0
        rows: 
            - cols: 
                - type: custom
                  custom: 
                      callback: 
                          method: renderMontantsRecap
                          params: 
                              - 1
                              
    recettes_recap: 
        objects_change_reload: BMP_EventMontant,BMP_EventMontantDetail
        panel: 0
        rows: 
            - cols: 
                - type: custom
                  custom: 
                      callback: 
                          method: renderMontantsRecap
                          params: 
                              - 2
        
#    billets:
#        title: Billetterie
#        rows:                
#            - cols:
#                - type: list
#                  col_lg: 12
#                  list: 
#                      title: Tarifs
#                      children: tarifs
#                      panel: 0
#                      
#                - type: list
#                  col_lg: 12
#                  list: 
#                      title: Vente de billets
#                      children: billets
#                      panel: 0
#            - cols: 
#                - type: view
#                  col_lg: 7
#                  col_md: 8
#                  col_sm: 12
#                  view: 
#                      name: total_billets
                    
    total_billets: 
        title: 
            callback: getTotalBilletsTitle
        icon: euro
        objects_change_reload: BMP_EventTarif,BMP_EventBillets
        rows: 
            - cols: 
                - type: custom
                  custom: 
                      callback: renderTotalBillets
                      
    breaks:
#        title: Calculs du break
#        icon: pie-chart
        panel: 0
        objects_change_reload: BMP_EventTarif,BMP_EventBillets
        rows:
            - cols:
                - type: fields_table
                  show: 
                      callback: isInPrevisionnelMode
                  col_lg: 6
                  col_md: 6
                  fields_table:
                      name: ca_bar
                - type: custom
                  col_lg: 6
                  col_md: 6
                  custom: 
                      callback: renderPrevisionnelBreaks
                
    billets_list:
        rows: 
            - cols:
                - type: list
                  col_lg: 12
                  list:
                      title: Détails des ventes par vendeur
                      children: billets
                      panel: 0
                    
    tarifs: 
        panel: 0
        rows: 
            - cols: 
                - type: list
                  col_lg: 6
                  col_md: 6
                  list: 
                      children: tarifs
                      
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  fields_table: 
                      name: billets_options
                      
    totaux:
        title: Montants HT totaux
        objects_change_reload: BMP_EventMontant,BMP_EventTarif,BMP_EventBillets
        icon: euro
        rows:
            - cols: 
                - type: custom
                  custom: 
                      callback: renderMontantsTotaux
            
    frais_hotel:
        title: Détail des frais d'hôtellerie
        icon: euro
        rows:
            - cols:
                - type: custom
                  custom: 
                      callback:
                          method: renderFraisHotel
                          
    bilans: 
        title: Bilans
        icon: bars
        rows: 
            - cols:
                - type: nav_tabs
                  nav_tabs: 
                      - id: totaux
                        title: Totaux
                        struct: 
                            type: view
                            view: 
                                panel: 0
                                name: totaux
                      - id: general
                        title: Récapitulatif général
                        struct: 
                            type: custom
                            custom: 
                                callback: renderMontantsRecap
                                panel: 0
                      - id: comptable
                        title: Bilans comptables
                        struct: 
                            type: custom
                            custom: 
                                callback: renderEventBilansComptables
                 
#    bilan_comptable:
#        rows: 
#            - cols: 
#                - type: list
#                  list: 
#                      name: bilan_comptable
#                      children: montants
#                      panel: 0
#                - type: custom
#                  custom:
#                      callback:
#                          method: renderSoldes
