bootstrap: 1

objects: 
    productservices: 
        instance: 
            bimp_object: BContract_Productservices
                
                
sections:
    - type: tabs
      tabs: 
        default:
            label: Services
            sections:
                - type: list
                  list: 
                      panel: 1
                      object: productservices