

# ***** Définitions *****

#input_def:
type: string
help: string
options: array
display_if:
    input_name: string
    show_values: array
    hide_values: array

#display_def:
type: string
format: string
values: array
    
#sort_option_def
label: string
value: 
    join:
        table: string
        field_value: string
        field_on: string
            
#button_def
label: string
icon_before: string
icon_after: string
onclick: string;
classes: array
data: array
tag: string