table: 
primary: 
controller: 

parent_id_property: 
parent_object: 

labels: 
    name: 
    name_plur: 
    isFemale: 

objects:
    nom_objet:
        relation: 
        delete: 
        instance:
                
associations:
    nom_asso:
        object: 
        table: 
        display:   
                
fields: 
    nom_champ:
        label: 
        type: 
        required: 
        default_value:
        input:
            type:
        display:
            type:        
        search: 
        sortable:
        sort_options:

views:
    nom_vue:
        title:
        edit_btn:
        delete_btn:
        rows:
            - cols: 
                  - type:
                    col_lg:
                    col_md:
                    col_sm:
                    col_xs:
lists:
    nom_list:
        checkboxes: 
        title: 
        icon: 
        bulk_actions: 
        sort_col: 
        sort_way: 
        n: 
        cols:
            col_name:
                label: 
                value: 
                field: 
                edit: 
                display: 
        add_btn: 
        edit_btn: 
        update_btn: 
        delete_btn: 
        view_btn: 
            
forms:
    nom_form:
        - field:
        - field:
          label:
          input: