CREATE TABLE IF NOT EXISTS `llx_bimpcore_signature` (
  `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `obj_module` varchar(255) NOT NULL DEFAULT '',
  `obj_name` varchar(255) NOT NULL DEFAULT '',
  `id_obj` int(11) NOT NULL DEFAULT 0,
  `doc_type` varchar(255) NOT NULL DEFAULT '',
  `type` int(11) NOT NULL DEFAULT 0,
  `signed` tinyint(1) NOT NULL DEFAULT 0,
  `date_open` date DEFAULT NULL,
  `date_signed` datetime DEFAULT NULL,
  `id_client` int(11) NOT NULL DEFAULT 0,
  `id_contact` int(11) NOT NULL DEFAULT 0,
  `id_user_client_signataire` int(11) NOT NULL DEFAULT 0,
  `allowed_users_client` TEXT NOT NULL,
  `nom_signataire` varchar(255) NOT NULL DEFAULT '',
  `email_signataire` varchar(255) NOT NULL DEFAULT '',
  `fonction_signataire` varchar(255) NOT NULL DEFAULT '',
  `ip_signataire` varchar(255) NOT NULL DEFAULT '',
  `base_64_signature` mediumtext DEFAULT NULL,
  `allow_elec` tinyint(1) NOT NULL DEFAULT 1,
  `allow_dist` tinyint(1) NOT NULL DEFAULT 1
);