table: bf_demande
controller: demande

icon: fas_hand-holding-usd
header_list_name: default
list_page_url: 
    controller: index
        
labels:
    name: demande de financement
    name_plur: demandes de financement
    is_female: 1

objects:
    commande:
        relation: hasOne
        delete: 0
        instance:
            bimp_object:
                module: bimpcommercial
                name: Bimp_Commande

    reference:
        relation: hasOne
        delete: 0
        instance:
            bimp_object:
                module: bimpfinancement
                name: Bimp_Demande

    contrat:
        relation: hasOne
        delete: 0
        instance:
            dol_object: contrat
            id_object:
                field_value: id_contrat

    facture:
        relation: hasOne
        delete: 0
        instance: 
            dol_object: facture
            id_object:
                field_value: id_facture

    facture_client:
        relation: hasOne
        delete: 0
        instance:
            dol_object: facture
            id_object:
                field_value: id_facture_client

    facture_fournisseur:
        relation: hasOne
        delete: 0
        instance:
            dol_object: facture
            id_object:
                field_value: id_facture_fournisseur
        card: 
            title: 
                object_prop: ref
            view_btn: 1

    client: 
        relation: hasOne
        delete: 0
        instance: 
            bimp_object:
                module: bimpcore
                name: Bimp_Societe
            id_object: 
                field_value: id_client
                
    client_contact: 
        relation: hasOne
        delete: 0
        instance: 
            bimp_object:
                module: bimpcore
                name: Bimp_Contact
            id_object:
                field_value: id_client_contact
    
    commercial:
        relation: hasOne
        delete: 0
        instance:
            bimp_object:
                module: bimpcore
                name: Bimp_User
            id_object:
                fiels_value: id_commercial

    supplier:
        relation: hasOne
        delete: 0
        instance: 
            bimp_object: 
                module: bimpcore
                name: Bimp_Societe
            id_object:
                field_value: id_supplier
                
    supplier_contact:
        relation: hasOne
        delete: 0
        instance:
            bimp_object:
                module: bimpcore
                name: Bimp_Contact
            id_object:
                field_value: id_supplier_contact
                
    comments:
        relation: hasMany
        delete: 1
        instance:
            bimp_object: BF_Comment
            
    refinanceurs:
        relation: hasMany
        delete: 1
        instance: 
            bimp_object: BF_Refinanceur
            
    rents:
        relation: hasMany
        delete: 1
        instance:
            bimp_object: BF_Rent
            
    rents_except: 
        relation: hasMany
        delete: 1
        instance: 
            bimp_object: BF_RentExcept
            
    frais_divers:
        relation: hasMany
        delete: 1
        instance: 
            bimp_object: BF_FraisDivers
            
    frais_fournisseur:
        relation: hasMany
        delete: 1
        instance: 
            bimp_object: BF_FraisFournisseur

    files:
        instance:
            bimp_object:
                module: bimpcore
                name: BimpFile
        list: 
            filters:
                parent_module: bimpfinancement
                parent_object_name: BF_Demande
        add_form: 
            name: upload
            values:
                fields: 
                    parent_module: bimpfinancement
                    parent_object_name: BF_Demande
                    
    lines: 
        relation: hasMany
        delete: 1
        instance: 
            bimp_object: BF_Line
            
associations:
    commandes:
        object: commande
        label: Ajouter une commande liée
        display: 
            default:
                type: nom_url
        input:
            type: search_list
            search_list:
                table: commande c
                field_return_value: c.rowid
                field_return_label: c.ref
                options:
                    default:
                        label: Recherche par référence de commande
                        fields_search: c.ref,c.rowid
                        join: societe s
                        join_on: c.fk_soc = s.rowid
                        join_return_label: s.nom
                        help: Entrez la référence de la commande
                    by_client:
                        label: Recherche par client
                        fields_search: s.nom,s.code_client
                        join: societe s
                        join_on: c.fk_soc = s.rowid
                        join_return_label: s.nom
                        help: Entrez le nom ou le code d'un client

fields:
    id_client:
        label: Client
        type: id_object
        object: client
        input:
            type: search_societe
            societe_type: customer
            help: Entrez le nom ou la référence pour rechercher un client
        sort_options:
            by_ref: 
                label: référence
                value:
                    join:
                        table: societe
                        field_value: ref
                        field_on: rowid

    id_commercial:
        label: Commercial
        type: id_object
        object: commercial
        input:
            type: search_user
        default_value: 
            prop: 
                name: id
                object: 
                    global: user

    id_contrat:
        label: Contrat
        type: id_object
        object: contrat
        input: 
            type: hidden

    id_facture:
        label: Facture banque
        type: id_object
        object: facture
        input:
            type: hidden

    id_facture_client:
        label: Facture VR client
        type: id_object
        object: facture_client
        input:
            type: hidden

    id_facture_fournisseur:
        label: Facture VR fournisseur
        type: id_object
        object: facture_fournisseur
        input:
            type: hidden

    id_client_contact:
        label: Contact client
        type: id_object
        object: client_contact
        depends_on: id_client
        input: 
            type: select
            options: 
                array: client_contacts
        display_if:
            field_name: id_client
            hide_values: 0,''
                    
    duration:
        label: Durée
        type: int
        values: 
            array: durations
        
    periodicity: 
        label: Périodicité
        type: int
        values: 
            array: periodicities
        
    montant_materiels:
        label: Montant matériels
        type: money
        default_value: 0
        
    montant_services:
        label: Montant services
        type: money
        default_value: 0
                
    montant_logiciels:
        label: Montant logiciels
        type: money
        default_value: 0
    
    commission_commerciale:
        label: Commission commerciale
        type: percent
        default_value: 0
                
    commission_financiere:
        label: Commission financière
        type: percent
        default_value: 0
                
    vr: 
        label: VR achat
        type: money
        default_value: 0
        
    vr_vente: 
        label: VR vente
        type: money
        default_value: 0
                
    mode_calcul:
        label: Mode de calcul
        type: int
        default_value: 2
        values: 
            array: calc_modes
                
    status:
        label: Statut
        type: int
        values: 
            array: status_list
                
    accepted:
        label: Acceptation définitive de la banque
        type: bool
                
    insurance:
        label: Assurance
        type: bool
        default_value: 0
        
    annexe: 
        label: Annexes
        type: int
        values: 
            array: annexes
        default_value: 0
        
    ca_prevu: 
        label: CA prévu
        type: money
        required: 0
        
    pba_prevu:
        label: PBA prévu
        type: money
        required: 0
        
    date_livraison:
        label: Date de livraison
        type: date
        required: 0
        search:
            type: date_range
            
    date_loyer:
        label: Date de mise en loyer
        type: date
        required: 0
        search:
            type: date_range
        
    id_supplier:
        label: Apporteur
        type: id_object
        object: supplier
        input: 
            type: search_societe
            help: Entrez le nom ou la référence pour rechercher un tiers
        
    id_supplier_contact:
        label: Contact apporteur
        type: id_object
        object: supplier_contact
        input: 
            type: select
            options:
                array: supplier_contacts
        display_if: 
            field_name: id_supplier
            hide_values: 0,''
        depends_on: id_supplier
        
forms:
    default: 
        rows: 
            - field: id_commercial
            - field: id_client
            - field: id_client_contact
            - field: id_supplier
            - field: id_supplier_contact
            - field: duration
            - field: periodicity
            
lists:
    default:
        checkboxes: 1
        bulk_actions:
            - label: supprimer les demandes de fincancement sélectionnées
              icon: fas_trash-alt
              onclick: deleteSelectedObjects('list_id', $(this))
        sort_field: date_create
        sort_way: desc
        n: 10
        add_form_name: default
        delete_btn: 1
        page_btn: 1
        modal_view: demande
        edit_form: default
        update_btn: 1
        cols:
            id:
                label: ID
                field: id
            date_create:
                field: date_create
            client: 
                field: id_client
                display: nom_url
            duration:
                field: duration
            periodicity:
                field: periodicity
            vr:
                field: vr
            vr_vente:
                field: vr_vente
            status:
                field: status
                edit: 1
      
fields_tables:
    contrat: 
        title: Contrat
        footer_extra_btn: 
            callback: getInfosExtraBtn
        icon: fas_file-signature
        rows: 
            - field: status
              edit: 1
            - field: accepted
              edit: 1
            - field: annexe
              edit: 1
            - field: date_livraison
              edit: 1
            - field: date_loyer
              edit: 1
            - field: id_commercial
              edit: 1
            - field: id_contrat
              edit: 0
              display: nom_url
            - field: id_facture_client
              edit: 0
              display: nom_url
            - field: id_facture_fournisseur
              edit: 0
              display: nom_url
    

    options: 
        title: Options
        footer_extra_btn:
            callback: genFacture
        icon: check-square-o
        rows: 
            - field: duration
              edit: 1
            - field: periodicity
              edit: 1
            - field: insurance
              edit: 1
            - field: mode_calcul
              edit: 1 
            - field: vr
              edit: 1    
            - field: vr_vente
              edit: 1    
            - field: ca_prevu
              edit: 1
            - field: pba_prevu
              edit: 1
            - field: id_facture
              edit: 0
              display: nom_url
              
    client: 
        title: Client
        icon: user-circle
        rows: 
            - field: id_client
              label: Société
              display: card
            - field: id_client_contact
              label: Contact
              display: card
    
    apporteur: 
        title: Apporteur
        icon: handshake-o
        rows:
            - field: id_supplier
              label: Société
              display: card
            - field: id_supplier_contact
              label: Contact
              display: card
              
    montants: 
        title: Montants
        icon: euro
        rows:
            - field: montant_materiels
              edit: 1
            - field: montant_services
              edit: 1
            - field: montant_logiciels
              edit: 1
            - field: vr
              edit: 1
            - field: vr_vente
              edit: 1
            - label: Montant total
              value: <span id="montant_total"></span>
            - field: commission_commerciale
              edit: 1
            - field: commission_financiere
              edit: 1
            - label: Montant total
              value: <span id="montant_total2"></span>
            - label: Durée Calculée
              value: <span id="duree_total"></span>
            - field: duration
              label: Durée demandée
            - field: mode_calcul
            - field: periodicity
              label: Périodicité demandé
            - label: Coût banque
              value: <span id="cout_banque"></span>
            - label: Loyer Théorique
              value: <span id="loyer_the"></span>
            - label: Total loyer Calculé
              value: <span id="total_loyer"></span>
            - label: Dif financement/demande
              value: <span id="dif_banque_demande"></span>
            - label: Loyer intermediaire
              value: <span id="loy_inter"></span>
            - label: Frais Divers
              value: <span id="frais_div"></span>
            - label: Marge Calculé
              value: <span id="ca_calc"></span>
              
    montants_fournisseurs: 
        title: Montants
        icon: euro
        rows:
            - field: montant_materiels
            - field: montant_services
            - field: montant_logiciels
            - label: Reste a payé Fournisseur
              value: <span id="rest_fact"></span>
        
views:
    demande: 
        title: nom
        edit_form: default
        delete_btn: 1
        rows:
            - cols: 
                - type: rows
                  col_lg: 6
                  col_md: 6
                  rows:                        
                      - cols: 
                          - type: fields_table
                            col_lg: 12
                            fields_table: 
                                name: contrat
                                  
                          
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  fields_table:
                      name: options

            
                                      
            - cols: 
                  - type: fields_table
                    col_lg: 6
                    col_md: 6
                    col_sm: 12
                    fields_table:
                        name: client
                              
                  - type: fields_table
                    col_lg: 6
                    col_md: 6
                    col_sm: 12
                    fields_table:
                        name: apporteur
                        
            
                
            - cols: 
                  - type: custom
                    col_lg: 6
                    col_md: 6
                    custom: 
                        callback: renderViewLoadedScript
                  
    montants:
        panel: 0
        rows:
            - cols:  
                  - type: fields_table
                    col_lg: 4
                    col_md: 5
                    fields_table:
                        name: montants
                  
                  - type: rows
                    col_lg: 8
                    col_md: 7
                    rows: 
                        - cols: 
                            - type: list
                              list: 
                                  children: frais_divers
                                  panel: 0
                            - type: list
                              list: 
                                  children: rents
                                  panel: 0
                            - type: list
                              list: 
                                  children: rents_except
                                  panel: 0
                         
            - cols: 
                  - type: custom
                    custom: 
                        callback: renderViewLoadedScript

            - cols:
                  - type: list
                    col_lg: 12
                    list: 
                        children: refinanceurs
                        panel: 0
            
    
    fournisseurs:
        title: nom
        edit_form: default
        delete_btn: 1
        rows:
            - cols: 
                  - type: fields_table
                    col_lg: 3
                    col_md: 4
                    col_sm: 12
                    fields_table:
                        name: montants_fournisseurs
                        
                  - type: list
                    col_lg: 9
                    col_md: 8
                    col_sm: 12
                    list: 
                        children: frais_fournisseur
                        panel: 0
