table: bf_demande
controller: demande
icon: fas_comment-dollar
new_status_logs: 1

header_btn: 
    callback: getActionsButtons
header_list_name: default
header_edit_form: edit

list_page_url: 
    controller: index
    
labels:
    name: demande de financement
    name_plur: demandes de financement
    is_female: 1

objects:
    contact_client: 
        extends: contact
        instance: 
            id_object:
                field_value: id_contact_client
    
    supplier: 
        relation: hasOne
        delete: 0
        instance: 
            bimp_object: 
                module: bimpcore
                name: Bimp_Fournisseur
            id_object: 
                field_value: id_supplier
                
    supplier_contact:
        extends: contact
        instance:
            id_object:
                field_value: id_supplier_contact
                
    lines: 
        relation: hasMany
        delete: 1
        instance: 
            bimp_object: BF_Line
            
    demandes_refinanceurs:
        relation: hasMany
        delete: 1
        instance: 
            bimp_object: BF_DemandeRefinanceur
            
    rents_except: 
        relation: hasMany
        delete: 1
        instance: 
            bimp_object: BF_RentExcept
            
    frais_divers:
        relation: hasMany
        delete: 1
        instance: 
            bimp_object: BF_FraisDivers
            
    frais_fournisseur:
        relation: hasMany
        delete: 1
        instance: 
            bimp_object: BF_FraisFournisseur

    files:
        instance:
            bimp_object:
                module: bimpcore
                name: BimpFile
        list: 
            filters:
                parent_module: bimpfinancement
                parent_object_name: BF_Demande
        add_form: 
            name: upload
            values:
                fields: 
                    parent_module: bimpfinancement
                    parent_object_name: BF_Demande

fields:
    ref: 
        label: Référence
        
    id_client:
        label: Client
        type: id_object
        object: client
        input:
            card: default
        create_form: light
        edit_form: default
            
    id_contact_client: 
        label: Contact client
        type: id_object
        object: contact_client
        create_form: default
        create_form_values:
            fields: 
                fk_soc: 
                    field_value: id_client
        depends_on: id_client
        input: 
            type: select
            options: 
                array: clientContacts
        search: 
            input: 
                type: search_object
        display_if:
            field_name: id_client
            hide_values: 0,''
            
    id_supplier:
        label: Apporteur
        type: id_object
        object: supplier
        input: 
            card: default
        create_form: light
        edit_form: default
        
    id_supplier_contact:
        label: Contact apporteur
        type: id_object
        object: supplier_contact
        input: 
            type: select
            options:
                array: supplierContacts
        search: 
            input: 
                type: search_object
        display_if: 
            field_name: id_supplier
            hide_values: 0,''
        depends_on: id_supplier
        create_form: default
        create_form_values:
            fields: 
                fk_soc: 
                    field_value: id_supplier
                    
    status:
        label: Statut
        type: int
        values: 
            array: status_list
            
    label: 
        label: Libellé
        
    duration:
        label: Durée
        type: int
        values: 
            array: durations
        
    periodicity: 
        label: Périodicité
        type: int
        values: 
            array: periodicities
            
    mode_calcul:
        label: Mode de calcul
        type: int
        default_value: 2
        values: 
            array: calc_modes
       
    montant_materiels:
        label: Montant matériels
        type: money
        default_value: 0
        
    montant_services:
        label: Montant services
        type: money
        default_value: 0
                
    montant_logiciels:
        label: Montant logiciels
        type: money
        default_value: 0
        
    vr_achat: 
        label: VR achat
        type: money
        default_value: 0
        
    vr_vente: 
        label: VR vente
        type: money
        default_value: 0
        
    ca_prevu: 
        label: CA prévu
        type: money
        required: 0
        
    pba_prevu:
        label: PBA prévu
        type: money
        required: 0
            
    date_loyer:
        label: Date de mise en loyer
        type: date
        
    agreement_number:
        label: N° d'accord
        
    commission_commerciale:
        label: Commission commerciale
        type: percent
        default_value: 0
        decimals: 6
                
    commission_financiere:
        label: Commission financière
        type: percent
        default_value: 0
        decimals: 6
      
forms: 
    create: 
        rows: 
            label: 
                field: label
            client:    
                field: id_client
            contact: 
                field: id_contact_client
            supplier: 
                field: id_supplier
            contact_supplier: 
                field: id_supplier_contact
            duration: 
                field: duration
            periodicity: 
                field: periodicity
            mode_calcul: 
                field: mode_calcul
            commission_commerciale: 
                field: commission_commerciale
            commission_financiere: 
                field: commission_financiere
            
    edit: 
        extends: create
        rows: 
            vr_achat: 
                field: vr_achat
            vr_vente: 
                field: vr_vente
            ca_prevu: 
                field: ca_prevu
            pba_prevu: 
                field: pba_prevu
            date_loyer: 
                field: date_loyer
                
fields_tables:
    infos: 
        title: Infos
        icon: fas_info-circle
        rows: 
            - field: date_loyer
              edit: 1
            - field: duration
              edit: 1
            - field: periodicity
              edit: 1
            - field: mode_calcul
              edit: 1 
    
    options: 
        title: Options
        icon: fas_check-square
        rows: 
            - field: commission_commerciale
              edit: 1
            - field: commission_financiere
              edit: 1
            - field: vr_achat
              edit: 1    
            - field: vr_vente
              edit: 1    
            - field: ca_prevu
              edit: 1
            - field: pba_prevu
              edit: 1
              
    client: 
        title: Client
        icon: user-circle
        rows: 
            - field: id_client
              label: Société
              display: card
            - field: id_contact_client
              label: Contact
              display: card
              
    supplier: 
        title: Apporteur
        icon: fas_handshake
        rows: 
            - field: id_supplier
              display: card
            - field: id_supplier_contact
              display: card
              
    montants: 
        title: Montants
        icon: euro
        rows:
            - field: montant_materiels
            - field: montant_services
            - field: montant_logiciels
            - label: Total demande
              value: 
                  callback: displayTotalDemande
        
views:
    default: 
        title: nom
        edit_form: edit
        objects_change_reload: BF_DemandeRefinanceur,BF_Line
        rows:
            0: 
                cols: 
                    - type: object_header
            1: 
                cols: 
                    - type: fields_table
                      col_lg: 6
                      col_md: 6
                      fields_table:
                          name: infos
                    - type: fields_table
                      col_lg: 6
                      col_md: 6
                      fields_table:
                          name: options
                      
            2: 
                cols: 
                    - type: fields_table
                      col_lg: 6
                      col_md: 6
                      show: 
                          field_value: id_client
                      fields_table:
                          name: client
                    - type: fields_table
                      col_lg: 6
                      col_md: 6
                      fields_table:
                          name: supplier
                    
            # Attention row #3 utilisée par extends prolease / si ajout passer à 4
        
    demande: 
        extends: default
        rows: 
            0: unset
            
    montants: 
        panel: 0
        objects_change_reload: BF_DemandeRefinanceur,BF_Line
        rows: 
            - cols: 
                - type: fields_table
                  col_md: 6
                  col_lg: 6
                  fields_table: 
                      name: options
                - type: fields_table
                  col_md: 6
                  col_lg: 6
                  fields_table: 
                      name: montants
                      
lists_cols: 
    id: 
        label: ID
        
lists:
    default:
        checkboxes: 1
        bulk_actions:
            - label: supprimer les demandes de fincancement sélectionnées
              icon: fas_trash-alt
              onclick: deleteSelectedObjects('list_id', $(this))
        sort_field: date_create
        sort_way: desc
        n: 10
        add_form_name: create
        delete_btn: 1
        page_btn: 1
        modal_view: demande
        edit_form: edit
        delete_btn: 1
        cols:
            id:
            date_create:
            id_client: 
            duration:
            periodicity:
            status:
