table: bf_demande_source
icon: fas_
common_fields: 0

parent_module: bimpfinancement
parent_object: BF_Demande
parent_id_property: id_demande

header_edit_form: edit

header_btn: 
    callback: getActionsButtons
    
labels:
    name: source
    is_female: 1
        
fields: 
    id_demande:
        label: Demande
        type: id_parent
        
    id_init_demande: 
        label: ID demande initiale
        type: id
        default_value: 0
        
    type:
        label: Type
        values: 
            array: types
            
    type_origine:
        label: Type origine
        values: 
            array: types_origines
        required: 1
            
    id_origine: 
        label: ID pièce d'origine
        type: id
        default_value: 0
        
    ref_origine: 
        label: Ref. pièce d'origine
        
    origine_data:
        label: Données pièce d'origine
        type: json
        
    id_client: 
        label: ID Client
        type: id
        default_value: 0
        
    ref_client:
        label: Ref. client
        
    client_data:
        label: Données client
        type: json
        
    id_commercial:
        label: ID Commercial
        type: id
        default_value: 0
        
    commercial_data:
        label: Données commercial
        type: json
        
    cancel_submitted: 
        label: Annulation soumise
        type: bool
        default_value: 0
        
    refuse_submitted: 
        label: Refus soumis
        type: bool
        default_value: 0
        
    
fields_tables: 
    infos: 
        title: Infos
        icon: fas_info-circle
        rows: 
            - field: id_demande
            - field: type
            - field: type_origine
            - label: Fournisseur
              value: 
                  callback: displayFournisseur
    
views: 
    default: 
        rows:
            - cols: 
                - type: object_header
            - cols: 
                - type: fields_table
                  fields_name: infos
                  col_md: 6
                  col_lg: 6
                - type: custom
                  custom: 
                      callback: renderCommercialData
                  col_md: 6
                  col_lg: 6
                  
            - cols: 
                - type: custom
                  custom: 
                      callback: renderClientData
                  col_md: 6
                  col_lg: 6
                  
                - type: custom
                  custom: 
                      callback: renderOrgineData
                  col_md: 6
                  col_lg: 6
                  
lists_cols: 
    client: 
        label: Client
        value: 
            callback: displayClient
    origine: 
        label: Pièce d'origine
        value: 
            callback: displayOrigine
    commercial: 
        label: Commercial
        value: 
            callback: displayCommercial
            
lists:
    default: 
        title: Sources des demandes de location
        icon: fas_
        configurable: 1
        checkboxes: 1
        bulk_actions:
            - label: supprimer les sources sélectionnées
              icon: fas_trash-alt
              onclick: deleteSelectedObjects('list_id', $(this))
        list_filters: 
            callback: getListFilters
        filters_panel: default
        sort_field: id
        sort_way: desc
        n: 10
        add_form_name: default
        edit_btn: 1
        edit_form: default
        delete_btn: 1
        page_btn: 1
        modal_view: default
        extra_btn: 
            callback: getListExtraBtn
        cols: 
            id_demande: 
            type: 
            client: 
            origine: 
            commercial: 
            
    demande: 
        extends: default
        title: Source de la demande
        cols: 
            id_demande: unset
            
    