table: bf_demande_refinanceur

parent_object: BF_Demande
parent_id_property: id_demande

positions: 1
position_insert: after
new_status_logs: 1

header_edit_form: default
header_btn: 
    callback: getActionsButtons

labels:
    name: demande refinanceur
    name_plur: demandes refinanceurs
    is_female: 1
    
objects: 
    refinanceur: 
        relation: hasOne
        delete: 0
        instance: 
            bimp_object: BF_Refinanceur
            id_object: 
                field_value: id_refinanceur
                
fields: 
    id_demande: 
        label: Demande
        type: id_parent
        input: 
            type: hidden
            
    id_refinanceur: 
        label: Refinanceur
        type: id_object
        object: refinanceur
        displays: 
            default: 
                type: callback
                method: displayRefinanceur
            soc_card: 
                type: callback
                method: displayRefinanceur
                params: 
                    - card
        values: 
            array: refinanceurs
        required: 1
        
    status:
        label: Statut
        type: int
        values:
            array: status_list
        default_value: 1
        required: 1
        
    rate:
        label: Taux d'emprunt annuel
        type: percent
        
#    coef:
#        label: Coéficient
#        type: float
#        decimals: 5
            
    qty: 
        label: Nombre de périodes
        type: qty
        min: 0
        default_value: 0
        decimals: 0
        
    amount_ht:
        label: Montant HT d'un remboursement
        type: money
        required: 0
        
    payment:
        label: Mode de règlement
        type: int
        values: 
            array: modes_paiements
        
    periodicity:
        label: Périodicité
        type: int
        values: 
            array: periodicities
        
    comment:
        label: Commentaire
        type: html
        input:
            rows: 3
            auto_expand: 1

forms: 
    default: 
        rows: 
            - field: id_refinanceur
            - custom: 1
              label: Demande éffectuée
              input_name: demande_done
              input: 
                  type: toggle
              value: 0
            - custom: 1
              label: Date demande
              input_name: date_demande
              input: 
                  type: datetime
                  display_now: 1
              display_if: 
                  field_name: demande_done
                  show_values: 1
            - field: periodicity
            - field: qty
            - field: amount_ht
#            - custom: 1
#              label: Mode de calcul
#              input_name: calc_mode
#              input: 
#                  type: switch_options
#                  options: 
#                      rate: Taux
#                      coef: Coéficient
#              value: rate
            - field: rate
#              display_if: 
#                  field_name: calc_mode
#                  show_values: rate
#            - field: coef
#              display_if: 
#                  field_name: calc_mode
#                  show_values: coef
            - field: payment
            - field: comment
             
    demande_done: 
        rows: 
            - custom: 1
              hidden: 1
              label: Demande effectuée
              input_name: demande_done
              input: 
                  type: hidden
              value: 1
            - custom: 1
              label: Date demande
              input_name: date_demande
              input: 
                  type: datetime
                  display_now: 1
            - field: periodicity
            - field: qty
            - field: amount_ht
#            - custom: 1
#              label: Mode de calcul
#              input_name: calc_mode
#              input: 
#                  type: switch_options
#                  options: 
#                      rate: Taux
#                      coef: Coéficient
#              value: rate
            - field: rate
#              display_if: 
#                  field_name: calc_mode
#                  show_values: rate
#            - field: coef
#              display_if: 
#                  field_name: calc_mode
#                  show_values: coef
            - field: payment
            - field: comment

    accepted: 
        rows: 
            - custom: 1
              hidden: 1
              label: Demande acceptée
              input_name: demande_accepted
              input: 
                  type: hidden
              value: 1
            - custom: 1
              label: Sous-conditions
              input_name: under_conditions
              input: 
                  type: toggle
              value: 0
            - custom: 1
              label: Conditions
              input_name: conditions
              input: 
                  type: textarea
                  rows: 3
                  auto_expand: 1
              display_if: 
                  field_name: under_conditions
                  show_values: 1                      
            - field: periodicity
            - field: qty
            - field: amount_ht
#            - custom: 1
#              label: Mode de calcul
#              input_name: calc_mode
#              input: 
#                  type: switch_options
#                  options: 
#                      rate: Taux
#                      coef: Coéficient
#              value: rate
            - field: rate
#              display_if: 
#                  field_name: calc_mode
#                  show_values: rate
#            - field: coef
#              display_if: 
#                  field_name: calc_mode
#                  show_values: coef
            - field: payment
            - field: comment
            
    refused: 
        rows: 
            - custom: 1
              label: Raisons du refus par le refinanceur
              input_name: reasons
              input: 
                  type: textarea
                  rows: 3
                  auto_expand: 1
                  
    cancel: 
        extends: refused
        rows: 
            0: 
                label: Raisons de l'abandon de cette demande
        
fields_tables: 
    infos: 
        title: Infos
        icon: fas_info-circle
        rows: 
            - field: id_demande
            - field: id_refinanceur
              display: soc_card
            - field: periodicity
              edit: 1
            - field: payment
              edit: 1
            - field: comment
              edit: 1
            
    montants: 
        title: Montants
        icon: fas_euro-sign
        rows: 
            - field: qty
              edit: 1
#            - field: coef
#              edit: 1
            - field: rate
              edit: 1
            - field: amount_ht
              edit: 1
            
views: 
    default: 
        rows: 
            - cols: 
                - type: object_header
            - cols: 
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  fields_table: 
                      name: infos
                      
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  fields_table: 
                      name: montants
                      
            - cols: 
                - type: custom
                  custom: 
                      callback: renderLogsList
                      
lists:
    default: 
        checkboxes: 
            callback: isDeletable
        positions: 1
        title: Demandes Refinanceurs
        icon: bank
        bulk_actions: 
            - label: Supprimer les lignes sélectionnées
              icon: fas_trash-alt
              onclick: deleteSelectedObjects('list_id', $(this));
              btn_class: deleteSelectedObjects
        delete_btn: 1
        edit_btn: 1
        add_form_name: default
        edit_form: default
        modal_view: default
        sort_field: position
        sort_way: asc
        n: 10
        extra_btn: 
            callback: getActionsButtons
        cols:
            id_refinanceur: 
            status: 
            periodicity: 
                edit: 1
            qty:
                edit: 1
            rate: 
                edit: 1
#            coef: 
#                edit: 1
            amount_ht: 
                edit: 1
            comment: 
            
            
        
            
