common_fields: 0
table: bf_refinanceur
icon: fas_university

header_list_name: default

list_page_url: 
    controller: index
    url_params: 
        tab: refinanceurs
        
labels:
    name: refinanceur
    
fields: 
    id_societe: 
        label: Société
        type: id_object
        object: societe
        input: 
            type: search_societe
        required: 1
        
    url_demande: 
        label: URL Demande financement
        
fields_tables: 
    infos: 
        title: Infos
        icon: fas_info
        rows: 
            - field: id_societe
              display: card
            - field: url_demande
              
views: 
    default: 
        rows: 
            - cols: 
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  fields_table: 
                      name: infos
                      
lists: 
    default:
        title: Refinanceurs
        icon: fas_university
        checkboxes: 1
        add_btn: 1
        add_form_name: default
        edit_btn: 1
        delete_btn: 1
        modal_view: default
        bulk_actions:
            - label: supprimer les refinanceurs sélectionnés
              icon: fas_trash-alt
              onclick: deleteSelectedObjects('list_id', $(this))
        sort_field: id
        sort_way: asc
        n: 10
        cols: 
            id_societe:
            url_demande: 
    