common_fields: 0
table: bf_refinanceur
icon: fas_university

header_list_name: default

list_page_url: 
    controller: index
    url_params: 
        tab: refinanceurs
        
labels:
    name: refinanceur
    
objects: 
    def_contact_signataire: 
        extends: contact
        instance: 
            id_object: 
                field_value: id_def_contact_signataire
                
fields: 
    id_societe: 
        label: Société
        type: id_object
        object: societe
        required: 1
        
    id_def_contact_signataire: 
        label: Contact signataire par défaut
        type: id_object
        object: def_contact_signataire
        default_value: 0
        values: 
            callback: 
                method: getSocieteContactsArray
                params: 
                    - field_value: id_societe
                    - 0
        input: 
            type: select
            options: 
                callback: 
                    method: getSocieteContactsArray
                    params: 
                        - field_value: id_societe
                        - 1
                        - ''
                        - 1
        depends_on: id_societe
        
    url_demande: 
        label: URL Demande financement
        
    taux: 
        label: Taux de cession annuels
        type: json
        displays: 
            default: 
                label: Affichage taux
                type: callback
                method: displayTaux
                
        input: 
            type: custom
            content: 
                callback: renderTauxInputs               
    
    active: 
        label: Actif
        type: bool
        default_value: 1
        
fields_tables: 
    infos: 
        title: Infos
        icon: fas_info
        rows: 
            - field: active
              edit: 1
            - field: id_societe
              display: card
            - field: url_demande
            - field: taux
              
views: 
    default: 
        rows: 
            - cols: 
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  fields_table: 
                      name: infos
                      
lists: 
    default:
        title: Refinanceurs
        icon: fas_university
        checkboxes: 1
        add_btn: 1
        add_form_name: default
        edit_btn: 1
        delete_btn: 1
        modal_view: default
        bulk_actions:
            - label: supprimer les refinanceurs sélectionnés
              icon: fas_trash-alt
              onclick: deleteSelectedObjects('list_id', $(this))
        sort_field: id
        sort_way: asc
        n: 10
        cols: 
            id_societe:
            id_def_contact_signataire:
                display: nom_url
            url_demande: 
            taux:
            active: 
                edit: 1
    