INSERT into llx_product (ref,entity,ref_ext,datec,tms,fk_parent,label,description,note,customcode,fk_country,fk_state,price,price_ttc,price_min,price_min_ttc,price_base_type,tva_tx,recuperableonly,localtax1_tx,localtax1_type,localtax2_tx,localtax2_type,fk_user_author,fk_user_modif,tosell,tobuy,onportal,fk_product_type,duration,seuil_stock_alerte,barcode,fk_barcode_type,accountancy_code_sell,accountancy_code_sell_intra,accountancy_code_sell_export,accountancy_code_buy,accountancy_code_buy_intra,accountancy_code_buy_export,partnumber,weight,weight_units,length,length_units,surface,surface_units,volume,volume_units,stock,pmp,cur_pa_ht,cur_pa_origin,cur_pa_id_origin,id_cur_fp,fifo,lifo,canvas,finished,hidden,import_key,desiredstock,url,tobatch,fk_price_expression,fk_unit,cost_price,default_vat_code,price_autogen,note_public,model_pdf,width,width_units,height,height_units,no_fixe_prices,duree,lock_admin,alerteActive,type_remise_arr,fk_project,net_measure,net_measure_units,batch_mask,lifetime,qc_frequency,mandatory_period,fk_default_bom, temp_crt, id_bimp)
SELECT ref,entity,ref_ext,datec,tms,fk_parent,label,description,note,customcode,fk_country,fk_state,price,price_ttc,price_min,price_min_ttc,price_base_type,tva_tx,recuperableonly,localtax1_tx,localtax1_type,localtax2_tx,localtax2_type,fk_user_author,fk_user_modif,tosell,tobuy,onportal,fk_product_type,duration,seuil_stock_alerte,barcode,fk_barcode_type,accountancy_code_sell,accountancy_code_sell_intra,accountancy_code_sell_export,accountancy_code_buy,accountancy_code_buy_intra,accountancy_code_buy_export,partnumber,weight,weight_units,length,length_units,surface,surface_units,volume,volume_units,stock,pmp,cur_pa_ht,cur_pa_origin,cur_pa_id_origin,id_cur_fp,fifo,lifo,canvas,finished,hidden,import_key,desiredstock,url,tobatch,fk_price_expression,fk_unit,cost_price,default_vat_code,price_autogen,note_public,model_pdf,width,width_units,height,height_units,no_fixe_prices,duree,lock_admin,alerteActive,type_remise_arr,fk_project,net_measure,net_measure_units,batch_mask,lifetime,qc_frequency,mandatory_period,fk_default_bom, ra.value, rowid FROM ERP_PROD_BIMP.llx_product a left JOIN ERP_PROD_BIMP.llx_product_remise_arriere ra ON ra.id_product = a.rowid AND ra.type = 'CRT' WHERE tosell = 1 AND tobuy = 1;

 

 


INSERT INTO llx_product_extrafields (fk_object, code_config,type2,serialisable,gamme,categorie,nature,collection,famille,fk_user_valid,date_valid,date_ask_valid,crt,ref_constructeur,pa_prevu,infos_pa,remisable,deee,rpcp,is_sav,validate) SELECT p.rowid,code_config,type2,serialisable,gamme,categorie,nature,collection,famille,fk_user_valid,date_valid,date_ask_valid,crt,ref_constructeur,pa_prevu,infos_pa,remisable,deee,rpcp,is_sav,validate FROM  ERP_PROD_BIMP.`llx_product_extrafields` e, llx_product p WHERE p.id_bimp = e.fk_object;

 

 

INSERT INTO `llx_product_remise_arriere` (id_product, type, nom, value, active) 
SELECT p.rowid, type, nom, value, active FROM ERP_PROD_BIMP.llx_product_remise_arriere e, llx_product p WHERE p.id_bimp = e.id_product AND e.type = 'CRT';