table: bic_user
icon: fas_user
common_fields: 1

parent_module: bimpcore
parent_object: Bimp_Client
parent_id_property: id_client

public_header_edit_form: public_edit
public_header_btn: 
    callback: getPublicActionsButtons
       
labels:
    name: compte utilisateur
    name_plur: comptes utilisateurs
    
nom_url: 
    syntaxe: <email>
                
objects:
    user_client_contrats:
        relation: hasMany
        delete: 1
        instance:
            bimp_object: 
                module: bimpinterfaceclient
                name: BIC_UserClientContrat
    
    societe:
        instance:
            bimp_object: unset
            dol_object:
                module: societe
                file: societe
            id_object:
                field_value: id_client
                
    tickets:
        relation: hasMany
        delete: 0
        instance:
            bimp_object: BIC_UserClientTicket

fields:
    id_client: 
        label: Client
        type: id_parent
        required: 1
        default_value: 0
        input: 
            card: default
        
    id_contact: 
        label: Contact client associé
        type: id_object
        object: contact
        input: 
            type: select
            options: 
                callback: 
                    method: getSocieteContactsArray
                    params: 
                        - field_value: id_client
                        - 1
        depends_on: id_client
        
    email:
        label: E-mail
        required: 1
        
    password:
        label: Mot de passe 
        type: password
        
    role: 
        label: Rôle
        type: int
        default_value: 1
        values: 
            array: roles
    
    status:
        label: Statut
        type: int
        values:
            array: status
        default_value: 1
            
    renew_required:
        label: Doit changer son mot de passe
        type: bool
        default_value: 0
        
    lang:
        label: Langue par défaut
        type: int
        values: 
            array: langs_list
        default_value: 0
        
forms:
    default:
        rows:
            id_client: 
                field: id_client
            email: 
                field: email
            contact: 
                field: id_contact
            role: 
                field: role
            status: 
                field: status
            renew: 
                field: renew_required
            send_pw: 
                custom: 1
                label: Envoyer le mot de passe par Email
                input_name: send_mail
                input:
                    type: toggle
                value: 1
            contrat: 
                object: user_client_contrats
                multiple: 1
              
    public: 
        extends: default
        rows: 
            id_client: 
                edit: 0
            renew: unset
            contrat: unset
            
    public_edit: 
        extends: public
        rows: 
            send_pw: unset
        
fields_tables:
    public:
        panel: 0
        rows: 
            - field: email
            - field: id_contact
            - field: role
            - field: status

views:
    public: 
        title: Mon compte utilisateur
        rows: 
            - cols: 
                - type: object_header
            - cols: 
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: public
                - type: list
                  show: 
                      callback: isNotAdmin
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  list: 
                      name: public_user_client
                      children: user_client_contrats
                                
lists:
    default:
        checkboxes: 0
        configurable: 1
        sort_field: id
        sort_way: desc
        n: 10
        delete_btn: 1
        page_btn: 1
        edit_form: default
        add_btn: 1
        add_form_name: default
        edit_btn: 1
        extra_btn: 
            callback: getListExtraButtons
        cols:
            id_client:
            email:
            id_contact:
            role:
            status:
                
    client: 
        extends: default
        cols: 
            client: unset
            
    public_client: 
        icon: fas_users
        extends: client
        configurable: 0
        page_btn: 0
        edit_form: public_edit
        add_form_name: public
        
cards:
    default:
        title: nom
        fields: 
            - label: Email
              field: email
            - label: Societe
              field: id_client
        view_btn: 1