table: bic_user
icon: fas_user
controller: pageUser
common_fields: 0

objects:
    user_client_contrat:
        relation: hasMany
        delete: 0
        instance:
            bimp_object: BIC_UserClientContrats
    
    societe:
        instance:
            dol_object:
                module: societe
                file: societe
                id_object:
                    field_value: attached_societe
                    
    tickets:
        instance:
            bimp_object: BIC_UserTickets

header_btn: 
    callback: getActionsButtons

labels:
    name:
        callback:
            method: lang
            params:
                - labelUserSing
    name_plur:
        callback:
            method: lang
            params:
                - labelUserPlur

fields:
    email:
        label:
            callback:
                method: lang
                params:
                    - labelFieldEmail
        type: string
    password:
        label: Mot de passe 
        type: password
    attached_societe:
        label: 
            callback:
                method: lang
                params:
                    - societeOfAccount
        type: id_object
        object: client
        required: 1
        input: 
            type: search_societe
            societe_type: customer
            help: 
                callback:
                    method: lang
                    params:
                        - helpSearchSociete
            card: default
        search:
            input: 
                type: search_societe
                societe_type: customer 
    role:
        label: 
            callback:
                method: lang
                params:
                    - labelFieldRole
        type: int
        values:
            array: role
        default_value: 
            callback: what_is_the_context
    status:
        label:
            callback:
                method: lang
                params:
                    - labelFieldStatus
        type: int
        values:
            array: status
    renew_required:
        label: 
            callback:
                method: lang
                params:
                    - mustChangePassword
        type: bool
    lang:
        label: Langue par défaut
        type: int
        values: 
            array: langs_list
        

lists:
    default:
        checkboxes: 0
        sort_field: date_create
        extra_btn:
            callback: getListExtraButtons
        sort_way: desc
        n: 10
        delete_btn: 1
        page_btn: 1
        edit_form: edit
        add_object_row: 0
        add_btn: 1
        add_form_name: edit
        update_btn: 1
        edit_btn: 1
        cols:
            email:
                field: email
            role:
                field: role
            status:
                field: status
            lang:
                field: lang
                show:
                    callback: showLang
    full:
        extends: default
        edit_form: editFull
        add_form_name: editFull
        add_form_values:
            fields:
                role: 1
        cols:
            attached_societe:
                field: attached_societe
                display: nom_url
            renew_required:
                field: renew_required
            lang:
                field: lang
                
fields_table:
    default:
        title: Status
        icon: fas_file-signature
        rows: 
            - field: email
              edit: 0
            - field: password
              edit: 0
            - field: role
              edit: 0
            - field: status
              edit: 0

views:
    pageUser: 
        title: 
            callback: displayEmail
        edit_form: default
        delete_btn: 1
        rows:
            - cols: 
                - type: list
                  show:
                      callback: it_is_not_admin
                  list:
                        children: user_client_contrat
    
    for_controller:
        rows:
            title: infos
            - cols:
                - type: nav_tabs
                  nav_tabs:
                      - id: attached_contrat
                        title: Contrats associés
                        show:
                            callback: it_is_not_admin
                        struct:
                            type: list
                            list:
                                children: user_client_contrat
                      - id: attached_tickets
                        title: Tickets support
                        struct: 
                            type: list
                            list:
                                name: pageUser
                                object: tickets
                            
                            
                        
                
forms:
    edit:
        objects_change_reload: BIC_UserClient, BIC_UserClientContrats
        rows:
            - field: email
            - field: role
            - field: status
            - field: lang
              show:
                  callback: showLang
            - field: attached_societe
              hidden: 1
            - custom: 1
              label: 
                  callback:
                      method: lang
                      params:
                          - sendEmail
              input_name: send_mail
              input:
                  type: toggle
              value: 1
            - object: user_client_contrat
              multiple: 1
    editFull:
        rows:
            - field: email
            - field: role
            - field: status
            - field: lang
              show:
                  callback: showLang
            - field: attached_societe
            - field: renew_required
            - custom: 1
              label: 
                  callback:
                      mathod: lang
                      params:
                          - sendEmail
              input_name: send_mail
              input:
                  type: toggle
              value: 1
        
cards:
    default:
        title: nom
        fields: 
            - label: Email
              field: email
            - label: Societe
              field: attached_societe
        view_btn: 1
