dol_object: 
    instance: 
        dol_object: 
            module: contrat
            file: contrat
            
table: contrat
primary: rowid
controller: contrat
icon: fas_file-signature
public_icon: pe_news-paper

list_page_url: 
    controller: index  
    
header_btn: 
    callback: getActionsButtons
    
header_edit_form: edit

public_header_btn: 
    callback: getPublicActionsButtons
    
labels: 
    name: contrat
                
objects:
    client:
        instance:
            id_object:
                field_value: fk_soc
    
    lines:
        relation: hasMany
        delete: 1
        instance:
            bimp_object: BCT_ContratLine
    
    avenant:
        relation: hasMany
        delete: 1
        instance:
            bimp_object: Bimp_ContratAvenant
    
    files:
        relation: hasMany
        delete: 1
        instance:
            bimp_object:
                module: bimpcore
                name: BimpFile
        list: 
            filters:
                parent_module: bimpcontract
                parent_object_name: BContract_contrat
                deleted: 0
        add_form: 
            name: upload
            values:
                fields: 
                    parent_module: bimpcontract
                    parent_object_name: BContract_contrat
    
    user_create:
        extends: user
        instance:
            id_object:
                field_value: fk_user_author
                
    user_modif: 
        extends: user
        instance:
            id_object:
                field_value: fk_user_modif
                
    commercial_suivi:
        extends: user
        instance:
            id_object:
                field_value: fk_commercial_suivi
                
    commercial_signature:
        extends: user
        instance:
            id_object:
                field_value: fk_commercial_signature
    
    entrepot: 
        instance: 
            id_object:
                field_value: entrepot
                
    bimp_entrepot: 
        instance: 
            id_object:
                field_value: entrepot
    
    client_facturation:
        extends: client
        instance:
            id_object:
                field_value: fk_soc_facturation
                
    signature: 
        relation: hasOne
        delete: 1
        instance: 
            bimp_object: 
                module: bimpcore
                name: BimpSignature
            id_object: 
                field_value: id_signature
                
    rib_client: 
        relation: hasOne
        delete: 0
        instance: 
            bimp_object: 
                module: bimpcore
                name: Bimp_SocBankAccount
            id_object:
                field_value: rib_client

fields:
    # Champs objet Dolibarr:
    statut:
        label: Statut
        type: int
        values:
            array: status_list
            
    ref: 
        label: Référence
        
    fk_soc:
        label: Client
        type: id_object
        object: client
        dol_prop: socid
        required: 1
        input: 
            card: default
        create_form: light
        
    ref_customer:
        label: Réf. client
        
    ref_supplier: 
        label: Réf. fournisseur
        
    ref_ext:
        label: Annule et remplace
        input:
            help: A remplir en cas de renouvellement d'un ancien contrat - 15 caractères maximum
            
    datec:
        label: Créé le
        type: datetime
        
    date_contrat:
        label: Date de signature
        type: date
    
    fk_user_author:
        label: Créé par
        type: id_object
        object: user_create
        dol_prop: user_author_id
        input: 
            type: search_user
            
    fk_user_modif: 
        label: Modifié par
        type: id_object
        object: user_modif
        input: 
            type: search_user
            
    fk_commercial_signature:
        label: Commercial signataire
        dol_prop: commercial_signature_id
        type: id_object
        object: commercial_signature
        input: 
            type: search_user
            help: Choisir le commercial responsable de la signature du contrat
        default_value: 
           prop:
               name: id
               object:
                   global: user
                   
    fk_commercial_suivi:
        label: Commercial suivi
        dol_prop: commercial_suivi_id
        type: id_object
        object: commercial_suivi
        input: 
            type: search_user
            help: Choisir le commercial responsable du suivi du contrat
        default_value: 
           prop:
               name: id
               object:
                   global: user
                   
    note_public:
        label: Note particulière au contrat
        type: html
        hashtags: 1
        
    note_private:
        label: Note privée
        type: html
        hashtags: 1
        
    # Champs Dolibarr non gérés : ref_supplier, entity, fk_projet, model_pdf, extraparams
            
    label:
        label: Libellé
        
    entrepot:
        label: Entrepôt
        dol_extra_field: 1
        type: id_object
        object: bimp_entrepot
        input: 
            type: search_entrepot
        
    secteur:
        label: Secteur
        values:
            array: contratSecteurs
            
    expertise:
        label: Expertise
        dol_extra_field: 1
        type: int
        values: 
            array: expertise
            
    fk_soc_facturation: 
        label: Client facturation
        type: id_object
        object: client_facturation
        input:
            card: default
            
    rib_client: 
        label: RIB client (pour prélèvements)
        type: id_object
        object: rib_client
        depends_on: fk_soc,fk_soc_facturation
        input:
            type: select
            options:
                callback: getClientRibsArray
        default_value: 0
                
    date_start:
        label: Date d'effet
        type: date
        dol_extra_field: 1
        required: 1
        
    duree_mois:
        label: Durée en mois
        type: qty
        dol_extra_field: 1
        default_value: 12
        required: 1
        
    fk_mode_reglement:
        label: Mode de règlement
        type: int
        dol_extra_field: 1
        default_value: 
            callback: getModeReglementClient
        values:
            array: modeReglements
            
    condregl:
        label: Conditions de règlement
        type: int
        dol_extra_field: 1
        default_value: 
            callback: getConditionReglementClient
        values:
            array: condReglements
        
    fk_user_cloture:
        label: Clos par
        type: int
        
    id_signature: 
        label: Signature
        type: id_object
        object: signature
        
    signature_params: 
        label: Paramètres incrustation signature
        type: json
        
    version: 
        label: Version
        type: int
        values: 
            1: Ancienne version
            2: Nouvelle version
       
views: 
    default: 
        rows:
          - cols: 
              - type: object_header
              
lists: 
    default:
        title: Tous les contrats
        configurable: 1
        checkboxes: 1
        bulk_actions:
            callback: getBulkActions
        sort_field: datec
        sort_way: desc
        n: 20
        add_form_name: default
        edit_btn: 1
        edit_form: edit
        delete_btn: 0
        modal_view: full
        page_btn: 1
        cols: 
            ref:
            objet_contrat:
            signed:
            statut:
            fk_soc:
            date_start:
            fk_commercial_suivi:
            commercialclient:

searches:
    default:
        fields_search: 
            - a.ref
            - s.nom
        joins:
            s: 
                table: societe
                on: a.fk_soc = s.rowid
                alias: s
        fields_return: 
            - a.ref
            - s.nom
        label_syntaxe: '<a.ref> (<s.nom>)'
        
cards:
    default:
        title: 
            field_value: ref
        status: statut
        fields: 
            - field: fk_soc
        view_btn: 1
