table: bimp_location
controller: location
icon: fas_business-time

list_page_url: 
    controller: index
            
header_list_name: default
header_edit_form: default

header_btn: 
    callback: getActionsButtons
        
nom_url: 
    with_status: 1
    syntaxe: <ref>
    card: default
    
labels:
    name: location
    is_female: 1
    
objects: 
    contact_facturation: 
        extends: contact
        instance: 
            id_object: 
                field_value: id_contact_facturation
    
    facture_acompte: 
        extends: facture
        instance: 
            id_object: 
                field_value: id_facture_acompte
                
    lines: 
        relation: hasMany
        delete: 1
        instance: 
            bimp_object: 
                module: bimplocation
                name: BimpLocationLine
                
fields: 
    ref: 
        label: Référence
        
    status: 
        label: Status
        type: int
        values: 
            array: status_list
            
    id_client: 
        label: Client
        type: id_object
        object: client
        required: 1
        input: 
            card: default
        create_form: light_particulier
        create_form_values: 
            fields: 
                marche: 
                    - 18
        edit_form: default
        
    id_contact_facturation: 
        label: Contact facturation
        type: id_object
        object: contact_facturation
        depends_on: id_client
        display_if:
            field_name: id_client
            hide_values: 0,
        create_form: default
        edit_form: default
        create_form_values:
            fields: 
                fk_soc: 
                    field_value: id_client
        input: 
            type: select
            options: 
                array: clientContacts
        search: 
            input: 
                type: search_object
        
    id_facture_acompte: 
        label: Facture d'acompte
        type: id_object
        object: facture_acompte
        
    date_from: 
        label: Du
        type: date
        required: 1
        
    date_to: 
        label: Au
        type: date
        required: 1
        
forms: 
    default: 
        rows: 
            - field: id_client
            - field: id_contact_facturation
            - field: date_from
            - field: date_to
        
        
fields_tables: 
    infos: 
        title: Informations
        icon: fas_info-circle
        rows: 
            - field: date_from
            - field: date_to
            - field: id_client
              display: card
            - field: id_contact_facturation
              display: card
            - field: id_facture_acompte
              show: 
                  field_value: id_facture_acompte
              
views: 
    default: 
        rows: 
            - cols: 
                  - type: object_header
            - cols: 
                  - type: fields_table
                    col_lg: 6
                    col_md: 6
                    fields_table: 
                        name: infos
                  
                  - type: custom
                    col_lg: 6
                    col_md: 6
                    custom:
                        callback: renderMontants
            - cols: 
                - type: list
                  list: 
                      title: Equipements
                      name: location
                      children: lines
       
filters_panels: 
    default: 
        filters: 
            - field: status
            - field: id_client
            - field: date_from
            - field: date_to
            
lists: 
    default: 
        title: Liste des locations
        icon: fas_business-time
        configurable: 1
        checkboxes: 1
        bulk_actions:
            - label: supprimer les location sélectionnées
              icon: fas_trash-alt
              onclick: deleteSelectedObjects('list_id', $(this))
        filters_panel: default
        sort_field: date_create
        sort_way: desc
        n: 10
        add_form_name: default
        edit_btn: 1
        delete_btn: 1
        page_btn: 1
        modal_view: default
        extra_btn: 
            callback: getListExtraBtn
        cols: 
            ref:
            status: 
            date_create:
            id_client: 
            date_from: 
            date_to: 
            
        