table: bc_caisse_session
common_fields: 0

icon: fas_user-clock

parent_object: BC_Caisse
parent_id_property: id_caisse

labels: 
    name: Session de caisse
    name_plur: Sessions de caisse
    is_female: 1
    
objects: 
    user_open: 
        extends: user
        instance: 
            id_object: 
                field_value: id_user_open
                
    user_closed: 
        extends: user
        instance: 
            id_object: 
                field_value: id_user_closed
                
fields: 
    id_caisse: 
        label: Caisse
        type: id_parent
        
    fonds_begin: 
        label: Fonds à l'ouverture
        type: money
        required: 1
        
    fonds_end: 
        label: Fonds à la fermeture
        type: money
        default_value: 0
        
    date_open: 
        label: Date et heure d'ouverture
        type: datetime
        
    date_closed: 
        label: Date et heure de fermeture
        type: datetime
        
    id_user_open: 
        label: Utilisateur à l'ouverture
        type: id_object
        object: user_open
        
    id_user_closed: 
        label: Utilisateur à la fermeture
        type: id_object
        object: user_closed
        
fields_tables: 
    default: 
        title: Information session
        icon: info
        rows: 
            - field: id_caisse
              display: nom
            - field: date_open
            - field: date_closed
            - field: fonds_begin
            - field: fonds_end
              show: 
                  field_value: fonds_end
            - field: id_user_open
              display: nom_url
            - field: id_user_closed
              display: nom_url
              show: 
                  field_value: id_user_closed
            
views: 
    default: 
        title: 
            callback: displaySessionName
        objects_change_reload: BC_Vente,Bimp_Paiement
        rows: 
            - cols: 
                - type: fields_table
                  fields_table: default
                  col_md: 6
                  col_lg: 6
                  
                - type: custom
                  custom: 
                      callback: renderPaymentsInfos
                  col_lg: 6
                  col_md: 6
                  
    full: 
        objects_change_reload: BC_Vente,Bimp_Paiement
        rows: 
            - cols: 
                - type: object_header
            - cols: 
                - type: view
                  view: 
                      name: default
                      panel: 0
            - cols: 
                - type: custom
                  custom: 
                      callback: renderPaymentsHistory
            - cols: 
                - type: custom
                  custom: 
                      callback: renderVentesList
                  
lists: 
    default: 
        title: Sessions de caisse
        icon: fas_user-clock
        sort_field: id
        sort_way: desc
        n: 10
        modal_view: full
        cols:
            centre: 
                field: id_caisse
                display: nom
            date_open: 
                field: date_open
            date_closed: 
                field: date_closed
            user_open: 
                field: id_user_open
                display: nom_url
            user_closed: 
                field: id_user_closed
                display: nom_url
            fonds_begin: 
                field: fonds_begin
            fonds_end:
                field: fonds_end
                