table: bnf_frais
icon: fas_sticky-note

labels: 
    name: note de frais
    name_plur: notes de frais
    is_female: 1
    
objects: 
    user: 
        relation: hasOne
        delete: 0
        instance: 
            bimp_object: 
                module: bimpcore
                name: Bimp_User
            id_object: 
                field_value: id_user
                
    montants: 
        relation: hasMany
        delete: 1
        instance: 
            bimp_object: BNF_FraisMontant
            
    kilometers:
        relation: hasMany
        delete: 1
        instance: 
            bimp_object: BNF_FraisKilometers
                
fields: 
    id_user: 
        label: Utilisateur
        type: id_object
        object: user
        input: 
            type: search_user
        defaul_value: 
            prop: 
                name: id
                object: 
                    global: user
        
    type: 
        label: Type
        type: int
        values: 
            array: types
        required: 1
        
    date: 
        label: Date
        type: date
        required: 1
        
    description: 
        label: Description
        type: text
        input: 
            auto_expand: 1
            rows: 1     
        
    status: 
        label: Statut
        type: int
        values: 
            array: status_list
        default_value: 1
        
    ticket_validated: 
        label: Ticket de caisse validé
        type: bool
        default_value: 0
        
    period: 
        label: Période
        type: int
        values: 
            array: periods
        display_if:
            field_name: type
            show_values: 1
      
forms: 
    default: 
        rows: 
            - field: id_user
            - field: date
            - field: type
            - field: description
            - field: period
            - object: montants
              multiple: 1
              display_if: 
                  field_name: type
                  hide_values: 5
            - object: kilometers
              multiple: 1
              display_if: 
                  field_name: type
                  show_values: 5
            
fields_tables: 
    default: 
        panel: 0
        rows: 
            - field: date
            - field: status
            - label: Total TTC
              value: 
                  callback: displayTotalAmount
            - field: id_user
              display: card
            - field: period
              show: 
                  callback: hasPeriod
            - field: type
            - field: description
            - field: ticket_validated
            
views: 
    default:
        objects_change_reload: BNF_FraisMontant,BNF_FraisKilometers
        rows: 
            - cols: 
                - type: object_header
            - cols: 
                - type: fields_table
                  fields_table: 
                      name: default
            - cols: 
                - type: list
                  show: 
                      callback: hasAmounts
                  list: 
                      children: montants
            - cols: 
                - type: list
                  show: 
                      callback: hasKilometers
                  list: 
                      children: kilometers
lists: 
    default: 
        title: Notes de frais
        checkboxes: 1
        objects_change_reload: BNF_FraisMontant,BNF_FraisKilometers
        bulk_actions:
            callback: getListBulkActions
        list_filters: 
            callback: getListFilters
        sort_field: date_create
        sort_way: desc
        n: 10
        add_form_name: default
        edit_btn: 1
        edit_form: default
        update_btn: 1
        delete_btn: 1
        modal_view: default
        extra_btn: 
            callback: getListExtraBtn
        cols:
            date: 
                field: date
            user: 
                field: id_user
                display: nom_url
            type: 
                field: type
            amount: 
                label: Total TTC
                value: 
                    callback: displayTotalAmount
            ticket: 
                field: ticket_validated
                edit: 1
            status: 
                field: status
    
    user: 
        title: Notes de frais
        checkboxes: 1
        objects_change_reload: BNF_FraisMontant,BNF_FraisKilometers
        bulk_actions:
            callback: getListBulkActions
        list_filters: 
            callback: getListFilters
        sort_field: date_create
        sort_way: desc
        n: 10
        add_form_name: default
        edit_btn: 1
        edit_form: default
        update_btn: 1
        delete_btn: 1
        modal_view: default
        extra_btn: 
            callback: getListExtraBtn
        cols:
            date: 
                field: date
            type: 
                field: type
            amount: 
                label: Total TTC
                value: 
                    callback: displayTotalAmount
            ticket: 
                field: ticket_validated
                edit: 1
            status: 
                field: status