colors: 
    default: 'B4B4B4'
    primary: 'BA434D'
    secondary: '636363'
    success: '348C41'
    info: '3B6EA0'
    warning: 'E69900'
    danger: 'A00000'
    important: '963E96'
    selection: '5897FB'
        
pdf:
    primary: 'BA434D'

interface_client: 
    primary: 'BA434D'
    
public_email: 
    primary: 'BA434D'