table: be_equipment_logiciel
common_fields: 0

parent_object: BE_Equipment
parent_id_property: id_equipment

labels:
    name: logiciel
    
objects: 
    product: 
        relation: hasOne
        delete: 0
        instance: 
            bimp_object:
                module: bimpcore
                name: Bimp_Product
            id_object: 
                field_value: id_product
                
    user_account:
        instance: 
            bimp_object: BE_UserAccount
            id_object: 
                field_value: id_user_account
                
associations:
    user_accounts: 
        label: Comptes utilisateurs
        object: user_account
        create_form: default
        display: 
            default: 
                type: card
                card: light
        input: 
            type: search_list
            search_list:
                table: be_user_account
                field_return_label: name
                field_return_value: id
                fields_search: name,login
            help: Entrez le nom d'un compte utilisateur pour effectuer une recherche
    
fields: 
    id_equipment: 
        label: Equipement
        type: id_parent
        
    id_product:
        label: Produit
        type: id_object
        object: product
        required_if: use_product=1
        input: 
            type: search_product
            help: Entrez un nom ou une référence pour rechercher un produit
        display_if: 
            field_name: use_product
            show_values: 1
        display: 
            default: 
                type: nom_url        
    serial: 
        label: Numéro de série / License
        
fields_table: 
    default: 
        panel: 0
        rows: 
            - field: id_product
              display: card
            - field: serial
            - association: user_accounts
              edit: 1        

views:
    default:
        title: nom
        edit_form: default
        delete_btn: 1
        rows:
            - cols: 
                  - type: fields_table
                    col_lg: 12
                    fields_table:
                        name: default 

forms:
    default: 
        rows: 
            - field: id_product
            - field: serial
            - association: user_accounts
            
lists: 
    default: 
        title: Logiciels
        icon: cube
        checkboxes: 1
        bulk_actions: 
            - label: Supprimer les lignes sélectionnées
              icon: trash
              onclick: deleteSelectedObjects('list_id', $(this));
              btn_class: deleteSelectedObjects
        add_form_name: default
        modal_view: default
        sort_field: id
        sort_way: desc
        n: 25
        edit_btn: 1
        delete_btn: 1
        enable_search: 0
        cols: 
            product: 
                field: id_product
                display: nom_url
            serial: 
                field: serial