table: be_logiciel
common_fields: 1

labels:
    name: logiciel
    
objects: 
    product: 
        instance: 
            bimp_object: unset
            dol_object: product
        card: 
            type: product_card
                
    fournisseur:
        instance: 
            bimp_object: unset
            dol_object: societe
        
fields: 
    use_product:
        label: Produit existant
        type: bool
        default_value: 1
        
    id_product:
        label: Produit
        type: id_object
        object: product
        required_if: use_product=1
        input: 
            type: search_product
            help: Entrez un nom ou une référence pour rechercher un produit
        display_if: 
            field_name: use_product
            show_values: 1
        displays: 
            default: 
                type: nom_url
        
    name: 
        label: Nom du produit
        display_if: 
            field_name: use_product
            show_values: 0
        required_if: use_product=0
        
    id_fournisseur:
        label: Fabricant
        type: id_object
        object: fournisseur
        input: 
            type: search_societe
            societe_type: supplier
        displays: 
            default: 
                type: nom_url
                external_link: 1
        display_if: 
            field_name: use_product
            show_values: 0
        required_if: use_product=0
            
    version:
        label: Version
        display_if: 
            field_name: use_product
            show_values: 0
        required_if: use_product=0
            
    type: 
        label: Type
        values: 
            array: 
                1: OS
                2: BDD
        default_value: 1

fields_tables: 
    default: 
        panel: 0
        rows:
            - label: Produit
              value: 
                  callback: 
                      method: displayProduct
                      params:
                          - card
            - field: type

views: 
    default:
        title: nom
        edit_form: default
        delete_btn: 1
        rows:
            - cols: 
                  - type: object_common_fields
                    col_lg: 3
                    col_sm: 12
                  - type: fields_table
                    col_lg: 9
                    fields_table:
                        name: default  

lists: 
    default: 
        bulk_actions: 
            - label: Supprimer les équipements sélectionnés
              icon: fas_trash-alt
              onclick: deleteSelectedObjects('list_id', $(this));
              btn_class: deleteSelectedObjects
        checkboxes: 1
        add_form_name: default
        sort_field: id
        sort_way: desc
        n: 25
        edit_btn: 1
        delete_btn: 1
        modal_view: default
        cols: 
            product: 
                label: Produit
                value: 
                    callback: 
                        method: displayProduct
                        params:
                            - nom_url
            type:
        
cards: 
    default: 
        fields: 
            - field: name
            - field: type
    large: 
        fields: 
            - label: Produit
              value: 
                  callback: displayProduct
            - field: type