table: be_equipment
controller: equipment
icon: desktop

header_list_name: default
header_edit_form: default

list_page_url: 
    controller: index
            
labels:
    name: équipement

objects:
    product:
        instance:
            bimp_object: unset
            dol_object: product
        cards: 
            default: 
                type: product_card
                
    contrat:
        instance:
            id_object: unset
            
    places: 
        relation: hasMany
        delete: 1
        instance: 
            bimp_object: BE_Place
            
    logiciels: 
        relation: hasMany
        delete: 1
        instance: 
            bimp_object: BE_EquipmentLogiciel
            
    facture: 
        instance: 
            bimp_object: unset
            dol_object: 
                module: compta/facture
                file: facture

associations:
    contrats:
        object: contrat
        display:
            default:
                type: callback
        label: Contrats
        input:
            type: search_list
            search_list:
                table: contrat
                field_return_value: a.rowid
                field_return_label: a.ref
                options:
                    default:
                        label: Recherche par référence contrat
                        fields_search: a.ref,a.rowid
                        join: societe s
                        join_on: a.fk_soc = s.rowid
                        join_return_label: s.nom
                        help: Entrez la référence ou l'ID d'un contrat
                    by_client:
                        label: Recherche par client
                        fields_search: s.nom,s.code_client
                        join: societe s
                        join_on: a.fk_soc = s.rowid
                        join_return_label: s.nom
                        help: Entrez le nom ou le code d'un client
                
fields: 
    id_product: 
        label: Produit
        type: id_object
        object: product
        default_value: 0
        input:
            type: search_list
            search_list: 
                table: product p
                field_return_value: p.rowid
                field_return_label: p.label,p.ref
                label_syntaxe: <label_2> - <label_1>
                join: product_extrafields pe
                join_on: p.rowid = pe.fk_object
                fields_search: p.rowid,p.ref,p.label,p.barcode
                filters: 
                    pe.serialisable: 1
            help: Entrez la référence, le nom, le code-barre ou l'id d'un produit pour effectuer une recherche
        display:
            default:
                type: field_value
            nom_url: 
                type: nom_url
            nom:
                type: nom
            card:
                type: card
                card: default
        sort_options:
            default:
                label: référence
                join_field: ref
            id:
                label: id du produit
            label:
                label: nom
                join_field: label
                
    product_label: 
        label: Désignation produit
        required_if: id_product=0
        display_if: 
            field_name: id_product
            show_values: 0,
        input: 
            help: Utilisez ce champ si cet équipement ne correspond à aucun produit enregistré
            
    type: 
        label: Type
        values: 
            array: types
        
    serial: 
        label: Numéro de série
        type: string
        size: 128
        required: 1
        search:
            type: value_part
            part_type: beginning
        
    ref_immo: 
        label: Réf. immobilisation
        default_value: ''
        
#   A suppr.
    available: 
        label: Disponible à la vente
        type: bool
        default_value: 1
        
#   A suppr.     
    return_available: 
        label: Disponible pour retour
        type: bool
        default_value: 1
        
    id_commande_line_return: 
        label: Ligne commande retour
        type: id
        default_value: 0
        
    date_purchase: 
        label: Date d'achat
        type: date
        required: 0
        search:
            type: date_range
        
    date_warranty_end: 
        label: Date de fin de garantie
        type: date
        required: 0
        search:
            type: date_range
        
    warranty_type: 
        label: Type de garantie
        type: string
        
    prix_achat:
        label: Prix d'achat HT
        type: money
        default_value: 0
        
    achat_tva_tx: 
        label: Tx TVA achat
        type: percent
        
    prix_vente_except: 
        label: Prix de vente exceptionnel (TTC)
        type: money
        default_value: 0
        input: 
            help: Laisser vide pour utiliser le prix de vente du produit
            
    vente_tva_tx: 
        label: Tx TVA vente
        type: percent
        
    prix_vente: 
        label: Prix de vente TTC
        type: money
        default_value: 0
        
    date_vente: 
        label: Date de vente
        type: datetime
        input: 
            type: hidden
            
    origin_element: 
        label: Element d'origine
        values: 
            array: origin_elements
    
    origin_id_element: 
        label: ID de l'élément d'origine
        type: int
        default_value: 0
        display: 
            default: 
                type: callback
                method: displayOriginElement
        display_if: 
            field_name: origin_element
            hide_values: 0
        input: 
            type: custom
            content: 
                callback: getOriginIdElementInput
        depends_on: origin_element
        
    id_facture:
        label: Facture
        type: id_object
        object: facture
        default_value: 0
        input: 
            type: hidden
        display: 
            default: 
                type: nom_url
                
    admin_login: 
        label: Login admin
        type: string
        size: 128
        required: 0
        searchable: 0
        
    admin_pword: 
        label: Mot de passe admin
        type: string
        size: 128
        required: 0
        searchable: 0        
        
    note:
        label: Note
        type: text
        size: 800
        required: 0
        sortable: 0
        searchable: 0
        
    id_package: 
        label: Package
        type: id_object
        object: package
        default_value: 0

fields_tables: 
    default: 
        panel: 1
        title: Informations
        icon: info-circle
        rows:
            - field: serial
            - field: ref_immo
            - label: Disponibilité
              value: 
                  callback: displayAvailability
            - label: Réservé / transfert en cours
              value: 
                  callback: displayReserved
            - field: date_purchase
            - field: prix_achat
            - field: achat_tva_tx
            - field: prix_vente_except 
            - field: warranty_type
            - field: date_warranty_end
            - field: note
              edit: 1
    
    objects: 
        panel: 1
        title: Objets liés
        icon: fas_link
        rows: 
            - label: Produit
              value: 
                  callback: 
                      method: displayProduct
                      params: 
                          - card
            - field: id_package
              display: nom_url
              show:
                  field_value: id_package
            - label: Type d'élément d'origine
              field: origin_element
            - field: origin_id_element
              label: Element d'origine
            - association: contrats
              edit: 1
    
    vente: 
        show: 
            callback: isSold
        panel: 1
        title: Vente
        icon: euro
        rows: 
            - field: prix_vente
              label: Vendu au prix TTC de
            - field: vente_tva_tx
            - field: date_vente
            - field: id_facture
            
views:
    infos:
        objects_change_reload: BE_Place
        edit_form: default
        delete_btn: 1
        rows:
            - cols: 
                  - type: fields_table
                    col_lg: 8
                    col_md: 7
                    col_sm: 12
                    fields_table:
                        name: default  
                        
                  - type: rows
                    col_lg: 4
                    col_md: 5
                    col_sm: 12
                    rows: 
                        - cols: 
                            - type: fields_table
                              fields_table: 
                                  name: objects
                        - cols: 
                            - type: fields_table
                              fields_table:
                                  name: vente
                              
    default: 
        objects_change_reload: BE_Place
        rows: 
            - cols: 
                - type: object_header
            - cols: 
                - type: view
                  view: 
                      name: infos
            - cols: 
                - type: list
                  list: 
                      name: default
                      children: places
                      
    reservations: 
        panel: 0
        rows: 
            - cols: 
                  - type: custom
                    custom: 
                        callback: renderReservationsList
                    
forms:
    default:
        rows: 
            - field: serial
            - field: id_product
              show: 
                  callback: isNotLoaded
            - field: product_label
            - field: type
#            - field: available
#            - field: return_available
            - field: date_purchase
            - field: prix_achat
            - field: achat_tva_tx
            - field: prix_vente_except
            - field: vente_tva_tx
            - field: origin_element
            - field: origin_id_element
            - field: warranty_type
            - field: date_warranty_end
            - field: note
            - association: contrats
            - object: places
            
    light:
        force_edit: 1
        rows:
            - field: serial
            - field: id_product
              show: 
                  callback: isNotLoaded
            - field: product_label
            - field: type
#            - field: available
            - field: date_purchase
            - field: warranty_type
            - field: date_warranty_end
            - association: contrats
            
    light_place: 
        rows: 
            - field: serial
            - field: id_product
            - field: product_label
            - field: type
#            - field: available
            - field: date_purchase
            - field: warranty_type
            - field: date_warranty_end
            - object: places
            
filters_panel: 
    default: 
        filters: 
            product: 
                field: id_product
            serial: 
                field: serial
            date_purchase: 
                field: date_purchase
            date_vente:
                field: date_vente
            type: 
                field: type
            in_package: 
                custom: 1
                field: in_package
                label: inclus dans un package
                type: check_list
                items: 
                    0: NON
                    1: OUI                
            place_position: 
                field: position
                child: places
            place_type: 
                field: type
                child: places
            place_entrepot: 
                field: id_entrepot
                child: places
            place_user: 
                field: id_user
                child: places
            place_client: 
                field: id_client
                child: places
            place_infos: 
                field: infos
                child: places
            place_date:
                field: date
                child: places
            
lists_cols: 
    id:
        label: ID
        field: id
        min_width: 60px
    ref_immo: 
        field: ref_immo
    type: 
        field: type
    product: 
        label: Produit
        value: 
            callback: 
                method: displayProduct
                params: 
                    - nom_url
        search: 
            type: value_part
    serial:
        field: serial
    place: 
        label: Emplacement
        value:
            callback: displayCurrentPlace
        search: 
            type: value_part
    place2: 
        label: Type emplacement
        value:
            callback: displayCurrentPlaceType
        search: 
            type: values
            input: 
                type: select
                options: 
                    options: 
                        array: typesPlace

    package: 
        field: id_package
        display: nom_url
    reserved: 
        label: Réservé / transfert en cours
        value: 
            callback: displayReserved
        search: 
            type: values
            input: 
                type: select
                options: 
                    options: 
                        array: hasReservations
    user_create:
        field: user_create
    prix_achat:
        field: prix_achat
        has_total: 1

lists:
    default: 
        checkboxes: 1
        configurable: 1
        bulk_actions: 
            - label: Supprimer les équipements sélectionnés
              icon: fas_trash-alt
              onclick: deleteSelectedObjects('list_id', $(this));
            - label: Générer étiquettes
              icon: fas_sticky-note
              onclick: setSelectedObjectsAction($(this), 'list_id', 'generateEtiquette', {}, null, null, true)
        filters_panel: default
        sort_field: date_create
        sort_way: desc
        n: 10
        list_filters: 
            callback:
                method: getListFilters
        extra_btn: 
            callback: getDefaultListExtraBtn
        add_form_name: default
        edit_btn: 1
        update_btn: 1
        delete_btn: 1
        view_btn: 1
        page_btn: 1
        total_row: 1
        modal_view: default
        cols:
            product: 
            serial:
            place2: 
            place: 
            package: 
            user_create:
            prix_achat:

    package: 
        enable_search: 0
        enable_sort: 0
        checkboxes: 1
        bulk_actions: 
            - label: Retirer les équipements sélectionnés
              icon: fas_trash-alt
              onclick: removeSelectedEquipmentsFromPackage('list_id', $(this));
            - label: Générer étiquettes
              icon: fas_sticky-note
              onclick: setSelectedObjectsAction($(this), 'list_id', 'generateEtiquette', {}, null, null, true)
        sort_field: serial
        sort_way: asc
        n: 20
        extra_btn: 
            callback: getPackageListExtraBtn
        cols: 
            pack_serial: 
                label: N° de série
                value: 
                    callback: 
                        method: getNomUrl
                        params: 
                            - 1
                            - 1
                            - 1
                            - default
            pack_product: 
                label: Produit
                value: 
                    callback: 
                        method: displayProduct
                        params: 
                            - nom_url
                            - 0
                            - 1
    
searches:
    default: 
        has_serial: 1
        fields_search: 
            - a.product_label
            - a.serial
        
cards: 
    default: 
        view_btn: 1
        fields: 
            - icon: fas_box
              label: Produit
              value: 
                  callback: 
                      method: displayProduct
                      params: 
                          - nom_url
            - icon: barcode
              field: serial
