table: be_equipment
controller: equipment

labels:
    name: équipement

objects:
    product:
        relation: hasOne
        instance:
            dol_object: product
            id_object:
                field_value: id_product
        cards: 
            default:
                title:
                    object_prop: label
                image: 
                    callback: 
                        method: getProductImageUrl
                        params: 
                            id_product:
                                field_value: id_product
                        instance: BimpTools
                        is_static: 1
                fields:
                    - label: Réf.
                      prop: ref
                view_btn: 1
                    
    contrat:
        instance:
            dol_object: contrat
            
    places: 
        instance: 
            bimp_object: BE_Place
            
    logiciels: 
        relation: hasMany
        delete: 1
        instance: 
            bimp_object: BE_EquipmentLogiciel

associations:
    contrats:
        object: contrat
        display:
            default:
                type: callback
                
        label: Contrats
        input:
            type: search_list
            search_list:
                table: contrat c
                field_return_value: c.rowid
                field_return_label: c.ref
                options:
                    default:
                        label: Recherche par référence contrat
                        fields_search: c.ref,c.rowid
                        join: societe s
                        join_on: c.fk_soc = s.rowid
                        join_return_label: s.nom
                        help: Entrez la référence ou l'ID d'un contrat
                    by_client:
                        label: Recherche par client
                        fields_search: s.nom,s.code_client
                        join: societe s
                        join_on: c.fk_soc = s.rowid
                        join_return_label: s.nom
                        help: Entrez le nom ou le code d'un client
                
fields: 
    id_product: 
        label: Produit
        type: id_object
        required: 1
        object: product
        input:
            type: search_list
            search_list: 
                table: product p
                field_return_value: p.rowid
                field_return_label: p.label,p.ref
                label_syntaxe: <label_2> - <label_1>
                join: product_extrafields pe
                join_on: p.rowid = pe.fk_object
                fields_search: p.rowid,p.ref,p.label,p.barcode
                filters: 
                    pe.serialisable: 1
            help: Entrez la référence, le nom, le code-barre ou l'id d'un produit pour effectuer une recherche
        display:
            default:
                type: field_value
            nom_url: 
                type: nom_url
            nom:
                type: nom
            card:
                type: card
                card: default
        sort_options:
            default:
                label: référence
                join_field: ref
            id:
                label: id du produit
            label:
                label: nom
                join_field: label
                
    type: 
        label: Type
        values: 
            array: types
        
    serial: 
        label: Numéro de série
        type: string
        size: 128
        required: 1
        search:
            type: value_part
            part_type: beginning
        
    reserved:
        label: Réservé / transfert en cours
        type: bool
        default_value: 0
        
    date_purchase: 
        label: Date d'achat
        type: date
        required: 0
        search:
            type: date_range
        
    date_warranty_end: 
        label: Date de fin de garantie
        type: date
        required: 0
        search:
            type: date_range
        
    warranty_type: 
        label: Type de garantie
        type: string
        values: 
            array: warranty_types
            
    prix_achat:
        label: Prix d'achat
        type: money
        default_value: 0
        
    origin_element: 
        label: Element d'origine
        values: 
            array: origin_elements
    
    origin_id_element: 
        label: ID de l'élément d'origine
        type: int
        default_value: 0
        display: 
            default: 
                type: callback
                method: displayOriginElement
        display_if: 
            field_name: origin_element
            hide_values: 0
        input: 
            type: custom
            content: 
                callback: getOriginIdElementInput
        depends_on: origin_element
                
    admin_login: 
        label: Login admin
        type: string
        size: 128
        required: 0
        searchable: 0
        
    admin_pword: 
        label: Mot de passe admin
        type: string
        size: 128
        required: 0
        searchable: 0        
        
    note:
        label: Note
        type: text
        size: 800
        required: 0
        sortable: 0
        searchable: 0

fields_tables: 
    default: 
        panel: 1
        title: Informations
        rows:
            - field: id_product
              display: card
            - field: serial
            - field: date_purchase
            - field: prix_achat
            - field: warranty_type
            - field: date_warranty_end
            - field: reserved
              edit: 1
            - label: Type d'élément d'origine
              field: origin_element
            - field: origin_id_element
              label: Element d'origine
            - field: note
              edit: 1
            - association: contrats
              edit: 1
              
views:
    default:
        title: nom
        edit_form: default
        delete_btn: 1
        rows:
            - cols: 
                  - type: object_common_fields
                    col_lg: 3
                    col_sm: 12
                  - type: fields_table
                    col_lg: 9
                    fields_table:
                        name: default           
                        
forms:
    default:
        rows: 
            - field: id_product
            - field: serial
            - field: type
            - field: date_purchase
            - field: prix_achat
            - field: origin_element
            - field: origin_id_element
            - field: warranty_type
            - field: date_warranty_end
            - field: reserved
            - field: admin_login
            - field: admin_pword
            - association: contrats
            
list:
    checkboxes: 1
    bulk_actions: 
        - label: Supprimer les équipements sélectionnés
          icon: trash
          onclick: deleteSelectedObjects('list_id', $(this));
          btn_class: deleteSelectedObjects
    sort_field: id_product
    sort_way: asc
    n: 10
    cols:
        id:
            label: ID
            field: id
            min_width: 60px
        type: 
            field: type
        product: 
            field: id_product
            display: nom_url
        serial:
            field: serial
        purchase:
            field: date_purchase
        warranty_type:
            field: warranty_type
        warranty_end:
            field: date_warranty_end
        reserved: 
            label: Réservé
            field: reserved
    add_form_name: default
    edit_btn: 1
    delete_btn: 1
    view_btn: 1
    page_btn: 1
    modal_view: default
    
searches:
    default: 
        has_serial: 1
        fields_search: a.serial
        
cards: 
    default: 
        view_btn: 1
        fields: 
            - icon: fa5_box
              field: id_product
              display: nom_url
            - icon: barcode
              field: serial