table: be_equipment
controller: equipment
icon: desktop

list_page_url: 
    controller: index
            
labels:
    name: équipement

objects:
    product:
        relation: hasOne
        instance:
            dol_object: product
            id_object:
                field_value: id_product
        cards: 
            default: 
                type: product_card
                
    contrat:
        instance:
            dol_object: contrat
            
    places: 
        instance: 
            bimp_object: BE_Place
            
    logiciels: 
        relation: hasMany
        delete: 1
        instance: 
            bimp_object: BE_EquipmentLogiciel
            
    facture: 
        relation: hasOne
        delete: 0
        instance: 
            dol_object: 
                module: compta/facture
                file: facture
            id_object: 
                field_value: id_facture

associations:
    contrats:
        object: contrat
        display:
            default:
                type: callback
        label: Contrats
        input:
            type: search_list
            search_list:
                table: contrat c
                field_return_value: c.rowid
                field_return_label: c.ref
                options:
                    default:
                        label: Recherche par référence contrat
                        fields_search: c.ref,c.rowid
                        join: societe s
                        join_on: c.fk_soc = s.rowid
                        join_return_label: s.nom
                        help: Entrez la référence ou l'ID d'un contrat
                    by_client:
                        label: Recherche par client
                        fields_search: s.nom,s.code_client
                        join: societe s
                        join_on: c.fk_soc = s.rowid
                        join_return_label: s.nom
                        help: Entrez le nom ou le code d'un client
                
fields: 
    id_product: 
        label: Produit
        type: id_object
        object: product
        default_value: 0
        input:
            type: search_list
            search_list: 
                table: product p
                field_return_value: p.rowid
                field_return_label: p.label,p.ref
                label_syntaxe: <label_2> - <label_1>
                join: product_extrafields pe
                join_on: p.rowid = pe.fk_object
                fields_search: p.rowid,p.ref,p.label,p.barcode
                filters: 
                    pe.serialisable: 1
            help: Entrez la référence, le nom, le code-barre ou l'id d'un produit pour effectuer une recherche
        display:
            default:
                type: field_value
            nom_url: 
                type: nom_url
            nom:
                type: nom
            card:
                type: card
                card: default
        sort_options:
            default:
                label: référence
                join_field: ref
            id:
                label: id du produit
            label:
                label: nom
                join_field: label
                
    product_label: 
        label: Désignation produit
        required_if: id_product=0
        display_if: 
            field_name: id_product
            show_values: 0,
        input: 
            help: Utilisez ce champ si cet équipement ne correspond à aucun produit enregistré
            
    type: 
        label: Type
        values: 
            array: types
        
    serial: 
        label: Numéro de série
        type: string
        size: 128
        required: 1
        search:
            type: value_part
            part_type: beginning
        
    date_purchase: 
        label: Date d'achat
        type: date
        required: 0
        search:
            type: date_range
        
    date_warranty_end: 
        label: Date de fin de garantie
        type: date
        required: 0
        search:
            type: date_range
        
    warranty_type: 
        label: Type de garantie
        type: string
            
    prix_achat:
        label: Prix d'achat
        type: money
        default_value: 0
        
    prix_vente_except: 
        label: Prix de vente exceptionnel (TTC)
        type: money
        default_value: 0
        input: 
            help: Laisser vide pour utiliser le prix de vente du produit
        
    prix_vente: 
        label: Prix de vente
        type: money
        default_value: 0
        
    date_vente: 
        label: Date de vente
        type: datetime
        input: 
            type: hidden
            
    origin_element: 
        label: Element d'origine
        values: 
            array: origin_elements
    
    origin_id_element: 
        label: ID de l'élément d'origine
        type: int
        default_value: 0
        display: 
            default: 
                type: callback
                method: displayOriginElement
        display_if: 
            field_name: origin_element
            hide_values: 0
        input: 
            type: custom
            content: 
                callback: getOriginIdElementInput
        depends_on: origin_element
        
    id_facture:
        label: Facture
        type: id_object
        object: facture
        default_value: 0
        input: 
            type: hidden
        display: 
            default: 
                type: nom_url
                
    admin_login: 
        label: Login admin
        type: string
        size: 128
        required: 0
        searchable: 0
        
    admin_pword: 
        label: Mot de passe admin
        type: string
        size: 128
        required: 0
        searchable: 0        
        
    note:
        label: Note
        type: text
        size: 800
        required: 0
        sortable: 0
        searchable: 0

fields_tables: 
    default: 
        panel: 1
        title: Informations
        icon: info-circle
        rows:
            - label: Produit
              value: 
                  callback: 
                      method: displayProduct
                      params: 
                          - card
            - field: serial
            - field: date_purchase
            - field: prix_achat
            - field: prix_vente_except 
            - field: warranty_type
            - field: date_warranty_end
            - label: Réservé / transfert en cours
              value: 
                  callback: displayReserved
            - label: Type d'élément d'origine
              field: origin_element
            - field: origin_id_element
              label: Element d'origine
            - field: note
              edit: 1
            - association: contrats
              edit: 1
              
    vente: 
        show: 
            callback: isSold
        panel: 1
        title: Vente
        icon: euro
        rows: 
            - field: prix_vente
              label: Vendu au prix de
            - field: date_vente
            - field: id_facture
            
views:
    default:
        edit_form: default
        delete_btn: 1
        rows:
            - cols: 
                  - type: fields_table
                    col_lg: 8
                    col_md: 7
                    col_sm: 12
                    fields_table:
                        name: default  
                        
                  - type: rows
                    col_lg: 4
                    col_md: 5
                    col_sm: 12
                    rows: 
                        - cols: 
                            - type: object_common_fields
                        - cols: 
                            - type: fields_table
                              fields_table:
                                  name: vente
                                  
    reservations: 
        panel: 0
        rows: 
            - cols: 
                  - type: custom
                    custom: 
                        callback: renderReservationsList
                    
forms:
    default:
        rows: 
            - field: id_product
            - field: product_label
            - field: serial
            - field: type
            - field: date_purchase
            - field: prix_achat
            - field: prix_vente_except
            - field: origin_element
            - field: origin_id_element
            - field: warranty_type
            - field: date_warranty_end
            - field: note
            - association: contrats        
            - object: places
            
    light:
        rows:
            - field: id_product
            - field: product_label
            - field: serial
            - field: type
            - field: date_purchase
            - field: warranty_type
            - field: date_warranty_end
            - association: contrats     
            
list:
#    checkboxes: 1
#    bulk_actions: 
#        - label: Supprimer les équipements sélectionnés
#          icon: trash
#          onclick: deleteSelectedObjects('list_id', $(this));
#          btn_class: deleteSelectedObjects
    sort_field: id_product
    sort_way: asc
    n: 10
    cols:
        id:
            label: ID
            field: id
            min_width: 60px
        type: 
            field: type
        product: 
            label: Produit
            value: 
                callback: 
                    method: displayProduct
                    params: 
                        - nom_url
            search: 
                type: value_part
        serial:
            field: serial
        place: 
            label: Emplacement
            value: 
                callback: displayCurrentPlace
            search: 
                type: value_part
        reserved: 
            label: Réservé / transfert en cours
            value: 
                callback: displayReserved
            search: 
                type: values
                input: 
                    type: select
                    options: 
                        options: 
                            array: hasReservations
    add_form_name: default
    edit_btn: 1
#    delete_btn: 1
    view_btn: 1
    page_btn: 1
    modal_view: default
    
searches:
    default: 
        has_serial: 1
        fields_search: a.serial
        
cards: 
    default: 
        view_btn: 1
        fields: 
            - icon: fa5_box
              label: Produit
              value: 
                  callback: 
                      method: displayProduct
                      params: 
                          - nom_url
            - icon: barcode
              field: serial