table: bimp_relance_clients
common_fields: 0
icon: fas_comment-dollar


    
entity_name: bimprelance

controller: relance_clients

header_list_name: default
list_page_url: 
    module: bimpcore
    controller: clients
    url_params: 
        tab: relances
    
labels: 
    name: relance clients
    name_plur: relances clients
    is_female: 1
    
nom_url: 
    syntaxe: <name>
    card: default
    modal_view: ''
    
objects: 
    lines: 
        relation: hasMany
        delete: 1
        instance: 
            bimp_object: 
                module: bimpcommercial
                name: BimpRelanceClientsLine
                
fields: 
    id_user: 
        label: Auteur
        type: id_object
        object: user
        
    date: 
        label: Date de création
        type: datetime
        
    mode: 
        label: Mode
        values: 
            array: modes
        
    date_prevue: 
        label: Date d'envoi prévue
        type: date
        
    note: 
        label: Note
        type: text          
        hashtags: 1
     
forms: 
    edit: 
        rows: 
            - field: date_prevue
            - custom: 1
              label: Mise à jour des date prévues des lignes de relances
              input_name: lines_update_option
              input: 
                  type: select
                  options: 
                      all: Toutes
                      unchanged: Seulement celles ayant une date identique à la date prévue initiale
                      changed: Seulement celles ayant une date différente de la date prévue initiale
                      none: Aucune
                      
    unpaid_file: 
        rows: 
            - custom: 1 
              label: Nom du fichier
              input_name: file_name
              input: 
                  type: text
            - custom: 1
              label: Du
              input_name: date_from
              input: 
                  type: date
            - custom: 1
              label: Au
              input_name: date_to
              input: 
                  type: date
                      
fields_tables: 
    default: 
        panel: 0
        rows: 
            - field: date
            - field: date_prevue
            - field: mode
            - field: id_user
              display: nom_url
              
views: 
    default: 
        rows: 
            - cols: 
                - type: fields_table
                  fields_table: default
                  col_lg: 6
            - cols: 
                - type: list
                  list: 
                      name: relance
                      children: lines
                
filters: 
    id_user: 
        type: user
        
filters_panels: 
    default: 
        filters: 
            id_user:
            date_prevue: 
            date:
            mode:
                
lists: 
    default: 
        title: Relances paiements clients
        configurable: 1
        objects_change_reload: Bimp_Client,BimpRelanceClientsLine
        filters_panel: default
        sort_field: id
        sort_way: desc
        n: 10
        extra_btn: 
            callback: getListExtraButtons
        header_buttons: 
            callback: getListExtraHeaderButtons
        before_content: 
            callback: renderBeforeListContent
        edit_btn: 1
        edit_form: edit
        page_btn: 1
        cols: 
            id_user: 
            date:
            date_prevue:
            mode:
            status: 
                label: Statuts
                value: 
                    callback: displayStatus
        
cards: 
    default:
        fields: 
            - field: date
            - field: date_prevue
            - field: mode
            - field: id_user
            - field: note