
table: facture_fourn_det
primary: rowid
common_fields: 0

parent_module: bimpcommercial
parent_object: Bimp_FactureFourn
parent_id_property: fk_facture_fourn

labels: 
    name: achat
    
objects:
    facture_fourn: 
        instance: 
            id_object: 
                field_value: fk_facture_fourn
                
    facture_fourn_line: 
        relation: hasOne
        delete: 0
        instance: 
            bimp_object: 
                module: bimpcommercial
                name: Bimp_FactureFournLine
                
    fournisseur: 
        instance: 
            id_object: 
                field_value: id_fourn
                
    product: 
        instance: 
            id_object: 
                field_value: fk_product
                
fields: 
#    Champs facturedet: 
    fk_facture_fourn: 
        label: Facture fournisseur
        type: id_parent
        object: facture_fourn
        
    fk_product: 
        label: Produit
        type: id_object
        object: product
        
    subprice: 
        label: Prix unitaire HT
        type: money
        
    tva_tx: 
        label: Taux de TVA
        type: percent
        
    qty: 
        label: Quantité
        type: qty
        decimals: 3
        
    remise_percent: 
        label: Remise (%)
        type: percent
        
    total_ht: 
        label: Total HT
        type: money
        
    total_tva: 
        label: Total TVA
        type: money
        
    total_ttc: 
        label: Total TTC
        type: money
        
    rang: 
        label: Position
        type: int
        unsigned: 1
        
#    Champs extra: 
    
    id_fourn: 
        label: Fournisseur
        type: id_object
        object: fournisseur
        extra: 1
    
    ref_fourn: 
        label: Ref. fournisseur
        extra: 1
        
    date: 
        label: Date
        extra: 1
        type: date
        
    id_entrepot: 
        label: Entrepot
        extra: 1
        type: id_object
        object: bimp_entrepot
        values: 
            array: entrepots
        sort_options: 
            default: 
                label: Par référence
                join_field: ref
                join_table: entrepot
                join_on: rowid
        
    secteur:
        label: Secteur
        extra: 1
        values: 
            array: secteurs
            
    categorie:
        label: Categorie
        extra: 1
        type: int
        values:
            callback: 
                method: getProductsTagsByTypeArray
                params:
                    - categorie
                    
    collection:
        label: Collection
        extra: 1
        type: int
        values:
            callback: 
                method: getProductsTagsByTypeArray
                params:
                    - collection
                    
    nature:
        label: Nature
        extra: 1
        type: int
        values:
            callback: 
                method: getProductsTagsByTypeArray
                params:
                    - nature
                    
    famille:
        label: Famille
        extra: 1
        type: int
        values:
            callback: 
                method: getProductsTagsByTypeArray
                params:
                    - famille
                    
    gamme:
        label: Gamme
        extra: 1
        type: int
        values:
            callback: 
                method: getProductsTagsByTypeArray
                params:
                    - gamme
        
fields_tables: 
    infos: 
        title: Infos
        icon: fas_info-circle
        rows: 
            - field: date
            - field: fk_product
              display: nom_url
            - field: ref_fourn
            - field: fk_facture_fourn
              display: card
              
    montants: 
        title: Montants
        icon: fas_euro-sign
        rows: 
            - field: qty
            - field: subprice
            - field: tva_tx
            - field: remise_percent
            - field: total_ht
            - field: total_tva
            - field: total_ttc
            
views: 
    default: 
        rows: 
            - cols: 
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: infos
                
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: montants
            
filters_panels: 
    default: 
        filters: 
            dates: 
            parent:fk_statut: 
                label: Statut facture
            parent:entrepot: 
            parent:ef_type:
            fk_product:
            id_fourn: 
            ref_fourn: 
            product:price:
            qty: 
            total_ht: 
            tva_tx:
            product:gamme: 
            product:categorie:
            product:collection:
            product:nature:
            product:famille:
        
lists_cols: 
    ref_const: 
        label: Ref. Constructeur
        value: 
            callback: displayRefConst    
    
lists: 
    default: 
        title: Achats de produits
        total_row: 1
        configurable: 1
        n: 10
        sort_field: date
        sort_way: desc
        filters_panel: default
        modal_view: default
        list_filters: 
            - name: fk_product
              filter: 
                  operator: '>' 
                  value: 0
        cols: 
            id_fourn: 
            ref_const: 
            product:collection:
            product:categorie:
            product:label: 
            qty:         
            total_ht:

stats_lists_cols: 
    tot_qty: 
        label: Qté totale
        type: sum
        field: qty
        data_type: float
        decimals: 2
    tot_brouillon: 
        label: Tot. Fac. brouillons
        type: sum
        data_type: money
        decimals: 2
        with_styles: 1
        field: total_ttc
        filters: 
            f.fk_statut: 0
    tot_valide: 
        label: Tot. Fac. validées
        type: sum
        field: total_ttc
        data_type: money
        decimals: 2
        with_styles: 1
        filters: 
            f.fk_statut: 
                in: 
                    - 1
                    - 2
    tot_abandon: 
        label: Tot. Fac. abandonnées
        type: sum
        field: total_ttc
        data_type: money
        decimals: 2
        with_styles: 1
        filters: 
            f.fk_statut: 3
                    
stats_lists: 
    default: 
        n: 50
        configurable: 1
        joins: 
            facture_fourn: 
                table: facture_fourn
                alias: f
                on: f.rowid = a.fk_facture_fourn
        filters_panel: default
        group_by_options: 
            - id_fourn
            - fk_product
            - id_entrepot
            - secteur
            - categorie
            - collection
            - nature
            - famille
            - gamme
        cols: 
            tot_qty: 
            tot_brouillon:
            tot_valide:
            tot_abandon: 
