extends: 
    module: bimpcommercial
    object_name: FournObjectLine
    
table: bimp_commande_fourn_line

parent_module: bimpcommercial
parent_object: Bimp_CommandeFourn

labels:
    name: ligne de commande fournisseur
    name_plur: lignes de commande fournisseur
    is_female: 1
    
objects: 
    line: 
        relation: hasOne
        delete: 0
        instance: 
            dol_object: 
                module: fourn
                file: fournisseur.commande
                class: CommandeFournisseurLigne
            id_object: 
                field_value: id_line

    dol_line: 
        instance: 
            bimp_object: 
                name: CommandeFournDolLine
                
fields: 
    id_obj: 
        label: Commande
        search: 
            input: 
                type: search_list
                search_list: 
                    table: commande_fournisseur
                    fields_search: rowid,ref
                    field_return_label: ref
                    field_return_value: rowid
                    
    receptions: 
        label: Réception
        type: json
        
    qty_modif: 
        label: Qté modifiée
        type: qty
        min: none
        max: none
        decimals: 3
        unsigned: 0
        default_value: 0
        
    # Tous les champs qty_xxx suivants sont uniquement à titre indicatifs 
    # et servent pour la liste "general" (Ne pas utiliser en PHP)   
    # Attention: les quantités sont en valeur absolues (toujours positifs, même pour les retours, sauf qty_total) . 
    
    qty_total: 
        label: Qté Totale
        type: qty
        default_value: 0
        display: 
            badge: 
                type: callback
                method: displayQty
                params: 
                    - total
        
    qty_received: 
        label: Qté reçue
        type: qty
        default_value: 0
        display: 
            badge: 
                type: callback
                method: displayQty
                params: 
                    - received
        
    qty_to_receive: 
        label: Qté à réceptionner
        type: qty
        default_value: 0
        display: 
            badge: 
                type: callback
                method: displayQty
                params: 
                    - to_receive
        
forms: 
    qty_modified: 
        rows: 
            - custom: 1
              label: Quantité totale reçue
              input_name: qty_modified
              content: 
                  callback: renderQtyModifiedInput
        
views: 
    reception: 
        title: Réceptionner
        icon: fas_arrow-circle-down
        rows: 
            - cols: 
                - type: custom
                  custom: 
                      callback: renderReceptionForm
                     
filters_panels: 
    default: 
        filters: 
            product: 
                field: fk_product
                child: dol_line
            date: 
                field: date_commande
                child: parent
            entrepot: 
                field: entrepot
                child: parent
            commande_fourn: 
                label: Commande
                field: id_obj
            commande_status:
                field: fk_statut
                child: parent
            invoice_status:
                field: invoice_status
                child: parent
            qty_total: 
                field: qty_total
            qty_to_receive:
                field: qty_to_receive
            qty_received:
                field: qty_received
            categ1:
                custom: 1
                label: Catégorie (1)
                field: categ1
                type: value
                input:
                    type: select
                    options: 
                        callback: getCategoriesArray
            categ2:
                custom: 1
                label: Catégorie (2)
                field: categ2
                type: value
                input:
                    type: select
                    options: 
                        callback: getCategoriesArray
            categ3:
                custom: 1
                label: Catégorie (3)
                field: categ3
                type: value
                input:
                    type: select
                    options: 
                        callback: getCategoriesArray
                
lists_cols: 
    qties: 
        label: Quantités
        value: 
            callback: displayQties
    commande_client: 
        label: Commmande client
        value: 
            callback: displayCommandeClient
    qty_total: 
        field: qty_total
        display: badge
        min_width: 60px
        max_width: 60px
    qty_received: 
        field: qty_received
        display: badge
        min_width: 60px
        max_width: 60px
    qty_to_receive: 
        label: Qté à récep. 
        field: qty_to_receive
        display: badge
        min_width: 60px
        max_width: 60px
    date: 
        field: date_commande
        child: parent
            
lists: 
    default:
        extends: default
        objects_change_reload: Bimp_CommandeFourn,ObjectLineRemise,BR_Reservation,BL_CommandeFournReception,BL_FactureFourn
        cols: 
            commande_client:
                
    logistique:
        extends: default
        objects_change_reload: Bimp_CommandeFourn,ObjectLineRemise,BR_Reservation,BL_CommandeFournReception,BL_FactureFourn
        title: Logistique produits / services
        icon: fas_truck-loading
        configurable: 1
        item_checkbox: 1
        after_list_content: unset
        header_buttons: unset
        bulk_actions: 
            callback: getLogistiqueBulkActions
        extra_btn: 
            callback: getLogistiqueExtraButtons
        cols: 
            desc:
            pu_ht: unset
            tva: unset
            pa_ht: unset
            qty: unset
            qties: 
            remise: unset
            total_ttc: unset
            margin: unset
            commande_client:
                
    general:
        list_filters: 
            - name: type
              filter: 
                  in: 1,3
        configurable: 1
        filters_panel: default
        filters_panel_open: 1
        sort_field: id
        sort_way: desc
        n: 25
        extra_btn: 
            callback: getGeneralListExtraButtons
        cols: 
            entrepot: 
                label: Entrepot
                field: entrepot
                child: parent
                display: ref
                min_width: 60px
                max_width: 60px
            commande_status: 
                label: St Cmd
                field: fk_statut
                child: parent
                display: icon
                min_width: 45px
                max_width: 45px
            invoice_status:
                label: Fac. Cmd
                field: invoice_status
                child: parent
                display: icon
                min_width: 45px
                max_width: 45px
            commande_fourn: 
                label: Commande
                field: id_obj
                display: nom_url
            desc:
                value: 
                    callback: 
                        method: displayLineData
                        params:
                           - desc_light
            dl_pu_ht: 
                field: subprice
                child: dol_line
            qty_total:
            qty_to_receive:
