extends: 
    module: bimpcommercial
    object_name: BimpComm

dol_object: 
    instance: 
        dol_object: 
            module: comm/propal
            file: propal
            
table: propal
controller: propal
icon: fas_file-invoice
list_page_url: 
    controller: propals

labels: 
    name: proposition commerciale
    name_plur: propositions commerciales
    is_female: 1
    
objects: 
    lines: 
        instance: 
            bimp_object: Bimp_PropalLine
            
    entrepot: 
        instance: 
            id_object:
                field_value: entrepot
                
    files:
        list: 
            filters:
                parent_object_name: Bimp_Propal
        add_form: 
            values:
                fields: 
                    parent_object_name: Bimp_Propal
                
fields:
    datec: 
        label: Créée le
        type: datetime
    datep: 
        label: Date
        dol_prop: date
        type: date
        input: 
            display_now: 1
        required: 1
    fin_validite: 
        label: Date de fin de validité
        type: date
    date_livraison: 
        label: Date de livraison
        type: date
    libelle: 
        label: Libellé
        dol_extra_field: 1
        required: 1
    ef_type: 
        label: Secteur
        dol_extra_field: 1
        values: 
            array: secteurs
        required: 1
    model_pdf: 
        default_value: bimpdevis
    pdf_hide_reduc: 
        label: Masquer les remises dans le PDF
        dol_extra_field: 1
        type: bool
        default_value: 0
        sortable: 0
    pdf_hide_total: 
        label: Masquer les totaux dans le PDF
        dol_extra_field: 1
        type: bool
        default_value: 0 
        sortable: 0
    pdf_hide_ref:
        label: Masquer les références des produits dans le PDF
        dol_extra_field: 1
        type: bool
        default_value: 0
        sortable: 0
    pdf_hide_ttc:
        label: Masquer le TTC dans le PDF
        dol_extra_field: 1
        type: bool
        default_value: 0
        sortable: 0
        
forms: 
    default: 
        rows: 
            - custom: 1
              input_name: id_user_commercial
              label: Commercial suivi proposition
              input: 
                  type: search_user
              show: 
                  callback: isNotLoaded
              value: 
                  prop: 
                      object: 
                          global: user
                      name: id
            - field: entrepot
            - field: ef_type
            - field: fk_soc
              show: 
                  callback: isNotLoaded
            - field: ref_client
            - field: libelle
            - field: fk_input_reason
              show: 
                  callback: isEditable
            - field: fk_cond_reglement
              show: 
                  callback: isEditable
            - field: fk_mode_reglement
              show: 
                  callback: isEditable
            - field: datep
              show: 
                  callback: isEditable
            - custom: 1
              label: Durée de validité (en jours)
              show: 
                  callback: isNotLoaded
              value: 
                  callback: getDureeValidite
              input_name: duree_validite
              data_type: int
              min: 0
              input: 
                  type: qty
            - field: fk_availability
              show: 
                  callback: isEditable
            - field: date_livraison
            - field: model_pdf
            - field: pdf_hide_reduc
            - field: pdf_hide_total
            - field: pdf_hide_ref
            - field: pdf_hide_ttc
            - field: note_private
            - field: note_public
            
    close: 
        rows: 
            - custom: 1
              label: Nouveau statut
              data_type: int
              input_name: new_status
              input: 
                  type: select
                  options: 
                      array: closeStatus
            - custom: 1
              label: Note
              data_type: text
              input_name: note
              input: 
                  type: textarea
                  rows: 3
                  auto_expand: 1
              value: 
                  field_value: note_private
                  
    duplicate_propal:
        rows: 
            - field: entrepot
            - field: fk_soc
            - field: libelle
            - field: ef_type
            - field: date_livraison
            
fields_tables: 
    infos: 
        rows: 
            - field: libelle
              edit: 1
            - field: fk_statut
            - field: entrepot
              display: nom_url
              edit: 1
            - field: ef_type
              edit: 1
            - field: fk_input_reason
              edit: 
                  callback: isEditable
            - field: datep
              edit: 
                  callback: isEditable
            - field: fin_validite
              edit: 
                  callback: isEditable
            - field: date_livraison
              edit: 1
            - field: fk_availability
              edit: 
                  callback: isEditable
    
    client: 
        rows: 
            - field: fk_soc
              display: card
            - field: ref_client
              edit: 
                  callback: isEditable
            - label: Remises client
              value: 
                  callback: displayRemisesClient
                  
    payment:
        rows:
            - field: fk_cond_reglement
              edit: 
                  callback: isEditable
            - field: fk_mode_reglement
              edit: 
                  callback: isEditable
                
    pdf: 
        rows: 
            - field: pdf_hide_reduc
              edit: 1
            - field: pdf_hide_total
              edit: 1
            - field: pdf_hide_ref
              edit: 1
            - field: pdf_hide_ttc
              edit: 1
            - label: Fichier PDF
              value: 
                  callback: displayPDFButton
                  
    totals: 
        rows: 
            - label: Remises
              value: 
                  callback: displayTotalRemises
            - field: total_ht
            - field: tva
            - field: total
            
views: 
    default: 
        objects_change_reload: Bimp_PropalLine,ObjectLineRemise,BimpFile
    content: 
        objects_change_reload: Bimp_PropalLine,ObjectLineRemise,BimpFile
    full: 
        objects_change_reload: Bimp_PropalLine,ObjectLineRemise,BimpFile
     
lists_cols: 
    libelle: 
        field: libelle
    secteur:
        field: ef_type
    entrepot: 
        field: entrepot
        display: nom_url
    commercial: 
        label: Commercial
        value: 
            callback: displayCommercial
        search: 
            input: 
                type: search_user
    date_create: 
        field: datec
    date: 
        field: datep
    fin: 
        field: fin_validite
        label: Fin validité
    livraison: 
        field: date_livraison
        label: Livraison
           
filters_panels: 
    default: 
        filters: 
            20: 
                field: datec
            21: 
                field: datep
            22: 
                field: date_livraison
            23: 
                field: libelle
            24: 
                field: ef_type
                
lists: 
    default: 
        title: Propositions commerciales
        icon: fas_file-invoice
        configurable: 1
        checkboxes: 1
        filters_panel: default
        bulk_actions:
            - label: supprimer les propositions commerciales sélectionnées
              icon: fas_trash-alt
              onclick: deleteSelectedObjects('list_id', $(this))
        list_filters: 
            callback: getListFilters
        n: 10
        add_form_name: default
        add_form_values: 
            fields: 
                entrepot: 
                    request: id_entrepot
                fk_soc:
                    request: id_client
        edit_btn: 1
        edit_form: default
        delete_btn: 
            callback: isDeletable
        modal_view: full
        page_btn: 1
        cols: 
            ref: 
            libelle: 
            statut: 
            date_create: 
            soc:
            entrepot: 
            secteur: 
            commercial:
            total_ttc: 
        
    user: 
        extends: default
        cols: 
            commercial: unset
                
    client: 
        extends: default
        cols: 
            client: unset
                
cards: 
    default: 
        title: 
            field_value: ref
        status: fk_statut
        view_btn: 1
        fields: 
            - field: total
            - label: Fichier PDF
              value: 
                  callback: displayPDFButton
        
searches:
    default: 
        fields_search: 
            - a.ref
            - ef.libelle
            - s.nom
        joins:
            - table: propal_extrafields
              on: a.rowid = ef.fk_object
              alias: ef
            - table: societe
              on: a.fk_soc = s.rowid
              alias: s
