table: relance_clients
common_fields: 0

labels: 
    name: relance clients
    name_plur: relances clients
    is_female: 1
    
nom_url: 
    syntaxe: <name>
    card: default
    modal_view: ''
    
objects: 
    lines: 
        relation: hasMany
        delete: 1
        instance: 
            bimp_object: 
                module: bimpcommercial
                name: BimpRelanceClientsLine
                
fields: 
    id_user: 
        label: Auteur
        type: id_object
        object: user
        
    date: 
        label: Date de création
        type: datetime
        
    mode: 
        label: Mode
        values: 
            array: modes
            
    pdf_file: 
        label: Fichier PDF
        
    date_prevue: 
        label: Date d'envoi prévue
        type: date
     
fields_tables: 
    default: 
        panel: 0
        rows: 
            - field: date
            - field: date_prevue
            - field: mode
            - field: id_user
              display: nom_url
views: 
    default: 
        rows: 
            - cols: 
                - type: fields_table
                  fields_table: default
                  col_lg: 6
            - cols: 
                - type: list
                  list: 
                      name: relance
                      children: lines
                
filters_panels: 
    default: 
        filters: 
            user: 
                field: id_user
                type: user
            date_prevue: 
                field: date_prevue
            date: 
                field: date
            mode: 
                field: mode
                
lists: 
    default: 
        title: Relances paiements clients
        objects_change_reload: BimpRelanceClientsLine
        filters_panel: default
        sort_field: id
        sort_way: desc
        n: 10
        extra_btn: 
            callback: getListExtraButtons
        header_buttons: 
            callback: getListExtraHeaderButtons
        cols: 
            user: 
                field: id_user
                display: nom_url
            date: 
                field: date
            date_prevue: 
                field: date_prevue
            mode: 
                field: mode
            status: 
                label: Statuts
                value: 
                    callback: displayStatus
        
cards: 
    default:
        fields: 
            - field: date
            - field: date_prevue
            - field: mode
            - field: id_user
              display: nom_url