extends: 
    module: bimpcommercial
    object_name: ObjectLine
    
table: bimp_commande_line

parent_module: bimpcommercial
parent_object: Bimp_Commande

labels: 
    name: ligne de commande
    name_plur: lignes de commande
    is_female: 1
    
objects: 
    line: 
        relation: hasOne
        delete: 0
        instance: 
            dol_object: 
                module: commande
                class: OrderLine
            id_object: 
                field_value: id_line
                
    dol_line: 
        instance: 
            bimp_object: 
                name: CommandeDolLine
                
    shipment: 
        instance: 
            bimp_object: 
                module: bimpreservation
                name: BL_CommandeShipment
            id_object: 
                field_value: id_shipment
                
fields: 
    id_obj: 
        label: Commande
        search: 
            input: 
                type: search_list
                search_list: 
                    table: commande
                    fields_search: rowid,ref
                    field_return_label: ref
                    field_return_value: rowid
                
    ref_reservations: 
        label: Référence réservations
        
    shipments: 
        label: Expéditions
        type: json
        
    factures: 
        label: Factures
        type: json
        
    equipments_returned: 
        label: Equipements retournés
        type: json
     
    qty_modif: 
        label: Qté modifiée
        type: qty
        min: none
        max: none
        decimals: 3
        unsigned: 0
        default_value: 0
     
    # Tous les champs qty_xxx suivants sont uniquement à titre indicatifs 
    # et servent pour la liste "general" (Ne pas utiliser en PHP)   
    # Attention: les quantités sont en valeur absolues (toujours positifs, même pour les retours, sauf qty_total) . 
        
    qty_total: 
        label: Qté Totale
        type: qty
        default_value: 0
        display: 
            badge:
                type: callback
                method: displayQty
                params: 
                    - total
        
    qty_shipped: 
        label: Qté expédiée
        type: qty
        default_value: 0
        display: 
            badge:
                type: callback
                method: displayQty
                params: 
                    - shipped
        
    qty_to_ship: 
        label: Qté à expédier
        type: qty
        default_value: 0
        display: 
            badge:
                type: callback
                method: displayQty
                params: 
                    - to_ship
        
    qty_billed: 
        label: Qté facturée
        type: qty
        default_value: 0
        display: 
            badge:
                type: callback
                method: displayQty
                params: 
                    - billed
        
    qty_to_bill: 
        label: Qté à facturer
        type: qty
        default_value: 0
        display: 
            badge:
                type: callback
                method: displayQty
                params: 
                    - to_bill
        
forms: 
    commande_fourn: 
        title: Ajouter à une commande fournisseur
        icon: fas_cart-arrow-down
        rows: 
            - custom: 1
              label: Quantité
              input_name: qty
              content: 
                  callback: renderCommandeFournQtyInput
            - custom: 1
              label: Type de prix
              data_type: int
              input_name: type_price
              input: 
                  type: select
                  options: 
                      1: Prix fournisseur
                      2: Prix d'achat exceptionnel
              value: 1
              
            - custom: 1
              label: Prix d'achat fournisseur
              input_name: id_fourn_price
              data_type: id_object
              object: fourn_price
              create_form: 
                  callback: getFournisseurPriceCreateForm
              create_form_values: 
                  fields: 
                      fk_product: 
                          prop: id_product
              input: 
                  type: select
                  options: 
                      array: productFournisseursPrices
                  extra_content: 
                      callback: renderFournPriceButtons
              value: 
                  callback: getCommandeFournIdPrice
              display_if: 
                  field_name: type_price
                  show_values: 1
              required_if: type_price=1
              
            - custom: 1
              label: Fournisseur
              input_name: id_fourn
              data_type: id_object
              input: 
                  type: select
                  options: 
                      array: prodFournisseurs
              display_if: 
                  field_name: type_price
                  show_values: 2
              required_if: type_price=2
              
            - custom: 1
              label: Prix d'achat exceptionnel (HT)
              input_name: pa_ht
              data_type: money
              value: 0
              input: 
                  type: text
              display_if: 
                  field_name: type_price
                  show_values: 2
              required_if: type_price=2
              
            - custom: 1
              label: Taux de TVA pour le prix d'achat exceptionnel
              input_name: tva_tx
              data_type: percent
              max: 100
              input:
                  type: text
              value: 20
              display_if: 
                  field_name: type_price
                  show_values: 2
#            - custom: 1
#              label: Remise sur le prix d'achat
#              input_name: remise_pa
#              data_type: percent
#              min: 0
#              max: 100
#              input: 
#                  type: text
#            - custom: 1
#              label: Intitulé de la remise sur le prix d'achat
#              input_name: remise_pa_label
#              data_type: string
#              input: 
#                  type: text
#              display_if: 
#                  field_name: remise_pa
#                  hide_values: 0
            - custom: 1
              label: Commande fournisseur
              input_name: id_commande_fourn
              value: new
              input: 
                  type: select
                  options: 
                      array: commandesFournisseurs
              depends_on: type_price,id_fourn_price,id_fourn
              
    qty_modified: 
        rows: 
            - custom: 1
              label: Quantité totale commande
              input_name: qty_modified
              content: 
                  callback: renderQtyModifiedInput
                  
    equipments_return: 
        title: Equipements retournés
        rows: 
            - custom: 1
              label: Equipements
              input_name: equipments
              multiple: 1
              data_type: items_list
              items_data_type: id_object
              object: equipment
              create_form: light_place
              create_form_values: 
                  callback: getNewEquipmentToReturnCreateFormValues
              content: 
                  callback: renderEquipmentsReturnInput
            
    returns_from_lines: 
        rows: 
            - custom: 1
              label: Quantités et équipements
              input_name: lines
              content: 
                  callback: renderReturnsFromLinesInputs
                      
views: 
    shipments: 
        panel: 0
        rows: 
            - cols: 
                - type: custom
                  custom: 
                      callback: renderShipmentsView
                      
    invoices: 
        panel: 0
        rows: 
            - cols: 
                - type: custom
                  custom: 
                      callback: renderInvoicesView
                      
lists_cols:
    commande: 
        label: Commande
        field: id_obj
        display: nom_url
    qties: 
        label: Quantités
        value: 
            callback: displayQties
    reservations: 
        label: Statuts
        value: 
            callback: displayReservationsStatus
        min_width: 620px
    qty_total: 
        label: Qté totale
        field: qty_total
        display: badge
        min_width: 60px
        max_width: 60px
    qty_shipped: 
        label: Qté expédiée
        field: qty_shipped
        display: badge
        min_width: 60px
        max_width: 60px
    qty_to_ship: 
        label: Qté à exp.
        field: qty_to_ship
        display: badge
        min_width: 60px
        max_width: 60px
    qty_billed: 
        label: Qté facturée
        field: qty_billed
        display: badge
        min_width: 60px
        max_width: 60px
    qty_to_bill: 
        label: Qté à fac. 
        field: qty_to_bill
        display: badge
        min_width: 60px
        max_width: 60px
    date: 
        field: date_commande
        child: parent

                
lists: 
    default: 
        objects_change_reload: ObjectLineRemise,Bimp_Commande
        add_btn: 
            callback: isCreatable
        edit_btn: 
            callback: isParentEditable
            
    logistique:
        extends: default
        title: Logistique produits / services
        icon: fas_truck-loading
        configurable: 1
        list_filters: 
            - name: type
              filter: 
                  operator: <>
                  value: 2
        item_checkbox: 
            callback: isNotTypeText
        after_list_content: unset
        header_buttons: unset
        objects_change_reload: Bimp_Commande,ObjectLineRemise,BR_Reservation,BL_CommandeShipment
        bulk_actions: 
            callback: getLogistiqueBulkActions
        extra_btn: 
            callback: getLogistiqueExtraButtons
        footer_extra_content:
            callback: renderLogistiqueListFooterExtraContent
        cols: 
            desc:
                value: 
                    callback: 
                        method: displayLineData
                        params:
                           - desc_light
            pu_ht: unset
            tva: unset
            pa_ht: unset
            qty: unset
            qties: 
            remise: unset
            total_ttc: unset
            margin: unset
            reservations:
                
    general:
        list_filters: 
            - name: type
              filter: 
                  in: 1,3
        configurable: 1
        filters_panel: default
        filters_panel_open: 1
        sort_field: id
        sort_way: desc
        n: 25
        extra_btn: 
            callback: getGeneralListExtraButtons
        cols:
            entrepot: 
                label: Entrepot
                field: entrepot
                child: parent
                display: ref
                min_width: 60px
                max_width: 60px
            commande_status: 
                label: St Cmd
                field: fk_statut
                child: parent
                display: icon
                min_width: 45px
                max_width: 45px
            logistique_status:
                label: Log Cmd
                field: logistique_status
                child: parent
                display: icon
                min_width: 45px
                max_width: 45px
            shipment_status:
                label: Exp Cmd
                field: shipment_status
                child: parent
                display: icon
                min_width: 45px
                max_width: 45px
            invoice_status:
                info: Statut facturation Commande
                label: Fac Cmd
                field: invoice_status
                child: parent
                display: icon
                min_width: 45px
                max_width: 45px
#            dl_product: 
#                field: fk_product
#                child: dol_line
#                display: nom_url
            commande: 
            desc:
                value: 
                    callback: 
                        method: displayLineData
                        params:
                           - desc_light
            dl_pu_ht: 
                field: subprice
                child: dol_line
            qty_total:
            qty_to_ship:
            qty_to_bill:
                                
#            tva:
#            remise_crt:
#                edit: 0
#            dl_remise: 
#                field: remise_percent
#                child: dol_line
#            total_ttc: 
#                field: total_ttc
#                child: dol_line

    
    
