extends: 
    module: bimpcommercial
    object_name: BimpComm

abstract: 0

dol_object: 
    instance: 
        dol_object: 
            module: fourn
            file: fournisseur.facture
            class: FactureFournisseur
            
table: facture_fourn
controller: factureFourn
icon: fas_file-invoice-dollar
list_page_url: 
    controller: facturesFourn

force_extrafields_update: 1


associations: 
    achatsFourn_Equipments:
        object: equipment
        label: Equipements concerné
        input:
            type: search_object
            object: equipment

labels: 
    name: facture fournisseur
    name_plur: factures fournisseurs
    is_female: 1
        
objects: 
    lines: 
        instance: 
            bimp_object: Bimp_FactureFournLine 
    files:
        list: 
            filters:
                parent_object_name: Bimp_FactureFourn
        add_form: 
            values:
                fields: 
                    parent_object_name: Bimp_FactureFourn
    fournisseur: 
        relation: hasOne
        delete: 0
        instance: 
            bimp_object: 
                module: bimpcore
                name: Bimp_Fournisseur
            id_object: 
                field_value: fk_soc
    user:
        relation: hasOne
        delete: 0
        instance: 
            bimp_object: 
                module: bimpcore
                name: Bimp_User
    account: 
        relation: hasOne
        delete: 0
        instance: 
            dol_object: 
                module: compta/bank
                file: account
            id_object: 
                field_value: fk_account
                    
fields: 
    fk_soc: 
        label: Fournisseur
        object: fournisseur
        input: 
            societe_type: supplier
            create_form: fournisseur_light
    ref_supplier: 
        label: Référence fournisseur
        required: 1
    type: 
        label: Type
        type: int
        values: 
            array: types
        default_value: 0
    paye:
        label: Payée
        type: bool
        default_value: 0
    amount: 
        label: Montant
        type: money
        default_value: 0
    tva: 
        label: TVA
        dol_prop: tva
        default_value: 0
    total_tva: 
        label: Total TVA
        type: money
        default_value: 0
    total_ttc: 
        label: Total TTC
        type: money
        default_value: 0
    remise: 
        label: Remise
        type: money
        default_value: 0
    close_code: 
        label: Code de fermeture
    close_note: 
        label: Note de fermeture
    datec: 
        label: Créée le
        type: datetime
    datef: 
        label: Date facturation
        dol_prop: date
        type: date
    date_lim_reglement: 
        label: Date d'échéance
        dol_prop: date_echeance
        type: date
    date_valid: 
        type: date
    fk_user_author: 
        dol_prop: unset
    fk_user_valid: 
        dol_prop: unset
    fk_facture_source: 
        label: Facture d'origine
        type: int
        default_value: 0
    fk_account: 
        label: Compte financier
        type: id_object
        object: account
        values: 
            array: bankAccounts
    exported:
        label: Etat comptable
        type: int
        values:
            array: exportedStatut
        
    fk_availability: unset
    fk_input_reason: unset
    ref_client: unset
    total: unset
    tx_marge: unset
    tx_marque: unset
    
forms:
    default: 
        title: Création d'une facture fournisseur standard
        msgs: 
            callback: getCreateFromOriginCheckMsg
        rows: 
            - custom: 1
              lable: Origine
              input_name: origin
              input: 
                  type: hidden
              value: 
                  request_field: origin
              hidden: 1
              
            - custom: 1
              lable: Origine
              input_name: origin_id
              data_type: int
              input: 
                  type: hidden
              value: 
                  request_field: origin_id
              hidden: 1
              
            - field: libelle
            - field: entrepot
            - field: ef_type
            - field: fk_soc
            - field: ref_supplier
            - field: datef
            - field: fk_cond_reglement
            - field: fk_mode_reglement
            - field: date_lim_reglement
            - field: model_pdf
            - field: zone_vente
              show: 
                  callback: isLoaded
            - field: note_public
            - field: note_private
            - association: achatsFourn_Equipments
              edit: 1
              show:
                  conf: useLinkAchatFournEquipment
                  
    duplicate_factfourn:
        title: Création d'une facture fournisseur standard
        msgs: 
            callback: getCreateFromOriginCheckMsg
        rows: 
            - field: fk_soc
            - field: ref_supplier
            - field: datef
        
            
fields_tables: 
    infos: 
        rows: 
            - field: entrepot
              display: nom_url
            - field: ef_type
            - field: libelle
              edit: 1
            - field: datef
              edit: 1
            - field: fk_statut
            - field: paye
            - field: fk_facture_source
              show: 
                  field_value: fk_facture_source
            - field: zone_vente
              edit: 1
            - field: exported
            - association: achatsFourn_Equipments
              edit: 1
              show:
                  conf: useLinkAchatFournEquipment
                  
    client: 
        title: Fournisseur
        icon: fas_building
        rows: 
            - field: fk_soc
              display: card
            - field: ref_supplier
              edit: 1
        
    payment:
        rows: 
            - field: fk_cond_reglement
              edit: 1
            - field: fk_mode_reglement
              edit: 1
            - field: date_lim_reglement
              edit: 1
            - field: fk_account
              display: nom_url
                
    pdf: 
        rows: 
            - label: Fichier PDF
              value: 
                  callback: displayPDFButton
                  
    totals: 
        rows: 
            - field: total_ht
            - field: total_tva
            - field: total_ttc
        
views: 
    default: 
        objects_change_reload: Bimp_FactureFournLine,ObjectLineRemise,BimpFile,Bimp_PaiementFourn
    content_infos: 
        objects_change_reload: Bimp_FactureFournLine,ObjectLineRemise,BimpFile,Bimp_PaiementFourn
    full: 
        objects_change_reload: Bimp_FactureFournLine,ObjectLineRemise,BimpFile,Bimp_PaiementFourn
        
filters_panels: 
    default: 
        filters: 
            total: unset
            ref_client: unset
            client:status: unset
            datec: unset
            datef:
            ref_supplier: 
            paye: 
                
lists_cols:         
    total_pa: unset
    client_facturation: unset
    tx_marge: unset
    tx_marque: unset
    
lists: 
    default: 
        title: Factures fournisseurs
        icon: fas_file-invoice-dollar
        bulk_actions:
            delete: 
                label: supprimer les factures fournisseurs sélectionnées
        sort_field: datec
        sort_way: desc
        cols: 
            ref: 
            fk_statut: 
            datec:
            fk_user_author:
            fk_soc: 
            total_ttc:
                
    fourn:
        extends: default
        cols:
            fk_soc: unset
    
cards: 
    default: 
        title: 
            field_value: ref
        status: fk_statut
        view_btn: 1
        fields: 
            - field: total_ttc
            - label: Payé
              value: 
                  callback: displayPaid
#            - label: Fichier PDF
#              value: 
#                  callback: displayPDFButton
                  
#    light: 
#        title: 
#            field_value: ref
#        view_btn: 0
#        fields: 
#            - field: total_ttc
#            - field: fk_statut
#            - label: Payé
#              value: 
#                  callback: displayPaid

searches:
    default: 
        fields_search: 
            - a.ref
            - ef.libelle
            - s.nom
            - a.ref_supplier
        joins:
            ef: 
                table: commande_fournisseur_extrafields
                on: a.rowid = ef.fk_object
                alias: ef
            s: 
                table: societe
                on: a.fk_soc = s.rowid
                alias: s
        fields_return: 
            - a.ref
            - s.nom
        label_syntaxe: '<a.ref> (Fourn: <s.nom>)'
