table: facturedet
primary: rowid

parent_module: bimpcommercial
parent_object: Bimp_Facture
parent_id_property: fk_facture

labels: 
    name: vente
    is_female: 1
    
objects:
    facture: 
        instance: 
            id_object: 
                field_value: fk_facture
                
    facture_line: 
        relation: hasOne
        delete: 0
        instance: 
            bimp_object: 
                module: bimpcommercial
                name: Bimp_FactureLine
                
    product: 
        instance: 
            id_object: 
                field_value: fk_product
            
    category: 
        relation: none
        delete: 0
        instance: 
            dol_object: 
                module: categories
                file: categorie
                
    marque: 
        extends: category
        relation: hasOne
        instance: 
            id_object: 
                field_value: marque
                
    gamme: 
        extends: category
        relation: hasOne
        instance: 
            id_object: 
                field_value: gamme
                
    user_commercial: 
        extends: user
        instance: 
            id_object: 
                field_value: id_commercial
                
fields: 
#    Champs facturedet: 
    fk_facture: 
        label: Facture
        type: id_parent
        object: facture
        
    fk_product: 
        label: Produit
        type: id_object
        object: product
        
    subprice: 
        label: Prix unitaire HT
        type: money
        
    tva_tx: 
        label: Taux de TVA
        type: percent
        
    qty: 
        label: Quantité
        type: qty
        decimals: 3
        
    remise_percent: 
        label: Remise (%)
        type: percent
        
    total_ht: 
        label: Total HT
        type: money
        
    total_tva: 
        label: Total TVA
        type: money
        
    total_ttc: 
        label: Total TTC
        type: money
        
    rang: 
        label: Position
        type: int
        unsigned: 1
        
#    Champs extra: 
    
    date: 
        label: Date
        extra: 1
        type: date
        
    id_client: 
        label: Client
        extra: 1
        type: id_object
        object: client
        
    id_entrepot: 
        label: Entrepot
        extra: 1
        type: id_object
        object: bimp_entrepot
        values: 
            array: entrepots
        sort_options: 
            default: 
                label: Par référence
                join_field: ref
                join_table: entrepot
                join_on: rowid
        
    id_user: 
        label: Utilisateur
        extra: 1
        type: id_object
        object: user
        values: 
            array: users
            
    id_commercial:
        label: Commercial
        extra: 1
        type: id_object
        object: user_commercial
        values: 
            array: users
            
    secteur:
        label: Secteur
        extra: 1
        values: 
            array: secteurs
        
    marque: 
        label: Marque
        extra: 1
        type: id_object
        object: marque
        values: 
            array: marques
            
    gamme: 
        label: Gamme matériel
        extra: 1
        type: id_object
        object: gamme
        values: 
            array: gammesMateriel
            
    product_categories: 
        label: Catégories produit
        extra: 1
        type: items_list
        items_data_type: id_object
        object: category
     
forms: 
    generate_apple_cvs:
        title: Générer Rapport CSV apple
        force_edit: 1
        rows: 
            - custom: 1
              label: Du
              data_type: date
              input_name: date_from
              input: 
                  type: date
            - custom: 1
              label: Au
              data_type: date
              input_name: date_to
              input: 
                  type: date    
            - custom: 1
              label: Générer le fichier "Inventaire"
              data_type: bool
              input_name: include_inventory
              input: 
                  type: toggle
              value: 1
            - custom: 1
              label: Générer le fichier "Ventes"
              data_type: bool
              input_name: include_sales
              input: 
                  type: toggle
              value: 1
            - custom: 1
              label: Inclure les ventes aux particuliers
              data_type: bool
              input_name: include_part_soc
              input: 
                  type: toggle
              value: 1
              display_if: 
                  field_name: soc_qties
                  show_values: 1
            - custom: 1
              label: Répartir le CA
              input_name: distribute_ca
              data_type: bool
              input: 
                  type: toggle
              value: 1
        
fields_tables: 
    infos: 
        title: Infos
        icon: fas_info-circle
        rows: 
            - field: date
            - field: fk_product
              display: nom_url
            - field: id_entrepot
              display: nom_url
            - field: secteur
            - field: id_user
              display: nom_url
            - field: id_client
              display: card
            - field: fk_facture
              display: card
              
    montants: 
        title: Montants
        icon: fas_euro-sign
        rows: 
            - field: qty
            - field: subprice
            - field: tva_tx
            - field: remise_percent
            - field: total_ht
            - field: total_tva
            - field: total_ttc
            
views: 
    default: 
        rows: 
            - cols: 
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: infos
                
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: montants
            
filters: 
    id_commercial:
        type: user
        
filters_panels: 
    default: 
        filters: 
            id_client:
            date: 
            id_entrepot: 
            secteur: 
            parent:fk_statut:
            id_user: 
            id_commercial:
            fk_product: 
            product:price:
            qty: 
            total_ht: 
            tva_tx:
            marque: 
            gamme: 
            product:categorie:
            product:collection:
            product:nature:
            product:famille:
        
lists_cols: 
    shortRef: 
        value: 
            callback: displayShortRef
        label: Ref courte
    pays2:
        label: Pays
        value: 
            callback: displayCountry
    type_materiel: 
        label: Type matériel
        value: 
            callback: displayTypeMateriel
    
lists: 
    default: 
        title: Ventes de produits
        total_row: 1
        configurable: 1
        n: 10
        sort_field: date
        sort_way: desc
        filters_panel: default
        modal_view: default
        list_filters: 
            - name: fk_product
              filter: 
                  operator: '>' 
                  value: 0
        header_buttons:
            callback: getListHeaderButtons
        cols: 
            pays2: 
            marque: 
            shortRef: 
            product:
            qty:             
            gamme: 
            type_materiel:           

stats_lists_cols: 
    nb_secteurs: 
        label: Nb Secteurs
        type: count_distinct
        field: secteur
    tot_qty: 
        label: Qté totale
        type: sum
        field: qty
        data_type: float
        decimals: 2
    tot_brouillon: 
        label: Tot. Fac. brouillons
        type: sum
        data_type: money
        decimals: 2
        with_styles: 1
        field: total_ttc
        filters: 
            f.fk_statut: 0
    tot_valide: 
        label: Tot. Fac. validées
        type: sum
        field: total_ttc
        data_type: money
        decimals: 2
        with_styles: 1
        filters: 
            f.fk_statut: 
                in: 
                    - 1
                    - 2
    tot_abandon: 
        label: Tot. Fac. abandonnées
        type: sum
        field: total_ttc
        data_type: money
        decimals: 2
        with_styles: 1
        filters: 
            f.fk_statut: 3
                    
stats_lists: 
    default: 
        n: 25
        configurable: 1
        joins: 
            facture: 
                table: facture
                alias: f
                on: f.rowid = a.fk_facture
        filters_panel: default
        group_by_options: 
            - id_entrepot
            - secteur
            - fk_product
        cols: 
            nb_secteurs:
            tot_qty: 
            tot_brouillon:
            tot_valide:
            tot_abandon: 