table: facturedet
primary: rowid

parent_module: bimpcommercial
parent_object: Bimp_Facture
parent_id_property: fk_facture

labels: 
    name: vente
    is_female: 1
    
objects:
    facture: 
        instance: 
            id_object: 
                field_value: fk_facture
                
    facture_line: 
        relation: hasOne
        delete: 0
        instance: 
            bimp_object: 
                module: bimpcommercial
                name: Bimp_FactureLine
                
    product: 
        instance: 
            id_object: 
                field_value: fk_product
            
    category: 
        relation: none
        delete: 0
        instance: 
            dol_object: 
                module: categories
                file: categorie
                
    marque: 
        extends: category
        relation: hasOne
        instance: 
            id_object: 
                field_value: marque
                
    gamme: 
        extends: category
        relation: hasOne
        instance: 
            id_object: 
                field_value: gamme
                
fields: 
#    Champs facturedet: 
    fk_facture: 
        label: Facture
        type: id_parent
        object: facture
        
    fk_product: 
        label: Produit
        type: id_object
        object: product
        
    subprice: 
        label: Prix unitaire HT
        type: money
        
    tva_tx: 
        label: Taux de TVA
        type: percent
        
    qty: 
        label: Quantité
        type: qty
        decimals: 3
        
    remise_percent: 
        label: Remise (%)
        type: percent
        
    total_ht: 
        label: Total HT
        type: money
        
    total_tva: 
        label: Total TVA
        type: money
        
    total_ttc: 
        label: Total TTC
        type: money
        
#    Champs extra: 
    
    date: 
        label: Date
        extra: 1
        type: date
        
    id_client: 
        label: Client
        extra: 1
        type: id_object
        object: client
        
    id_entrepot: 
        label: Entrepot
        extra: 1
        type: id_object
        object: entrepot
        values: 
            array: entrepots
        
    id_user: 
        label: Utilisateur
        extra: 1
        type: id_object
        object: user
        values: 
            array: users
            
    secteur:
        label: Secteur
        extra: 1
        values: 
            array: secteurs
        
    marque: 
        label: Marque
        extra: 1
        type: id_object
        object: marque
        values: 
            array: marques
            
    gamme: 
        label: Gamme matériel
        extra: 1
        type: id_object
        object: gamme
        values: 
            array: gammesMateriel
            
    product_categories: 
        label: Catégories produit
        extra: 1
        type: items_list
        items_data_type: id_object
        object: category
     
forms: 
    generate_apple_cvs:
        title: Générer Rapport CSV apple
        force_edit: 1
        rows: 
            - custom: 1
              label: Du
              data_type: date
              input_name: date_from
              input: 
                  type: date
            - custom: 1
              label: Au
              data_type: date
              input_name: date_to
              input: 
                  type: date    
            - custom: 1
              label: Générer le fichier "Inventaire"
              data_type: bool
              input_name: include_inventory
              input: 
                  type: toggle
              value: 1
            - custom: 1
              label: Générer le fichier "Ventes"
              data_type: bool
              input_name: include_sales
              input: 
                  type: toggle
              value: 1
            - custom: 1
              label: Inclure les ventes aux particuliers
              data_type: bool
              input_name: include_part_soc
              input: 
                  type: toggle
              value: 1
              display_if: 
                  field_name: soc_qties
                  show_values: 1
            - custom: 1
              label: Répartir le CA
              input_name: distribute_ca
              data_type: bool
              input: 
                  type: toggle
              value: 1
        
fields_tables: 
    infos: 
        title: Infos
        icon: fas_info-circle
        rows: 
            - field: date
            - field: fk_product
              display: nom_url
            - field: id_entrepot
              display: nom_url
            - field: secteur
            - field: id_user
              display: nom_url
            - field: id_client
              display: card
            - field: fk_facture
              display: card
              
    montants: 
        title: Montants
        icon: fas_euro-sign
        rows: 
            - field: qty
            - field: subprice
            - field: tva_tx
            - field: remise_percent
            - field: total_ht
            - field: total_tva
            - field: total_ttc
            
views: 
    default: 
        rows: 
            - cols: 
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: infos
                
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: montants
            
filters_panels: 
    default: 
        filters: 
            client:
                field: fk_soc
                child: facture
            dates: 
                field: date
            entrepot: 
                field: id_entrepot
            secteur: 
                field: secteur
            status: 
                field: fk_statut
                child: parent
            user: 
                field: id_user
#            client: 
#                field: id_client
            product: 
                field: fk_product
            priceProd:
                field: price
                child: product
            qty: 
                field: qty
            total_ht: 
                field: total_ht
            tva_tx:
                field: tva_tx
            marque: 
                field: marque
            gamme: 
                field: gamme
            categ1:
                custom: 1
                label: Catégorie (1)
                field: categ1
                type: value
                input:
                    type: select
                    options: 
                        callback: getCategoriesArray
            categ2:
                custom: 1
                label: Catégorie (2)
                field: categ2
                type: value
                input:
                    type: select
                    options: 
                        callback: getCategoriesArray
            categ3:
                custom: 1
                label: Catégorie (3)
                field: categ3
                type: value
                input:
                    type: select
                    options: 
                        callback: getCategoriesArray
            categorie:
                field: categorie
                child: product
            collection:
                field: collection
                child: product
            nature:
                field: nature
                child: product
            famille:
                field: famille
                child: product
        
lists_cols: 
    facture: 
        field: fk_facture
        display: nom_url
    product: 
        field: fk_product
        display: nom_url
    shortRef: 
        value: 
            callback: displayShortRef
        label: Ref courte
    pays2:
        value: 
            callback: displayCountry
        label: Pays
    label:
        field: label
        child: product
#    pays:
#        field: state
#        child: client
    subprice: 
        field: subprice
    tva_tx: 
        field: tva_tx
    qty: 
        field: qty
        has_total: 1
    remise_percent: 
        field: remise_percent
    total_ht: 
        field: total_ht
        has_total: 1
    total_tva: 
        field: total_tva
        has_total: 1
    total_ttc: 
        field: total_ttc
        has_total: 1
    date: 
        field: date
    entrepot: 
        field: id_entrepot
        display: nom_url
    user: 
        field: id_user
        display: nom_url
    secteur: 
        field: secteur
    marque: 
        field: marque
    gamme: 
        field: gamme
    type_materiel: 
        label: Type matériel
        value: 
            callback: displayTypeMateriel
    categorie:
        field: categorie
        child: product
    collection:
        field: collection
        child: product
    nature:
        field: nature
        child: product
    famille:
        field: famille
        child: product
    
lists: 
    default: 
        title: Ventes de produits
        total_row: 1
        configurable: 1
        n: 10
        sort_field: date
        sort_way: desc
        filters_panel: default
        modal_view: default
        list_filters: 
            - name: fk_product
              filter: 
                  operator: '>' 
                  value: 0
        header_buttons:
            callback: getListHeaderButtons
        cols: 
            pays: 
            marque: 
            shortRef: 
            product:
            qty:             
            gamme: 
            type_materiel: 
             

stats_lists: 
    default: 
        n: 20
        joins: 
            facture: 
                table: facture
                alias: f
                on: f.rowid = a.fk_facture
        filters_panel: default
        group_by_options: 
            - id_entrepot
            - secteur
        cols: 
            qty: 
                label: Qté totale
                type: sum
                field: qty
            tot_brouillon: 
                label: Tot. Fac. brouillons
                type: sum
                field: total_ttc
                filters: 
                    f.fk_statut: 0
            tot_valide: 
                label: Tot. Fac. validées
                type: sum
                field: total_ttc
                filters: 
                    f.fk_statut: 
                        in: 
                            - 1
                            - 2
            tot_abandon: 
                label: Tot. Fac. abandonnées
                type: sum
                field: total_ttc
                filters: 
                    f.fk_statut: 3