primary: rowid

header_btn: 
    callback: getActionsButtons
    
header_list_name: default
    
objects:
    lines: 
        relation: hasMany
        delete: 1
        instance: 
            bimp_object: 
                module: bimpcommercial
                name: ObjectLine
        
    client: 
        instance: 
            id_object: 
                field_value: fk_soc
                
    contact: 
        instance: 
            id_object: unset
                
    files:
        relation: hasMany
        delete: 1
        instance:
            bimp_object:
                module: bimpcore
                name: BimpFile
        list: 
            filters:
                parent_module: bimpcommercial
                parent_object_name: BimpComm
                deleted: 0
        add_form: 
            name: upload
            values:
                fields: 
                    parent_module: bimpcommercial
                    parent_object_name: BimpComm
            
    user_author:
        extends: user
        instance: 
            id_object: 
                field_value: fk_user_author
            
    user_valid:
        extends: user
        instance: 
            id_object: 
                field_value: fk_user_valid
                
fields:
    entrepot: 
        label: Entrepôt
        dol_extra_field: 1
        type: id_object
        object: entrepot
        required: 1
        input: 
            type: search_entrepot
        default_value: 
            callback: getDefaultEntrepot
    ref: 
        label: Référence
    fk_statut: 
        label: Statut
        type: int
        dol_prop: statut
        values: 
            array: status_list
    fk_soc: 
        label: Client
        dol_prop: socid
        type: id_object
        object: client
        input: 
            type: search_societe
            societe_type: customer
            card: default
        required: 1
        create_form: light
    ref_client: 
        label: Référence client
    libelle: 
        label: Libellé
        dol_extra_field: 1
        required: 1
    ef_type: 
        label: Secteur
        dol_extra_field: 1
        values: 
            array: secteurs
        required: 1
    fk_cond_reglement: 
        label: Conditions de règlement
        dol_prop: cond_reglement_id
        type: id
        values: 
            array: condReglements
        input: 
            type: select_cond_reglement
        default_value: 
            callback: getCondReglementBySociete
        depends_on: fk_soc
        required: 1
    fk_mode_reglement: 
        label: Mode de règlement
        dol_prop: mode_reglement_id
        type: int
        values: 
            array: modeReglements
        input: 
            type: select_payment
            include_empty: 1
        default_value: 
            callback: getModeReglementBySociete
        depends_on: fk_soc
    fk_availability: 
        label: Délai de livraison
        dol_prop: availability_id
        type: int
        values: 
            array: availabilities
        input: 
            type: select_availability
        default_value: 0
    fk_input_reason: 
        label: Origine
        dol_prop: demand_reason_id
        type: int
        values: 
            array: demandReasons
        input: 
            type: select_input_reasons
        default_value: 0
    fk_user_author: 
        label: Créée par
        dol_prop: user_author_id
        type: id_object
        object: user_author
        input: 
            type: hidden
        filter: 
            input: 
                type: search_user
    fk_user_valid: 
        label: Validée par
        dol_prop: user_valid_id
        type: id_object
        object: user_valid
        input: 
            type: hidden
        filter: 
            input: 
                type: search_user
    total: 
        label: Total TTC
        dol_prop: total_ttc
        type: money
    total_ht: 
        label: Total HT
        type: money
    tva: 
        label: Total TVA
        dol_prop: total_tva
        type: money    
    model_pdf: 
        label: Modèle de document par défaut
        dol_prop: modelpdf
        values: 
            array: modelsPdf
        sortable: 0
    note_private: 
        label: Note privée
        type: html
        sortable: 0
    note_public: 
        label: Note publique
        type: html  
        sortable: 0
    remise_globale: 
        label: Remise globale
        type: percent
        default_value: 0
        decimals: 8
        display_if: 
            field_name: use_amount
            show_values: 0
    remise_globale_label: 
        label: Intitulé de la remise globale
        type: text
        input: 
            rows: 1
            auto_expand: 1
        default_value: 
            callback: getDefaultRemiseGlobaleLabel
    zone_vente: 
        label: Zone de vente
        type: int
        values: 
            array: zones_vente
        dol_extra_field: 1
        default_value: 1
        input: 
            help: Si vous indiquez "Hors-UE", tous les taux de TVA des lignes actuelles seront mis à 0 de manière irréversible.
    
forms: 
    contact:
        title: Ajouter un contact
        rows: 
            - custom: 1
              label: Type
              input_name: type
              input: 
                  type: select
                  options: 
                      1: Contact tiers
                      2: Utilisateur
            - custom: 1
              label: Tiers
              input_name: id_client
              input: 
                  type: search_societe
                  societe_type: customer
              value: 
                  field_value: fk_soc
              display_if: 
                  field_name: type
                  show_values: 1
            - custom: 1
              label: Contact
              input_name: id_contact
              data_type: id_object
              object: contact
              create_form: default
              create_form_values:
                  fields: 
                      fk_soc: 
                          callback: getAddContactIdClient
              value: 
                  request: fields/id_contact
              input: 
                  type: select
                  options: 
                      array: clientContacts
              display_if: 
                  field_name: type
                  show_values: 1
              depends_on: id_client
            - custom: 1
              label: Utilisateur
              input_name: id_user
              input: 
                  type: search_user
              value: 
                  prop:
                      object: 
                          global: user
                      name: id
              display_if: 
                  field_name: type
                  show_values: 2
            - custom: 1
              label: Type de contact
              input_name: tiers_type_contact
              input: 
                  type: select
                  options: 
                      array: externalContactTypes
              display_if: 
                  field_name: type
                  show_values: 1
            - custom: 1
              label: Type de contact
              input_name: user_type_contact
              input: 
                  type: select
                  options: 
                      array: internalContactTypes
              display_if: 
                  field_name: type
                  show_values: 2 
                  
    duplicate:
        rows: 
            - field: entrepot
            - field: fk_soc
            
    use_remise:
        rows: 
            - custom: 1
              label: Remise / avoir à appliquer
              input_name: id_discount
              data_type: int
              input: 
                  type: select_remises
                  id_client: 
                      field_value: fk_soc
                  extra_filters:
                      callback: getRequestSelectRemisesFilters
        
    remise_globale: 
        title: Remise Globale
        icon: percent
        rows: 
            - field: remise_globale_label
            - custom: 1
              label: Définir à partir d'un montant fixe
              input_name: use_amount
              data_type: bool
              input: 
                  type: toggle
              value: 1
            - field: remise_globale
            - custom: 1
              label: Montant de la remise
              input_name: remise_globale_amount
              data_type: money
              input: 
                  help: Ce montant sera déduit du Total TTC et sera converti en pourcentage global. 
              value: 
                  callback: getRemiseGlobaleAmount
              display_if: 
                  field_name: use_amount
                  show_values: 1
            
    email: 
        rows: 
            - custom: 1
              label: Emetteur
              input_name: from
              input: 
                  type: select
                  options: 
                      array: emailUsersFrom
                      
            - custom: 1
              label: Destinataires
              input_name: mail_to
              input: 
                  type: custom
                  content: 
                      callback: 
                          method: renderMailToInputs
                          params: 
                              - mail_to
                  multiple: 1
              required: 1
              
            - custom: 1
              label: Copies à
              input_name: copy_to
              input: 
                  type: custom
                  content: 
                      callback: 
                          method: renderMailToInputs
                          params: 
                              - copy_to
                  multiple: 1
                          
            - custom: 1
              label: Accusé de réception
              input_name: confirm_reception
              data_type: bool
              input: 
                  type: toggle
              default_value: 0
              
            - custom: 1
              label: Modèle de courriel
              input_name: id_model
              input: 
                  type: select
                  options: 
                      array: emailModels
                      
            - custom: 1
              label: Objet
              input_name: mail_object
              input: 
                  type: text
              value: 
                  callback: getEmailTopicByModel
              depends_on: id_model
              
            - custom: 1
              label: Message
              data_type: html
              input_name: msg_html
              input: 
                  type: html
              value: 
                  callback: getEmailContentByModel
              depends_on: id_model
              
            - custom: 1
              label: Fichiers joints
              input_name: join_files
              data_type: id_object
              input: 
                  type: check_list
                  items: 
                      array: files
              value: 
                  callback: getJoinFilesValues
              object: files
              create_form: upload
              create_form_label: Ajouter
              create_form_values: 
                  fields: 
                      parent_module: 
                          prop: module
                      parent_object_name: 
                          prop: object_name
                      id_parent: 
                          prop: id
                          
    acompte: 
        title: Ajouter un acompte
        icon: fas_hand-holding-usd
        rows: 
            - custom: 1
              label: Mode de paiement
              input_name: id_mode_paiement
              data_type: id
              required: 1
              input: 
                  type: select_payment
                  include_empty: 1
            - custom: 1
              label: Montant
              input_name: amount
              data_type: money
              required: 1
              input: 
                  type: text
                  
fields_tables: 
    infos: 
        title: Informations
        icon: info-circle
                  
    client: 
        title: Client
        icon: user
        
    payment:
        title: Règlement
        icon: euro
                
    pdf: 
        title: Document
        icon: fas_file-pdf
                                    
    sav_infos: 
        title: Informations
        icon: info-circle
                  
    totals: 
        title: Montants totaux
        icon: euro
                  
    notes:
        title: Notes
        icon: fas_sticky-note
        rows: 
            - field: note_public
            - field: note_private
    
filters_panels: 
    default: 
        filters: 
            ref: 
                field: ref
            ref_client: 
                field: ref_client
            statut: 
                field: fk_statut
            soc: 
                field: fk_soc
            entrepot: 
                field: entrepot
            secteur: 
                field: ef_type
            libelle: 
                field: libelle
            user_create: 
                field: fk_user_author
            user_valid: 
                field: fk_user_valid
            date_create: 
                field: datec
            availability:
                field: fk_availability
            cond_reglement: 
                field: fk_cond_reglement
            mode_reglement: 
                field: fk_mode_reglement
            total_ht: 
                field: total_ht
            total_ttc: 
                field: total
            remise_globale: 
                field: remise_globale
            note_private: 
                field: note_private
            note_public: 
                field: note_public
                    
lists_cols: 
    libelle: 
        field: libelle
    secteur:
        field: ef_type
    entrepot: 
        field: entrepot
        display: nom_url
    ref: 
        label: Réf. 
        field: ref
    soc: 
        field: fk_soc
        display: nom_url
    ref_client: 
        field: ref_client
    statut: 
        field: fk_statut
    total_ht: 
        field: total_ht
    total_ttc: 
        field: total
    total_tva: 
        field: tva
    cond_reglement: 
        field: fk_cond_reglement
    mode_reglement: 
        field: fk_mode_reglement
    availability: 
        field: fk_availability
    input_reason: 
        field: fk_input_reason
    user_create:
        field: fk_user_author
        display: nom_url
    user_valid: 
        field: fk_user_valid
        display: nom_url
        
lists: 
    default: 
        configurable: 1
        checkboxes: 1
        filters_panel: default
        bulk_actions:
              icon: fas_trash-alt
              onclick: deleteSelectedObjects('list_id', $(this))
        n: 10
        add_form_name: default
        edit_btn: 1
        edit_form: default
        delete_btn: 1
        modal_view: full
        page_btn: 1
        extra_btn: 
            callback: getDefaultListExtraButtons
        list_filters: 
            callback: getListFilters
    mini_user_create:
        extends: default
        n: 5
        cols: 
            user_author: unset
            entrepot: unset
            secteur: unset
            date_create: unset
            commercial: unset
            
views: 
    default: 
        objects_change_reload: BimpFile,BimpNote
        delete_btn: 1
        edit_form: default
        footer_extra_btn: 
            callback: getActionsButtons
        rows: 
            - cols: 
                - type: rows
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  rows: 
                      - cols: 
                            - type: fields_table
                              fields_table:
                                  name: infos
                                  
                      - cols: 
                            - type: fields_table
                              fields_table: 
                                  name: payment
                      
                - type: rows
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  rows: 
                      - cols: 
                          - type: fields_table
                            fields_table: 
                                name: client
                                
                      - cols:
                            - type: fields_table
                              fields_table: 
                                  name: notes
                            
    full: 
        objects_change_reload: Bimp_File
        rows: 
            - cols: 
                - type: object_header
            - cols: 
                - type: view
                  view: 
                      name: default
            - cols: 
                - type: view
                  view: 
                      name: content
            - cols:
                - type: custom
                  custom: 
                      callback: 
                          method: renderNotesList
                          params:
                              - 1
        
    content_infos: 
        rows: 
            - cols: 
                - type: rows
                  col_lg: 7
                  col_md: 7
                  col_sm: 12
                  rows: 
                      - cols: 
                            - type: fields_table
                              fields_table: 
                                  name: totals
                            - type: custom
                              custom:
                                  callback: renderMarginsTable
                - type: fields_table
                  col_lg: 5
                  col_md: 5
                  fields_table:
                      name: pdf
                      
            - cols: 
                - type: custom
                  col_lg: 5
                  col_md: 5
                  col_sm: 12
                  custom: 
                      callback: renderContentExtraLeft
                - type: custom
                  col_lg: 7
                  col_md: 7
                  col_sm: 12
                  custom: 
                      callback: renderContentExtraRight
                
    content: 
        no_reload: 1
        rows:          
            - cols: 
                - type: view
                  view: 
                      name: content_infos
                      panel: 0
            - cols: 
                - type: list
                  list: 
                      name: default
                      children: lines
                      title: Lignes
