extends: 
    module: bimpcommercial
    object_name: BimpComm
    
dol_object: 
    instance: 
        dol_object: 
            module: compta/facture
            file: facture
            
force_extrafields_update: 1

table: facture
controller: facture
icon: fas_file-invoice-dollar
list_page_url: 
    controller: factures

labels: 
    name: facture
    is_female: 1
    
objects: 
    lines: 
        instance: 
            bimp_object: Bimp_FactureLine
            
    entrepot: 
        instance: 
            id_object:
                field_value: entrepot
                
    account: 
        instance:
            id_object: 
                field_value: fk_account
    
    files:
        list: 
            filters:
                parent_object_name: Bimp_Facture
        add_form: 
            values:
                fields: 
                    parent_object_name: Bimp_Facture
                    
fields: 
    facnumber: 
        label: Référence
        dol_prop: ref
    exported:
        label: Comptabilisée
        type: int
    type: 
        label: Type
        type: int
        values: 
            array: types
        input: 
            type: select
            options: 
                array: selectTypes
        depends_on: fk_soc
    model_pdf: 
        default_value: bimpfact
    datec: 
        label: Créée le
        type: datetime
    datef: 
        label: Date facturation
        dol_prop: date
        type: date
        input: 
            display_now: 1
        required: 1
    date_lim_reglement:
        label: Date limite de réglement
        type: date
    fk_account: 
        label: Compte bancaire
        type: id_object
        object: account
        input: 
            type: select_mysoc_account
    centre: 
        label: Centre
        dol_extra_field: 1
        values: 
            array: centres
        display_if: 
            field_name: ef_type
            show_values: S
        default_value: ''
    total: 
        label: Total HT
        dol_prop: total_ht
        type: money
    total_ttc: 
        label: Total TTC
        type: money
    fk_user_author: 
        dol_prop: user_author
    fk_user_valid: 
        dol_prop: user_valid
    paye: 
        label: Paye
        type: bool
        default_value: 0
        
    ref: unset
    fk_availability: unset
    fk_input_reason: unset
    total_ht: unset
    marge: 
        label: Marge
        type: money
        default_value: 0
        
forms: 
    
    default: 
        msgs: 
            callback: renderCreateWarning
        rows:
            - custom: 1
              lable: Origine
              input_name: origin
              input: 
                  type: hidden
              value: 
                  request_field: origin
              hidden: 1
              
            - custom: 1
              lable: Origine
              input_name: origin_id
              data_type: int
              input: 
                  type: hidden
              value: 
                  request_field: origin_id
              hidden: 1
              
            - field: fk_soc
                  
            - field: ref_client
            
            - field: type
              show: 
                  callback: isNotLoaded
                  
            - custom: 1
              label: Type d'acompte
              input_name: typedeposit
              input: 
                  type: select
                  options: 
                      array: typesDeposit
              display_if:
                  fields_names: type,origin
                  type: 
                      hide_values: 1,2,4,5
                  origin: 
                      show_values: propal,commande
              show: 
                  callback: isNotLoaded
                      
            - custom: 1
              label: Facture remplacée
              input_name: id_facture_replaced
              data_type: int
              input: 
                  type: select
                  options: 
                      array: replacedInvoices
              value: 
                callback: getRequestIdFactureReplaced
              display_if: 
                  field_name: type
                  show_values: 1
              show: 
                  callback: isNotLoaded
              depends_on: fk_soc
                  
            - custom: 1
              label: Facture à corriger
              input_name: id_facture_to_correct
              data_type: int
              input: 
                  type: select
                  options: 
                      array: FacturesToCorrect
              value: 
                  callback: getRequestIdFactureToCorrect
              display_if: 
                  field_name: type
                  show_values: 2
              depends_on: fk_soc
              show: 
                  callback: isNotLoaded
              
            - custom: 1
              label: Créer l'avoir avec les même lignes que la factures dont il est issu
              data_type: bool
              input: 
                  type: toggle
              value: 1
              input_name: avoir_same_lines
              display_if: 
                  fields_names: type,id_facture_to_correct
                  type: 
                      show_values: 2
                  id_facture_to_correct:
                      hide_values: 0
              show: 
                  callback: isNotLoaded
            
            - custom: 1
              label: Créer l'avoir avec le montant restant à payer de la facture dont il est issu.
              data_type: bool
              input: 
                  type: toggle
              value: 0
              input_name: avoir_remain_to_pay
              display_if: 
                  fields_names: type,id_facture_to_correct
                  type: 
                      show_values: 2
                  id_facture_to_correct:
                      hide_values: 0
              show: 
                  callback: isNotLoaded
                 
            - field: ef_type
            - field: entrepot
              show: 
                  callback: isEditable
            
            - field: centre
              show: 
                  callback: isEditable
            
            - field: libelle
            
            - field: datef
              show: 
                  callback: isEditable
                  
            - field: fk_cond_reglement
              show: 
                  callback: isEditable
            - field: fk_mode_reglement
              show: 
                  callback: isEditable
                  
            - field: date_lim_reglement
                  
            - field: fk_account
              show: 
                  callback: isEditable
                  
            - field: model_pdf
              show: 
                  callback: isNotLoaded
            - field: zone_vente
              show: 
                  callback: isLoaded
            - field: remise_globale_label
              show: 
                  callback: hasRemiseGlobale
            - field: note_private
            
            - field: note_public
            
    paid_partially:
        msgs: 
            - content: Cette facture n'a pas été payée à hauteur du montant initial. Pour quelle raison voulez-vous la classer malgré tout?
              type: warning
        rows: 
            - custom: 1
              label: Raison
              input_name: close_code
              input: 
                  type: select
                  options: 
                      array: closeReasons
            - custom: 1
              label: Commentaires
              input_name: close_note
              input: 
                  type: textarea
                  rows: 3
                  auto_expand: 1
                  
    cancel:
        msgs: 
            - content: Pour quelle raison voulez-vous classer la facture abandonnée ?
              type: warning
        rows: 
            - custom: 1
              label: Raison
              input_name: close_code
              input: 
                  type: select
                  options: 
                      array: cancelReasons
            - custom: 1
              label: Commentaires
              input_name: close_note
              input: 
                  type: textarea
                  rows: 3
                  auto_expand: 1
                  
    duplicate:
        rows: 
            2: 
                field: libelle
            3: 
                field: ef_type
            4:
                field: date_lim_reglement
            5: 
                field: datef
            6:
                field: fk_account
                
    validate: 
        title: Validation
        rows: 
            - custom: 1
              label: Informations
              input_name: validation_type
              content: 
                  callback: renderValidationFormInfos
            - custom: 1
              label: Déplacer les lignes négatives dans un avoir
              input_name: create_avoir
              data_type: bool
              input: 
                  type: toggle
              value: 1
              display_if: 
                  field_name: validation_type
                  show_values: 2
            - custom: 1
              label: Convertir l'avoir en remise
              input_name: convert_avoir_to_reduc
              data_type: bool
              input: 
                  type: toggle
              value: 1
              display_if: 
                  fields_names: validation_type,create_avoir
                  validation_type: 
                      show_values: 1,2
                  create_avoir: 
                      hide_values: 0
            - custom: 1
              label: Appliquer la remise à la facture
              input_name: use_discount_in_facture
              data_type: bool
              input: 
                  type: toggle
              value: 1
              display_if: 
                  fields_names: validation_type,convert_avoir_to_reduc,create_avoir
                  validation_type: 
                      show_values: 1,2
                  convert_avoir_to_reduc: 
                      hide_values: 0
                  create_avoir: 
                      hide_values: 0
            - custom: 1
              hidden: 1
              input_name: hide_force_validation
              data_type: bool
              input: 
                  type: hidden
              value: 
                  callback: checkEquipmentsAttribution
            - custom: 1
              label: Forcer la validation
              input_name: force_validate
              content: 
                  callback: renderForceValidationInput
              display_if: 
                  field_name: hide_force_validation
                  hide_values: 1
              
fields_tables: 
    infos: 
        rows: 
            - label: Type
              value: 
                  callback: displayType
            - field: libelle
              edit: 1
            - field: fk_statut
            - field: centre
            - field: entrepot
              display: nom_url
            - field: ef_type
              edit: 
                  callback: isEditable
            - field: datef
              edit: 
                  callback: isEditable
            - field: zone_vente
              edit: 1
    
    client: 
        rows: 
            - field: fk_soc
              display: card
            - field: ref_client
              edit: 1
            - label: Remises client
              value: 
                  callback: displayRemisesClient
            
    payment:
        rows:
            - field: fk_account    
              edit: 1
            - field: fk_cond_reglement
              edit: 
                  callback: isEditable
            - field: fk_mode_reglement
              edit: 
                  callback: isEditable
            - field: date_lim_reglement
                
    pdf: 
        rows: 
            - field: remise_globale_label
              edit: 1
              show: 
                  callback: hasRemiseGlobale
            - label: Fichier PDF
              value: 
                  callback: displayPDFButton
                                                 
    totals: 
        rows: 
            - label: Remises
              value: 
                  callback: displayTotalRemises
            - field: total
            - field: tva
            - field: total_ttc
            
views: 
    default: 
        objects_change_reload: Bimp_FactureLine,Bimp_Paiement,ObjectLineRemise,BimpFile
    content_infos: 
        objects_change_reload: Bimp_FactureLine,Bimp_Paiement,ObjectLineRemise,BimpFile
    full: 
        objects_change_reload: Bimp_FactureLine,Bimp_Paiement,ObjectLineRemise,BimpFile
        
filters_panels: 
    default: 
        filters: 
            paye: 
                field: paye
                show: 1
            ref: 
                field: facnumber
            total_ht:
                field: total
            total_ttc: 
                field: total_ttc
                
            availability: unset
            
lists_cols: 
    ref: 
        field: facnumber
    type: 
        field: type
    centre: 
        field: centre
    paid: 
        label: Payée
        value: 
            callback: 
                method: displayPaidStatus
                params: 
                    - 0
                    - 1
    total_ht: 
        field: total
#        has_total: 1
    total_ttc: 
#        has_total: 1
        field: total_ttc
    pdf: 
        label: Fichier PDF
        value: 
            callback: 
                method: displayPDFButton
                params: 
                    - false
    datec: 
        field: datec
    availability: unset
    input_reason: unset
    marge:
        field: marge
    
lists: 
    default: 
        total_row: 1
        title: Factures
        icon: fas_file-invoice-dollar
        bulk_actions: unset
        sort_field: datec
        sort_way: desc
        add_btn_label: Créer une nouvelle facture
        add_form_values: 
            fields: 
                entrepot: 
                    request: id_entrepot
                fk_soc:
                    request: id_client
        delete_btn: 0
        cols: 
            ref: 
            type: 
            statut: 
            paid: 
            soc: 
            commercial:
            total_ttc: 
            pdf:
        
    client: 
        extends: default
        cols: 
            soc: unset
            
cards: 
    default: 
        title: 
            field_value: facnumber
        status: fk_statut
        view_btn: 1
        fields: 
            - field: total_ttc
            - label: Payé
              value: 
                  callback: displayPaid
            - label: Fichier PDF
              value: 
                  callback: displayPDFButton
                  
    light: 
        title: 
            field_value: facnumber
        view_btn: 0
        fields: 
            - field: total_ttc
            - field: fk_statut
            - label: Payé
              value: 
                  callback: displayPaid
        
searches:
    default: 
        fields_search: 
            - facnumber
