
extends: 
    module: bimpcommercial
    object_name: BimpComm

dol_object: 
    instance: 
        dol_object: 
            module: fourn
            file: fournisseur.commande
            class: CommandeFournisseur
            
table: commande_fournisseur
controller: commandeFourn
icon: fas_cart-arrow-down
list_page_url: 
    controller: commandesFourn

labels: 
    name: commande fournisseur
    name_plur: commandes fournisseurs
    is_female: 1
        
objects: 
    lines: 
        instance: 
            bimp_object: Bimp_CommandeFournLine
            
    fournisseur: 
        relation: hasOne
        delete: 0
        instance: 
            bimp_object: 
                module: bimpcore
                name: Bimp_Fournisseur
            id_object: 
                field_value: fk_soc
            
    receptions: 
        relation: hasMany
        delete: 1
        instance: 
            bimp_object: 
                module: bimplogistique
                name: BL_CommandeFournReception
                
    files:
        list: 
            filters:
                parent_object_name: Bimp_CommandeFourn
        add_form: 
            values:
                fields: 
                    parent_object_name: Bimp_CommandeFourn
               
    user: 
        relation: hasOne
        delete: 0
        instance: 
            bimp_object: 
                module: bimpcore
                name: Bimp_User
            
    user_approve:
        extends: user
        instance: 
            id_object: 
                field_value: fk_user_approve
            
    user_approve2:
        extends: user
        instance: 
            id_object: 
                field_value: fk_user_approve2
            
    user_resp:
       extends: user
       instance: 
           id_object: 
              field_value: fk_user_resp
              
    entrepot: 
        instance: 
            id_object: 
                field_value: entrepot
      
associations: 
    factures: 
        object: facture_fourn
        label: Factures
        display: 
            default: 
                type: nom_url
                
fields: 
    fk_soc: 
        label: Fournisseur
        object: fournisseur
        input: 
            societe_type: supplier
            create_form: fournisseur_light
    ref_supplier: 
        label: Référence fournisseur
    total_ttc: 
        label: Total TTC
        type: money
    remise_percent: 
        label: Remise
        type: percent
        default_value: 0
    date_creation: 
        label: Créée le
        dol_prop: date
        type: datetime
    date_valid: 
        label: Validée le
        type: datetime
    date_approve: 
        label: 1ère approbation le
        type: datetime
    date_approve2: 
        label: 2ème approbation le
        type: datetime
    date_commande: 
        label: Date de la commande
        type: date
        input: 
            display_now: 1
    date_livraison: 
        label: Date prévue de livraison
        type: date
    fk_user_approve: 
        label: Approuvée par
        dol_prop: user_approve_id
        type: id_object
        object: user_approve
        input: 
            type: hidden
    fk_user_approve2: 
        label: Approuvée (2) par
        dol_prop: user_approve_id2
        type: id_object
        object: user_approve2
        input: 
            type: hidden
    fk_user_resp: 
        label: Personne en charge
        type: id_object
        object: user_resp
        default_value: 
            prop:
                name: id
                object: 
                    global: user
        input: 
            type: search_user
    fk_input_method: 
        label: Méthode de commande
        dol_prop: methode_commande_id
        type: int
        values: 
            array: commandeMethods
    fk_cond_reglement:
        required: 0
    attente_info: 
        label: En attente d'infos
        type: bool
        default_value: 0         
    invoice_status: 
        label: Statut facturation
        type: int
        values: 
            array: invoice_status
    billed: 
        label: Facturé
        type: bool
        default_value: 0
    status_forced: 
        label: Status forcés
        type: json
#    fk_account: 
#        label: Compte bancaire
#        type: id_object
#        object: account
    delivery_type: 
        label: Addresse de livraison
        type: int
        values: 
            array: delivery_types
        default_value: 0
#    type_entrepot: 
#        label: Type entrepôt
#        type: int
#        values: 
#            array: types_entrepot
        
    custom_delivery: 
        label: Adresse de livraison personnalisée
        type: text
        input: 
            auto_expand: 1
            rows: 3
        display_if: 
            field_name: delivery_type
            show_values: 2
    ref_client: unset
    total: unset
    fk_availability: unset
    fk_input_reason: unset
    remise_globale: unset
    remise_globale_label: unset
    
forms: 
    default: 
        rows: 
            - field: entrepot
            - field: libelle
            - field: ef_type
            - field: fk_soc
            - field: fk_user_resp
            - field: ref_supplier
            - field: delivery_type
            - field: custom_delivery
            - field: date_livraison
            - field: fk_cond_reglement
            - field: fk_mode_reglement
#            - field: fk_account
            - field: model_pdf
            - field: zone_vente
              show: 
                  callback: isLoaded
            - field: attente_info
            - field: note_private
            - field: note_public
            
    make_order: 
        rows: 
            - field: date_commande
            - field: fk_input_method
            
    receive: 
        rows: 
            - custom: 1
              label: Date de livraison
              input_name: date_livraison
              data_type: date
              input: 
                  type: date
                  display_now: 1
            - custom: 1
              label: Livraison
              input_name: livraison_type
              input: 
                  type: select
                  options: 
                      array: livraison_types
            - custom: 1
              label: Commentaires
              data_type: string
              input_name: comments
              input: 
                  type: text
                  
    duplicate_commande_fourn: 
        title: Cloner
        force_edit: 1
        rows: 
            - field: libelle
            - field: entrepot
            - field: ef_type
            - field: fk_soc
            - field: ref_supplier
            - field: delivery_type
            - field: custom_delivery
            - field: date_livraison
            
    force_status: 
        title: Forcer un statut
        msgs: 
            - content: Lorqu&apos;un statut est forcé, il cesse d&apos;être déterminé automatiquement<br/>Pour annuler un forçage, sélectionnez "Aucun forçage"
              type: info
        rows: 
            - custom: 1
              label: Type de statut
              input_name: status_type
              input: 
                  type: select
                  options: 
                      reception: Statut réception
                      invoice: Statut facturation
            - custom: 1
              label: Forcer le statut à
              input_name: reception_status
              display_if: 
                  field_name: status_type
                  show_values: reception
              input: 
                  type: select
                  options:
                      -1: Aucun forçage
                      3: En attente de réception
                      4: Reçue partiellement
                      5: Reçue entièrement
            - custom: 1
              label: Forcer le statut à
              input_name: invoice_status
              display_if: 
                  field_name: status_type
                  show_values: invoice
              input: 
                  type: select
                  options:
                      -1: Aucun forçage
                      0: Non facturée
                      1: Facturée partiellement
                      2: Facturée
                      
    invoice: 
        title: Facturation de réceptions
        icon: fas_file-invoice-dollar
        rows: 
            receptions: 
                custom: 1
                label: Réceptions de la commande à facturer
                input_name: receptions
                data_type: id
                input: 
                    type: check_list
                    items: 
                        array: factureReceptions
            add_origin_line: 
                custom: 1
                label: Inclure des lignes de texte indiquant la ou les commandes fournisseur d'origine
                input_name: add_origin_line
                data_type: bool
                input: 
                    type: toggle
                value: 1
            id_facture: 
                custom: 1
                label: Facture fournisseur
                data_type: id
                input_name: id_facture
                input: 
                   type: select
                   options: 
                       array: facturesFournisseur
                   help: Liste des factures fournisseur brouillon pour ce fournisseur et ce secteur.
            id_entrepot: 
                custom: 1
                show: 0
                label: Entrepôt
                input_name: id_entrepot
                input: 
                    type: search_entrepot
                display_if: 
                    field_name: id_facture
                    show_values: 0
            libelle: 
                custom: 1
                label: Libelle
                input_name: libelle
                input: 
                    type: text
                display_if: 
                    field_name: id_facture
                    show_values: 0
            ef_type: 
                custom: 1
                show: 0
                label: Secteur
                input_name: ef_type
                input: 
                    type: select
                    options: 
                        array: secteurs
                display_if: 
                    field_name: id_facture
                    show_values: 0
            ref_supplier:
                custom: 1
                label: Référence fournisseur
                input_name: ref_supplier
                data_type: string
                input: 
                    type: text
                display_if: 
                    field_name: id_facture
                    show_values: 0
            datef: 
                custom: 1
                label: Date facture
                data_type: date
                input_name: datef
                input: 
                    type: date
                    display_now: 1
                display_if: 
                    field_name: id_facture
                    show_values: 0
            date_lim_reglement: 
                custom: 1
                label: Date d'échéance
                data_type: date
                input_name: date_lim_reglement
                required: 1
                input: 
                    type: date
                display_if: 
                    field_name: id_facture
                    show_values: 0
            cond_reglement: 
                custom: 1
                label: Conditions de réglement
                input_name: id_cond_reglement
                data_type: id
                input: 
                    type: select_cond_reglement
                display_if: 
                    field_name: id_facture
                    show_values: 0
            mode_reglement: 
                custom: 1
                label: Mode de réglement
                input_name: id_mode_reglement
                data_type: id
                input: 
                    type: select_payment
                display_if: 
                    field_name: id_facture
                    show_values: 0
            note_publique: 
                custom: 1
                label: Note publique
                input_name: note_public
                data_type: text
                input: 
                    type: textarea
                    rows: 3
                    auto_expand: 1
                display_if: 
                    field_name: id_facture
                    show_values: 0
            note_privee: 
                custom: 1
                label: Note privée
                input_name: note_private
                data_type: text
                input: 
                    type: textarea
                    rows: 3
                    auto_expand: 1
                display_if: 
                    field_name: id_facture
                    show_values: 0
                  
    bulk_invoice: 
        extends: invoice
        title: Nouvelle facture fournisseur
        rows: 
            receptions: 
                label: Réceptions à facturer
                input: 
                    items: 
                        array: postReceptions
                    help: Attention, toutes les réceptions doivent être du même fournisseur
                value: 
                    request_field: receptions                    
            id_facture: 
                hidden: 1
                input: 
                    type: hidden
                value: 0
            id_entrepot: 
                show: 1
            ef_type: 
                show: 1
         
fields_tables: 
    infos: 
        rows: 
            - field: entrepot
              display: nom_url
              edit: 1
            - field: ef_type    
            - field: fk_statut
            - field: invoice_status
            - field: attente_info
              edit: 1
            - field: date_commande
            - field: date_livraison
              edit: 1
            - field: delivery_type
              edit: 1
            - field: custom_delivery
              edit: 1
            - field: fk_input_method
              show: 
                  field_value: fk_input_method
            - field: entrepot
            - field: zone_vente
              edit: 1
    
    fournisseur: 
        title: Fournisseur
        icon: fas_building
        rows: 
            - field: fk_soc
              display: card
            - field: ref_supplier
              edit: 1
                  
    payment:
        rows:
            - field: fk_cond_reglement
              edit: 
                  callback: isEditable
            - field: fk_mode_reglement
              edit: 
                  callback: isEditable
                
    pdf: 
        rows: 
            - label: Fichier PDF
              value: 
                  callback: displayPDFButton
                  
    totals: 
        rows: 
            - label: Remises
              value: 
                  callback: displayTotalRemises
            - field: total_ht
            - field: tva
            - field: total_ttc
            
views: 
    default: 
        objects_change_reload: Bimp_CommandeFournLine,ObjectLineRemise,BimpFile
        rows: 
            0: 
                cols: 
                    1:
                        rows: 
                            0: 
                                cols: 
                                    0: 
                                        fields_table: 
                                            name: fournisseur
    content: 
        rows: 
            0: 
                cols: 
                    1: unset
    
    content_infos: 
        objects_change_reload: Bimp_CommandeFournLine,ObjectLineRemise,BimpFile
    full: 
        objects_change_reload: Bimp_CommandeFournLine,ObjectLineRemise,BimpFile                 
    
filters_panels: 
    default: 
        filters: 
            type: unset
            date_create: 
                field: date_creation
            total_ttc: 
                field: total_ttc
            ref_supplier: 
                field: ref_supplier
            date_commande: 
                field: date_commande
            date_livraison: 
                field: date_livraison
            fk_user_resp: 
                field: fk_user_resp
                
            availability: unset
            ref_client: unset
            remise_globale: unset
            remise_globale_label: unset
            
lists_cols: 
    ref_supplier: 
        field: ref_supplier
    total_ttc:
        field: total_ttc    
    remise: 
        field: remise_percent
    date_creation: 
        field: date_creation
    date_valid: 
        field: date_valid
    date_approve: 
        field: date_approve
    date_approve2: 
        field: date_approve2
    date_commance: 
        field: date_commance
    date_livration: 
        field: date_livration
    attente: 
        field: attente_info
    user_author: 
        field: fk_user_author
        display: nom_url
    user_valid: 
        field: fk_user_valid
        display: nom_url
    user_approve: 
        field: fk_user_approve
        display: nom_url
    user_approve2: 
        field: fk_user_approve2
        display: nom_url
    user_resp: 
        field: fk_user_resp
        display: nom_url
    invoice_status:
        label: St. Fac
        field: invoice_status
        display: icon
        min_width: 30px;
        max_width: 30px;
    billed: 
        label: Facturée
        type: bool
        default_value: 0
        input: 
            type: hidden
        
        
#    input_method: 
#        field: fk_input_method
#        display: nom_url
#    account: 
#        field: fk_account
#        display: nom_url
        
    total_pa: unset
    ref_client: unset
    availability: unset
    input_reason: unset
    tx_marge: unset
    tx_marque: unset
    
lists: 
    default: 
        title: Commandes fournisseurs
        icon: fas_cart-arrow-down
        bulk_actions:
            - label: supprimer les commandes fournisseurs sélectionnées
        sort_field: date_creation
        sort_way: desc
        cols: 
            ref: 
            statut: 
            attente:
            date_creation:
            user_resp:
            soc: 
            total_ttc:
                
    fourn:
        extends: default
        extends: default
        cols: 
            soc: unset
                
cards:
    default: 
        title: nom
        status: fk_statut
        fields: 
            - label: Fournisseur
              field: fk_soc
              display: nom_url
            - label: Entrepôt
              field: entrepot
              display: nom_url
        view_btn: 1
        
searches:
    default: 
        fields_search: 
            - a.ref
            - ef.libelle
            - s.nom
        joins:
            - table: propal_extrafields
              on: a.rowid = ef.fk_object
              alias: ef
            - table: societe
              on: a.fk_soc = s.rowid
              alias: s
