
table: facture_fourn_det
primary: rowid

parent_module: bimpcommercial
parent_object: Bimp_FactureFourn
parent_id_property: fk_facture_fourn

labels: 
    name: achat
    
objects:
    facture_fourn: 
        instance: 
            id_object: 
                field_value: fk_facture_fourn
                
    facture_fourn_line: 
        relation: hasOne
        delete: 0
        instance: 
            bimp_object: 
                module: bimpcommercial
                name: Bimp_FactureFournLine
                
    fournisseur: 
        instance: 
            id_object: 
                field_value: id_fourn
                
    product: 
        instance: 
            id_object: 
                field_value: fk_product
                
                
fields: 
#    Champs facturedet: 
    fk_facture_fourn: 
        label: Facture fournisseur
        type: id_parent
        object: facture_fourn
        
    fk_product: 
        label: Produit
        type: id_object
        object: product
        
    subprice: 
        label: Prix unitaire HT
        type: money
        
    tva_tx: 
        label: Taux de TVA
        type: percent
        
    qty: 
        label: Quantité
        type: qty
        decimals: 3
        
    remise_percent: 
        label: Remise (%)
        type: percent
        
    total_ht: 
        label: Total HT
        type: money
        
    total_tva: 
        label: Total TVA
        type: money
        
    total_ttc: 
        label: Total TTC
        type: money
        
#    Champs extra: 
    
    id_fourn: 
        label: Fournisseur
        type: id_object
        object: fournisseur
        extra: 1
    
    ref_fourn: 
        label: Ref. fournisseur
        extra: 1
        
    date: 
        label: Date
        extra: 1
        type: date
        
fields_tables: 
    infos: 
        title: Infos
        icon: fas_info-circle
        rows: 
            - field: date
            - field: fk_product
              display: nom_url
            - field: ref_fourn
            - field: fk_facture_fourn
              display: card
              
    montants: 
        title: Montants
        icon: fas_euro-sign
        rows: 
            - field: qty
            - field: subprice
            - field: tva_tx
            - field: remise_percent
            - field: total_ht
            - field: total_tva
            - field: total_ttc
            
views: 
    default: 
        rows: 
            - cols: 
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: infos
                
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: montants
            
filters_panels: 
    default: 
        filters: 
            dates: 
                field: date
            status: 
                field: fk_statut
                child: parent
            product: 
                field: fk_product
            fourn: 
                field: id_fourn
            ref_fourn: 
                field: ref_fourn
            priceProd:
                field: price
                child: product
            qty: 
                field: qty
            total_ht: 
                field: total_ht
            tva_tx:
                field: tva_tx
            gamme: 
                field: gamme
                child: product
            categorie:
                field: categorie
                child: product
            collection:
                field: collection
                child: product
            nature:
                field: nature
                child: product
            famille:
                field: famille
                child: product
        
lists_cols: 
    facture: 
        field: fk_facture_fourn
        display: nom_url
    product: 
        field: fk_product
        display: nom_url
    fourn: 
        field: id_fourn
        display: nom_url
    ref: 
        field: ref
        child: product
    ref_fourn: 
        field: ref_fourn
    label:
        field: label
        child: product
    subprice: 
        field: subprice
    tva_tx: 
        field: tva_tx
    qty: 
        field: qty
        has_total: 1
    remise_percent: 
        field: remise_percent
    total_ht: 
        field: total_ht
        has_total: 1
    total_tva: 
        field: total_tva
        has_total: 1
    total_ttc: 
        field: total_ttc
        has_total: 1
    date: 
        field: date
    marque: 
        field: 
    gamme: 
        field: gamme
        child: product
    categorie:
        field: categorie
        child: product
    collection:
        field: collection
        child: product
    nature:
        field: nature
        child: product
    famille:
        field: famille
        child: product
    
    
lists: 
    default: 
        title: Achats de produits
        total_row: 1
        configurable: 1
        n: 10
        sort_field: date
        sort_way: desc
        filters_panel: default
        modal_view: default
        list_filters: 
            - name: fk_product
              filter: 
                  operator: '>' 
                  value: 0
        cols: 
            fourn: 
            ref_fourn: 
            categorie:
            label: 
            collection:
            qty:         
            total_ht:
