dol_object: 
    instance: 
        dol_object: 
            module: compta/paiement
            file: paiement
            
table: paiement
primary: rowid
icon: fas_euro-sign

labels: 
    name: paiement

fields: 
#    Champs en base
    ref: 
        label: Référence
    statut: 
        label: Statut
        type: int
    datec:
        label: Créé le
        type: date
    datep: 
        label: Date
        type: date
        input:
            type: date
            display_now: 1
        dol_prop: date
    amount: 
        label: Montant
        type: money
    num_paiement: 
        label: Num.
        dol_prop: num_paiement
        display_if: 
            field_name: id_mode_paiement
            show_values: CHQ,VIR
    fk_bank: 
        label: Opération sur compte
        type: int
        dol_prop: bank_line
    note: 
        label: Note
        type: text
        user_edit: 1
    exported:
        label: Comptabilisée
        type: bool
        
#    Champs extra: 
    type: 
        label: Type
        values: 
            array: modeReglements
        extra: 1   
    
forms: 
    default: 
        # Attention: étendu par Bimp_PaiementFourn
        rows: 
            rbt: 
                custom: 1
                label: Type d'opération
                data_type: bool
                input_name: is_rbt
                input: 
                    type: select
                    options: 
                        0: Paiement factures client
                        1: Remboursement avoirs client
            soc: 
                custom: 1
                label: Client
                data_type: id_object
                input_name: id_client
                input: 
                    type: search_societe
                    societe_type: customer
                required: 1
                value: 
                    request_field: id_client
            use_caisse: 
                custom: 1
                input_name: use_caisse
                label: Paiement en caisse
                data_type: bool
                content: 
                    callback: renderUseCaisseInput
            caisse: 
                custom: 1
                label: Caisse
                data_type: id_object
                input_name: id_caisse
                content: 
                    callback: renderCaisseInput
                display_if: 
                    field_name: use_caisse
                    show_values: 1
            compte:
                custom: 1
                label: Compte bancaire
                input_name: id_account
                input: 
                    type: select_mysoc_account
                value: 
                    callback: getDefaultBankAccount
                depends_on: id_caisse
            datep:
                field: datep
            mode_paiement:
                custom: 1
                label: Mode de paiement
                input_name: id_mode_paiement
                input: 
                    type: select_payment
                    value_type: code
                    include_empty: 1
                value: 
                    request_field: id_mode_paiement
                required: 1
            num_paiement: 
                field: num_paiement
                label: N° (Chèque ou virement)
            emetteur: 
                custom: 1
                label: Emetteur (Chèque ou virement)
                data_type: string
                input_name: nom_emetteur
                input: 
                    type: text
                display_if: 
                    field_name: id_mode_paiement
                    show_values: CHQ,VIR
            banque_emetteur: 
                custom: 1
                label: Banque émetteur (chèque)
                data_type: string
                input_name: banque_emetteur
                input: 
                    type: text
                display_if: 
                    field_name: id_mode_paiement
                    show_values: CHQ
            note: 
                field: note
            avoirs:
                custom: 1
                label: Avoirs client
                depends_on: id_client
                input_name: avoirs
                input: 
                    type: select_remises
                    id_client: 
                        request_field: id_client
                    multiple: 1
                display_if: 
                    fields_names: id_client,is_rbt
                    is_rbt: 
                        show_values: 0
                    id_client: 
                        hide_values: 0,
            factures: 
                custom: 1
                label: Factures à payer / Avoirs à rembourser
                depends_on: id_client,is_rbt
                input_name: factures
                display_if: 
                    field_name: id_client
                    hide_values: 0,
                content: 
                    callback: renderFacturesAmountsInputs
          
    single: 
        extends: default
        rows: 
            rbt: unset
            soc: unset
            avoirs: unset
            factures: unset
            
            id_facture: 
                custom: 1
                label: Facture
                input_name: id_facture
                hidden: 1
                input: 
                    type: hidden
            
            amount: 
                custom: 1
                input_name: single_amount
                label: Montant
                data_type: money
                decimals: 2
                input: 
                    type: text
                    
            force_extra_paiement: 
                custom: 1
                hidden: 1
                input_name: force_extra_paiement
                input: 
                    type: hidden
                value: 0
                
                    
    move_amount: 
        title: Déplacer un montant d'une facture à une autre
        rows: 
            - custom: 1
              label: Facture d'origine
              input_name: id_facture_from
              data_type: id
              required: 1
              input: 
                  type: select
                  options: 
                      array: factures
            - custom: 1
              label: Montant à déplacer
              input_name: amount_to_move
              data_type: money
              required: 1
              content: 
                  callback: renderAmountToMoveInput
              depends_on: id_facture_from
            - custom: 1
              label: Facture de destination
              input_name: id_facture_to
              required: 1
              input: 
                  type: search_object
                  object: facture
                  card: detail
      
fields_tables: 
    infos: 
        title: Infos
        icon: fas_info-circle
        rows: 
            - field: type
            - field: amount
            - field: ref
            - field: num_paiement
            - field: datep
            - field: exported
            - field: note
            
    objects: 
        title: Objets liés
        icon: fas_link
        rows: 
            - label: Client(s)
              value: 
                  callback: displayClient
            - label: Facture(s)
              value: 
                  callback: displayFactures
            
views: 
    default: 
        rows: 
            - cols: 
                - type: object_header
            - cols: 
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  fields_table: 
                      name: infos
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  fields_table: 
                      name: objects
                
filters: 
    id_facture: 
        label: Facture
        data_type: id_object
        type: value
        input: 
            object: facture
    id_client: 
        custom: 1
        label: Client
        data_type: id_object
        type: value
        input: 
            type: search_societe
            
filters_panels: 
    default: 
        filters: 
            ref: 
            datep: 
            type: 
            amount: 
            id_facture: 
            id_client:
                    
lists_cols: 
    factures: 
        label: Factures
        value: 
            callback: displayFactures
        search: 
            type: values
            input: 
                type: search_object
                options: 
                    object: facture
                    card: light
    client: 
        label: Client
        value: 
            callback: displayClient
        search: 
            type: values
            input: 
                type: search_societe
    
lists: 
    default: 
        configurable: 1
        checkboxes: 0
        sort_field: id
        sort_way: desc
        n: 10
        extra_btn: 
            callback: getListsExtraButtons
        filters_panel: default
        cols: 
            ref: 
            client: 
            type: 
            datep:  
            amount: 
            factures: 
                
    client: 
        extends: default
        cols: 
            client: unset
                