extends: 
    module: bimpcommercial
    object_name: BimpComm

abstract: 0

dol_object: 
    instance: 
        dol_object: 
            module: comm/propal
            file: propal
            
table: propal
controller: propal
icon: fas_file-invoice
list_page_url: 
    controller: propals

labels: 
    name: proposition commerciale
    name_plur: propositions commerciales
    is_female: 1
    
objects: 
    lines: 
        instance: 
            bimp_object: Bimp_PropalLine
                
    files:
        list: 
            filters:
                parent_object_name: Bimp_Propal
        add_form: 
            values:
                fields: 
                    parent_object_name: Bimp_Propal
                    
    user_close: 
        extends: user
        instance: 
            id_object: 
                field_value: fk_user_cloture
    
    contrat:
        instance:
            bimp_object:
                module: bimpcontract
                name: BContract_contrat
                
fields:
    datec: 
        label: Créée le
        type: datetime
    datep: 
        label: Date
        dol_prop: date
        type: date
        input: 
            display_now: 1
        required: 1
    fin_validite: 
        label: Date de fin de validité
        type: date
    date_livraison: 
        label: Date de livraison
        type: date
        input:
            help:
                callback: getHelpDateRenouvellementContrat
    marge: 
        label: Marge
        type: money
        default_value: 0
    model_pdf: 
        default_value: bimpdevis
    pdf_hide_pu: 
        label: Masquer les prix unitaires dans le PDF
        dol_extra_field: 1
        type: bool
        default_value: 0
        sortable: 0
    pdf_hide_reduc: 
        label: Masquer les remises dans le PDF
        dol_extra_field: 1
        type: bool
        default_value: 0
        sortable: 0
    pdf_hide_total: 
        label: Masquer les totaux dans le PDF
        dol_extra_field: 1
        type: bool
        default_value: 0 
        sortable: 0
    pdf_hide_ref:
        label: Masquer les références des produits dans le PDF
        dol_extra_field: 1
        type: bool
        default_value: 0
        sortable: 0
    pdf_hide_ttc:
        label: Masquer le TTC dans le PDF
        dol_extra_field: 1
        type: bool
        default_value: 0
        sortable: 0    
    pdf_periodicity: 
        label: Périodicité
        dol_extra_field: 1
        type: int
        values: 
            array: pdf_periodicities
        default_value: 0
    pdf_periods_number: 
        label: Nombre de périodes
        dol_extra_field: 1
        type: qty
        min: 0
        decimals: 0
        default_value: 0
    pdf_proforma: 
        label: Facture proforma
        dol_extra_field: 1
        type: bool
        default_value: 0
    fk_user_cloture: 
        label: Fermée par
        dol_prop: user_close_id
        type: id_object
        object: user_close
        input: 
            type: hidden
                
forms: 
    default: 
        on_save: redirect
        rows: 
            - field: replaced_ref
            - custom: 1
              input_name: id_user_commercial
              label: Commercial suivi proposition
              input: 
                  type: search_user
              show: 
                  callback: isNotLoaded
              value: 
                  prop: 
                      object: 
                          global: user
                      name: id
            - field: entrepot
            - field: ef_type
            - field: fk_soc
            - field: ref_client
            - field: libelle
            - field: fk_input_reason
              show: 
                  callback: isEditable
            - field: fk_cond_reglement
              show: 
                  callback: isEditable
            - field: fk_mode_reglement
              show: 
                  callback: isEditable
            - field: datep
              show: 
                  callback: isEditable
            - custom: 1
              label: Durée de validité (en jours)
              show: 
                  callback: isNotLoaded
              value: 
                  callback: getDureeValidite
              input_name: duree_validite
              data_type: int
              min: 0
              input: 
                  type: qty
            - field: fk_availability
              show: 
                  callback: isEditable
            - field: date_livraison
            - field: model_pdf
            - field: pdf_hide_pu
            - field: pdf_hide_reduc
            - field: pdf_hide_total
            - field: pdf_hide_ref
            - field: pdf_hide_ttc
            - field: pdf_periodicity
            - field: pdf_periods_number
            - field: pdf_proforma
            - field: zone_vente
              show: 
                  callback: isLoaded
            - field: note_private
            - field: note_public
            - field: prime
            
    close: 
        rows: 
            - custom: 1
              label: Nouveau statut
              data_type: int
              input_name: new_status
              input: 
                  type: select
                  options: 
                      array: closeStatus
            - custom: 1
              label: Note
              data_type: text
              input_name: note
              input: 
                  type: textarea
                  rows: 3
                  auto_expand: 1
              value: 
                  field_value: note_private
                  
    duplicate_propal:
        extends: duplicate
        force_edit: 1
        rows: 
            date_propal: 
                field: datep
            date_liv: 
                field: date_livraison
    
    contrat:
        rows:
            - field: fk_soc
              show: 
                  callback: isNotRenouvellementContrat
            - custom: 1
              label: Secteur
              show:
                  callback: isNotRenouvellementContrat
              input_name: secteur_contrat
              value:
                  callback:
                      object: contrat
                      method: showValueSecteurInPropal
                      params:
                          0:
                              field_value: ef_type
              input:
                  type: select
                  options:
                      callback:
                            object: contrat
                            method: getSecteursContrat
                  
            - custom: 1
              label: Libellé du contrat
              show: 
                  callback: isNotRenouvellementContrat
              input_name: label
              value:
                  field_value: libelle
              input:
                  type: text
            - custom: 1
              label: Annule et remplace
              input_name: ref_ext
              show: 
                  callback: isNotRenouvellementContrat
              input:
                  type: text
                  size: 15
                  help: A remplir en cas de renouvellement d'un ancien contrat - 15 caractères maximum
            - custom: 1
              label: Référence client
              input_name: ref_customer
              show: 
                  callback: isNotRenouvellementContrat
              input:
                  type: text
              value:
                  callback:
                      method: getData
                      params:
                          - ref_client
            - custom: 1
              label: Début de validité du contrat
              required: 1
              input_name: valid_start
              value:
                  field_value: date_livraison
              input:
                  type: date
                  display_now: 1
            - custom: 1
              label: Durée en mois
              input_name: duree_mois
              show: 
                  callback: isNotRenouvellementContrat
              input:
                  type: qty
              value: 12
            - custom: 1
              label: Périodicitée de facturation
              input_name: periodicity
              value: 12
              show: 
                  callback: isNotRenouvellementContrat
              input:
                  type: select
                  options:
                      prop:
                          object: contrat
                          name: period
                          is_static: 1
            - custom: 1
              label: Objet du contrat
              input_name: objet_contrat
              show: 
                  callback: isNotRenouvellementContrat
              input:
                  type: select
                  options:
                      prop:
                          object: contrat
                          name: objet_contrat
                          is_static: 1
            - custom: 1
              show: 
                  callback: isNotRenouvellementContrat
              label: Delai d'intervention
              input_name: gti
              value: 8
              input:
                  type: select
                  options:
                      prop:
                          object: contrat
                          name: gti
                          is_static: 1       
            - custom: 1
              label: Renouvellement
              show: 
                  callback: isNotRenouvellementContrat
              input_name: re_new
              value: 12
              input:
                  type: select
                  options:
                      prop:
                          object: contrat
                          name: renouvellement
                          is_static: 1
            - field: fk_mode_reglement
            - custom: 1
              show: 
                  callback: isNotRenouvellementContrat
              label: Utiliser l'indice SYNTEC
              value: 1
              input_name: use_syntec
              input: 
                  type: toggle
            - custom: 1
              label: Commercial signature
              input_name: commercial_signature
              show: 
                  callback: isNotRenouvellementContrat
              value:
                  prop:
                    name: id
                    object:
                        global: user
              input: 
                type: search_user
            - custom: 1
              label: Commercial suivi du contrat
              show: 
                  callback: isNotRenouvellementContrat
              input_name: commercial_suivi
              value:
                  prop:
                    name: id
                    object:
                        global: user
              input: 
                type: search_user
            - custom: 1
              label: Note particulière au contrat
              input_name: note_public
              input:
                  type: html
              value:
                  callback:
                      method: getData
                      params:
                          - note_public
            - custom: 1
              label: Note privée
              input_name: note_private
              input:
                  type: html
              value:
                  callback:
                      method: getData
                      params:
                          - note_private
            
fields_tables: 
    infos: 
        rows: 
            - field: replaced_ref
              show: 
                  field_value: replaced_ref
            - field: libelle
              edit: 1
            - field: fk_statut
            - field: entrepot
              display: nom_url
              edit: 1
            - field: ef_type
              edit: 1
            - field: fk_input_reason
              edit: 
                  callback: isEditable
            - field: datep
              edit: 
                  callback: isEditable
            - field: fin_validite
              edit: 
                  callback: isEditable
            - field: date_livraison
              edit: 1
            - field: fk_availability
              edit: 
                  callback: isEditable
            - field: zone_vente
              edit: 1
    
    client: 
        rows: 
            - field: fk_soc
              display: card
            - field: ref_client
              edit: 
                  callback: isEditable
            - label: Remises client
              value: 
                  callback: displayRemisesClient
                  
    payment:
        rows:
            - field: fk_cond_reglement
              edit: 
                  callback: isEditable
            - field: fk_mode_reglement
              edit: 
                  callback: isEditable
                
    pdf: 
        rows: 
            - field: pdf_hide_pu
              edit: 1
            - field: pdf_hide_reduc
              edit: 1
            - field: pdf_hide_total
              edit: 1
            - field: pdf_hide_ref
              edit: 1
            - field: pdf_hide_ttc
              edit: 1
            - field: pdf_periodicity
              edit: 1
            - field: pdf_periods_number
              edit: 1
            - field: pdf_proforma
              edit: 1
            - label: Fichier PDF
              value: 
                  callback: displayPDFButton
                  
    totals: 
        rows: 
            - label: Remises
              value: 
                  callback: displayTotalRemises
            - field: total_ht
            - field: tva
            - field: total
            - field: prime
            
views: 
    default: 
        objects_change_reload: Bimp_PropalLine,ObjectLineRemise,BimpFile,RemiseGlobale
    content_infos: 
        objects_change_reload: Bimp_PropalLine,ObjectLineRemise,BimpFile,RemiseGlobale
    full: 
        objects_change_reload: Bimp_PropalLine,ObjectLineRemise,BimpFile,RemiseGlobale
     
lists_cols: 
    fin_validite: 
        label: Fin validité
    date_livraison: 
        label: Livraison
           
filters_panels: 
    default: 
        filters: 
            total_ttc: unset
            type: unset
            datep: 
            date_livraison: 
                
lists: 
    default: 
        title: Propositions commerciales
        icon: fas_file-invoice
        bulk_actions:
            delete: 
                label: supprimer les propositions commerciales sélectionnées
        add_form_values: 
            fields: 
                entrepot: 
                    request: id_entrepot
                fk_soc:
                    request: id_client
        cols: 
            ref: 
            libelle: 
            fk_statut: 
            datec: 
            fk_soc:
            entrepot: 
            ef_type: 
            commercial:
            total: 
        
    user: 
        extends: default
        title: Mes propositions commerciales
        cols: 
            commercial: unset
                
    client: 
        extends: default
        cols: 
            fk_soc: unset
                
cards: 
    default: 
        title: 
            field_value: ref
        status: fk_statut
        view_btn: 1
        fields: 
            - field: replaced_ref
            - field: total
            - label: Fichier PDF
              value: 
                  callback: displayPDFButton

searches:
    default: 
        fields_search: 
            - a.ref
            - ef.libelle
            - s.nom
            - a.replaced_ref
        joins:
            ef: 
                table: propal_extrafields
                on: a.rowid = ef.fk_object
                alias: ef
            s: 
                table: societe
                on: a.fk_soc = s.rowid
                alias: s
        fields_return: 
            - a.ref
            - s.nom
        label_syntaxe: '<a.ref> (Client: <s.nom>)'