extends: 
    module: bimpcommercial
    object_name: FournObjectLine
    
table: bimp_commande_fourn_line

parent_module: bimpcommercial
parent_object: Bimp_CommandeFourn

labels:
    name: ligne de commande fournisseur
    name_plur: lignes de commande fournisseur
    is_female: 1
    
objects: 
    line: 
        relation: hasOne
        delete: 0
        instance: 
            dol_object: 
                module: fourn
                file: fournisseur.commande
                class: CommandeFournisseurLigne
            id_object: 
                field_value: id_line

fields: 
    qty_modif: 
        label: Qté modifiée
        type: qty
        min: none
        max: none
        decimals: 3
        unsigned: 0
        default_value: 0
        
    receptions: 
        label: Réception
        type: json
        
forms: 
    qty_modified: 
        rows: 
            - custom: 1
              label: Quantité totale reçue
              input_name: qty_modified
              content: 
                  callback: renderQtyModifiedInput
        
views: 
    reception: 
        title: Réceptionner
        icon: fas_arrow-circle-down
        rows: 
            - cols: 
                - type: custom
                  custom: 
                      callback: renderReceptionForm
                      
lists_cols: 
    qties: 
        label: Quantités
        value: 
            callback: displayQties
    commande_client: 
        label: Commmande client
        value: 
            callback: displayCommandeClient
    qty_modif:
        field: qty_modif
            
lists: 
    logistique:
        extends: default
        title: Logistique produits / services
        icon: fas_truck-loading
        configurable: 1
        item_checkbox: 1
        after_list_content: unset
        header_buttons: unset
        objects_change_reload: Bimp_CommandeFourn,ObjectLineRemise,BR_Reservation,BL_CommandeFournReception
        bulk_actions: 
            callback: getLogistiqueBulkActions
        extra_btn: 
            callback: getLogistiqueExtraButtons
        cols: 
            desc:
            pu_ht: unset
            tva: unset
            pa_ht: unset
            qty: unset
            qties: 
            remise: unset
            total_ttc: unset
            margin: unset
            commande_client:
    general:
        filters_panel: default
        configurable: 1
        cols: 
            commande_fourn: 
                label: Commande fourn
                field: id_obj
                display: nom_url
            desc:
            pu_ht: 
            tva:
            remise_crt:
            pa_ht: 
            qty: 
            remise: 
            total_ttc: 
            margin:
            commande_status: 
                label: Statut commande
                field: fk_statut
                child: parent
                
filters_panels: 
    default: 
        filters: 
            commande_fourn: 
                field: commande_fourn
            desc: 
                field: desc
            pu_ht: 
                field: pu_ht
            tva:
                field: tva
            remise_crt: 
                field: remise_crt
            pa_ht: 
                field: pa_ht
            qty: 
                field: qty
            remise:
                field: remise
            total_ttc:
                field: total_ttc
            margin:
                field: margin
            commande_status:
                field: fk_statut
                child: parent