extends: 
    module: bimpcommercial
    object_name: ObjectLine

abstract: 0

table: bimp_commande_line

parent_module: bimpcommercial
parent_object: Bimp_Commande

labels: 
    name: ligne de commande
    name_plur: lignes de commande
    is_female: 1
    
objects: 
    line: 
        relation: hasOne
        delete: 0
        instance: 
            dol_object: 
                module: commande
                class: OrderLine
            id_object: 
                field_value: id_line
                
    dol_line: 
        instance: 
            bimp_object: 
                name: CommandeDolLine
                
    shipment: 
        instance: 
            bimp_object: 
                module: bimpreservation
                name: BL_CommandeShipment
            id_object: 
                field_value: id_shipment
                
fields: 
    id_obj: 
        label: Commande
        search: 
            input: 
                type: search_list
                search_list: 
                    table: commande
                    fields_search: rowid,ref
                    field_return_label: ref
                    field_return_value: rowid
                
    ref_reservations: 
        label: Référence réservations
        
    shipments: 
        label: Expéditions
        viewable: 0
        filterable: 0
        type: json
        
    factures: 
        label: Factures
        viewable: 0
        filterable: 0
        type: json
        
    equipments_returned: 
        label: Equipements retournés
        viewable: 0
        filterable: 0
        type: json
     
    qty_modif: 
        label: Qté modifiée
        type: qty
        min: none
        max: none
        decimals: 6
        unsigned: 0
        viewable: 0
        filterable: 0
        default_value: 0
        
    periodicity: 
        label: Périodicité facturation
        values: 
            array: periodicities
        default_value: 0
        
    nb_periods: 
        label: Nombre de périodes à facturer
        type: qty
        min: 0
        max: none
        decimals: 0
        
    periods_start:
        label: Date début
        type: date
        
    next_date_facture:
        label: Date prochaine facture
        type: date
        
    fact_echue:
        label: Facturation à terme échu
        type: bool
     
    # Tous les champs qty_xxx suivants sont uniquement à titre indicatifs 
    # et servent pour la liste "general" (Ne pas utiliser en PHP)   
    # Attention: les quantités sont en valeur absolues (toujours positifs, même pour les retours, sauf qty_total) . 
        
    qty_total: 
        label: Qté Totale
        type: qty
        default_value: 0
        displays: 
            badge:
                type: callback
                method: displayQty
                params: 
                    - total
        
    qty_shipped: 
        label: Qté expédiée
        type: qty
        default_value: 0
        displays: 
            badge:
                type: callback
                method: displayQty
                params: 
                    - shipped
        
    qty_to_ship: 
        label: Qté à expédier
        type: qty
        default_value: 0
        displays: 
            badge:
                type: callback
                method: displayQty
                params: 
                    - to_ship
        
    qty_billed: 
        label: Qté facturée
        type: qty
        default_value: 0
        displays: 
            badge:
                label: Badge
                type: callback
                method: displayQty
                params: 
                    - billed
        
    qty_to_bill: 
        label: Qté à facturer
        type: qty
        default_value: 0
        displays: 
            badge:
                label: Badge
                type: callback
                method: displayQty
                params: 
                    - to_bill
                    
    qty_shipped_not_billed: 
        label: Qté livrée non facturée
        type: qty
        default_value: 0
        displays: 
            badge:
                label: Badge
                type: callback
                method: displayQty
                params: 
                    - shipped_not_billed
                    
    qty_billed_not_shipped: 
        label: Qté facturer non livrée
        type: qty
        default_value: 0
        displays: 
            badge:
                label: Badge
                type: callback
                method: displayQty
                params: 
                    - billed_not_shipped
        
forms: 
    commande_fourn: 
        title: Ajouter à une commande fournisseur
        icon: fas_cart-arrow-down
        rows: 
            - custom: 1
              label: Quantité
              input_name: qty
              content: 
                  callback: renderCommandeFournQtyInput
            - custom: 1
              label: Type de prix
              data_type: int
              input_name: type_price
              input: 
                  type: select
                  options: 
                      1: Prix fournisseur
                      2: Prix d'achat exceptionnel
              value: 1
              
            - custom: 1
              label: Prix d'achat fournisseur
              input_name: id_fourn_price
              data_type: id_object
              object: fourn_price
              create_form: 
                  callback: getFournisseurPriceCreateForm
              create_form_values: 
                  fields: 
                      fk_product: 
                          prop: id_product
              input: 
                  type: select
                  options: 
                      array: productFournisseursPrices
                  extra_content: 
                      callback: renderFournPriceButtons
              value: 
                  callback: getCommandeFournIdPrice
              display_if: 
                  field_name: type_price
                  show_values: 1
              required_if: type_price=1
              
            - custom: 1
              label: Fournisseur
              input_name: id_fourn
              data_type: id_object
              input: 
                  type: select
                  options: 
                      array: prodFournisseurs
              display_if: 
                  field_name: type_price
                  show_values: 2
              required_if: type_price=2
              
            - custom: 1
              label: Prix d'achat exceptionnel (HT)
              input_name: pa_ht
              data_type: money
              value: 0
              input: 
                  type: text
              display_if: 
                  field_name: type_price
                  show_values: 2
              required_if: type_price=2
              
            - custom: 1
              label: Taux de TVA pour le prix d'achat exceptionnel
              input_name: tva_tx
              data_type: percent
              max: 100
              input:
                  type: text
              value: 20
              display_if: 
                  field_name: type_price
                  show_values: 2
#            - custom: 1
#              label: Remise sur le prix d'achat
#              input_name: remise_pa
#              data_type: percent
#              min: 0
#              max: 100
#              input: 
#                  type: text
#            - custom: 1
#              label: Intitulé de la remise sur le prix d'achat
#              input_name: remise_pa_label
#              data_type: string
#              input: 
#                  type: text
#              display_if: 
#                  field_name: remise_pa
#                  hide_values: 0
            - custom: 1
              label: Commande fournisseur
              input_name: id_commande_fourn
              value: new
              input: 
                  type: select
                  options: 
                      array: commandesFournisseurs
              depends_on: type_price,id_fourn_price,id_fourn
              
    qty_modified: 
        rows: 
            - custom: 1
              label: Quantité totale commande
              input_name: qty_modified
              content: 
                  callback: renderQtyModifiedInput
                  
    equipments_return: 
        title: Equipements retournés
        rows: 
            - custom: 1
              label: Equipements
              input_name: equipments
              multiple: 1
              data_type: items_list
              items_data_type: id_object
              object: equipment
              create_form: light_place
              create_form_values: 
                  callback: getNewEquipmentToReturnCreateFormValues
              content: 
                  callback: renderEquipmentsReturnInput
            
    returns_from_lines: 
        rows: 
            - custom: 1
              label: Quantités / équipements retournés
              input_name: lines
              content: 
                  callback: renderReturnsFromLinesInputs
    
    periodicity: 
        title: Facturation périodique
        rows: 
            periodicity: 
                field: periodicity
            nb_periods: 
                field: nb_periods
            periods_start:
                field: periods_start
            fact_echue:
                field: fact_echue
            next_date_facture:
                field: next_date_facture
                edit: 0
            
fields_tables: 
    resume:
        title: Résumé
        icon: fas_cart-arrow-down
        rows: 
            commande: 
                label: Commande
                field: id_obj
                display: nom_url
            desc:
                label: Description
                info: Version longue
                value: 
                    callback: 
                        method: displayLineData
                        params:
                            - desc
            fin_service:
                label: Date de fin
                value: 
                    callback: 
                        method: displayServiceFin
                        
views: 
    default: 
        rows: 
            - cols: 
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: resume
                      
    shipments: 
        panel: 0
        rows: 
            - cols: 
                - type: custom
                  custom: 
                      callback: renderShipmentsView
                      
    invoices: 
        panel: 0
        rows: 
            - cols: 
                - type: custom
                  custom: 
                      callback: renderInvoicesView
        
filters: 
    reservations_status: 
        label: Statut réservation
        type: check_list
        items: 
            array: reservationsStatus
                    
filters_panels: 
    default: 
        filters:
            parent:ref:
                label: Ref. Commande
            parent:fk_statut:
                label: Statut commande
            parent:logistique_status: 
                label: Statut logistique commande
            parent:shipment_status:
                label: Statut expédition commande
            parent:invoice_status:
                label: Statut facture commande
            reservations_status:
            qty_total: 
            qty_to_ship:
            qty_to_bill: 
            qty_shipped:
            qty_billed: 
            qty_billed_not_shipped: 
            qty_shipped_not_billed: 
                        
lists_cols:
    qties: 
        label: Quantités
        value: 
            callback: displayQties
    reservations: 
        label: Statuts
        value: 
            callback: displayReservationsStatus
        min_width: 620
    qty_total: 
        label: Qté totale
        display: badge
        max_width: 60
    qty_shipped: 
        label: Qté exp.
        display: badge
        min_width: 60
    qty_to_ship: 
        label: Qté à exp.
        display: badge
        min_width: 60
    qty_billed: 
        label: Qté facturée
        display: badge
        min_width: 60
    qty_to_bill: 
        label: Qté à fac. 
        display: badge
        min_width: 60
    qty_billed_not_shipped: 
        label: Qté fac non liv. 
        display: badge
        min_width: 60
    qty_shipped_not_billed: 
        label: Qté liv. non fac.
        display: badge
        min_width: 60
    qty_logistique: 
        label: Qtés logistique
        value: 
            callback: displayLogistiqueQties
    nb_periods_billed: 
        label: Périodes facturées
        value: 
            callback: displayBilledPeriods
    nb_periods_tobill: 
        label: Nb périodes à facturer à date
        value: 
            callback: displayNbPeriodsToBill
    old_date_expe:
        label: Date dernière exp. 
        value: 
            callback: 
                method: getOldInfoExpe
                params: 
                    - date
    old_ref_expe:
        label: Dernier ref expé
        value: 
            callback: 
                method: getOldInfoExpe
                params: 
                    - ref
    nb_expe_brouillon:
        label: Nombre d'Expé brouillon
        value: 
            callback: 
                method: getOldInfoExpe
                params: 
                    - nbBrouillon
    old_date_fact:
        label: Date dernière fac.
        value: 
            callback: 
                method: getOldInfoFact
                params: 
                    - ref
    old_ref_fact:
        label: Dernière ref fact
        value: 
            callback: 
                method: getOldInfoFact
                params: 
                    - date
        
lists: 
    default: 
        objects_change_reload: ObjectLineRemise,Bimp_Commande
            
    logistique:
        checkboxes: 1
        title: Logistique produits / services
        icon: fas_truck-loading
        configurable: 1
        position: 1
        position_open: 1
        enable_search: 1
        enable_sort: 1
        pagination: 0
        sort_field: position
        sort_way: asc
        n: 0
        add_btn: 0
        edit_btn: 0
        update_btn: 0
        delete_btn: 0
        objects_change_reload: Bimp_Commande,ObjectLineRemise,BR_Reservation,BL_CommandeShipment
        list_filters: 
            - name: type
              filter: 
                  operator: <>
                  value: 2
        item_checkbox: 
            callback: isNotTypeText
        bulk_actions: 
            callback: getLogistiqueBulkActions
        extra_btn: 
            callback: getLogistiqueExtraButtons
        footer_extra_content:
            callback: renderLogistiqueListFooterExtraContent
        cols: 
            desc_light:
            qties: 
            reservations:
                
    general:
        list_filters: 
            - name: type
              filter: 
                  in: 1,3
        configurable: 1
        filters_panel: default
        filters_panel_open: 1
        sort_field: id
        sort_way: desc
        n: 25
        extra_btn: 
            callback: getGeneralListExtraButtons
        cols:
            parent:entrepot: 
            parent:fk_statut:
            parent:shipment_status:
            parent:invoice_status:
            id_obj: 
            desc_light:
            dol_line:subprice:
            qty_total:
            qty_to_ship:
            qty_to_bill:

    logistic_fourn: 
        extends: general
        
    general_periode:
        extends: general
        cols:
            unextends: 1
            parent:invoice_status: 
            id_obj: 
            desc: 
            nb_periods_billed: 
            periods_start: 
            nb_periods_tobill:
            next_date_facture:
        
cards: 
    default: 
        fields: 
            commande: 
                label: Commande
                field: id_obj
                display: nom_url
            desc:
                label: Description
                info: Version longue
                value: 
                    callback: 
                        method: displayLineData
                        params:
                            - desc
            fin_service:
                label: Date de fin
                value: 
                    callback: 
                        method: displayServiceFin                      
