extends: 
    module: bimpcommercial
    object_name: FournObjectLine

abstract: 0

table: bimp_commande_fourn_line

parent_module: bimpcommercial
parent_object: Bimp_CommandeFourn

labels:
    name: ligne de commande fournisseur
    name_plur: lignes de commande fournisseur
    is_female: 1
    
objects: 
    line: 
        relation: hasOne
        delete: 0
        instance: 
            dol_object: 
                module: fourn
                file: fournisseur.commande
                class: CommandeFournisseurLigne
            id_object: 
                field_value: id_line

    dol_line: 
        instance: 
            bimp_object: 
                name: CommandeFournDolLine
                
fields: 
    id_obj: 
        label: Commande
        search: 
            input: 
                type: search_list
                search_list: 
                    table: commande_fournisseur
                    fields_search: rowid,ref
                    field_return_label: ref
                    field_return_value: rowid
                    
    receptions: 
        label: Réception
        type: json
        viewable: 0
        filterable: 0
        
    qty_modif: 
        label: Qté modifiée
        type: qty
        viewable: 0
        filterable: 0
        min: none
        max: none
        decimals: 3
        unsigned: 0
        default_value: 0
        
    # Tous les champs qty_xxx suivants sont uniquement à titre indicatifs 
    # et servent pour la liste "general" (Ne pas utiliser en PHP)   
    # Attention: les quantités sont en valeur absolues (toujours positifs, même pour les retours, sauf qty_total) . 
    
    qty_total: 
        label: Qté Totale
        type: qty
        default_value: 0
        displays: 
            badge: 
                type: callback
                method: displayQty
                params: 
                    - total
        
    qty_received: 
        label: Qté reçue
        type: qty
        default_value: 0
        displays: 
            badge: 
                type: callback
                method: displayQty
                params: 
                    - received
        
    qty_to_receive: 
        label: Qté à réceptionner
        type: qty
        default_value: 0
        displays: 
            badge: 
                type: callback
                method: displayQty
                params: 
                    - to_receive
        
    qty_billed: 
        label: Qté facturé
        type: qty
        default_value: 0
        displays: 
            badge: 
                type: callback
                method: displayQty
                params: 
                    - billed
        
    qty_to_billed: 
        label: Qté à facturé
        type: qty
        default_value: 0
        displays: 
            badge: 
                type: callback
                method: displayQty
                params: 
                    - to_billed
        
    qty_received_not_billed: 
        label: Qté recu à facturé
        type: qty
        default_value: 0
        displays: 
            badge: 
                type: callback
                method: displayQty
                params: 
                    - received_not_billed
        
forms: 
    qty_modified: 
        rows: 
            - custom: 1
              label: Quantité totale reçue
              input_name: qty_modified
              content: 
                  callback: renderQtyModifiedInput
        
views: 
    reception: 
        title: Réceptionner
        icon: fas_arrow-circle-down
        rows: 
            - cols: 
                - type: custom
                  custom: 
                      callback: renderReceptionForm
                     
filters_panels: 
    default: 
        filters: 
            parent:ref: 
                label: Ref. Commande
            parent:date_commande: 
                label: Date commande
            parent:fk_statut:
                label: Statut commande
            parent:invoice_status:
                label: Statut facturation commande
            parent:ref_supplier:
            qty_total: 
            qty_to_receive:
            qty_received:
            qty_billed:
            qty_to_billed:
            qty_received_not_billed:
                
lists_cols: 
    qties: 
        label: Quantités
        value: 
            callback: displayQties
    commande_client: 
        label: Commmande client
        value: 
            callback: displayCommandeClient
    qty_total: 
        display: badge
        min_width: 60
    qty_received: 
        display: badge
        min_width: 60p
    qty_to_receive: 
        label: Qté à récep.
        display: badge
        min_width: 60
    qty_billed: 
        label: Qté fact.
        display: badge
        min_width: 60
    qty_to_billed: 
        label: Qté à fact. 
        display: badge
        min_width: 60
    qty_received_not_billed:
        label: Qté recu à fact.
        display: badge
        min_width: 60
    desc_light_url: 
        extends: desc
        info: Version courte avec lien commande client d'origine
        value: 
            callback: 
                params:
                    - desc_light_url
                        
lists: 
    default:
        extends: default
        objects_change_reload: Bimp_CommandeFourn,ObjectLineRemise,BR_Reservation,BL_CommandeFournReception,BL_FactureFourn
                
    logistique:
        extends: default
        objects_change_reload: Bimp_CommandeFourn,ObjectLineRemise,BR_Reservation,BL_CommandeFournReception,BL_FactureFourn
        title: Logistique produits / services
        icon: fas_truck-loading
        configurable: 1
        item_checkbox: 1
        after_list_callback: unset
        header_buttons: unset
        bulk_actions: 
            callback: getLogistiqueBulkActions
        extra_btn: 
            callback: getLogistiqueExtraButtons
        cols: 
            unextends: 1
            desc_light:
            commande_client:
            total_ttc:
            qties:     
                
    global: 
        cols: 
            qty_total:
            qty_to_receive:
            qty_to_billed:   
                
    general:
        list_filters: 
            - name: type
              filter: 
                  in: 1,3
        configurable: 1
        filters_panel: default
        filters_panel_open: 1
        sort_field: id
        sort_way: desc
        n: 25
        extra_btn: 
            callback: getGeneralListExtraButtons
        cols: 
            parent:entrepot: 
                display: ref
            parent:fk_statut: 
                label: St Cmd
                display: icon
                min_width: 45
            parent:invoice_status:
                label: Fac. Cmd
                display: icon
                min_width: 45
            id_obj:
            desc_light:
            dol_line:subprice:
            qty_total:
            qty_to_receive:
            qty_to_billed:
