CREATE TABLE IF NOT EXISTS `tariff` (
    `id`                INTEGER AUTO_INCREMENT PRIMARY KEY,
    `label`             VARCHAR(255) NOT NULL,
    `date_creation`     DATETIME,
    `date_start`        DATETIME,
    `date_end`          DATETIME,
    `require_names`     BOOLEAN NOT NULL DEFAULT 0,
    `price`             FLOAT NOT NULL,
    `type_extra_1`      INTEGER,
    `type_extra_2`      INTEGER,
    `type_extra_3`      INTEGER,
    `type_extra_4`      INTEGER,
    `type_extra_5`      INTEGER,
    `type_extra_6`      INTEGER,
    `name_extra_1`      VARCHAR(255),
    `name_extra_2`      VARCHAR(255),
    `name_extra_3`      VARCHAR(255),
    `name_extra_4`      VARCHAR(255),
    `name_extra_5`      VARCHAR(255),
    `name_extra_6`      VARCHAR(255),
    `require_extra_1`   INTEGER,
    `require_extra_2`   INTEGER,
    `require_extra_3`   INTEGER,
    `require_extra_4`   INTEGER,
    `require_extra_5`   INTEGER,
    `require_extra_6`   INTEGER,
    `id_prod_extern`    INTEGER,
    `fk_event`          INTEGER NOT NULL,
    `number_place`      INTEGER DEFAULT 0,
    `date_stop_sale`    DATETIME,
    `email_text`        TEXT NOT NULL,
    FOREIGN KEY (`fk_event`) REFERENCES `event` (`id`)
) ENGINE=innodb;