# Entité: bimp => A transférer vers prolease

fields: 
    id_bimp_propale: 
        label: ID devis BIMP
        type: id
        default_value: 0
        
    id_bimp_client: 
        label: ID client BIMP
        type: id
        default_value: 0
        
    id_bimp_contact: 
        label: ID contact client BIMP
        type: id
        default_value: 0
        
    bimp_propale: 
        label: Infos devis BIMP
        type: json
        
    bimp_client: 
        label: Infos client BIMP
        type: json
        
    bimp_contact: 
        label: Infos contact client BIMP
        type: json
        
views: 
    demande: 
        rows: 
            3: 
                cols: 
                    - type: custom
                      show: 
                          field_value: id_bimp_client
                      col_lg: 6
                      col_md: 6
                      custom: 
                          callback: renderBimpClientData
                    - type: custom
                      show: 
                          field_value: id_bimp_propal
                      col_lg: 6
                      col_md: 6
                      custom: 
                          callback: renderBimpPropalData
                      
        
        
