extends: 
    module: bimpcore
    object_name: Bimp_Societe
    
controller: client

list_page_url: 
    controller: clients
    
icon: fas_user-circle

header_list_name: default
header_edit_form: default
header_delete_btn: 1
                    
fields: 
    client: 
        default_value: 1
    fournisseur:
        default_value: 0
                    
views: 
    client:
        extends: default
        objects_change_reload: BimpRelanceClientsLine
                      
forms:
    light: 
        title: Ajout d'un client
        rows: 
            client: 
                hidden: 1
                value: 1
            fournisseur: 
                hidden: 1
                value: 0
            mode_reglement_supplier: unset
            cond_reglement_supplier: unset
                  
    default: 
        rows: 
            client: 
                hidden: 0
            fournisseur: 
                hidden: 0
            mode_reglement_supplier: unset
            cond_reglement_supplier: unset
            code_compta_fournisseur: unset
            accounting_account_fournisseur: unset
            remise_supplier: unset
            
    merge: 
        rows: 
            soc_merge: 
                label: Client en doublon</br>(Le client à supprimer)
                input: 
                    type: search_object
                    object: client
            import_data: 
                label: Récupérer les données du client à supprimer<br/>(Pour celles non définies dans le client à conserver)
                
    relance_paiements: 
        modal_format: large
        title: Relancer les paiements clients
        rows: 
#            - custom: 1
#              label: Liste clients
#              input_name: id_objects
#              hidden: 1
#              input: 
#                  type: hidden
            - custom: 1
              input_name: send_emails
              label: Envoyer les emails pour les premières et deuxièmes relances
              input: 
                  type: toggle
              value: 1
            - custom: 1
              input_name: date_prevue
              label: Date prévue d'envoi des relances
              input: 
                  type: date
                  display_now: 1
                  help: Cette date pourra être modifiée individuellement pour chaque relance en attente
            - custom: 1
              label: Afficher
              hidden: 
                  callback: isLoaded
              input_name: display_mode
              input: 
                  type: select
                  options: 
                      callback: getRelancesDisplayModesArray
              value: 
                  callback: getDefaultRelancesDisplayMode
            - custom: 1
              label: Factures impayées à relancer
              input_name: id_objects
              content: 
                  callback: renderFacturesToRelancesInputs
              depends_on: id_objects,display_mode
            
    deactivate_relances: 
        title: Déactivation des relances
        rows: 
            - field: relances_infos
              required: 1
              
    attribute_commercial: 
        title: Attribution d'un commercial
        rows: 
            - custom: 1
              label: Commercial
              input_name: id_user_commercial
              input: 
                  type: search_user
      
filters_panels: 
    default: 
        filters: 
            code_fournisseur: unset
            code_compta_fournisseur: unset
            accounting_account_fournisseur: unset
    
lists:
    default: 
        title: Liste des Clients
        icon: fas_user-circle
        list_filters:
            - name: client
              filter: 1
        add_btn_label: Nouveau client
        header_buttons: 
            callback: getDefaultListExtraHeaderButtons
        modal_view: full
        bulk_actions:
            0: 
                label: supprimer les clients sélectionnés
        extra_bulk_actions: 
            callback: getListExtraBulkActions
        list_actions: 
            callback: getFilteredListActions
        cols: 
            code_fournisseur: unset
            
    clients_caisse: 
        extends: default
        extra_btn: 
            - label: Sélectionner ce client
              icon: arrow-circle-right
              onclick: selectClientFromList($(this))

searches: 
    default:
        fields_search: 
            3: a.code_client
        fields_return: 
            0: a.code_client
            1: a.nom
            2: a.name_alias
        filters: 
            a.client: 
                in: 
                    array: 
                        - 1
                        - 2
                        - 3
      
stats_lists_cols: 
    nb_client: 
        label: Nb Client
        type: count_distinct
        field: nom
#    tot_qty: 
#        label: Qté totale
#        type: sum
#        field: qty
#        data_type: float
#        decimals: 2
#    tot_brouillon: 
#        label: Tot. Fac. brouillons
#        type: sum
#        data_type: money
#        decimals: 2
#        with_styles: 1
#        field: total_ttc
#        filters: 
#            f.fk_statut: 0
#    tot_valide: 
#        label: Tot. Fac. validées
#        type: sum
#        field: total_ttc
#        data_type: money
#        decimals: 2
#        with_styles: 1
#        filters: 
#            f.fk_statut: 
#                in: 
#                    - 1
#                    - 2
#    tot_abandon: 
#        label: Tot. Fac. abandonnées
#        type: sum
#        field: total_ttc
#        data_type: money
#        decimals: 2
#        with_styles: 1
#        filters: 
#            f.fk_statut: 3
            
            
stats_lists: 
    default: 
        n: 10
        configurable: 1
#        joins: 
#            facture: 
#                table: facture
#                alias: f
#                on: f.rowid = a.fk_facture
        filters_panel: default
        group_by_options: 
            - secteuractivite
            - marche
        cols: 
            nb_client:
#            tot_qty: 
#            tot_brouillon:
#            tot_valide:
#            tot_abandon: