dol_object: 
    instance: 
        dol_object: user
        
table: user
primary: rowid
icon: fas_user

controller: user

header_btn: 
    callback: getActionsButtons
    
header_list_name: default
header_edit_form: card
header_delete_btn: 1

list_page_url: 
    controller: users
    params: 
        tab: default
    
name_syntaxe: <firstname> <lastname>
nom_url: 
    syntaxe: <name>
    card: default

labels: 
    name: utilisateur
    
objects: 
    user_group:
        instance:
            bimp_object:
                module: bimpcore
                name: Bimp_UserGroup
                
    resp_user:
        relation: hasOne
        delete: 0
        instance: 
            dol_object: user
            id_object: 
                field_value: fk_user
                
    def_entrepot: 
        extends: entrepot
        instance: 
            id_object: 
                field_value: defaultentrepot
                
    def_bimp_entrepot: 
        extends: bimp_entrepot
        instance: 
            id_object: 
                field_value: defaultentrepot
                
fields: 
    statut:
        label: Statut
        values: 
            array: status_list
        field: statut
    admin: 
        label: Administrateur
        type: bool
        default_value: 0 
    login: 
        label: Identifiant
        required: 1
    lastname: 
        label: Nom
        required: 1
    firstname:
        label: Prénom
    gender: 
        label: Genre
        values:
            array: genders
    email: 
        label: E-mail
    alias: 
        label: Alias mail
        dol_extra_field: 1
    job: 
        label: Poste / fonction
    employee: 
        label: Salarié
        type: bool
    dateemployment:
        label: Date d'embauche
        type: date
    address: 
        label: Adresse
        type: text
    zip: 
        label: Code postal
        input: 
            type: search_ziptown
            field_type: zip
            town_field: town
            country_field: fk_country
        search: 
            input: 
                type: text
            type: value_part
            part_type: beginning
    town: 
        label: Ville
        input: 
            type: search_ziptown
            field_type: town
            zip_field: zip
            country_field: fk_country
        search: 
            input: 
                type: text
            type: value_part
    fk_country: 
        label: Pays
        dol_prop: country_id
        type: int
        default_value: 1
        input: 
            type: search_country
        displays: 
            default: 
                type: callback
                method: displayCountry
    office_phone:
        label: Tél. pro
    user_mobile: 
        label: Tél. portable
    phone_perso: 
        label: Tél. portable perso
        dol_extra_field: 1
        type: password
    skype: 
        label: Identifiant Skype
    fk_user: 
        label: Responsable hiérarchique
        type: id_object
        object: resp_user
        input: 
            type: search_user
    synchaction:
        label: Synchro Agenda
        dol_extra_field: 1
        type: bool
    displayedinglobaladdressbook:
        label: Dans l'annuaire
        dol_extra_field: 1
        type: bool
    mailquota:
        label: Quota Mail
        dol_extra_field: 1
    signature: 
        label: Signature
        type: html
    note: 
        label: Note
        type: text
    apple_id: 
        label: Identifiant Apple
        dol_extra_field: 1
    apple_service: 
        label: Service Apple
        dol_extra_field: 1
    apple_techid: 
        label: Tech ID Apple
        dol_extra_field: 1
    gsxresa:
        label: Notification réservations GSX
        dol_extra_field: 1
        type: bool
    apple_shipto: 
        label: N° ShipTo Apple
        dol_extra_field: 1
    id8sens: 
        label: ID Comm 8Sens
        dol_extra_field: 1
    idtech8sens: 
        label: ID Tech 8Sens
        dol_extra_field: 1
    mail_sec: 
        label: E-Mail de secours
        dol_extra_field: 1
        type: password
    code_sms: 
        label: Code SMS
        dol_extra_field: 1
        type: text
    echec_auth: 
        label: Nombre d'echecs d'authentification consecutifs
        dol_extra_field: 1
        type: int
    comp:
        label: Compétence
        dol_extra_field: 1
        type: text
    defaultentrepot: 
        label: Entrepot par default
        dol_extra_field: 1
        type: id_object
        object: def_bimp_entrepot
        input: 
            type: search_entrepot
    apple_centre: 
        label: Centre SAV
        dol_extra_field: 1
    object_header_locked: 
        label: Vérouiller les en-têtes
        type: bool
        default_value: 0
    secteur: 
        label: Secteur
        dol_extra_field: 1
        values: 
            array: secteurs
    is_dev: 
        label: Développeur
        type: bool
        default_value: 0
        
    id_docusign: 
        label: Identifiant DocuSign
        
forms:
    light: 
        rows:
            - field: lastname
            - field: firstname
            - field: office_phone
            - field: user_mobile
            - field: phone_perso
            - field: mail_sec
            - field: alias
            - field: synchaction
            - field: apple_id
            - field: apple_service
            - field: apple_shipto
            - field: apple_techid
            - field: gsxresa
            - field: id8sens
            - field: idtech8sens
            - field: comp
            - field: signature
            - field: defaultentrepot
            - field: apple_centre
            - field: secteur
            - field: echec_auth
            
    export_conges: 
        title: Générer fichier d'export des conges
        rows: 
            - custom: 1
              label: Du
              input_name: date_from
              input: 
                  type: date
            - custom: 1
              label: Au
              input_name: date_to
              input: 
                  type: date
            - custom: 1
              label: Types de conges
              input_name: types_conges
              input: 
                  type: check_list
                  items: 
                      0: Congés payés
                      1: Absence exceptionnelle
                      2: RTT
            - custom: 1
              label: Valide
              input_name: types_valide
              input: 
                  type: check_list
                  items: 
                      0: Valide
                      1: Non valide
                      
    interface_params: 
        title: Paramètres interface
        rows: 
            - custom: 1
              label: Thème
              input_name: MAIN_THEME
              input: 
                  type: select
                  options: 
                      eldy: Thème classique (Eldy)
                      BimpTheme: Thème BIMP
              value: 
                  callback: 
                      method: getUserParamValue
                      params: 
                          - MAIN_THEME
                          - eldy
              
fields_tables: 
    identity:
        title: Identité
        icon: id-card
        rows: 
            - field: firstname
            - field: lastname
            - field: login
            - field: gender
    security:
        title: Securité
        icon: lock
        rows: 
            - field: code_sms
            - field: echec_auth
            
    address:
        title: Adresse
        icon: map-marker
        rows: 
            - field: address
            - field: zip
            - field: town
            - field: fk_country
            
    contact: 
        title: Informations de contact
        icon: phone
        rows: 
            - field: email
            - field: alias
            - field: office_phone
            - field: user_mobile
            - field: phone_perso
            - field: mail_sec
            - field: skype
            - field: synchaction
            - field: displayedinglobaladdressbook
            - field: mailquota
        
    status: 
        title: Statut
        icon: user
        rows: 
            - field: job
            - field: employee
            - field: dateemployment
            - field: fk_user
              display: nom_url
            - field: comp
            - field: defaultentrepot
            - field: apple_centre
            - field: secteur
        
    notes: 
        title: Notes
        icon: fas_file-alt
        rows: 
            - field: note
            - field: signature
            
    apple: 
        title: Données Apple
        icon: apple
        rows: 
            - field: apple_id
            - field: apple_service
            - field: apple_techid
            - field: apple_shipto
            - field: gsxresa
            
    8sens: 
        title: Données 8sens
        icon: file-tex
        rows: 
            - field: id8sens
            - field: idtech8sens
        
views: 
    default: 
        edit_form: 
            callback: getEditFormName
        rows: 
            - cols: 
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: contact
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: identity
                      
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: security       
                      
            - cols: 
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: address
                      
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: status
                      
            - cols: 
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: notes
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: apple
                      
    validations_redir: 
        rows: 
            - cols: 
                type: custom
                custom: 
                    callback: renderValidationsRedirForm
                    
filters_panel: 
    default: 
        filters: 
            firstname: 
            lastname: 
            login: 
            group:
                
filters: 
    group: 
        label: Groupe
        data_type: id_object
        object: user_group
        type: value
        input: 
            type: search_group
            include_empty: 1
            empty_label: Aucun        
        
lists:
    bygroup:
        extends: default
        filters_panel: unset
        add_form_name: unset
        header_buttons: unset
        edit_btn: unset
        edit_form: unset
        delete_btn: unset
        list_filters: 
            callback:
                method: getFilterByGroup
                
    bygroupperms:
        extends: default
        filters_panel: unset
        add_form_name: unset
        header_buttons: unset
        edit_btn: unset
        edit_form: unset
        delete_btn: unset
        list_filters: 
            callback:
                method: getGroupsRights
                
    default: 
        checkboxes: 1
        configurable: 1
        filters_panel: default
        bulk_actions:
            - label: supprimer les utilisateurs sélectionnés
              icon: fas_trash-alt
              onclick: deleteSelectedObjects('list_id', $(this))
        sort_field: id
        sort_way: desc
        n: 10
        add_form_name: default
        delete_btn: 1
        page_btn: 1
        modal_view: default
        edit_btn: 1
        edit_form: 
            callback: getEditFormName
        header_buttons: 
            callback: getDefaultListHeaderButton
        cols:
            gender:
            firstname:
            lastname: 
            login: 
            job:
            email: 
            office_phone:
                   
views_lists: 
    default: 
        title: Utilisateurs
        component_type: card
        component_name: default
        view_btn: 0
        add_btn: 0
        edit_form: default
        item_col_lg: 6
        item_col_md: 6
        item_modal_view: default
        
cards:
    default: 
        title: nom
        status: statut
        fields: 
            - field: login
            - field: job
              label: Poste
            - label: Adresse
              value: 
                  callback: 
                      method: displayFullAddress
                      params: 
                          - 1
            - label: Contact
              value: 
                  callback: 
                      method: displayFullContactInfos
                      params: 
                          - 1
        
    public: 
        check_view_right: 0
        fields: 
            - field: office_phone
              icon: fas_phone
            - label: E-mail
              icon: fas_at
              value: 
                  callback: displayPublicEmail
        
searches: 
    default: 
        fields_search: 
            - a.rowid
            - a.login
            - a.firstname
            - a.lastname
            - a.email
        fields_return: 
            - a.firstname
            - a.lastname
        label_syntaxe: '<a.firstname> <a.lastname>'