table: bimpcore_hashtag
controller: hashtag
common_fields: 0
icon: fas_hashtag

list_page_url: 
    controller: admin
    url_params: 
        tab: hashtags
            
header_list_name: default
header_edit_form: default

labels: 
    name: hashtag
    
nom_url: 
    syntaxe: <code>
    card: default
    
fields: 
    code: 
        label: Mot-clé
        required: 1
        
    label: 
        label: Libellé
        
    description: 
        label: Description
        type: text
        hashtags: 1
        input: 
            auto_expand: 1
            rows: 3
            
fields_tables: 
    desc: 
        panel_header: 0
        rows: 
            - field: description
              edit: 1
    
views: 
    default: 
        rows: 
            - cols: 
                - type: object_header
            - cols: 
                - type: fields_table
                  fields_table: 
                      name: desc
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
            - cols: 
                - type: custom
                  col_lg: 12
                  custom: 
                      callback: renderLinkedObjectsLists
            - cols:
                - type: custom
                  custom: 
                      callback: 
                          method: renderNotesList
                          params:
                              - 1
lists: 
    default: 
        title: Liste des Hashtags
        checkboxes: 1
        bulk_actions:
            - label: supprimer les hashtags sélectionnés
              icon: fas_trash-alt
              onclick: deleteSelectedObjects('list_id', $(this))
        sort_field: id
        sort_way: desc
        n: 10
        add_form_name: default
        edit_btn: 1
        edit_form: default
        delete_btn: 1
        page_btn: 1
        modal_view: default
        cols: 
            code:
                edit: 1
            label: 
                edit: 1
            description: 
                edit: 1
        
cards: 
    default:
        title: 
            field_value: code
        fields: 
            - field: label
            - field: description
    
searches: 
    default: 
        fields_search: 
            - a.code
            - a.label
        fields_return: 
            - a.code
            - a.label
        label_syntaxe: '<a.code> - <a.label>'