table: bimpcore_cgv

labels:
    name: CGV
    name_plur: CGV
    
objects:
    centre:
        instance:
            bimp_object:
                module: bimpsupport
                name: BS_CentreSav
                id_object:
                    field_value: id_centre
    
fields:
    types_pieces :
        label: Types de pièce
        required: 1
        values:
            facture: Facture
            devis: Devis
            commande: Commande
            bl: Bon de livraison
            contrat: Contrat
            contrat_loc: Contrat de location
        type: items_list
        items_braces: 1
        items_add_all_btn: 1
    secteurs :
        label: Secteurs
        required: 1
        values:
            callback:
                method: getSecteursArray
                params:
                    - 1
                    - ""
                    - Tous les secteurs
        type: items_list
        items_braces: 1
        items_add_all_btn: 1
    id_centre :
        label: Centre
        type: id_object
        object: centre
#        required: 1
        default_value: 0
        input:
            help: A renseigner uniquement pour le secteur SAV
    date_start :
        label: Date de mise en application
        type: date
        required: 1
    nb_pages :
        label: Nombre de pages
        type: qty
        decimals: 0
        min: 1
#        default_value: 1
        required: 1
    signature_y_pos :
        label: Position en Y du bloc signature
        type: qty
        decimals: 0
        min: 0
        default_value: 0
        input:
            help: Laisser à 0 pour ne pas afficher le bloc signature
        required: 1
    
lists_cols:
    pdf:
        label: PDF
        value:
            callback: dispayPdfButton
            
lists:
    default:
        title: Liste des CGV
        configurable: 1
        checkboxes: 1
        filters_panel: default
        bulk_actions:
            -   label: Supprimer les lignes sélectionnées
                icon: fas_trash-alt
                onclick: deleteSelectedObjects('list_id', $(this))
        sort_field: date_create
        sort_way: desc
        n: 0
        add_form_name: default
        add_btn_label: Nouvelle CGV par pièce
        edit_btn: 1
        edit_form: edit
        extra_btn:
            callback: getListExtraButtons
        modal_view: default
        cols:
            types_pieces:
            secteurs:
            id_centre:
            date_start:
            pdf:
            nb_pages:
            signature_y_pos:
            
    
    cgvCentre:
        extends: default
        cols:
            id_centre: unset
            
forms:
    default:
        rows:
            - field: types_pieces
            - field: secteurs
            - field: id_centre
            - field: date_start
            - custom: 1
              label: Fichier
              input_name: file
              required: 1
              input:
                  type: drop_files
                  allowed_ext: pdf
                  help: Fichier PDF de la CGV
                  max_items: 1
            - field: nb_pages
            - field: signature_y_pos
    
    modifyPdfForm:
        rows:
            -   custom: 1
                label: Fichier
                input_name: file
                required: 1
                input:
                    type: drop_files
                    allowed_ext: pdf
                    help: Fichier PDF de la CGV
                    max_items: 1
            -   field: nb_pages
            -   field: signature_y_pos


     
views:
    default:
        title:
            callback: getName
        #            callback: getCode
        
        objects_change_reload: BimpCGV
        rows:
            - cols:
                  - type: object_header
            - cols:
                  - type: fields_table
                    col_lg: 12
                    col_mg: 12
                    fields_table:
                        name: infoscgv
filters_panels:
    default:
        filters:
            types_pieces:
            secteurs:
            id_centre:
            date_start:

fields_tables:
    infoscgv:
        title: Informations CGV
        icon: info-circle
        rows:
            types_pieces:
                field: types_pieces
            secteurs:
                field: secteurs
            id_centre:
                field: id_centre
            date_start:
                field: date_start
