abstract: 1
table: bimpcore_report
common_fields: 0
controller: report
icon: fas_file-alt
    

list_page_url: 
    controller: reports
            
header_list_name: default

labels: 
    name: rapport
    
objects: 
    lines: 
        relation: hasMany
        delete: 1
        instance:
            bimp_object: BimpReportLine
            
fields: 
    title: 
        label: Titre
    type: 
        label: Type
        values: 
            array: types
        required: 1
    begin: 
        label: Début
        type: datetime
        displays: 
            default: 
                type: datetime
                show_hour: 1
    end: 
        label: Fin
        type: datetime
        displays: 
            default: 
                type: datetime
                show_hour: 1
    nb_successes: 
        label: Nb succès
        type: int
        default_value: 0
        unsigned: 1
        displays: 
            badge:
                type: callback
                method: displayBadgeNumber
                params: 
                    - nb_successes
    nb_errors: 
        label: Nb erreurs
        type: int
        default_value: 0
        unsigned: 1
        displays: 
            badge:
                type: callback
                method: displayBadgeNumber
                params: 
                    - nb_errors
    nb_warnings: 
        label: Nb alertes
        type: int
        default_value: 0
        unsigned: 1
        displays: 
            badge:
                type: callback
                method: displayBadgeNumber
                params: 
                    - nb_warnings
    nb_infos: 
        label: Nb Infos
        type: int
        default_value: 0
        unsigned: 1
        displays: 
            badge:
                type: callback
                method: displayBadgeNumber
                params: 
                    - nb_infos
        
views: 
    full: 
        rows: 
            - cols: 
                - type: object_header
            - cols: 
                - type: fields_table
                  col_md: 6
                  col_lg: 6
                  field_table: default
            - cols: 
                - type: list
                  list: 
                      name: report
                      children: objects_data
            - cols: 
                - type: list
                  list: 
                      name: report
                      children: lines
                      
    default: 
        extends: full
        rows: 
            0: unset
        
lists_cols: 
    nb_successes: 
        display: badge
        min_width: 30
    nb_errors: 
        display: badge
        min_width: 30
    nb_warnings: 
        display: badge
        min_width: 30
    nb_infos: 
        display: badge
        min_width: 30
        
filters_panels: 
    default: 
        filters: 
            type: 
            begin: 
            end: 
            nb_successes: 
            nb_errors: 
            nb_warnings:
            nb_infos:
        
lists: 
    default: 
        title: Rapports
        checkboxes: 1
        bulk_actions:
            - label: supprimer les rapports sélectionnés
              icon: fas_trash-alt
              onclick: deleteSelectedObjects('list_id', $(this))
        filters_panel: default
        sort_field: id
        sort_way: desc
        n: 10
        delete_btn: 1
        modal_view: full
        page_btn: 1
            
            