table: product_fournisseur_price
common_fields: 0
primary: rowid
icon: fas_euro-sign

parent_module: bimpcore
parent_object: Bimp_Product
parent_id_property: fk_product

nom_url: 
    syntaxe: <name>
    
labels: 
    name: prix d'achat fournisseur
    name_plur: prix d'achat fournisseur
    
objects: 
    product: 
        instance: 
            id_object: 
                field_value: fk_product
    fournisseur: 
        instance: 
            id_object: 
                field_value: fk_soc
                
fields: 
    fk_product: 
        label: Produit
        type: id_parent
        object: product
        input: 
            type: hidden
        required: 1
            
    fk_soc: 
        label: Fournisseur
        type: id_object
        object: fournisseur
        required: 1
        
    ref_fourn:
        label: Référence produit fournisseur
        required: 1
    
    quantity:
        label: Quantité minimum
        type: int
        default_value: 1
        input: 
            type: hidden
        
    price: 
        label: Prix HT (sans remise)
        type: money
        required: 1
        decimals: 4
        history: 1
        
    tva_tx: 
        label: Taux de TVA
        type: percent
        default_value: 
            callback: 
                method: cacheServeurFunction
                params:
                    - getDefaultTva
        decimals: 4
        min: 0
        max: 100
        unsigned: 1
    
    remise_percent: 
        label: Remise par défaut qté min.
        type: percent
        decimals: 6
        min: 0
        max: 100
        default_value: 0
        input: 
            type: hidden
        
    unitprice: 
        label: Prix unitaire HT
        type: money
        default_value: 0
        input: 
            type: hidden
            
    datec: 
        label: Créé le
        type: detetime
        
    stockFourn:
        label: Stock chez le fournisseur
        type: float
    
forms: 
    default: 
        rows: 
            prod: 
                field: fk_product
            soc: 
                field: fk_soc
            ref_fourn: 
                field: ref_fourn
            price: 
                field: price
            tva: 
                field: tva_tx
            is_cur_pa: 
                custom: 1
                label: Définir comme prix d'achat actuel du produit
                input_name: is_cur_pa
                data_type: bool
                input: 
                    type: toggle
                value: 1
            update_comm_fourn: 
                custom: 1
                label: Mettre à jour les prix d'achats des commandes fournisseurs pour les unités non réceptionnées
                input_name: update_comm_fourn
                data_type: bool
                input: 
                    type: toggle
                value: 0
                display_if: 
                    field_name: is_cur_pa
                    show_values: 1
                  
    create_prod:
        extends: default
        rows:
            prod: unset
            update_comm_fourn: unset
              
fields_table: 
    default: 
        panel: 0
        rows: 
            - field: fk_product
              display: nom_url
            - field: ref_fourn
            - field: fk_soc
              display: nom_url
            - field: price
            - field: tva_tx
            - field: stockFourn
            
views: 
    default: 
        modal_format: small
        rows: 
            - cols: 
                - type: fields_table
                  fields_table: 
                      name: default
        
lists: 
    default: 
        filters_panel: default
        configurable: 1
        title: Liste des prix d'achat fournisseur
        sort_field: id
        sort_way: desc
        n: 50
        page_btn: 1
        edit_btn: 1
        delete_btn: 1
        edit_form: default
        add_form_name: default
        cols: 
            fk_soc:
            ref_fourn:
            quantity:
            tva_tx:
            price:
            remise_percent:
            stockFourn:
            
    fourn:
        extends: default
        cols:
            fk_soc: unset
            
cards: 
    default: 
        fields: 
            - field: fk_product
              display: nom_url
            - field: fk_soc
              display: nom_url
            - field: price
            - field: tva_tx
            
            
filters_panels:
    default: 
        filters: 
            fk_soc:
            ref_fourn:
            quantity:
            tva_tx:
            price:
            remise_percent:
            stockFourn:
