table: bimpcore_signature
controller: signature
icon: fas_signature
public_icon: pe_pen
common_fields: 0

list_page_url: 
    controller: signatures
    
nom_url: 
    syntaxe: <name>
    
header_list_name: default
header_btn: 
    callback: getActionsButtons
    
labels:
    name: signature
    is_female: 1
    
objects: 
    user_client: 
        relation: hasOne
        delete: 0
        instance: 
            bimp_object: 
                module: bimpinterfaceclient
                name: BIC_UserClient
            id_object: 
                field_value: id_user_client_signataire
                
    users_client: 
        relation: none
        instance: 
            bimp_object: 
                module: bimpinterfaceclient
                name: BIC_UserClient
                
fields:     
    obj_module: 
        label: Module
        required: 1

    obj_name: 
        label: Nom objet
        required: 1
        
    id_obj: 
        label: id_objet
        type: id
        required: 1

    doc_type: 
        label: Type de document
        displays: 
            name:
                label: Nom document
                type: callback
                method: displayDocType
        
    doc_name: 
        label: Fichier document
        
    type: 
        label: Type signature
        type: int
        values: 
            array: types
        input: 
            type: select
            options: 
                callback: getTypeInputOptions
        default_value: 0                
        
    signed: 
        label: Signé
        type: bool
        default_value: 0
        
    date_signed: 
        label: Date signature
        type: datetime

    id_client: 
        label: Client
        type: id_object
        object: client
        required: 1
        
    id_contact: 
        label: Contact
        type: id_object
        object: contact
        default_value: 0
        
    id_user_client_signataire:
        label: Compte utilisateur signataire
        type: id_object
        object: user_client
        default_value: 0
        
    allowed_users_client: 
        label: Comptes utilisateurs du client autorisés pour cette signature
        type: items_list
        items_data_type: id_object
        items_braces: 1
        object: users_client
        input: 
            type: check_list
            select_all_buttons: 1
            search_input: 1
            items: 
                callback: getClientUsersArray
        create_form: default
        create_form_values: 
            fields: 
                id_client: 
                    field_value: id_client
                id_contact: 
                    field_value: id_contact
                status: 1
                role: 0
        
    nom_signataire: 
        label: Nom signataire
        
    email_signataire:
        label: E-mail signataire
        
    ip_signataire: 
        label: Adresse IP signataire
        
    base_64_signature:
        label: Image signature
    
    public_url:
        label: Numéro encodé
        
    public_access_code:
        label: Code d'accès à distance
        
    public_access_date_from:
        label: Date d'ouverture de l'accès
        type: datetime
        
    public_access_date_to:
        label: Date de fermeture de l'accès
        type: datetime
        
forms:
    open_sign_dist:
        title: Signature à distance
        icon: fas_sign-in
        values: 
            fields: 
                allowed_users_client: 
                    callback: getDefaultAllowedUsersClient
        rows: 
            - custom: 1
              label: Ouvrir automatiquement l'accès public
              show: 
                  callback: showAutoOpenPublicAccess
              input_name: auto_open
              value: 1
              input: 
                  type: toggle
                  help: 
                      callback: getAutoOpenPublicAccessInputHelp
                      
            - custom: 1
              label: Adresse e-mail du compte utilisateur à créer
              input_name: new_user_email
              input: 
                  type: text
              show: 
                  callback: showOpenPublicAccessNewUserEmailInput
              value: 
                  callback: getOpenPublicAccessNewUserDefaultEmail
              display_if: 
                  field_name: auto_open
                  show_values: 1
                  
            - field: allowed_users_client
              display_if: 
                  field_name: auto_open
                  hide_values: 1
            
    sign_papier: 
        title: Dépôt document signé
        icon: fas_file-download
        values: 
            fields: 
                nom_signataire: 
                    callback: getDefaultNomSignataire
        rows: 
            - field: nom_signataire
              required: 1
            - custom: 1
              label: Fichier
              input_name: file_signed
              input: 
                  type: file_upload
              required: 1
            
    sign_elec: 
        title: Signature électronique
        icon: fas_file-signature
        values: 
            fields: 
                nom_signataire: 
                    callback: getDefaultNomSignataire
                email_signataire: 
                    callback: getDefaultEmailSignataire
        rows: 
            - field: nom_signataire
            - field: email_signataire
            - custom: 1
              label: Signature
              input_name: signature
              input: 
                  type: signature_pad
            
    sign_dist: 
        title: Signature à distance
        icon: fas_file-signature
        values: 
            fields: 
                nom_signataire: 
                    callback: getDefaultNomSignataire
        rows: 
            - field: nom_signataire
            - custom: 1
              label: Signature
              input_name: signature
              input: 
                  type: signature_pad
            
fields_tables: 
    infos: 
        icon: fas_info-circle
        title: Informations
        rows:
            - label: Objet
              value: 
                  callback: displayObj
            - field: doc_type
              display: name
            - field: doc_name
            - field: id_client
            - field: id_contact
            - field: signed
            
    signature:
        icon: signature
        title: Infos signature
        show: 
            field_value: signed
        rows: 
            - field: date_signed
            - field: type
            - field: id_user_client_signataire
              show: 
                  field_value: id_user_client_signataire
            - field: nom_signataire
            - field: email_signataire
            - field: ip_signataire
            
            
    public_access:
        icon: fas_sign-in-alt
        title: Accès espace client
        rows: 
            - field: allowed_users_client
#            - field: public_url
#            - field: public_access_code
#            - field: public_access_date_from
#            - field: public_access_date_to
            
views:
    default: 
        rows: 
            - cols: 
                - type: object_header
            - cols: 
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: infos
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: public_access
            - cols: 
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: signature
            - cols: 
                - type: custom
                  custom: 
                      callback: renderNotesList
              
lists_cols: 
    obj: 
        label: Objet
        value: 
            callback: displayObj
            
    doc_type: 
        display: name
        
    public_sign: 
        label: Signer
        value: 
            callback: dispayPublicSign
        
    public_document: 
        label: Document
        value: 
            callback: displayPublicDocument
        
lists: 
    default: 
        configurable: 1
        checkboxes: 1
        bulk_actions:
            - label: supprimer les signatures sélectionnées
              icon: fas_trash-alt
              onclick: deleteSelectedObjects('list_id', $(this))
        sort_field: id
        sort_way: desc
        n: 10
        add_form_name: default
#        edit_btn: 1
#        edit_form: edit
        delete_btn: 1
        page_btn: 1
        modal_view: default
        extra_btn: 
            callback: getListExtraBtn
        cols: 
            obj: 
            doc_type: 
            signed: 
            type: 
            date_signed: 
            nom_signataire: 
            email_signataire:
            
    public_client: 
        title: Liste de vos signatures
        configurable: 0
        checkboxes: 0
        cols: 
            obj: 
                label: Elément lié
            doc_type: 
            type:
            date_signed: 
            nom_signataire: 
            public_document: 
            public_sign: 
            
            
        