table: bimp_c_values8sens
common_fields: 0

fields:
    label:
        label: Label
    type:
        label: Type
        values: 
            array: 
                categorie: Categorie
                famille: Famille
                nature: Nature
                collection: Collection
                gamme: Gamme
                
forms:
    deleteFus:
        rows:
            - label: Tags pour remplacements
              custom: 1
              input_name: replace
              input: 
                  type: select
                  options: 
                      callback: 
                          method: getReplaceTags
            
lists: 
    default: 
        configurable: 1
        sort_field: id
        sort_way: desc
        n: 10
        add_form_name: default
        add_object_row: 1
#        modal_view: default
        edit_btn: 1
        edit_form: default
        extra_btn: 
            callback: getListExtraBtn
#        delete_btn: 1
        cols:
            label:
            type: