dol_object: 
    instance: 
        dol_object: 
            module: product/stock
            file: entrepot

table: entrepot
primary: rowid
icon: fas_warehouse

header_edit_form: default
header_btn:
    callback: getActionsButtons

controller: entrepot

nom_url:
    syntaxe: <ref>
    card: default

labels:
    name: entrepôt

fields:
    ref:
        label: Référence
        dol_prop: label
        required: 1
    
    lieu:
        label: Nom
    
    description:
        label: Description
        hashtags: 1
    
    address:
        label: Adresse
    
    zip:
        label: Code postal
    
    town:
        label: Ville
    
    statut:
        label: Statut
        type: int
        values:
            array: status_list
        default_value: 1

fields_tables:
    infos:
        title: Infos
        icon: fas_info
        rows:
            ref:
                field: ref
            lieu:
                field: lieu
            desc:
                field: description
            address:
                label: Adresse
                value:
                    callback: displayFullAdress

views:
    default:
        edit_btn: 1
        rows:
            -   cols:
                    -   type: fields_table
                        col_lg: 12
                        col_md: 12
                        fields_table:
                            name: infos
    complet:
        edit_btn: 1
        rows:
            -   cols:
                    -   type: fields_table
                        col_lg: 6
                        col_md: 6
                        fields_table:
                            name: infos
            -   cols:
                    -   type: custom
                        custom:
                            callback: renderStocksView

filters_panels:
    default:
        filters:
            ref:
            lieu:
            zip:
            town:
            statut:

lists_cols:
    full_address:
        label: Adresse complète
        value:
            callback: displayFullAdress
    mail:
        label: Mail
        value:
            callback: getMail
    valStock:
        label: Valorisation achat HT
        value:
            callback: getValStock

lists:
    default:
        configurable: 1
        filters_panel: default
        sort_field: rowid
        sort_way: desc
        n: 10
        add_form_name: default
        modal_view: default
        page_btn: 1
        edit_btn: 1
        edit_form: default
        delete_btn: 1
        cols:
            ref:
            lieu:
            description:
            address:
            zip:
            town:
            statut:
            valStock:

searches:
    default:
        fields_search:
            - a.ref
            - a.lieu
            - a.town
        fields_return:
            - a.ref
            - a.lieu
            - a.town
        label_syntaxe: '<a.ref> - <a.lieu> (<a.town>)'

cards:
    default:
        title: nom
        fields:
            ref:
                field: ref
                label: Ref.
            address:
                label: Adresse
                value:
                    callback: displayFullAdress
        view_btn: 1

list_page_url:
    controller: admin
#    url_params:
#        tab: admin


forms:
    CorrectionStock:
        title: Correction manuel du stock
        rows:
            -   custom: 1
                label: Sens
                input_name: sens
                input:
                    type: select
                    options:
                        0: Entrant (ajout)
                        1: Sortant (retrait)
            -   custom: 1
                label: Quantité
                input_name: qty
                data_type: float
                min: 0
                decimals: 6
                input:
                    type: qty
            
            -   custom: 1
                input_name: id_product
                label: Produit
                type: id_product
                object: product
                input:
                    type: search_product
            
            -   custom: 1
                input_name: comment
                label: Infos
                input:
                    type: text
        buttons:
            -   type: submit
                label: Enregistrer
                class: btn-primary
            -   type: reset
                label: Annuler
                class: btn-secondary
        action: save
        method: POST

header_list_name: default
