dol_object: 
    instance: 
        dol_object: user
        
table: user
primary: rowid

labels: 
    name: utilisateur
    
objects: 
    resp_user:
        relation: hasOne
        delete: 0
        instance: 
            dol_object: user
            id_object: 
                field_value: fk_user
                
fields: 
    admin: 
        label: Administrateur
        type: bool
        default_value: 0 
    login: 
        label: Identifiant
        required: 1
    lastname: 
        label: Nom
        required: 1
    firstname:
        label: Prénom
        required: 1
    gender: 
        label: Genre
        values:
            array: genders
    email: 
        label: E-mail
    job: 
        label: Poste / fonction
    employee: 
        label: Salarié
        type: bool
    dateemployment:
        label: Date d'embauche
        type: date
    address: 
        label: Adresse
        type: text
    zip: 
        label: Code postal
        input: 
            type: search_ziptown
            field_type: zip
            town_field: town
            country_field: fk_country
        search: 
            input: 
                type: text
            type: value_part
            part_type: beginning
    town: 
        label: Ville
        input: 
            type: search_ziptown
            field_type: town
            zip_field: zip
            country_field: fk_country
        search: 
            input: 
                type: text
            type: value_part
    fk_country: 
        label: Pays
        dol_prop: country_id
        type: int
        default_value: 1
        input: 
            type: search_country
        display: 
            default: 
                type: callback
                method: displayCountry
    office_phone:
        label: Tél. pro
    user_mobile: 
        label: Tél. portable
    skype: 
        label: Identifiant Skype
    fk_user: 
        label: Responsable hiérarchique
        type: id_object
        object: resp_user
        input: 
            type: search_user
    synchaction:
        label: Synchro Agenda
        dol_extra_field: 1
        type: bool
    displayedinglobaladdressbook:
        label: Dans l'annuaire
        dol_extra_field: 1
        type: bool
    mailquota:
        label: Quota Mail
        dol_extra_field: 1
    signature: 
        label: Signature
        type: html
    note: 
        label: Note
        type: text
    apple_id: 
        label: Identifiant Apple
        dol_extra_field: 1
    apple_service: 
        label: Service Apple
        dol_extra_field: 1
    apple_techid: 
        label: Tech ID Apple
        dol_extra_field: 1
    gsxresa:
        label: Notification réservations GSX
        dol_extra_field: 1
        type: bool
    apple_shipto: 
        label: N° ShipTo Apple
        dol_extra_field: 1
    id8sens: 
        label: ID Comm 8Sens
        dol_extra_field: 1
    idtech8sens: 
        label: ID Tech 8Sens
        dol_extra_field: 1
    mail_sec: 
        label: E-Mail de secours
        dol_extra_field: 1
    comp:
        label: Compétence
        dol_extra_field: 1
        type: text
    defaultentrepot: 
        label: Entrepot par default
        dol_extra_field: 1
    apple_centre: 
        label: Centre SAV
        dol_extra_field: 1
        
forms:
    light: 
        rows:
            - field: lastname
            - field: firstname
            - field: office_phone
            - field: user_mobile
            - field: mail_sec
            - field: apple_id
            - field: apple_service
            - field: apple_shipto
            - field: apple_techid
            - field: gsxresa
            - field: id8sens
            - field: idtech8sens
            - field: comp
            - field: signature
            - field: defaultentrepot
            - field: apple_centre
            
lists:
    default: 
        checkboxes: 1
        bulk_actions:
            - label: supprimer les utilisateurs sélectionnés
              icon: fas_trash-alt
              onclick: deleteSelectedObjects('list_id', $(this))
        sort_field: id
        sort_way: desc
        n: 50
        add_form_name: default
        delete_btn: 1
        page_btn: 1
        modal_view: default
        edit_btn: 1
        cols:
            gender:
                field: gender
            firstname:
                field: firstname
            lastname: 
                field: lastname
            login: 
                field: login
            job:
                field: job
            email: 
                field: email
            office_phone: 
                field: office_phone
                
fields_tables: 
    identity:
        title: Identité
        icon: id-card
        rows: 
            - field: firstname
            - field: lastname
            - field: login
            - field: gender
            
    address:
        title: Adresse
        icon: map-marker
        rows: 
            - field: address
            - field: zip
            - field: town
            - field: fk_country
            
    contact: 
        title: Informations de contact
        icon: phone
        rows: 
            - field: email
            - field: office_phone
            - field: user_mobile
            - field: skype
            - field: mail_sec
            - field: synchaction
            - field: displayedinglobaladdressbook
            - field: mailquota
        
    status: 
        title: Statut
        icon: user
        rows: 
            - field: job
            - field: employee
            - field: dateemployment
            - field: fk_user
              display: nom_url
            - field: comp
            - field: defaultentrepot
            - field: apple_centre
        
    notes: 
        title: Notes
        icon: fas_file-alt
        rows: 
            - field: note
            - field: signature
            
    apple: 
        title: Données Apple
        icon: apple
        rows: 
            - field: apple_id
            - field: apple_service
            - field: apple_techid
            - field: apple_shipto
            - field: gsxresa
            
    apple: 
        title: Données 8sens
        icon: file-tex
        rows: 
            - field: id8sens
            - field: idtech8sens
        
views: 
    default: 
        rows: 
            - cols: 
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: identity
                      
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: contact
                      
            - cols: 
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: address
                      
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: status
                      
            - cols: 
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: notes
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: apple
        
cards:
    default: 
        type: user_card
        
