extends: 
    module: bimpcore
    object_name: Bimp_Societe
    
controller: client

list_page_url: 
    controller: clients
    
icon: fas_user-circle

header_list_name: default
header_edit_form: default
header_delete_btn: 1
                    
fields: 
    client: 
        default_value: 1
    fournisseur:
        default_value: 0
                    
views: 
    client:
        extends: default
        objects_change_reload: BimpRelanceClientsLine
                      
forms:
    light: 
        title: Ajout d'un client
        rows: 
            client: 
                hidden: 1
                value: 1
            fournisseur: 
                hidden: 1
                value: 0
            mode_reglement_supplier: unset
            cond_reglement_supplier: unset
                  
    default: 
        rows: 
            client: 
                hidden: 0
            fournisseur: 
                hidden: 0
            mode_reglement_supplier: unset
            cond_reglement_supplier: unset
            code_compta_fournisseur: unset
            accounting_account_fournisseur: unset
            remise_supplier: unset
            
    merge: 
        rows: 
            soc_merge: 
                label: Client en doublon</br>(Le client à supprimer)
                input: 
                    type: search_object
                    object: client
            import_data: 
                label: Récupérer les données du client à supprimer<br/>(Pour celles non définies dans le client à conserver)
                
    relance_paiements: 
        modal_format: large
        title: Relancer les paiements clients
        rows: 
#            - custom: 1
#              label: Liste clients
#              input_name: id_objects
#              hidden: 1
#              input: 
#                  type: hidden
            - custom: 1
              input_name: send_emails
              label: Envoyer les emails pour les premières et deuxièmes relances
              input: 
                  type: toggle
              value: 1
            - custom: 1
              input_name: date_prevue
              label: Date prévue d'envoi des relances
              input: 
                  type: date
                  display_now: 1
                  help: Cette date pourra être modifiée individuellement pour chaque relance en attente
            - custom: 1
              label: Afficher
              hidden: 
                  callback: isLoaded
              input_name: display_mode
              input: 
                  type: select
                  options: 
                      all: Tout
                      relancables: Seulement les clients dont les relances sont activées
                      not_relancables: Seulement les clients dont les relances sont désactivées
              value: relancables
            - custom: 1
              label: Factures impayées à relancer
              input_name: id_objects
              content: 
                  callback: renderFacturesToRelancesInputs
              depends_on: id_objects,display_mode
            
    deactivate_relances: 
        title: Déactivation des relances
        rows: 
            - field: relances_infos
              required: 1
              
lists_cols: 
    ref: 
        field: code_client
    code_compta:
        field: code_compta
      
filters_panels: 
    default: 
        filters: 
            relances_actives: 
                field: relances_actives
                label: Relances activées
                
            code_fournisseur: unset
            code_compta_fournisseur: unset
            accounting_account_fournisseur: unset
    
lists:
    default: 
        title: Liste des Clients
        icon: fas_user-circle
        list_filters:
            - name: client
              filter: 1
        add_btn_label: Nouveau client
        header_buttons: 
            callback: getDefaultListExtraHeaderButtons
        modal_view: full
        bulk_actions:
            0: 
                label: supprimer les clients sélectionnés
        extra_bulk_actions: 
            callback: getListExtraBulkActions
        list_actions: 
            callback: getFilteredListActions
    clients_caisse: 
        extends: default
        extra_btn: 
            - label: Sélectionner ce client
              icon: arrow-circle-right
              onclick: selectClientFromList($(this))

searches: 
    default:
        fields_search: 
            3: a.code_client
        fields_return: 
            0: a.code_client
            1: a.nom
            2: a.name_alias
        filters: 
            a.client: 
                in: 
                    array: 
                        - 1
                        - 2
                        - 3
