extends: 
    module: bimpcore
    object_name: Bimp_Societe
    
controller: client
list_page_url: 
    controller: clients
    
icon: fas_user-circle

header_list_name: default
header_edit_form: default
header_delete_btn: 1
                    
fields: 
    client: 
        default_value: 1
    fournisseur:
        default_value: 0
        
fields_tables: 
    identity:
        title: Identité
        icon: id-card
        rows: 
            - field: code_client
            - field: nom
            - field: name_alias
            - field: fk_typent
            - field: client
            - field: barcode
            - field: code_compta
            - field: num_sepa     
            - field: accounting_account
            - field: id_reseaunance
            - field: id_ldldc
            - field: is_salarie
            - field: is_subsidiary
            - label: Infos contact
              value: 
                  callback: displayFullContactInfos
            - label: Adresse
              value: 
                  callback: displayFullAddress
            
    infos_comm: 
        title: Informations commerciales
        icon: fas_briefcase
        rows: 
            - label: Commerciaux
              value: 
                  callback: displayCommerciaux
            - field: remise_client
            - label: Avoirs disponibles
              value: 
                  callback: displayDiscountAvailables
            - field: outstanding_limit
              edit: 1
            - field: mode_reglement
              edit: 1
            - field: cond_reglement
              edit: 1
#            - field: fk_account
            - field: secteuractivite
              edit: 1
            - field: marche
            - field: notecreditsafe
            - field: mail_licence
            - field: exported
            
views: 
    client:
        rows: 
            - cols: 
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: identity
                      
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: contact
                      
            - cols: 
                - type: fields_table
                  col_lg: 12
                  fields_table: 
                      name: address
            
            - cols:
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: identifiers
                      
#                - type: fields_table
#                  col_lg: 6
#                  col_md: 6
#                  col_sm: 12
#                  fields_table: 
#                      name: infos
                      
            - cols: 
                - type: fields_table
                  col_lg: 12
                  fields_table: 
                      name: notes
                      
    full: 
        panel: 0
        rows: 
            - cols: 
                - type: object_header
            - cols: 
                - type: view
                  view: 
                      name: default
                      panel: 0
                      
forms:
    light: 
        title: Ajout d'un client
        rows: 
            mode_reglement_supplier: unset
            cond_reglement_supplier: unset
                  
    default: 
        rows: 
            mode_reglement_supplier: unset
            cond_reglement_supplier: unset
            code_compta_fournisseur: unset
            accounting_account_fournisseur: unset
            remise_supplier: unset
            
    merge: 
        rows: 
            soc_merge: 
                label: Client en doublon</br>(Le client à supprimer)
            import_data: 
                label: Récupérer les données du client à supprimer<br/>(Pour celles non définies dans le client à conserver)
                
    relance_paiements: 
        modal_format: large
        title: Relancer les paiements clients
        rows: 
            - custom: 1
              label: Factures impayées à relancer
              content: 
                  callback: renderFacturesToRelancesInputs
            
lists:
    default: 
        title: Liste des Clients
        icon: fas_user-circle
        list_filters:
            - name: fournisseur
              filter: 0
        add_btn_label: Nouveau client
        header_buttons: 
            callback: getDefaultListExtraHeaderButtons
        modal_view: full
        bulk_actions:
            0: 
                label: supprimer les clients sélectionnés     
        
    clients_caisse: 
        extends: default
        extra_btn: 
            - label: Sélectionner ce client
              icon: arrow-circle-right
              onclick: selectClientFromList($(this))

searches: 
    default:
        fields_search: 
            3: a.code_client
        fields_return: 
            0: a.code_client
            1: a.nom
            2: a.name_alias
        filters: 
            a.client: 
                in: 
                    array: 
                        - 1
                        - 2
                        - 3