extends: 
    module: bimpcore
    object_name: Bimp_Societe
    
controller: client

list_page_url: 
    controller: clients
    
icon: fas_user-circle

header_list_name: default
header_edit_form: default
header_delete_btn: 1
                    
public_header_edit_form: public
           
objects: 
    public_users: 
        relation: hasMany
        delete: 1
        instance: 
            bimp_object: 
                module: bimpinterfaceclient
                name: BIC_UserClient
        
fields: 
    client: 
        default_value: 1
    fournisseur:
        default_value: 0
        
    mode_reglement_supplier: unset
    cond_reglement_supplier: unset
                    
fields_tables: 
    public_infos: 
        panel: 0
        rows: 
            - field: nom
            - field: name_alias
            - field: code_client
            - field: code_compta
            - field: num_sepa
            - label: Adresse
              value: 
                  callback: displayFullAddress
            - label: Informations de contact
              value: 
                  callback: displayFullContactInfos
            
    public_infos_company: 
        panel: 0
        rows: 
            - field: tva_assuj
            - field: tva_intra
            - field: siren
              label: SIREN
            - field: siret
              label: SIRET
            - field: ape
              label: APE
            - field: idprof4
              label: RCS
              
    atradius:
        panel: 1
        rows: 
            - field: notecreditsafe
            - custom: 1 
              label: Lettre Crédit Safe  
              value:
                  callback: getCreditSafeLettre
            - field: outstanding_limit_credit_safe
              edit: 1
            - field: outstanding_limit_icba
              edit: 1
            - field: outstanding_limit_credit_check
              edit: 1
            - field: outstanding_limit_atradius
              edit: 1
            - field: outstanding_limit_manuel
              edit: 1
            - field: outstanding_limit
            - label: PDF Rapport Assurance crédit
              input_name: send_emails
              input: 
                  type: file_upload
              show: 
                callback: useAtradius
              value:
                callback: displayAtradiusFile
            - field: date_depot_icba
              edit: 1
            - field: date_atradius
              edit: 1
            - field: date_demande_atradius
            - label: Mettre à jour assurance Atradius
              value: 
                  callback: displayFormAtradius
              show: 
                callback: useAtradius
            - field: id_atradius
            - field: status_atradius
      
views: 
    client:
        extends: default
        objects_change_reload: BimpRelanceClientsLine
                      
    public_client: 
        title: Mon compte client
        rows: 
            - cols: 
                - type: object_header
            - cols: 
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  fields_table: 
                      name: public_infos
                - type: fields_table
                  show: 
                      callback: isCompany
                  col_lg: 6
                  col_md: 6
                  fields_table: 
                      name: public_infos_company    
            - cols: 
                - type: list
                  col_lg: 12
                  list: 
                      name: public
                      children: contacts
                      
    atradius:
        title: Assurance crédit HT
        objects_change_reload: Bimp_Client
        rows: 
            - cols: 
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  fields_table: 
                      name: atradius 
                      
forms:
    light: 
        title: Ajout d'un client
        rows: 
            client: 
                hidden: 1
                value: 1
            fournisseur: 
                hidden: 1
                value: 0
            mode_reglement_supplier: unset
            cond_reglement_supplier: unset
                  
    default: 
        rows: 
            client: 
                hidden: 0
            fournisseur: 
                hidden: 0
                value: unset
            mode_reglement_supplier: unset
            cond_reglement_supplier: unset
            code_compta_fournisseur: unset
            accounting_account_fournisseur: unset
            remise_supplier: unset
            
    merge: 
        rows: 
            soc_merge: 
                label: Client en doublon</br>(Le client à supprimer)
                input: 
                    type: search_object
                    object: client
            import_data: 
                label: Récupérer les données du client à supprimer<br/>(Pour celles non définies dans le client à conserver)
                
    relance_paiements: 
        modal_format: large
        title: Relancer les paiements clients
        rows: 
#            - custom: 1
#              label: Liste clients
#              input_name: id_objects
#              hidden: 1
#              input: 
#                  type: hidden
            - custom: 1
              input_name: send_emails
              label: Envoyer les emails pour les premières et deuxièmes relances
              input: 
                  type: toggle
              value: 1
            - custom: 1
              input_name: date_prevue
              label: Date prévue d'envoi des relances
              input: 
                  type: date
                  display_now: 1
                  help: Cette date pourra être modifiée individuellement pour chaque relance en attente
            - custom: 1
              label: Afficher
              hidden: 
                  callback: isLoaded
              input_name: display_mode
              input: 
                  type: select
                  options: 
                      callback: getRelancesDisplayModesArray
              value: 
                  callback: getDefaultRelancesDisplayMode
            - custom: 1
              label: Factures impayées à relancer
              input_name: id_objects
              content: 
                  callback: renderFacturesToRelancesInputs
              depends_on: id_objects,display_mode
              
    free_relance: 
        modal_format: large
        rows: 
            relance_idx: 
                custom: 1
                label: N° de relance
                input_name: relance_idx
                input: 
                    type: qty
                data_type: int
                min: 1
                max: 3
                value: 1
                required: 1
            date: 
                custom: 1
                label: Date
                input_name: date
                data_type: date
                input: 
                    type: date
                    display_now: 1
                required: 1
            contact: 
                custom: 1
                label: Contact
                input_name: id_contact
                input: 
                    type: select
                    options: 
                        array: contacts
                value: 
                    callback: getIdContactForRelances
            method: 
                custom: 1
                label: Méthode de relance
                input_name: method
                value: 0
                data_type: id
                required: 1
                input: 
                    type: select
                    options: 
                        0: ''
                        1: Courrier
                        2: E-mail
                        3: SMS
                        4: Téléphone
                        5: Interne
            note: 
                custom: 1
                label: Note
                input_name: note
                input: 
                    type: textarea
                    rows: 3
                    auto_expand: 1
            factures: 
                custom: 1
                label: Factures
                input_name: factures
                content: 
                    callback: renderFreeRelancesFacturesInputs
                depends_on: relance_idx
               
    deactivate_relances: 
        title: Déactivation des relances
        rows: 
            - field: relances_infos
              required: 1
              
    attribute_commercial: 
        title: Attribution d'un commercial
        rows: 
            - custom: 1
              label: Commercial
              input_name: id_user_commercial
              input: 
                  type: search_user
                  
    cond_mode_reglement:
        title: Condition et Mode de réglement
        rows:
              - custom: 1
                label: Mode de réglement
                input_name: mode_reglement
                input: 
                    type: select
                    options: 
#                        array: modeReglements
                        callback:
                            method: getModeReglements
                            params:
                                - 0
                    
              - custom: 1
                label: Conditions de réglement
                input_name: cond_reglement
                input: 
                    type: select
                    options: 
                        array: condReglements
      
    public: 
        rows: 
            - field: nom
            - field: name_alias
            - field: address
            - field: zip
            - field: town
            - field: fk_pays
            - field: email
            - field: phone
            - field: fax
            - field: skype
    atradius_file:
        rows:
            - custom: 1
              label: PDF Rapport Assurance crédit
              input_name: file
              input: 
                  type: file_upload
#              value:
#                callback: displayAtradiusFile
    setOutstandingAtradius:
        rows:
            - custom: 1
              label: Montant 
              input_name: montant_atradius
              input: 
                  type: text
        
filters: 
    nb_notes_suivi: 
        label: Nb notes suivi recouvrement
        type: range
        
filters_panels: 
    default: 
        filters: 
            code_fournisseur: unset
            code_compta_fournisseur: unset
            accounting_account_fournisseur: unset
    
lists_cols: 
    nb_notes_suivi: 
        label: Nb. notes suivi recouvrement
        align: center
        value: 
            callback: displayNbNotesSuivi
    icba_file:
      label: PDF Rapport Assurance crédit ICBA
      value:
        callback: 
            method: displayAtradiusFile
            params:
                - 1
            
lists:
    default: 
        title: Liste des Clients
        icon: fas_user-circle
        list_filters:
            client: 
                name: client
                filter: 
                    operator: '>'
                    value: 0
        add_btn_label: Nouveau client
        header_buttons: 
            callback: getDefaultListExtraHeaderButtons
        modal_view: full
        bulk_actions:
            0: 
                label: supprimer les clients sélectionnés
        extra_bulk_actions: 
            callback: getListExtraBulkActions
        list_actions: 
            callback: getFilteredListActions
        cols: 
            code_fournisseur: unset
            
    clients_caisse: 
        extends: default
        extra_btn: 
            - label: Sélectionner ce client
              icon: arrow-circle-right
              onclick: selectClientFromList($(this))

cards: 
    default: 
        fields: 
            code_fournisseur: unset
            code_compta_fournisseur: unset
            outstanding_limit: 
                field: outstanding_limit
            commercial: 
                label: Commercial
                value: 
                    callback: 
                        method: displayCommerciaux
                        params: 
                            - 0

searches: 
    default:
        fields_search: 
            3: a.code_client
        fields_return: 
            0: a.code_client
            1: a.nom
            2: a.name_alias
        filters: 
            a.client: 
                in: 
                    array: 
                        - 1
                        - 2
                        - 3
      
stats_lists_cols: 
    nb_client: 
        label: Nb Client
        type: count_distinct
        field: nom
#    tot_qty: 
#        label: Qté totale
#        type: sum
#        field: qty
#        data_type: float
#        decimals: 2
#    tot_brouillon: 
#        label: Tot. Fac. brouillons
#        type: sum
#        data_type: money
#        decimals: 2
#        with_styles: 1
#        field: total_ttc
#        filters: 
#            f.fk_statut: 0
#    tot_valide: 
#        label: Tot. Fac. validées
#        type: sum
#        field: total_ttc
#        data_type: money
#        decimals: 2
#        with_styles: 1
#        filters: 
#            f.fk_statut: 
#                in: 
#                    - 1
#                    - 2
#    tot_abandon: 
#        label: Tot. Fac. abandonnées
#        type: sum
#        field: total_ttc
#        data_type: money
#        decimals: 2
#        with_styles: 1
#        filters: 
#            f.fk_statut: 3
            
            
stats_lists: 
    default: 
        n: 10
        configurable: 1
#        joins: 
#            facture: 
#                table: facture
#                alias: f
#                on: f.rowid = a.fk_facture
        filters_panel: default
        group_by_options: 
            - secteuractivite
            - marche
        cols: 
            nb_client:
#            tot_qty: 
#            tot_brouillon:
#            tot_valide:
#            tot_abandon:
