dol_object: 
    instance: 
        dol_object: product
        
table: product
primary: rowid
icon: fas_box
controller: product

header_btn:
    callback: getActionsButtons
    
header_list_name: default
list_page_url: list

labels: 
    name: produit
    
objects: 
    fourn_price: 
        relation: hasOne
        delete: 0
        instance: 
            bimp_object: 
                module: bimpcore
                name: Bimp_ProductFournisseurPrice
            id_object: 
                field_value: id_cur_fp

    files:
        relation: hasMany
        delete: 1
        instance:
            bimp_object:
                module: bimpcore
                name: BimpFile
        list: 
            filters:
                parent_module: bimpcore
                parent_object_name: Bimp_Product
                
    entrepot: 
        instance: 
            id_object:
                field_value: entrepot
                
    default_entrepot:
        extends: entrepot
        
fields: 
    ref: 
        label: Réf.
        
    label: 
        label: Libellé
        
    description: 
        label: Description
        type: html
        
    url: 
        label: URL publique
        
    note: 
        label: Note
        type: text
        dol_prop: note_private
        
    fk_product_type: 
        label: Type
        dol_prop: type
        values: 
            array: product_type
        type: int
        
    stock: 
        label: Stock réel
        dol_prop: stock_reel
        type: int
        default_value: 0
        
    barcode: 
        label: Code-barres
        
    fk_barcode_type: 
        label: Type de code-barres
        dol_prop: barcode_type
        type: int
        
    price: 
        label: Prix
        type: money
        
    price_ttc: 
        label: Prix TTC
        type: money
        
    price_min: 
        label: Prix minimum
        type: money
        
    price_min_ttc: 
        label: Prix minimum TTC
        type: money
        
    price_base_type: 
        label: Base du prix
        values: 
            array: price_base_types
        
    cost_price: 
        label: Prix de revient
        type: money
        
    pmp: 
        label: Prix d'achat moyen pondéré
        type: money
        value:
            callback: getPMP
        
    id_cur_fp: 
        label: Prix d'achat fournisseur courant
        type: id_object
        object: fourn_price
        default_value: 0
        
    cur_pa_ht: 
        label: Prix d'achat actuel
        type: money
        default_value: 0
        
    cur_pa_origin: 
        label: Type origine pa
        
    cur_pa_id_origin: 
        label: ID origine pa
        type: id
        default_value: 0
        
    pa_prevu: 
        label: Prix d'achat prévu
        dol_extra_field: 1
        type: money
        default_value: 0
        
    infos_pa: 
        label: Informations prix d'achat
        dol_extra_field: 1
        type: text
        
    default_vat_code: 
        label: Code TVA par défaut
        
    tva_tx: 
        label: Taux de TVA
        type: percent
        default_value: 20
        
    recuperableonly: 
        label: TVA récupérable seulement
        dol_prop: tva_npr
        type: bool
        
    tosell: 
        label: En vente
        dol_prop: status
        type: bool
        default_value: 1
        
    tobuy: 
        label: En achat
        dol_prop: status_buy
        type: bool
        default_value: 1
        
    customcode: 
        label: Code douane
        
    fk_country: 
        label: Pays d'origine
        dol_prop: country_id
        type: int
        default_value: 1
        input: 
            type: search_country
        display: 
            default: 
                type: callback
                method: displayCountry        
    weight: 
        label: Poids 
        type: float
        
    weight_units: 
        label: Unité de poids
        type: int
        values:
            array: units_weight
        
    length: 
        label: Longueur
        type: float
        
    length_units: 
        label: Unité de longueur
        type: int
        values:
            array: units_length
        
    width: 
        label: Largeur
        type: float
        
    width_units: 
        label: Unité de largeur
        type: int
        values:
            array: units_length
            
    height: 
        label: Hauteur
        type: float
        
    height_units: 
        label: Unité de hauteur
        type: int
        values:
            array: units_length
        
    surface: 
        label: Surface
        type: float
        
    surface_units: 
        label: Unité de surface
        type: int
        values:
            array: units_surface
        
    volume: 
        label: Volume
        type: float
        
    volume_units:
        label: Unité de volume
        type: int
        values:
            array: units_volume
        
    validate: 
        label: Validé
        dol_extra_field: 1
        type: bool
        default_value: 0
        
    serialisable: 
        label: Sérialisable
        type: bool
        dol_extra_field: 1
        default_value: 0
        
    remisable: 
        label: Remisable
        type: bool
        dol_extra_field: 1
        default_value: 1
        
    type2: 
        label: Sous-type
        type: int
        values: 
            array: sousTypes
        dol_extra_field: 1
        default_value: 0
        
    crt: 
        label: Remise CRT
        type: percent
        decimals: 3
        dol_extra_field: 1
        default_value: 0
        
    accountancy_code_sell:
        label: Code comptable (Vente)
        type: string
        
    accountancy_code_buy:
        label: Code comptable (Achat)
        type: string
        
    deee:
        label: Eco-Taxe
        type: money
        dol_extra_field: 1
        
    rpcp:
        label: Copie privée
        type: money
        dol_extra_field: 1
        
    zone_pr:
        label: Emplacement LYON
        type: text
        dol_extra_field: 1
        
#    best_buy_price:
#        label: Meilleur prix d'achat
#        type: money
#        extra: 1
        
    seuil_stock_alerte:
        label: Limite stock pour alerte
        type: int
        edit: 1

    desiredstock:
        label: Stock désiré optimal
        type: int
        edit: 1
#        
#    product_categories: 
#        label: Tags/catégories
#        extra: 1
        
    localtax1_tx:
        label: Taxe locale 1
        type: money
        dol_extra_field: 1

        
    localtax1_type:
        label: Type de taxe locale 1
        type: int
        dol_extra_field: 1

        
    localtax2_tx:
        label: Taxe locale 2
        type: money
        dol_extra_field: 1

        
    localtax2_type:
        label: Type de taxe locale 2
        type: int
        dol_extra_field: 1


#    ref_constructeur:
#        label: Réf. constructeur
#        type: string
#        dol_extra_field: 1

        
    fk_default_warehouse:
        label: Entrepôt par défaut
        type: id_object
        object: default_entrepot
        default_value: 0
        input:
            type: search_entrepot 
        dol_extra_field: 1



#    Champs non gérés
#    ref_ext
#    localtax1_tx
#    localtax2_tx
#    localtax1_type
#    localtax2_type
#    tobatch
#    duration
#    finished
#    canvas

forms: 
    light: 
        rows: 
            - custom: 1
              label: Marque
              input_name: marque
              input: 
                  type: text
              show: 
                  callback: isNotLoaded
            - custom: 1
              label: Ref. constructeur
              input_name: ref_constructeur
              input: 
                  type: text            
              show: 
                  callback: isNotLoaded
            - field: ref
              show: 
                  callback: isLoaded
            - field: label
            - field: description  
            - field: fk_product_type
            - field: type2
            - field: price
            - field: tva_tx
            - field: pa_prevu
            - field: infos_pa
            - field: serialisable
            - field: note
            - field: zone_pr
            
    etiquettes: 
        title: Générer des etiquettes
        icon: fas_sticky-note
        rows: 
            - custom: 1
              label: Type d'étiquette à générer
              input_name: type
              input: 
                  type: select
                  options: 
                      stock: Stock
                      magasin: Magasin
            - custom: 1
              label: Nombre
              input_name: qty
              data_type: int
              input: 
                  type: qty
              decimals: 0
              min: 1
              
    merge: 
        msgs: 
            - content: Attention, cette opération est irreversible
              type: warning
        title: Fusionner
        icon: fas_object-group
        rows: 
            - custom: 1
              label: Fusionner avec
              input_name: id_merged_product
              required: 1
              input: 
                  type: search_product
            - custom: 1
              label: Produit à conserver
              input_name: id_kept_product
              data_type: int
              required: 1
              content: 
                  callback: renderMergeKeptProductInput
              depends_on: id_merged_product                  

fields_tables: 
    infos: 
        title: Informations
        icon: fas_info-circle
        rows:  
            - field: ref
            - field: label
            - field: description
            - field: fk_product_type
            - field: type2
            - field: barcode
            - field: customcode
            - field: accountancy_code_buy
            - field: accountancy_code_sell
            - field: note
            - field: fk_default_warehouse
              display: nom_url

            
    prices: 
        title: Prix de vente
        icon: fas_euro-sign
        rows:  
            - field: price
              label: Prix HT
            - field: tva_tx
            - field: deee
            - field: rpcp
            - field: price_ttc
            - field: price_min_ttc
            - field: cost_price
    
    prices_buy: 
        title: Prix d'achat
        icon: fas_euro-sign
        rows:  
            - field: price
              label: Prix HT
            - field: tva_tx
            - field: price_ttc
            - field: price_min_ttc
            - field: cost_price
            - field: cur_pa_ht

       
    status: 
        title: Statuts
        icon: fas_check-square
        rows: 
            - field: validate
              edit: 1
            - field: serialisable
              edit: 1
            - field: type2
              edit: 1
            - field: tosell
              edit: 1
            - field: tobuy
              edit: 1
            - field: stock
            - field: zone_pr
              edit: 1
    
    infos_complementaires:
        title: Informations complémentaires
        icon: plus
        edit: 1
        rows:
            - field: url
            - field: stock
            - field: fk_country
            - label: Cétégories
              value: 
                  callback: displayCategories
            - field: localtax1_tx
            - field: localtax1_type
            - field: localtax2_tx
            - field: localtax2_type
#            - field: ref_constructeur
            - field: crt

    measures: 
        edit: 1
        rows:
        title: Mesures
        rows:
            - field: weight
            - field: weight_units
            - field: length
            - field: length_units
            - field: width
            - field: width_units
            - field: height
            - field: height_units
            - field: surface
            - field: surface_units
            - field: volume
            - field: volume_units
        
    stock:
        title: Vue globale
        icon: fas_check-square
        rows:
            - field: pmp
#            - field: best_buy_price
            - field: price
            - field: price_min
            - field: seuil_stock_alerte
            - field: desiredstock

views: 
    default: 
        rows: 
            - cols: 
                - type: fields_table
                  col_lg: 12
                  fields_table: 
                      name: infos
                      
            - cols: 
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: prices
                      
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: status
    
    fiche:
        edit_form: light
        delete_btn: 1
        rows:
            - cols: 
                - type: fields_table
                  col_lg: 7
                  col_md: 7
                  fields_table: 
                      name: infos
                - type: fields_table
                  col_lg: 5
                  col_md: 5
                  fields_table: 
                      name: status
                - type: fields_table
                  col_lg: 7
                  col_md: 7
                  col_sm: 12
                  fields_table: 
                      name: infos_complementaires
                      
                - type: fields_table
                  col_lg: 5
                  col_md: 5
                  fields_table:
                      name: measures
            
    
    product_price:
        rows:
            - cols:
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: prices
                
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: prices_buy
                - type: custom
                  col_lg: 12
                  col_md: 12
                  custom:
                      callback: renderListeFournisseur
                      
    product_note:
        rows:
            - cols:
                - type: custom
                  custom:
                      callback: renderNotesList
                      
    product_categorize:
        rows:
            - cols:
                - type: custom
                  custom:
                      callback: renderCategorize
                      
    stock:
        rows:
            - cols:
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: stock
                      
filters_panels: 
    default: 
        filters: 
            - field: ref
            - field: label
            - field: fk_product_type
            - field: price
            - field: price_ttc
            - field: barcode
            - field: serialisable
            - field: remisable
            - field: tosell
            - field: tobuy
            - custom: 1
              label: Catégorie (1)
              field: categ1
              type: value
              input:
                  type: select
                  options: 
                      callback: getCategoriesArray
            - custom: 1
              label: Catégorie (2)
              field: categ2
              type: value
              input:
                  type: select
                  options: 
                      callback: getCategoriesArray
            - custom: 1
              label: Catégorie (3)
              field: categ3
              type: value
              input:
                  type: select
                  options: 
                      callback: getCategoriesArray
      
lists_cols: 
    zone_pr: 
        field: zone_pr
    validate: 
        field: validate
                
lists: 
    default: 
        title: Produits
        icon: fas_box
        configurable: 1
        filters_panel: default
        sort_field: id
        sort_way: desc
        n: 50
        page_btn: 1
        edit_btn: 1
        edit_form: light
        add_form_name: light
        modal_view: default
        cols: 
            ref: 
                field: ref
            label: 
                field: label
            type: 
                field: fk_product_type
            barcode: 
                field: barcode
            stock: 
                field: stock
            price: 
                field: price_ttc
            tva: 
                field: tva_tx
            serialisable: 
                field: serialisable
                
cards: 
    default: 
        view_btn: 1
        fields: 
            - field: ref
            - field: barcode
            
searches:
    default: 
        fields_search: 
            - label
            - ref
