dol_object: 
    instance: 
        dol_object: 
            module: comm/propal
            file: propal
            
table: propal
primary: rowid

labels: 
    name: proposition commerciale
    name_plur: propositions commerciales
    is_female: 1
    
objects: 
    entrepot: 
        relation: hasOne
        delete: 0
        instance: 
            dol_object: 
                module: product/stock
                file: entrepot
            id_object:
                field_value: entrepot
                
fields: 
    ref: 
        label: Référence
    fk_statut: 
        label: Statut
        type: int
        dol_prop: statut
        values: 
            array: status_list
    date: 
        label: Date
        type: date
    fin_validite: 
        label: Date de fin de validité
        type: date
    date_livraison: 
        label: Date de livraison
        type: date
    total: 
        label: Total TTC
        dol_prop: total_ttc
        type: money
    total_ht: 
        label: Total HT
        type: money
    tva: 
        label: Total TVA
        dol_prop: total_tva
        type: money    
    libelle: 
        label: Libellé
        dol_extra_field: 1
    entrepot: 
        label: Entrepôt
        dol_extra_field: 1
        type: id_object
        object: entrepot
        input: 
            type: search_entrepot
    pdf_hide_reduc: 
        label: Masquer les remises dans le PDF
        dol_extra_field: 1
        type: bool
        default_value: 0
        
    pdf_hide_total: 
        label: Masquer les totaux dans le PDF
        dol_extra_field: 1
        type: bool
        default_value: 0
    
        
fields_tables: 
    default: 
        title: Informations
        icon: info-circle
        rows: 
            - field: fk_statut
            - field: date
              edit: 1
            - field: fin_validite
              edit: 1
            - field: date_livraison
              edit: 1
            - field: libelle
              edit: 1
            - field: pdf_hide_reduc
              edit: 1
            - field: pdf_hide_total
              edit: 1
            - label: Fichier PDF
              value: 
                  callback: displayPDFButton
                  
    totals: 
        title: Montants totaux
        icon: euro
        rows: 
            - field: total_ht
            - field: tva
            - field: total
                  
views: 
    sav: 
        Title: Devis
        icon: fas_file-invoice
        objects_change_reload: BS_SAV,BS_SavPropalLine,BS_ApplePart
        rows: 
            - cols: 
                - type: fields_table
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  fields_table: 
                      name: default
                   
                - type: rows
                  col_lg: 6
                  col_md: 6
                  col_sm: 12
                  rows: 
                      - cols: 
                          - type: fields_table
                            fields_table: 
                                name: totals
                                
                          - type: custom
                            custom: 
                                callback: renderMarginsTable
        
cards: 
    default: 
        title: 
            field_value: ref
        status: fk_statut
        view_btn: 1
        fields: 
            - field: total
            - label: Fichier PDF
              value: 
                  callback: displayPDFButton
        