
dol_object: 
    instance: 
        dol_object: 
            module: societe
            file: companybankaccount
            class: CompanyBankAccount
            
table: societe_rib
primary: rowid
icon: fas_university
common_fields: 0

parent_module: bimpcore
parent_object: Bimp_Societe
parent_id_property: fk_soc

header_edit_form: default

labels: 
    name: RIB
    name_plur: RIBs
    
objects:  
    societe: 
        instance: 
            id_object: 
                field_value: fk_soc
    
fields: 
    fk_soc: 
        label: Societe
        dol_prop: socid
        type: id_parent
        required: 1
        
    default_rib: 
        label: Compte par défaut
        type: bool
        default_value: 1
        
    type: 
        label: type
        input: 
            type: hidden
        default_value: ban
        
    label: 
        label: Intitulé du compte (interne a l'ERP)
        required: 1
        
    rum:
        label: Code RUM
        displays: 
            custom: 
                label: Affichage personnalisé
                type: callback
                method: displayRum
            
        edit: 0
#        required: 1
        
    bank: 
        label: Banque
#        required: 1
        
    iban_prefix: 
        label: IBAN Prefix
        dol_prop: iban
        input: 
            help: ex FR76
        
    code_banque: 
        label: Code banque
        
    code_guichet: 
        label: Code guichet
        
    number: 
        label: Numéro de compte
        
    cle_rib: 
        label: Clé RIB
        
    bic: 
        label: BIC/SWIFT
        
    domiciliation: 
        label: Domiciliation du compte
        type: text
        
    proprio: 
        label: Titulaire du compte
        
    owner_address: 
        label: Adresse du titulaire
        type: text
        
    datec: 
        label: Créé le
        type: datetime
        input: 
            type: hidden
        
    tms: 
        label: Dernière mise à jour le
        type: datetime
        dol_prop: datem
        input: 
            type: hidden
    exported:
        label: Exporté en compta
        type: bool
        
fields_table: 
    default: 
        panel: 0
        rows: 
            - field: fk_soc
              display: nom_url
#            - field: exported
            - label: Exporté en compta
              value:
                  callback: renderExportedField
            - field: default_rib
            - field: type
            - field: label
            - field: bank
            - label: RIB
              value: 
                  callback: displayRib
            - field: iban_prefix
            - field: bic
            - field: domiciliation
            - field: proprio
            - field: owner_address
            
views: 
    default: 
        modal_format: small
        rows: 
            - cols: 
                - type: object_header
            - cols: 
                - type: fields_table
                  fields_table:
                      name: default
                 
lists_cols: 
    rib: 
        label: IBAN
        value: 
            callback: displayRib
    iban:
        label: Iban
        value:
            callback: getIban
    devise:
        label: Devise
        value:
            callback: getdevise
                    
lists: 
    default: 
        n: 10
        sort_field: rowid
        filters_panel: default
        sort_way: desc
        add_btn: 1
        delete_btn: 1
        add_form_name: add
        modal_view: default
        edit_btn: 1
        cols:
            exported:
            fk_soc: 
            label: 
            rum:
                display: custom
            bank: 
            rib: 
            bic: 
            devise:
            
    soc: 
        extends: default
        title: Comptes bancaires du client
        pagination: 0
        n: 0
        cols: 
            fk_soc: unset
            default_rib:
                
    client: 
        extends: soc
        title: Comptes bancaires du client
            
    fourn: 
        extends: soc
        title: Comptes bancaires du fournisseur
        
forms: 
    default:
        msgs: 
            - content: Attention, ne rentrer un RIB qu'une fois le mandat signé en votre possession
              type: danger
        all_fields: 1
        rows: 
            file:
                custom: 1
                label: Mandat SEPA signé
                custom: 1
                input_name: file
                input:
                    type: file_upload
    add:
        rows:
            label:
                field: label
            
            
filters_panel: 
    default: 
        filters: 
            exported:
            fk_soc: 
            label: 
            rum:
            bank: 
            bic: 
            
        
    
        
    
        
        
    
    