table: usergroup
primary: rowid
common_fields: 0
icon: fas_users
controller: userGroup

dol_object: 
    instance: 
        dol_object: 
            module: user
            file: usergroup
            class: UserGroup
            
labels: 
    name: Groupe d'utilisateur
    
objects:
    user:
        instance:
            bimp_object:
                module: bimpcore
                name: Bimp_User
    user_group_rights:
        instance:
            bimp_object:
                module: bimpcore
                name: Bimp_UserGroup_Rights
    files:
        relation: hasMany
        delete: 1
        instance:
            bimp_object:
                module: bimpcore
                name: BimpFile
        list: 
            filters:
                parent_module: bimpcore
                parent_object_name: Bimp_UserGroup
                deleted: 0

        
    
nom_url: 
    syntaxe: <nom>
    modal_view: ''
    
fields: 
    nom: 
        label: Nom
        dol_prop: name
        
    note: 
        label: Note
        type: text
        
    mail: 
        label: Mail principal
        dol_extra_field: 1
        
    alias: 
        label: Alias mail
        dol_extra_field: 1
        
    displayedinglobaladdressbook: 
        label: Dans l'annuaire
        type: bool
        dol_extra_field: 1
        default_value: 0
        
    secteur: 
        label: Secteur
        dol_extra_field: 1
        values: 
            array: secteurs
        
filters_panels: 
    default: 
        filters: 
            nom: 
            mail: 
            alias: 
            note: 
            secteur:
    
lists: 
    default: 
        configurable: 1
        filters_panel: default
        sort_field: rowid
        sort_way: desc
        n: 10
        page_btn: 1
        cols: 
            nom:
            mail: 
            alias: 
            secteur: 
            note:
                
    user: 
        extends: default
        joins: 
            - table: usergroup_user
              on: ugu.fk_usergroup = a.rowid
              alias: ugu
        extra_btn: 
            callback: getUserListExtraButtons
            
searches: 
    default: 
        fields_search: 
            - a.nom
        fields_return: 
            - a.nom
        label_syntaxe: '<a.nom>'

fields_tables:
    informations:
        title: informations
        rows:
            - field: nom
            - field: mail
            - field: alias
            - field: secteur
            - field: note
     
views:
    fiche: 
        panel: 0
        rows:
            - cols:
                - type: rows
                  col_lg: 12
                  col_md: 12
                  rows:
                    - cols:
                        - type: fields_table
                          col_lg: 6
                          fields_table:
                            name: informations
                        - type: list
                          col_lg: 6
                          list: 
                              title: Utilisateurs du groupe
                              name: bygroup
                              object: user
                    - cols:
                        - type: list
                          col_lg: 12
                          list: 
                              title: Permissions du groupe
                              name: bygrouprights
                              object: user_group_rights   